### ISSUE TITLE
nyc instrument should resolve source filenames.

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/nyc#1014]
Create ./somefile.js then run `nyc instrument somefile.js`.  The instrumented code produces coverage data for the filename `'somefile.js'` when it really should be producing coverage for `path.resolve('somefile.js')`.  This causes oddness in reporting when combining pre-instrumented code with code that nyc instruments on the fly (during execution).

CC @AndrewFinlay

**Comment by AndrewFinlay** [comment]
Good to see this issue resolved, it was biting me in the `instrument --cwd` changes.  I had to jump through hoops to get that test to pass.  Dropping that requirement should make for a much cleaner implementation.
