### ISSUE TITLE
NYC Dependency "Wrong Version" Error?

### ISSUE THREAD

**Issue by simlu** [istanbuljs/nyc#1025]
Getting some bizarre dependency errors after updating (something changed in the last day?)

```
error "nyc#find-cache-dir#make-dir" is wrong version: expected "^1.0.0", got "2.1.0"
```
and similar...

Starting to investigate this more now.

Edit: It seems `@babel/register@7.0.0` and `nyc@13.3.0` are competing for dependencies?

**Comment by coreyfarrell** [comment]
`find-cache-dir` just released an update today which updated make-dir from `^1.0.0` to `^2.0.0`.  I'm unsure what you've done but `find-cache-dir` is bundled with all current releases of nyc so it shouldn't have updated.  Possibly `npm update` or something like that breaks bundled modules (unless you're installing nyc from the git repo).

**Comment by simlu** [comment]
More precisely this happens when running

`yarn check --integrity --verify-tree`

**Comment by coreyfarrell** [comment]
Please post a link to a repository where you are seeing the issue.

**Comment by simlu** [comment]
Sure thing. Here are simple instructions to reproduce:

(1) Checkout https://github.com/blackflux/object-rewrite locally
(2) Run `yarn install --freeze-lockfile`
(3) `yarn check --integrity --verify-tree` -> succeeds
(4) Run `yarn upgrade`
(5) `yarn check --integrity --verify-tree` -> now fails

**Comment by coreyfarrell** [comment]
I believe you are experiencing a bug in yarn.  I'm getting a different error `"nyc#make-dir#pify" is wrong version: expected "^3.0.0", got "4.0.1"` but this tells me that yarn is not resolving the dependencies correctly.  Worth noting that yarn really shouldn't be messing with the nyc dependencies as they are bundled.  I didn't experience this issue with `npm` but I don't know how you would generate a working updated yarn.lock.

**Comment by simlu** [comment]
Oh boy... thanks for the quick help!

I'll report back here with any further findings, but feel free to close this for now. I will request a re-open as necessary.

**Comment by coreyfarrell** [comment]
I hope you find resolution, sorry I can't be more directly helpful.
