### ISSUE TITLE
[Q] A way to conditionally exclude path

### ISSUE THREAD

**Issue by Makpoc** [istanbuljs/nyc#1030]
Is there a way to _conditionally_ exclude path from coverage? I have a project where I'm using nyc for test coverage for both unit and integration tests. I have a default set of excludes in package.json under nyc.exclude: [...]. I need to be able to add (preferably without replacing the defaults) few more files to exclude only for the unit-tests script (e.g. files related to db operations, that are required in the tested code, but are stubbed)

Any idea if that's possible?

**Comment by coreyfarrell** [comment]
That feature is not yet released, it will be part of 14.0.0.  I still have a couple patches that need to go in before I can do a release.

@Makpoc once 14.0.0 is released you will be able to create `nyc.config.js` that would export nyc configuration options.  Once that's available you will be able to use any logic you want (for example appending the exclude list based on an environmental variable).

**Comment by Makpoc** [comment]
Great! Thanks. I found several references to `nyc.config.js` but it was way less then expected. I understand now why that was.

**Comment by coreyfarrell** [comment]
`nyc@14.0.0-alpha.0` has been released to npm to allow easier testing.  Please note that additional breaking changes will occur before 14.0.0 final is released.  I'm closing this issue, you can monitor release progress at #1051.
