### ISSUE TITLE
Custom coverage reports from generated coverage data

### ISSUE THREAD

**Issue by lb-** [istanbuljs/nyc#1034]
Is it possible to programmatically generate the `json` output as exampled here:
https://istanbul.js.org/docs/advanced/alternative-reporters/#json

From that json, then generate the html as per here:
https://istanbul.js.org/docs/advanced/alternative-reporters/#html

The use case for us is to generate test-coverage like reports, but the reports actually represent files with specific sets of comments in the file, or arbitrary files of any kind. Our current project is a maintained 'fork' of another large project, we have a specific set of formatted comment blocks that we would read (eg. a gulp task), then use to generate the file/line references that the json format needs.

I realise this is probably not the core use case for istanbul or nyc, but just keen to know if we can generate the nice html reports from a custom generated set of json and what parts of the istanbul libraries we should investigate for this.

Thank you so much

**Comment by JaKXz** [comment]
Hi @lb-, this is an interesting question, thanks for sharing it. I would encourage you to look through the internals of [istanbul-lib-report](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-lib-report) which is what nyc uses to create reports based on coverage data. Assuming you provide the same format for coverage.json as input, you should be able to create the reports you want to, but I can't guarantee that for your use case.

**Comment by lb-** [comment]
@JaKXz  - thanks, will do

**Comment by dkelosky** [comment]
This kind of works; I tried something with an assembler language:
![image](https://user-images.githubusercontent.com/14940561/121403227-b35ca480-c928-11eb-8169-3689abc1ae74.png)

I can build a `coverage-final.json`.  However, it doesn't seem like anything in the [spec ](https://github.com/gotwarlost/istanbul/blob/master/coverage.json.md#format-of-coveragejson) allows for identifying comments (like line 10 and the end of line 5).  

It seems the HTML generator interprets `//` or `/* ... */` as comments.  Is this extendable in some way to identify my own comments via `coverage-final.json` ?
