### ISSUE TITLE
nyc mocha help needed

### ISSUE THREAD

**Issue by ochikov** [istanbuljs/nyc#1040]
Hello,
I have an issue that I cannot resolve without your help. 
I am running mocha tests using chai asserts. When I run the test file using mocha, e.g: ```mocha test/cli-commands/coverage/coverage.js ```
The tests are running OK.

When I use 
```nyc --check-coverage --lines 95 mocha 'test/**/*.js' --require mocha.opts.helper.js```
All the test are failing due to timeout or something else that I don't understand. 

What is the difference when I run the command with ```nyc``` and without ```nyc```.
Do you have some special timeout that I can specify ? 

Thank you.

**Comment by coreyfarrell** [comment]
nyc adds instrumentation (hit counters) to your code so this could make the code take slightly longer than before.  nyc does not impose timeout's, this would be mocha.  Possibly your timeouts are set with little margin of error and the instrumented code takes just too long.

That is all anyone can say without a minimal repository showing a reproduction.

**Comment by ochikov** [comment]
@coreyfarrell can you clone https://github.com/LimeChain/etherlime/tree/new-coverage 
and then run ```npm test``` or ```nyc --check-coverage --lines 95 mocha 'test/**/*.js' --require mocha.opts.helper.js```

Thank you.

**Comment by ochikov** [comment]
@coreyfarrell When I am running the tests with ```nyc``` there is a solc file that inside in it, there are checks for environment. For some reason, when running ```nyc``` it assumes that the environment is a web, not a NODE, and  from there are my errors.

How to tweak ```nyc``` to run NODE environment ?

**Comment by ochikov** [comment]
The problem was that on other test, I set a global window object. That was the problem and after spend quite time for debugging, I was able to fix it! Thank you!

**Comment by catchashu10** [comment]
Hi @ochikov can you please tell me how you overcame global window object  issue while using nyc?
I am facing the similar problem where my test cases are running with mocha but when I am using nyc with mocha, test cases are failing. I am using global window object.
