### ISSUE TITLE
What is the different between nyc and jest test ? 

### ISSUE THREAD

**Issue by UrielZohar** [istanbuljs/nyc#1043]
I'm trying to understand what is the different between jest and [istanbul](https://istanbul.js.org/). 

I wrote a little code [here](https://github.com/UrielZohar/istanbul-with-jest) that test a little function with [jest](https://jestjs.io/) and istanbul ,

in its `package.json` there are 2 scripts - 

the first one is - 
    `nyc --reporter=html --reporter=text jest --u --coverage
`
the second one is - 
    `jest --u --coverage
`
By running both them separatly I'm getting the same result , both them are giving a table to the console and the `coverage` folder.

Can you explain me what is the added value I'm getting by write the `nyc` in the beginning of the script line ?

**Comment by coreyfarrell** [comment]
jest uses istanbul libraries behind the scenes, so if you are using jest then you don't need nyc.  nyc is needed if you want coverage reports on other testing frameworks (a couple examples are mocha or ava).
