### ISSUE TITLE
Using --all with nyc instrument

### ISSUE THREAD

**Issue by madskonradsen** [istanbuljs/nyc#1044]
## Expected Behavior
`./node_modules/.bin/nyc instrument #{srcPath} #{defaultPath}/instrumented --exclude-after-remap=false --all`

I'm pre-instrumenting my code and expecting `--all` to include even my untested files

## Observed Behavior
Non-tested files are left out of my final report.

I have a suspicion that I'm misunderstanding the flow of nyc. Shouldn't `--all` be usable with standalone instrumentation?

**Comment by JaKXz** [comment]
@madskonradsen I know that there is some ongoing work for this and it will probably be released in nyc v14. For now you can try installing from master and see if it's been merged yet but no promises there!

cc @AndrewFinlay @coreyfarrell

**Comment by AndrewFinlay** [comment]
@madskonradsen, if you're pre-instrumenting code neither option `--all` or `--exclude-after-remap` will have any effect on the result.  

When using the instrument command `--all` is implied.  When nyc runs in its default mode it instruments source files just in time, as they're required by the test.  When creating instrumented files only and then nyc has no way of knowing which source files are exercised by the tests, so it instruments everything.  `--exclude-after-remap` is used in merging and reporting.

**Comment by coreyfarrell** [comment]
`nyc instrument` does not actually collect coverage, it only generates code capable of collecting coverage.  `nyc --all=true npm test` is what collects coverage.  To give more information I'll need to see a minimal repository demonstrating the issue with your way of running instrumentation / tests.
