### ISSUE TITLE
Generators "branch not covered"

### ISSUE THREAD

**Issue by LXSMNSYC** [istanbuljs/nyc#1045]
## Link to bug demonstration repository.
Repo for the demonstration: https://github.com/LXSMNSYC/iterable-js

Please run ```npm install``` and ```npm run test``` to get coverages.

## Expected Behavior
All files that shows 100% coverage should also have 100% branch covered.

## Observed [Behavior](url)
![Screenshot from 2019-03-28 15-41-17](https://user-images.githubusercontent.com/4783372/55139317-6ab5d800-5170-11e9-9faa-c649bcea96fe.png)

See how the branch was executed 91x and yet it is reported as uncovered.

## Forensic Information

**Operating System:** Ubuntu 18.04.2 LTS
**Environment Information:** Node v11.12.0, NPM 6.9.0

**Comment by coreyfarrell** [comment]
@LXSMNSYC Could you try following the instructions at https://istanbul.js.org/docs/tutorials/es2015/ ?  I suspect that `@babel/plugin-transform-regenerator` might be introducing a branch in generated code and running `@babel/register` from mocha instead of running it from nyc may be causing nyc to see the generated code instead of the source.

**Comment by LXSMNSYC** [comment]
Hello @coreyfarrell thanks for the reply!

Here is my scripts configuration for my package.json:
```json
  "scripts": {
    "linux-mocha": "./node_modules/.bin/mocha --require @babel/register -R spec --recursive",
    "linux-test": "./node_modules/.bin/nyc --reporter=html npm run linux-mocha",
    "linux-docs": "./node_modules/.bin/esdoc",
    "linux-cjs": "./node_modules/.bin/rollup src/index.js --format cjs --name \"Iterable\" --file index.js",
    "linux-browser": "./node_modules/.bin/rollup src/index.js --format iife --name \"Iterable\" --file dist/index.js",
    "linux-minify": "npm run linux-browser && ./node_modules/.bin/terser dist/index.js --compress --mangle --output dist/index.min.js",
    "linux-build": "npm run linux-cjs && npm run linux-minify && npm run linux-docs && npm run linux-test",
    "win-mocha": "node node_modules/mocha/bin/mocha --require @babel/register -R spec --recursive",
    "win-test": "node node_modules/nyc/bin/nyc.js --reporter=html npm run win-mocha",
    "win-docs": "node node_modules/esdoc/out/src/ESDocCLI.js",
    "win-cjs": "node node_modules/.bin/rollup src/index.js --format cjs --name \"Iterable\" --file index.js",
    "win-browser": "node node_modules/.bin/rollup src/index.js --format iife --name \"Iterable\" --file dist/index.js",
    "win-minify": "npm run win-browser && node node_modules/.bin/terser dist/index.js --compress --mangle --output dist/index.min.js",
    "win-build": "npm run win-cjs && npm run win-minify && npm run win-docs && npm run win-test",
    "mocha": "npm run linux-mocha || npm run win-mocha",
    "test": "npm run linux-test || npm run win-test",
    "docs": "npm run linux-docs || npm run win-docs",
    "cjs": "npm run linux-cjs || npm run win-cjs",
    "browser": "npm run linux-browser || npm run win-browser",
    "minify": "npm run linux-minify || npm run win-minify",
    "build": "npm run cjs && npm run minify && npm run docs && npm test"
  },
```
As you can see, I am running @babel/register in mocha and I run the mocha script I have made with nyc.

Thanks for sharing that link, I'll try the configuration as provided in the tutorial
