### ISSUE TITLE
Unable to waive coverage of else if block

### ISSUE THREAD

**Issue by arbrock** [istanbuljs/nyc#1046]
<a href="https://github.com/arbrock/nyc-elseif-bug">Demo Repository</a>

```javascript
function buggy_if(do_if, do_elseif) {
  if (do_if) {
    console.log("Hit if branch");
  } else /* istanbul ignore if */ if(do_elseif) {
    console.log("Hit else if branch");
  } else {
    console.log("Hit final else");
  }
}
buggy_if(true, false);
buggy_if(false, false);
```
## Expected Behavior
Running 'nyc npm test' reports 100% coverage of the function, since all statements are either covered or waived.
## Observed Behavior
The else if block is reported as uncovered.

I've also included a couple workarounds I have tried in the repository, both of which have the side effect of waiving coverage on the final else block. Is there a workaround I've missed?

This is similar to issue #595, but different.
## Forensic Information

**Operating System:** CentOS 6.6
**Environment Information:** https://gist.github.com/arbrock/6485d6799d021f753b5cf4904bbc08a0

**Comment by GCSBOSS** [comment]
I have the same behavior here. Anyone else having trouble with `ignore if` and ìgnore else`?

**Comment by coreyfarrell** [comment]
This bug is fixed in nyc 15, please upgrade.
