### ISSUE TITLE
Impossible to install nyc

### ISSUE THREAD

**Issue by sergebesson** [istanbuljs/nyc#1048]
## Link to bug demonstration repository.

__no demonstration repository available__

## Expected Behavior

Expected nyc to be installed

## Observed Behavior

```bash
$ npm i nyc
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/parser@^7.4.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sbesson/.npm/_logs/2019-04-03T09_15_08_853Z-debug.log
```

## Forensic Information

```bash
$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        16.04
Codename:       bionic
```

**Environment Information:** information about your project's environment, see instructions below:

[output.txt](https://github.com/istanbuljs/nyc/files/3037840/output.txt)

Serge BESSON

**Comment by coreyfarrell** [comment]
I'm not able to reproduce here.  `@babel/parser` was just released 14 hours ago, maybe your local npm cache is out of sync?  I've seen a similar issue with npm before, my `npm` client said a dependency didn't exist but other people had no issue.  I remember trying to clear npm caches but that didn't help.  The issue seemed to resolve itself when I rebooted my workstation.

**Comment by sergebesson** [comment]
i just tried again and it worked just fine.

...

**Comment by coreyfarrell** [comment]
Thanks for reporting back.
