### ISSUE TITLE
Typescript coverage doesn't include some lines after 13.2.0 update

### ISSUE THREAD

**Issue by damyanpetev** [istanbuljs/nyc#1049]
## Link to bug demonstration repository.

https://github.com/damyanpetev/typescript-coverage-repro
(install `nyc@latest` to see the difference)

## Expected Behavior
Coverage report on a TypeScript project to include all relevant lines and if/else paths.
## Observed Behavior
After updating v13.1.0  to latest (specifically above v13.2.0) coverage percents differ and seem to ignore some lines (specifically noticed that with if/else blocks). Consequently, the coverage also doesn't report the if/else paths that are not taken:
![image](https://user-images.githubusercontent.com/3198469/55489451-9afeea00-563a-11e9-8ad5-38fd29281d4a.png)

## Forensic Information

**Operating System:** Windows 10
**Environment Information:** tested on both node v8.15.1/v10.15.2 with npm 6.4.1.
(initial commit on demo repo has [package-lock.json](https://github.com/damyanpetev/typescript-coverage-repro/blob/e1694525e8826fa2f055562fe259b4f5de1a1d8f/package-lock.json) with packages installed)

**Comment by damyanpetev** [comment]
Actually, not that many changes between v13.1.0...v13.2.0 with potential to affect output.

The `--all` flag (include fix) caused no change.
There were some package updates, and in those a jump to `"istanbul-lib-source-maps": "^3.0.2"`. Manually updating only that package instead of nyc did reproduce the issue.

As far as I can tell it's to do with this change https://github.com/istanbuljs/istanbuljs/commit/f97ffc7518807acc67159eb74993c3f822bce67a#diff-1e46034f56d264608f2601bcff19a795, though the description doesn't suggest the change I'm observing. Then again, way out of my depth w/ source maps to be able to tell what's going on there.

**Comment by coreyfarrell** [comment]
I can confirm this bug, though I don't have a solution.  The change you reference in istanbul-lib-source-maps definitely fixed some bugs.  Source maps are difficult, fixing one bug often causes another.  I took a look at your project but wasn't able to gain any insight to what's going wrong.

CC @JaKXz @bcoe not sure if you have any troubleshooting ideas.

**Comment by fictitious** [comment]
I'm also experiencing this problem. I have an example TypeScript code for which nyc incorrectly reports 100% branch coverage.

After some digging, it looks like after [this same commit](https://github.com/istanbuljs/istanbuljs/commit/f97ffc7518807acc67159eb74993c3f822bce67a#diff-1e46034f56d264608f2601bcff19a795), the `if` statement is missing from `statementMap` after a transformation from locations in generated `.js` file back to locations in `.ts` file. I have [pull request](https://github.com/istanbuljs/istanbuljs/pull/374) for istanbuljs which adds one test to `istanbul-lib-source-map`  where missing coverage data can be seen (commented out, it's there if you run the test with 2.0 version of `istanbul-lib-source-map`).

After some more digging, in 3.0 version of `istanbul-lib-source-map`, the end range for `if` statement in question is [obtained with this call](https://github.com/istanbuljs/istanbuljs/commit/f97ffc7518807acc67159eb74993c3f822bce67a#diff-2e962004ffaa89595263fae1ffa2324bR42)

```javascript
    var beforeEndMapping = sourceMap.originalPositionFor({
        line: generatedEnd.line,
        column: generatedEnd.column - 1,
    });

```
That `column - 1` causes `originalPositionFor()` to return mapping with source set to `null`, which causes the `if` statement data to be dropped from coverage data. In 2.0, the statement end position was obtained by calling `originalPosisionFor()` directly on `generatedEnd` position, without subtracting `-1` from column.

At this point, it's completely unclear to me if it's a bug in either

- source map data generated by TypeScript compiler
- `originalPositionFor()` implementation in `source-map` package
- the code in `istanbul-lib-source-map`

The first question is: if there's `{generatedLine, generatedColumn}` position in generated code for which `{originalLine, originalColumn}` position can be obtained in the original source code - is it safe to assume that valid position in original source code can always be obtained for `{generatedLine, generatedColumn - 1}` ?

**Comment by coreyfarrell** [comment]
@damyanpetev @fictitious please retest with nyc@14.1.0 (currently published to npm `next` tag).  This should resolve the issue for you.

**Comment by fictitious** [comment]
Can't say for the original report, but my problem is gone with nyc@14.1.0. Thanks!
