### ISSUE TITLE
Code coverage using Python Jasmine

### ISSUE THREAD

**Issue by xirdneh** [istanbuljs/nyc#1064]
I am using [python jasmine](https://jasmine.github.io/setup/python.html) and want to get code coverage. I tried running `nyc jasmine-ci --browser firefox` but nyc's output is empty.
Is there any way to get nyc check code coverage while using python jasmine?

## Expected Behavior
Report being created.

## Observed Behavior
Empty output.

## Forensic Information

**Operating System:** Debian

**Comment by coreyfarrell** [comment]
nyc is a node.js coverage tool, it won't directly support python (and doesn't directly support browser testing).  The only way to get coverage from outside node.js is for that outside program to get coverage JSON files into `.nyc_output/` with the proper format.  The directory can be configured using the nyc argument `--temp-dir`, for example `nyc --temp-dir coverage/tmp/`.

**Comment by xirdneh** [comment]
@coreyfarrell Even if I instrument the code first?

**Comment by coreyfarrell** [comment]
Something needs to get the coverage results (`window.__coverage__` in the browser) written to a JSON file in the nyc temp-dir (`.nyc_output` by default).  nyc doesn't talk to python or the browser.

**Comment by bcoe** [comment]
@xirdneh :wave: as @coreyfarrell mentions, you can use `nyc` to output reports, once you get the raw coverage object from `window.__coverage__`, you might also look at a tool like [puppeteer](https://developers.google.com/web/tools/puppeteer/) that lets you collect coverage directly from the browser; there is documentation on the puppeteer project outlining how to do so.
