### ISSUE TITLE
Windows causes coverage to be 0%

### ISSUE THREAD

**Issue by michaelKurowski** [istanbuljs/nyc#1065]
## Link to bug demonstration repository.
https://github.com/michaelKurowski/lokim2/tree/nyc-issue-branch

## Expected Behavior
- `npm i` in the main directory
- `gulp prepareDev`
- put some mongodb credentials into `src/server/config.json` (mlab provides free ones, I can also send credentials to a free instance created there)
- `gulp serverTestCoverage`
- I should see a table with files covered with realistic results. Something like that:
https://gist.github.com/michaelKurowski/09e493010cfe6ac5faa0c823f4605845

## Observed Behavior
Everything works flawlessly on Linux, but on Windows I get a corrupted report:
https://gist.github.com/michaelKurowski/a562595264d935b22d57f79daeaeefb6

## Forensic Information

**Operating System:** Observed on Windows 7 and 10
**Environment Information:** 
https://gist.github.com/michaelKurowski/01980c68ac8916605b36292f33f77504

**Comment by coreyfarrell** [comment]
The repository you linked is using nyc@11.7.0 which uses babel 6.  Current versions of nyc use babel 7, are you able to upgrade?

It looks like you are not getting any actual coverage on Windows, the data you are seeing is the result of the `--all` argument to nyc.  I suspect this could be an issue with the PATH getting overwritten or something running `node` by absolute path.  nyc creates an executable script called `node` in a temporary directory and adds that to the system PATH.  This causes any subprocess which runs `node` to use the script which injects nyc's coverage collection logic.  I've seen this fail on Windows but the reason is not always clear.

**Comment by michaelKurowski** [comment]
I'll upgrade.
Our gulp script uses Node's `child_process.spawn` to run the nyc. Can it be the cause? If so, how could we avoid it while using spawn?

**Comment by coreyfarrell** [comment]
How you run nyc should generally not be an issue.  So you run NYC and at that point it 'hijacks' new `node` subprocesses.  The issue could be that you are running `nyc npx gulp serverTest`.  Maybe try instead `npx nyc gulp serverTest`, that way nyc runs as a sub-process of npx instead of the other way around (I know npx manipulates the path but not entirely sure of the edge case details).

I have to be honest your project is setup very differently than most others.  This is of course your choice but be aware doing things your own unique way means that nobody else has experience with your setup and may be unable to provide useful advice.

**Comment by michaelKurowski** [comment]
Which part of the setup are you refering to?

**Comment by coreyfarrell** [comment]
Both.  Most projects use npm scripts for testing and do not run tests from gulp.  Some may have a `pretest` script which will run `gulp build` or something of that nature.  The way this project is setup may or may not have an effect on your results, but it's vastly different from the norm and that adds to the cognitive burden for others to understand what is going on.

**Comment by mariszin** [comment]
Having the same issue here. On Win10 w/ Git Bash, I get:
```
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |        0 |        0 |        0 |        0 |                   |
 models           |        0 |        0 |        0 |        0 |                   |
  club.js         |        0 |      100 |        0 |        0 |       2,3,9,10,12 |
  competition.js  |        0 |      100 |        0 |        0 |       2,3,9,10,12 |
  group.js        |        0 |      100 |        0 |        0 |       2,3,9,10,12 |
  index.js        |        0 |        0 |        0 |        0 |... 29,30,34,35,37 |
  person.js       |        0 |      100 |        0 |        0 |   2,3,11,12,13,15 |
  result.js       |        0 |      100 |        0 |        0 |... 22,23,24,25,27 |
  stage.js        |        0 |      100 |        0 |        0 |   2,3,11,12,13,15 |
  user.js         |        0 |        0 |        0 |        0 |... 25,26,27,29,33 |
 routes           |        0 |        0 |        0 |        0 |                   |
  auth.js         |        0 |      100 |        0 |        0 |... 14,17,18,19,22 |
  competitions.js |        0 |        0 |        0 |        0 |... 3,90,93,96,100 |
  index.js        |        0 |      100 |      100 |        0 |... 10,11,12,13,15 |
  stages.js       |        0 |        0 |        0 |        0 |... 49,55,58,61,65 |
 routes/admin     |        0 |        0 |        0 |        0 |                   |
  competitions.js |        0 |        0 |        0 |        0 |... 48,49,52,53,59 |
  index.js        |        0 |      100 |      100 |        0 |       1,2,4,5,6,8 |
  upload.js       |        0 |        0 |        0 |        0 |... 22,126,127,137 |
  users.js        |        0 |        0 |        0 |        0 |... 30,31,33,34,40 |
------------------|----------|----------|----------|----------|-------------------|
```
When I run the same command on Ubuntu Bash:
```
------------------|----------|----------|----------|----------|-------------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    68.72 |    28.57 |    38.81 |    69.01 |                   |
 models           |    89.71 |    54.55 |    80.95 |    89.71 |                   |
  club.js         |      100 |      100 |      100 |      100 |                   |
  competition.js  |      100 |      100 |      100 |      100 |                   |
  group.js        |      100 |      100 |      100 |      100 |                   |
  index.js        |       95 |    66.67 |      100 |       95 |                13 |
  person.js       |      100 |      100 |      100 |      100 |                   |
  result.js       |      100 |      100 |      100 |      100 |                   |
  stage.js        |      100 |      100 |      100 |      100 |                   |
  user.js         |    53.85 |        0 |    33.33 |    53.85 | 18,20,25,26,27,29 |
 routes           |    76.92 |    66.67 |    42.86 |    77.92 |                   |
  auth.js         |    63.64 |      100 |        0 |    63.64 |        9,14,18,19 |
  competitions.js |    90.63 |      100 |       75 |    90.63 |          53,90,96 |
  index.js        |      100 |      100 |      100 |      100 |                   |
  stages.js       |    54.17 |        0 |        0 |    56.52 |... 36,49,55,58,61 |
 routes/admin     |    47.42 |        0 |        0 |    47.42 |                   |
  competitions.js |    42.31 |        0 |        0 |    42.31 |... 47,48,49,52,53 |
  index.js        |      100 |      100 |      100 |      100 |                   |
  upload.js       |     41.3 |        0 |        0 |     41.3 |... 10,120,122,127 |
  users.js        |    52.63 |        0 |        0 |    52.63 |... 23,30,31,33,34 |
------------------|----------|----------|----------|----------|-------------------|
```
node -v  => v10.15.3
Using only yarn to run tests (`yarn test`). 
Relevant package.json :
```
...
  "devDependencies": {
    "chai": "^4.2.0",
    "chai-http": "^4.2.1",
    "cross-env": "^5.2.0",
    "mocha": "^6.1.3",
    "nodemon": "^1.18.10",
    "nyc": "^14.0.0"
  },
  "nyc": {
    "all": true,
    "include": [
      "models/**/*.js",
      "routes/**/*.js"
    ]
  }
...
```

**Comment by calebcartwright** [comment]
It looks setting `all` to `true` in the config is a cause of missing coverage on Windows with v14.

Setting `all` to `false` fixes coverage info for me.

**Comment by SimonSchick** [comment]
Also running into this with v14, configuration looking something like

```
  "nyc": {
    "cache": false,
    "all": true,
    "include": [
      "dist/backend/**/*",
      "src/backend/**/*"
    ],
    "exclude": [
      "config",
      "dist/backend/app/single.js",
      "dist/backend/app/cluster.js",
      "dist/backend/app/db/migrator.js",
      "dist/backend/app/db/migrate.generate.js",
      "dist/backend/app/db/migrate.up.js",
      "dist/backend/app/db/migrate.down.js",
      "dist/backend/app/server/caches/catbox-redis.js",
      "dist/backend/**/*.test.js",
      "dist/backend/test",
      "dist/backend/setup.js",
      "dist/backend/unit.setup.js",
      "dist/backend/app/server/plugins/debugRequest.js",
      "dist/backend/app/server/plugins/routeValidation.js",
      "dist/backend/scripts"
    ]
  },
```

I've tried to change it to:
```
  "nyc": {
    "cache": false,
    "include": [
      "src/backend/**/*"
    ],
    "exclude": [
      "config",
      "dist/backend/app/single.ts",
      "dist/backend/app/cluster.ts",
      "dist/backend/app/db/migrator.ts",
      "dist/backend/app/db/migrate.generate.ts",
      "dist/backend/app/db/migrate.up.ts",
      "dist/backend/app/db/migrate.down.ts",
      "dist/backend/app/server/caches/catbox-redis.ts",
      "dist/backend/**/*.test.ts",
      "dist/backend/test",
      "dist/backend/setup.ts",
      "dist/backend/unit.setup.ts",
      "dist/backend/app/server/plugins/debugRequest.ts",
      "dist/backend/app/server/plugins/routeValidation.ts",
      "dist/backend/scripts"
    ]
  },
``` but no files appear to be instrumented at all.
Setting `all` to `false` doesn't change this either.

**Comment by calebcartwright** [comment]
@SimonSchick another thing we found that helped in one TS repo was explicitly setting the extension key:

```
  "extension": [
    ".ts"
  ],
```

**Comment by coreyfarrell** [comment]
@calebcartwright you are experiencing a different issue than OP.  Your issue (I suspect) is that nyc@14 enables `--exclude-after-remap` which means that we look at the source-maps to determine the original filename and process include, exclude, and extension matching to determine what should/shouldn't be reported.

Everybody: please do not comment here unless you are experiencing the exact issue @michaelKurowski reported - flawless coverage under Linux but not Windows.  For everything else please post a new issue including all required information.

**Comment by calebcartwright** [comment]
@coreyfarrell - fair enough, but the coverage problems we are seeing are only occurring on Windows just like the OP. Coverage is fine on Mac and Linux. I was just sharing things I've seen that address that coverage gap on Windows

**Comment by coreyfarrell** [comment]
@calebcartwright OP has experienced the issue with nyc@11.  If you are only experiencing the issue with nyc@14 then it's definitely a different issue, even if it has some of the same symptoms.

**Comment by SimonSchick** [comment]
After adding `extensions` I can confirm I have the same issue as OP now on v14.

**Comment by michaelKurowski** [comment]
I've tested the latest nyc and it still doesn't work.
@SimonSchick solution doesn't help either.

I'll check the PATH, and try to invoke nyc directly.

**Comment by michaelKurowski** [comment]
I've "consol logged" the PATH inside tests while running them via gulp serverTestCoverage, and it has more entries that system one, I've performed a diff, and turns out that no entries from system one has been lost.

**Comment by michaelKurowski** [comment]
Issue has been solved.
I've had to run mocha directly in `gulp serverTest` instead of using `npx`
