### ISSUE TITLE
vulnerability from npm audit

### ISSUE THREAD

**Issue by maikelmclauflin** [istanbuljs/nyc#1066]
## Expected Behavior
should pass npm audit
## Observed Behavior
does not

## Environment Information

```
# paste the output here
$ npx envinfo@latest --preset nyc
npx: installed 1 in 1.793s

  System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 86.77 MB / 8.00 GB
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.npm-packages/bin/npm
  npmPackages:
    @babel/cli: ^7.4.3 => 7.4.3 
    @babel/node: ^7.2.2 => 7.2.2 
    babel-eslint: ^8.2.3 => 8.2.6 
    nyc: ^13.3.0 => 13.3.0 


```

**Comment by coreyfarrell** [comment]
The issue is that nyc@13.3.0 bundles it's dependencies.  This is changing in nyc@14 which we are in the process of releasing.  The test version `nyc@14.0.0-rc.1` does not report this vulnerability.

Worth noting this is a false positive as istanbul-reports does not use untrusted templates.  I'm leaving this ticket open until we can get 14.0.0 published.

**Comment by maikelmclauflin** [comment]
Can confirm. `nyc@14.0.0-rc.1` does not report error. Thanks for the quick response.

**Comment by coreyfarrell** [comment]
nyc@14.0.0 is now released, upgrading nyc will clear this `npm audit` report.

I'm leaving this bug pinned for a few more days so people can see to upgrade.

**Comment by aaddaamm** [comment]
I've upgraded to v14 but i'm still seeing the audit error for nyc > istanbul-reports > handlebars.
https://www.npmjs.com/advisories/755

Node 8.15.0
npm 6.4.1
yarn 1.15.2

**Comment by coreyfarrell** [comment]
have you deleted/regenerated your yarn.lock and/or package-lock.json?

**Comment by aaddaamm** [comment]
That did it. Thanks @coreyfarrell
