### ISSUE TITLE
Question - Adding support for PureScript

### ISSUE THREAD

**Issue by NickSeagull** [istanbuljs/nyc#1081]
Hello! I recently discovered nyc, and before anything, I'd like to thank all the contributors for the work you've done, it is awesome ❤️ 

I'd like to know if there is support for non-mainstream languages, like PureScript, that compile to JavaScript. I've tried using nyc with a PureScript project, but the coverage reported is not quite true.

I know that nyc supports source mapping, and that's what I used, but it reports no coverage.

The code that I have written for a test in PureScript is like this one:

```haskell
module Test.Main where

import Prelude

import Effect (Effect)
import Test.Spec (describe, it)
import Test.Spec.Assertions (shouldEqual)
import Test.Spec.Reporter.Console (consoleReporter)
import Test.Spec.Runner (run)
import Components.Foo (foo)

main :: Effect Unit
main = run [consoleReporter] do
  describe "something" do
    it "tests" do
      foo `shouldEqual` 42
```

which compiles to the following JavaScript

```javascript
// Generated by purs version 0.12.5
"use strict";
var Components_Foo = require("../Components.Foo/index.js");
var Data_Eq = require("../Data.Eq/index.js");
var Data_Show = require("../Data.Show/index.js");
var Test_Spec = require("../Test.Spec/index.js");
var Test_Spec_Assertions = require("../Test.Spec.Assertions/index.js");
var Test_Spec_Reporter_Console = require("../Test.Spec.Reporter.Console/index.js");
var Test_Spec_Runner = require("../Test.Spec.Runner/index.js");
var main = Test_Spec_Runner.run([ Test_Spec_Reporter_Console.consoleReporter ])(Test_Spec.describe("something")(Test_Spec.it("tests")(Test_Spec_Assertions.shouldEqual(Data_Show.showInt)(Data_Eq.eqInt)(Components_Foo.foo)(42))));
module.exports = {
    main: main
};
//# sourceMappingURL=index.js.map
```

The tested source file is `Components.Foo`:

```haskell
module Components.Foo where

foo :: Int
foo = 42
```

which compiles to:

```javascript
// Generated by purs version 0.12.5
"use strict";
var foo = 42;
module.exports = {
    foo: foo
};
//# sourceMappingURL=index.js.map
```

In theory, it should report that I'm using at least `foo`. But it reports 0% of coverage:

![image](https://user-images.githubusercontent.com/7448243/56488994-22bc7380-64d8-11e9-9680-6cd9b0866438.png)

![image](https://user-images.githubusercontent.com/7448243/56489011-2e0f9f00-64d8-11e9-9f32-e5aa8eac65e0.png)

Is there something that I can do on my side to allow using nyc with PureScript? Perhaps adding some hook to the test framework or something?

[Link to demo repo](https://gitlab.com/NickSeagull/purescript-nyc-testing)

**Comment by coreyfarrell** [comment]
Pre-compiling might work, I don't know anything about PureScript so I can't comment on that but nyc operates on JavaScript and other variations of the language supported by the [babel parser](https://babeljs.io/docs/en/babel-parser#language-extensions).

Transpiled languages are an advanced topic of nyc, you did not provide a minimum demo repo as request in the bug template so I'm unable to provide more specific advice.

**Comment by NickSeagull** [comment]
Apologies, I just setup a demo repo, and added it to the end of the first comment 😁

**Comment by bpmccurdy** [comment]
@NickSeagull 

If you run `nyc spago test -- -g sourcemaps` twice in a row there is output based on the sourcemaps
Seems like you just need to precompile before running with nyc.

FIRST RUN
```
...
Compiling Test.Spec.Reporter.Base
Compiling Test.Spec.Reporter.Console
Compiling Test.Spec.Reporter.Spec
Compiling Test.Spec.Reporter.Tap
Compiling Test.Spec.Reporter.Dot
Compiling Test.Main
Compiling Test.Spec.Reporter
Build succeeded.
something
  ✓︎ tests

Summary
1/1 test passed

Tests succeeded.
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```
SECOND RUN
```
[purescript-nyc-testing[master]]-> nyc spago test -- -g sourcemaps
Installation complete.
Build succeeded.
something
  ✓︎ tests

Summary
1/1 test passed

Tests succeeded.
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |      100 |      100 |        0 |                   |
 Foo.purs |        0 |      100 |      100 |        0 |                 4 |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by NickSeagull** [comment]
Awesome, thanks!

**Comment by andys8** [comment]
Hey, I wanted to give it a try with:

```
nyc --clean -e ".purs" spago test  --purs-args "-g sourcemaps
```
(spago changed the way you pass args to purs)

I end up with a large list containing all foreign imports and dependencies. Hard to tell if the result is still fine and using sourcemaps correctly.

Did you end up with using this to produce statistics? How did you use `nyc`s configuration arguments to use `output` for sourcemaps, but ignore dependencies?

**Comment by NickSeagull** [comment]
Didn't touch this apart from the quick tests I did when openened the issue sorry, perhaps some other user can give more insights
