### ISSUE TITLE
feat: Support `nycRC()` in configuration object

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/nyc#1087]
I'm toying with programmatically created configurations at [@cfware/nyc](https://github.com/cfware/cfware-nyc).  This module exports a class with methods implemented as both static factory functions and chainable non-static manipulation functions.  The idea is that you could create an nyc.config.js as follows:
```js
'use strict';

module.exports = require('@cfware/nyc')
  .fullCoverage()
  .include('lib/**')
  .exclude('lib/do-not-cover.js')
  .settings;
```

This example has two main benefits over normal declarative config:
* `.fullCoverage()` sets multiple properties (similar to `tap --100`)
* `.exclude()` does not clear defaults so `lib/do-not-cover.js` is in addition to `testExclude.defaultExcludes`.

I'd love to avoid having to explicitly use `.settings` in my `nyc.config.js` files.  This could be supported if the nyc `lib/config-util.js` did something like:
```js
if (Symbol.for('nycrc') in config) {
  config = config[Symbol.for('nycrc')]
}
```
In all supported versions of node `Symbol.for('nycrc') === Symbol.for('nycrc')` so this would allow nyc to pull it's configuration from config generator objects such as mine.  I've already verified that adding this code does not break any existing tests.

@bcoe @JaKXz @isaacs any thoughts / objections?

**Comment by coreyfarrell** [comment]
The patch is simple enough so I just posted a PR.

**Comment by bcoe** [comment]
@coreyfarrell huh, prior to classes having `#`, I'd always used `Symbols` for internal information hiding in modules -- have never used `Symbol.for`.

What's the advantage of this over a string key like `nyc`?

**Comment by coreyfarrell** [comment]
I was thinking that `Symbol.for` would be more intentional and impossible to set via JSON (possibly impossible to set in yaml, though I don't use yaml).  It also avoids reserving a basic class member so nyc isn't restricting the meaning of `generatorInstance.nyc()`.

**Comment by coreyfarrell** [comment]
@bcoe what do you think of using a method `toNYCRC()` instead?  This way it will follow the convention of other conversion routines (toString, toJSON) and won't look like a configuration option.

**Comment by bcoe** [comment]
@coreyfarrell seems reasonable to me :+1:; I think what I've seen other libraries do is just have the default export be an object with the config (which I think is what we support today if you have an `nycrc.js`) -- what advantages are there to having a `toNYCRC()` method?

**Comment by JaKXz** [comment]
@coreyfarrell building on my comment on #1088 - I think calling `.settings` from your config generator there is the right way to go in your `nyc.config.js`... I think nyc has enough ways to accept configs, and TBH the correct next step (IMHO) would be to do something like what https://github.com/davidtheclark/cosmiconfig does.

**Comment by coreyfarrell** [comment]
Since you're against this I can abandon.  I think we support enough formats, I was just looking to make it easier to use a config generator.

**Comment by coreyfarrell** [comment]
Adding support for `nyc.config.mjs` in nyc 15 has incidentally made this possible.  Since we have to `await` the result of the config load it is now possible for configuration generators to be PromiseLike objects, so:
```js
class ConfigGenerator {
  // Add methods / properties for constructing `this[settings]`

  async then(fn) {
    return fn(await this[settings]);
  }
}
```
