### ISSUE TITLE
lcov.info is empty after upgrade to v14.

### ISSUE THREAD

**Issue by sramam** [istanbuljs/nyc#1090]
## Link to bug demonstration repository
https://github.com/tufan-io/node-starter

### Installation (nyc@v13)
```
cd  /tmp
git clone https://github.com/tufan-io/node-starter demo-app
cd demo-app
npm install
# ENTER x3 to power through the prompts
```
It installs all dependencies (slightly dated), but the build passes and reports the proper coverage @100%.
```
======================= Coverage summary =======================
Statements   : 100% ( 2/2 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 1/1 )
Lines        : 100% ( 2/2 )
=============================================================
```

Now upgrade to nyc@14 to see the problem
```
npm i nyc@14
npm run test
```
```
======================= Coverage summary =======================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
=============================================================
```

## Expected Behavior

A proper coverage report as with `nyc@13` after the upgrade to `nyc@14`

## Observed Behavior
with `nyc@14`, no coverage reports are being generated and the text-summary reports `Unknown% ( 0/0 )`

### lcov.info nyc@13
```
$ ls -l coverage/lcov.info
-rw-r--r--  1 sramam  wheel  127 Apr 25 14:00 coverage/lcov.info
```

### lcov.info nyc@14
```
$ ls -l coverage/lcov.info
-rw-r--r--  1 sramam  wheel  0 Apr 25 13:58 coverage/lcov.info
```

### Troubleshooting steps
I have tried to change the package.json:nyc config from 
```
# with nyc@13
"nyc": {
    "exclude": [
      "config/**/*",
      "dist/**/test/**/*.*",
      "dist/**/test/**/*.js"
    ]
}
```
to (and a couple more alternatives), but to no avail.
```
# with nyc@14
"nyc": {
    "exclude": [
      "config/**/*",
      "dist/**/test/**/*.*",
      "dist/**/test/**/*.js"
    ],
    "include": [
      "dist/**/*.js",
      "src/**/*.ts"
    ],
    "sourceMap": true,
    "instrument": true,
    "cache": true,
    "all": false
  },
```

What am I missing?

## Environment Information

```
$ npx envinfo@latest --preset nyc
npx: installed 1 in 4.55s

  System:
    OS: macOS Mojave 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 32.61 MB / 8.00 GB
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    Yarn: 1.2.1 - ~/.yarn/bin/yarn
    npm: 6.5.0 - ~/trial/v1.0.0/demo-app/node_modules/.bin/npm
  npmPackages:
    nyc: ^14.0.0 => 14.0.0
    typescript: ^3.4.5 => 3.4.5

```

**Comment by sramam** [comment]
hmm... 
I'm most certainly mis-understanding how remapping of instrumentation is supposed to work here.
Having a hard time distinguishing between brownian and forward motion here:

```
"nyc": {
    "all": true,
    "instrument": true,
    "extension": [".ts", ".js"],
    "include": [
      "!config/**/*",
      "!src/**/test/**/*",
      "src/**/*"
    ]
  },
```

```
> cross-env NODE_ENV=test nyc -r html -r lcov -r text ava --verbose


  ✔ main

  1 test passed

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |      100 |        0 |        0 |                   |
 index.ts |        0 |      100 |        0 |        0 |                 3 |
----------|----------|----------|----------|----------|-------------------|
```

When I try to use the compiled files in dist, 
```
"nyc": {
    "all": true,
    "instrument": true,
    "extension": [".ts", ".js"],
    "include": [
      "!config/**/*",
      "!dist/**/test/**/*",
      "dist/**/*"
    ]
  },
```
```
> cross-env NODE_ENV=test nyc -r html -r lcov -r text ava --verbose


  ✔ main

  1 test passed

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by coreyfarrell** [comment]
You need to add `src/**/*` to your `include` list even when testing against compiled sources.  NYC looks at the source-map of files in `dist/` and determines the original filename, then removes them from the reports due to not being included.  So you need `dist/` to be included so the instrumentation happens, `src/` to allow them to be shown by reporting.

**Comment by sramam** [comment]
I see. This is what I tried:

```
"nyc": {
    "all": true,
    "instrument": true,
    "extension": [".ts", ".js"],
    "include": [
      "!config/**/*",
      "!**/test/**/*",
      "!**/test.*",
      "dist/**/*",
      "src/**/*"
    ]
  },
```
```
$ npx nyc -r html -r lcov -r text ava --verbose

  ✔ main

  1 test passed

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |      100 |        0 |        0 |                   |
 index.ts |        0 |      100 |        0 |        0 |                 3 |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by coreyfarrell** [comment]
@sramam it seems this configuration change has resolve the issue for you so I'm closing this issue.  If this is incorrect comment and we can reopen.

**Comment by sramam** [comment]
@coreyfarrell, the code base should indicate 100% coverage. The test cases clearly do that.
It only fails with nyc@14. I had it working with nyc@13.

I'm clueless on why it's failing here.

### Expected
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 index.ts |      100 |      100 |      100 |      100 |                 3 |
----------|----------|----------|----------|----------|-------------------|
```

### Actual 
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |      100 |        0 |        0 |                   |
 index.ts |        0 |      100 |        0 |        0 |                 3 |
----------|----------|----------|----------|----------|-------------------|
```


Do you have an example of a compiled (TypeScript perhaps?!) example with nyc@14?

For the moment, I am sticking to nyc@13, but would really like to move up to nyc@14. 
I am willing to dig till we get to the bottom of this, but would appreciate any pointers.

**Comment by coreyfarrell** [comment]
@sramam sorry I misunderstood.  The main thing that is changed from nyc@13 to nyc@14 is that the `include`, `exclude` and `extension` options must allow the source and compiled files to match.

Have you tried with nyc@14.1.0?  14.0.0 had some issues with related to transpiled sources and the `all` option.

**Comment by sramam** [comment]
indeed! nyc@14.1 seems to work much better. 

with
```
  "nyc": {
    "extension": [
      ".ts",
      ".tsx"
    ],
    "exclude": [
      "**/test/**"
    ]
  },
```
I was able to get 
```
=============================== Coverage summary ===============================
Statements   : 100% ( 2/2 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 1/1 )
Lines        : 100% ( 2/2 )
================================================================================
```

**Comment by relief-melone** [comment]
I still get that bevavioud. All the solutions above did not work for me. With v13.3.0 everything still works fine. It also happens when I use the compiled .js files for testing. My versions

**mocha:** 6.1.4
**nyc:** 14.1.1

**mocha.opts**
```
--recursive
dist/test/*.js
```

**.nycrc:**
``` javascript
{
    "reporter" : ["text-summary", "text"],
    "extension": [".js"],
    "include": [
      "dist/**/*"
    ],
    "exclude": [
        "**/test/**"
    ]
}
```

Coverage just keeps empty. I have been searching for quite some time now. Numerous configurations, but still nothing works. 13.3.0 also works without all this stuff and just the option for the /dist/test directory. Any suggestions?

**Comment by sramam** [comment]
@relief-melone, can you try 

```
{
    "reporter" : ["text-summary", "text"],
    "extension": [".ts"],
    "exclude": [
        "**/test/**"
    ]
}
```

**Comment by relief-melone** [comment]
Works!!! Awesome. I found so many way more complicated solutions. Nothing had any effect. Still I don't really understand what went wrong before. Why didn't it work with the dist/*.js files and is it not necessary anymore to have babel and ts-node etc. installed as well as sourceMap: true etc. to make istanbul work with typescript?

Anyway thanks again for the quick reply.

**Comment by sramam** [comment]
I'm not an expert - but as I understand it, 
1. nyc/istanbul knows which files to include from the underlying test-framework - mocha/ava etc.
2. The extension tells it to follow any source-maps found in these file till the desired extension is recached.
3. The exclude tells it to prevent reporting on test-files.

Hence the include was un-necessary. 
The extension needed to be changed to follow-the-source-map.

Hope that helps.
