### ISSUE TITLE
Feature request: fewer dependencies

### ISSUE THREAD

**Issue by evert** [istanbuljs/nyc#1092]
I use nyc for most of my node and typescript projects. nyc is a very large contributor to the total size of my `node_modules`.

According to [this tool](https://npm.anvaka.com/#/view/2d/nyc), the nyc package results in 234 leaf nodes in the dependency tree.

I realizing this might not be a priority for you. After all, `nyc` is very complex and what it needs to do is complicated. I'm also not offering a suggestion on how to improve this.

I'm just bringing this up as something that I've noticed. I like my own dependency graphs slim.

So yea, don't take it as a complaint, but maybe take it as a data point or nice to have. Simpler dependency trees reduce risk in a variety of ways.

**Comment by JaKXz** [comment]
In the short term you can just use `npx nyc npm test`  in your test script instead of having nyc as a dependency. 

We have had discussions on this in the past, and the conclusion was that this isn't an extremely high priority because there are other issues (bugs, features) to get to. I think perf would be a better metric for us to track, but, we're not quite at that capacity yet (AFAIK).

**Comment by evert** [comment]
Thank you for the detailed answer. It's appreciated, and I totally understand this perspective. I will close this issue to not add to the noise

**Comment by coreyfarrell** [comment]
Also worth noting some of the largest parts of our dependency tree are shared with other very common development tools and starting with nyc@14.0.0 we no longer bundle dependencies.  nyc@14.1.0 alone takes about 23MB to install, but in my personal projects just over half of this is always shared with other development tools.  So not bundling is often a huge win for actual install size.

**Comment by evert** [comment]
Yea fwiw, it was never about size. I just wanted to try and help the npm ecosystem a tiny bit by removing some of these 1-liner dependencies. Totally get that not everyone shares that philosophy
