### ISSUE TITLE
Incorrect coverage report in 13.x and 14.x

### ISSUE THREAD

**Issue by ThWoywod** [istanbuljs/nyc#1097]
I try to get the test coverage from a more or less large Typescript project by using nyc. Nearly all my TypeScript files will have their own test files with many test cases. 

In my option all this files should be covered by nyc. I try a lot with different nyc configurations and different versions of how to execute the test files.

At the beginning I start with a configuration where single files (which actually should have tests) will not appear in the coverage report. I could fix this issue by requiring "ts-node/register" and "source-map-support/register" to the nyc configuration. Now all files are listed in the coverage report but nyc think that there are no fitting tests.

![image](https://user-images.githubusercontent.com/9079596/57082587-4e6d0400-6cf7-11e9-9eb4-fc534a213f0c.png)

I do not have any idea why this tests should not be covered. I try to reproduce it in a new bug-demo project but their, everything works well. 

### Troubleshooting steps
- [x] still occurrring when I put `cache: false` in my nyc config
- [x] setting tsconfig `sourceMap: true` makes no difference
- [x] set the typescript target to es6 makes no difference
- [x] execute tests with node, ts-node or jasmine-ts makes no difference
- [x] still occurrring when i only use `exclude` without `include` in my nyc config
- [x] using @istanbuljs/nyc-config-typescript makes no difference
- [x] using "ts-node/register/transpile-only" instead of "ts-node/register" will not work (it throws 
 a "Cannot read property 'loc' of undefined" exception, see screenshot-2)

## Environment Information
```
npx envinfo@latest --preset nyc
npx: Installierte 1 in 1.93s

  System:
    OS: macOS Mojave 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 130.55 MB / 16.00 GB
  Binaries:
    Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
    npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
  npmPackages:
    nyc: ^14.1.0 => 14.1.0 
    source-map-support: ^0.5.12 => 0.5.12 
    ts-node: ^8.1.0 => 8.1.0 
    typescript: ^2.9.2 => 2.9.2 



---
Jasmine: 2.99.0

```

## NYC Configuration

```
"nyc": {
    "cache": false,
    "all": true,
    "sourceMap": true,
    "instrument": true,
    "exclude-after-remap": false,
    "extension": [
      ".ts"
    ],
    "check-coverage": true,
    "require": [
      "ts-node/register",
      "source-map-support/register"
    ],
    "include": [
      "app"
    ],
    "reporter": [
      "lcov",
      "text",
      "html"
    ],
    "exclude": [
      "**/*.d.ts",
      "coverage/**",
      "js/**",
      "builds/**",
      "config/**",
      "**/spec/**",
      "**/*.spec.ts",
      "**/node_modules/**",
      "gulpfile.js",
      "dummy-start.ts"
    ]
  },
```

screenshot-2
![image](https://user-images.githubusercontent.com/9079596/57086568-a8bd9300-6cfe-11e9-9c5c-bee3abfe4fec.png)

**Comment by JaKXz** [comment]
Can you provide a link to your repo or a minimal reproduction? Also can you follow the instructions here: https://npm.im/@istanbuljs/nyc-config-typescript and see if that fixes your issue?

**Comment by Codex-** [comment]
Also finding this on many TS projects too, have had to revert to 13.* for now.

**Comment by molant** [comment]
We are having the [same problem in webhint](https://github.com/webhintio/hint/issues/2309). This was working fine with 13.3.0 😞

**Comment by ThWoywod** [comment]
Thank you for the really quick replay! I already tried `@istanbuljs/nyc-config-typescript` but it makes no differences. Depending on `@istanbuljs/nyc-config-typescript` I create my own nyc config like shown in the Issue. So the `@istanbuljs/nyc-config-typescript` don't work for me :-(

I already tried to revert to 13.* but the issue still occurs in my project.

Unfortunately, I can't reproduce this issue in a new demo project.

**Comment by JaKXz** [comment]
I have several examples of PRs I've made that simplify the `nyc` configuration in most projects with nyc-config-typescript... without a demo repository there's not much more help I can provide you other than suggesting you remove all the config you have and follow the instructions closely.

**Comment by JaKXz** [comment]
@molant upon reviewing the webhint repo, it appears that it makes automatic upgrades without much review, so I think your claim of a regression might just be due to a breaking change between major versions (likely to do with the `--exclude-after-remap` flag). 

Please read the changelog and the new documentation closely. Like I suggested for OP, I would recommend resetting your config entirely and starting with the preset that is appropriate for your project. As maintainers we don't have the time to painstakingly investigate *every* repo like this, so we have been making a more concerted effort to update our documentation to support everyone.

**Comment by Codex-** [comment]
@JaKXz put together a sample where nyc is failing to generate coverage:
https://github.com/Codex-/nyc-bug

nyc is only run on *.js files, no middle layers like ts-node etc. 

### Steps to run
1) `npm i`
2) `npm run build`
3) `npm run test`

Test simply executes: `nyc --reporter=lcov --reporter=html mocha` where mocha is configured to only run `*.test.js` files.

## Output
### 13.3.0 lcov.info:
```
TN:
SF:C:\Dev\p\nyc-bug\src\index.ts
FN:1,testFunc
FNF:1
FNH:1
FNDA:1,testFunc
DA:1,1
DA:2,1
LF:2
LH:2
BRF:0
BRH:0
end_of_record
```

### 14.1.0 lcov.info
Empty

**Comment by maleeb** [comment]
It works for me if I use the extension option from here:
https://github.com/istanbuljs/nyc#common-configuration-options

Default is just '.js' so u have to add '.ts' also

Like 
`nyc --reporter='lcov' --extension='.ts' mocha`

or 

```
"nyc": {
    ...
    "extension": [
        ".ts"
    ],
    ...
}
```

**Comment by coreyfarrell** [comment]
@maleeb thanks for testing / responding.

The original poster of this issue has stated that downgrading to 13.x did not fix the issue, so all problems caused by upgrade to 14.x are off topic on this ticket.  @Codex- please follow the suggestion from @maleeb (click Show Comment to see it).

All comments not related to OP's issue are hidden as off topic so it's easier to find information relevant to this specific issue.  Unless your issue can be reproduced on 13.x or you have advice for that specific issue please do not post any further comments to this ticket, please open a new ticket instead.

**Comment by neilpalima** [comment]
The latest version 15.0.0 has this issue. Downgrading back to 14.1.1 works fine.

**Comment by Codex-** [comment]
What's your config? Probably need to raise a new issue

**Comment by neilpalima** [comment]
@Codex- I saw a latest [issue](https://github.com/istanbuljs/nyc/issues/1291)
