### ISSUE TITLE
Expand default extension list

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/nyc#1103]
Since enabling `--exclude-after-remap` we've had some issue with TS projects.  We need to add `.ts` to the default extension list.  While we're at it we should also add `.cjs` and `.mjs`.  Any other extensions we should instrument or report on by default?

This is a potentially breaking change so it will be for nyc@15.

CC @bcoe @JaKXz

**Comment by bcoe** [comment]
@coreyfarrell this seems like a reasonable list to me :+1:

**Comment by JaKXz** [comment]
`jsx` and `.tsx` would be good to add

**Comment by bcoe** [comment]
I don't know the answer to the forcing question off the top of my head; perhaps when we have a bit of time we could setup a `.jsx` and `.ts` repo for both `ts-node` and an explicit compile step -- see if we can figure out default configuration that works relatively well for both use-cases, and is easy to modify where it doesn't work well.

**Comment by Raynos** [comment]
I ran into this as well when upgrading nyc. Thanks for fixing this.

**Comment by Enet4** [comment]
Just to let the devs know that I'm looking forward to a new release of `nyc`. I was expecting the default extensions to include .ts, but it appears that these changes are still not applicable to the latest version.

**Comment by coreyfarrell** [comment]
@Enet4 the next release will be semver-major, you can watch for progress at #1104.  We're working on it but are still dealing with some blockers.  No ETA yet.
