### ISSUE TITLE
nyc generate empty coverage

### ISSUE THREAD

**Issue by diiiego83** [istanbuljs/nyc#1108]
Hi All,
nyc is currently generate an empty coverage result. I tried different configurations but it seems that is not able to track the sources.
my code have dist structure:
```
- dist/app/*.js
- dist/utest/test.js
```
I'm running the test in the transpiled js dist folder
```
"scripts": {
    "test": "mocha ./dist/utest/test.js --exit",
    "coverage": "nyc npm test",
  },  
  "nyc": {
    "include": [
      "dist/**/*.js"
    ],
    "reporter": [
      "text-summary",
      "html",
      "cobertura"
    ],
    "sourceMap": true,
    "instrument": true
}
```

```
=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```
ENV configuartion:
```
 System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
    Memory: 25.57 GB / 31.85 GB
  Binaries:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    istanbul: 0.4.5 => 0.4.5
    nyc: ^14.1.0 => 14.1.0
    ts-node: 8.0.3 => 8.0.3
    typescript: 3.3.1 => 3.3.1
```

**Comment by coreyfarrell** [comment]
Based on the limited information you've provided I suspect you need to add `"src/**"` to your `nyc.include` setting and set `[".ts"]` for `nyc.extension`.  That said it's unknown if you also have other issues because you haven't linked a repository.  It's possible you don't even need to set the `nyc.include` option, the default exclude's might just do the right thing.

Also note that your ENV configuration shows that `istanbul@0.4.5` was installed.  This deprecated module has been shown to cause other problems, I recommend investigating how that module is being installed and try to avoid it.

**Comment by diiiego83** [comment]
I removed istanbul and ts-node.
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1545M v5 @ 2.90GHz
    Memory: 24.15 GB / 31.85 GB
  Binaries:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    nyc: ^14.1.0 => 14.1.0
    typescript: 3.3.1 => 3.3.1
```

Still no working.
I moved back the version to ^13.3.0 and it works. coverage reported correctly. This version has a high vulnerability.
```

                       === npm audit security report ===                        
                                                                                
# Run  npm install --save-dev nyc@14.1.0  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
                                                                                
  High            Prototype Pollution                                           
                                                                                
  Package         handlebars                                                    
                                                                                
  Dependency of   nyc [dev]                                                     
                                                                                
  Path            nyc > istanbul-reports > handlebars                           
                                                                                
  More info       https://nodesecurity.io/advisories/755                        
                                                                                


found 1 high severity vulnerability in 3929 scanned packages
  1 vulnerability requires semver-major dependency updates.

```

**Comment by diiiego83** [comment]
@coreyfarrell I've noticed that if I add the "require": [ "ts-node/register" ] configuration the coverage is generated. The strange things is that i not testing any .ts file but the transpiled .js. I've create an example here https://github.com/diiiego83/nyctest 

git clone https://github.com/diiiego83/nyctest.git
npm install
npm test (should work)
npm coverage (test ok - coverage ok)
remove "require": [ "ts-node/register" ] from the package.json
npm coverage (test ok - coverage empty)

hope this will help.

**Comment by coreyfarrell** [comment]
> Based on the limited information you've provided I suspect you need to add "src/**" to your nyc.include setting and set [".ts"] for nyc.extension. That said it's unknown if you also have other issues because you haven't linked a repository. It's possible you don't even need to set the nyc.include option, the default exclude's might just do the right thing.

Just follow the advice I gave.  You are precompiling so you should not use ts-node/register.
