### ISSUE TITLE
Empty text & lcov output

### ISSUE THREAD

**Issue by ScottRudiger** [istanbuljs/nyc#1115]
## Link to bug demonstration repository

https://github.com/ScottRudiger/AsyncAF/tree/nyc-repro

## Expected Behavior

Prior to updating `nyc` from `v11.7.3` to `v14.1.1` the appropriate output for both `text` and `lcov` was generated.

You can see this behavior in the above repo by running:

```bash
npm install --save-dev nyc@11.7.3
npm run cover
```

## Observed Behavior

With `npm@14.1.1`, however, the text output is:
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

The `index.hmtl` generated by `lcov` also seems to be missing my classes/methods and generates a pretty empty `html` file:

![Screen Shot 2019-05-12 at 11 06 46 PM](https://user-images.githubusercontent.com/26824724/57599335-26597e00-750b-11e9-9509-026af2e9974b.png)

### Troubleshooting steps
- [x] still occurrring when I put `cache: false` in my nyc config
- I've also tried everything listed in [this issue](https://github.com/istanbuljs/nyc/issues/822) to no avail.
  - Use `--exit` flag with mocha.
  - Delete `node_modules/.cache`
- And I've looked at the changelog, but the breaking changes from `11` to `14` seem unrelated.

## Environment Information

```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 57.43 MB / 8.00 GB
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  npmPackages:
    @babel/core: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @babel/node: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @babel/plugin-proposal-object-rest-spread: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @babel/plugin-transform-runtime: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @babel/polyfill: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @babel/preset-env: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @babel/register: ^7.0.0-beta.46 => 7.0.0-beta.46 
    @babel/runtime: ^7.0.0-beta.46 => 7.0.0-beta.46 
    babel-loader: ^8.0.0-beta.2 => 8.0.0-beta.2 
    babel-plugin-istanbul: ^5.1.4 => 5.1.4 
    istanbul: ^0.4.5 => 0.4.5 
    nyc: ^14.1.1 => 14.1.1 
    rollup-plugin-babel: ^4.0.0-beta.4 => 4.0.0-beta.4 
```

**Comment by coreyfarrell** [comment]
Your project is very large/complex.  Are you testing built or bundled sources?  If so I believe you will need to modify your `include` option in `.nycrc` to allow not only the built files but also the original sources.  Your issue is likely the result of changes to the include/exclude logic.

Also your `include` and `exclude` statements use relative paths starting with `./`.  This causes problems with current versions, please try modifying your `.nycrc` as follows:
```js
{
  "check-coverage": true,
  "lines": 100,
  "statements": 100,
  "functions": 100,
  "branches": 100,
  "reporter": [
    "text",
    "lcov"
  ],
  "cache": false,
  "include": [
    "lib**"
  ],
  "exclude": [
    "lib/methods/_internal**",
    "lib/methods/arrays/sumAF.js"
  ]
}
```

**Comment by ScottRudiger** [comment]
@coreyfarrell Thank you! The relative paths was my issue. Removing the `./` fixed everything. I must have missed this on the changelog.

**Comment by coreyfarrell** [comment]
I'm not sure it was specifically mentioned in the change-log, this could be one of those edge-case issues caused by test-exclude replacing micromatch with minimatch.  I've opened istanbuljs/istanbuljs#402 to investigate this further.
