### ISSUE TITLE
Instrumentation differences between nyc and istanbul, the old one

### ISSUE THREAD

**Issue by AndrewFinlay** [istanbuljs/nyc#1118]
I've been moving my client side tests from istanbul to nyc and have noticed an issue in the way nyc classifies statements.  In the following statement `for (var i = 0; i < env.count; i++)` nyc considers the whitespace between `=` and `0` to also be a statement.

## Link to bug demonstration repository
[min reproduction](https://github.com/AndrewFinlay/nyc_instrumenter_issue_min)

Run with npm test.
This will run nyc@latest and istanbul@0.4.5 instrumentation on a test file and produce two files in the root directory, 'statementMap_nyc.txt' and 'statementMap_istanbul.txt'.  Each file will contain prettified statementMaps extracted from instrumented source files created under both nyc and istanbul.  

There will be an entry in nyc's output that's not found in istanbuls, corresponding to some  whitespace in the for loop.

```
            2: {
                start: {
                    line: 11,
                    column: 17
                },
                end: {
                    line: 11,
                    column: 18
                }
            },
```

## Expected Behavior
nyc considers `for (var i = 0; i < env.count; i++)` to be a statement, but not the whitespace between the `=` and the `0`.

## Observed Behavior
nyc considers the whitespace between the `=` and the `0` to be a statement.

### Troubleshooting steps
None taken, I'd assume this should work out of the box.

## Environment Information

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
    Memory: 1.63 GB / 32.00 GB
  Binaries:
    Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.15.0/bin/npm
  npmPackages:
    istanbul: ^0.4.5 => 0.4.5 
    nyc: ^14.1.1 => 14.1.1 

```

**Comment by coreyfarrell** [comment]
istanbul-lib-instrument columns start from 0.  You can see this if you add a line-feed to your src/index.js:
```js
'use strict';

(function(env) {
    // Nyc's instrumenter thinks that the space between '=' and '0' below is a statment
    for (var i = 
0; i < env.count; i++) 
    {
        console.log('Running ' + i + ' of ' + count + '.');
    }
})(this);
```

With this modified source you would see statement 2 start at column 0 and end at column 1.  This is reporting the assignment as a statement.  The actual bug I see this demo repo showing is that `i < env.count` is not seen as a branch and `i++` is not seen as a statement.  Originally all statements inside the `for` were ignored, istanbuljs/istanbuljs#188 enabled instrumentation for the initialization of the loop.

**Comment by AndrewFinlay** [comment]
Hi Corey, thanks for the background on this it makes a little more sense now.  

I probably should have called this issue 'Instrumentation differences between nyc and istanbul, the old one'.  Anyway I think the crux of my problem now is that the `var i =` part of `var i = 0` of an assignment expression is no longer included in the listing in the statement map.  From a multiple variable declaration point of view it kind of makes sense but I'm still not clear on why the statement part would be `0` and not `i = 0`.

**Comment by coreyfarrell** [comment]
What we're discussing is actually istanbul-lib-instrument.  I'm not sure if it can include the `i = ` part of a declaration.  This is not specific to `for(...)`.  We currently have:
* `var i;` - declaration is not considered a statement
* `var i = 0;` - the assignment expression `0` is considered a statement, the declaration still is not
* `i = 1;` - not a declaration so the entire thing is the statement.

This is partly the result of how babel works but I also think it's not necessarily wrong.  I'm not sure how coverage `i = 0` of `var i = 0` would be accomplished.

**Comment by AndrewFinlay** [comment]
It sounds like this is a low priority heading towards won't fix, and I'm happy to live with this as it is.  I did have another question regarding differences in function mappings and how it affects reporting, but after doing some digging that all seems to be answered by [istanbuljs/istanbuljs#285](https://github.com/istanbuljs/istanbuljs/issues/285).  

So to sum up, I suppose it's as simple as instrumentation in nyc is different to instrumentation in istanbul, and this will affect the results presented in any reports.
