### ISSUE TITLE
issue while doing npm run test

### ISSUE THREAD

**Issue by imdebashree** [istanbuljs/nyc#1119]
Hello everybody,
When generating an html coverage report with
 "test:unit": "CONF_DIR=${BPA_CORE_DIR}/build/data nyc mocha",
when i am doing npm run test:unit , the following error is occured:
# paste the output here

![Screenshot from 2019-05-15 18-38-15](https://user-images.githubusercontent.com/31128318/57778003-c6e4b380-7740-11e9-92dc-efcde123a558.png)
![Screenshot from 2019-05-15 18-37-59](https://user-images.githubusercontent.com/31128318/57778004-c77d4a00-7740-11e9-9d97-a343ffa5020e.png)

**Comment by coreyfarrell** [comment]
This report does not contain any of the required information.  Please follow the new issue instructions and provide all required information.  https://raw.githubusercontent.com/istanbuljs/nyc/master/.github/ISSUE_TEMPLATE.md
