### ISSUE TITLE
json-summary causes a crash

### ISSUE THREAD

**Issue by frank-long** [istanbuljs/nyc#1120]
## Expected Behavior

Expected a json summary file to be created

## Observed Behavior

A crash processinfo folder appeared instead on the summary

**Comment by coreyfarrell** [comment]
I just did a quick test against one of my own repos, no crash on the json-summary report.  Please provide all required information requested by the new issue template: https://raw.githubusercontent.com/istanbuljs/nyc/master/.github/ISSUE_TEMPLATE.md.
