### ISSUE TITLE
How can I merge different rows in to single one in coverage.json?

### ISSUE THREAD

**Issue by ldy2009** [istanbuljs/nyc#1121]
I have one coverage.json file. And it contains some rows in it. Generally, all the paths in this json are distinct. But in my test scenario, some of them can be considered as the same. (Some paths are generated by joining /temp/ in it.) I can filter them out but how can I merge their corresponding value (statementMap etc.) together? Is there any APIs or commands of Istanbul be enable this functionality?

```
{
    "C:\\Report\private\reporting-ux\index.js": {
        "statementMap": {....},
        "fnMap": {......}
        ...
    },
    "C:\\Report\temp\private\reporting-ux\index.js": {
        "statementMap": {......},
        "fnMap": {......}
        .....
    }
} 
```

### Expectation Behavior
```
{
    "C:\\Report\private\reporting-ux\index.js": {
        "statementMap": {merged data},
        "fnMap": {merged data}
        ...
    }
} 
```

**Comment by coreyfarrell** [comment]
If `C:\\Report\temp\private\reporting-ux\index.js` has a source-map referring to the original source at `C:\\Report\private\reporting-ux\index.js` then this should happen automatically in nyc reports.  If you have the necessary source-maps then `nyc report -r json` should produce coverage/coverage-final.json`.

**Comment by coreyfarrell** [comment]
Did my suggestion help?  If not you will need to post a demo repository.
