### ISSUE TITLE
nyc not generating report

### ISSUE THREAD

**Issue by mega6382** [istanbuljs/nyc#1122]
Link to bug Demo repo: https://github.com/mega6382/nyc-bug-demo

I am using nyc with mocha to generate reports for my tests in html and lcov, it was working fine until recently but then it suddenly stopped working even though I haven't changed anything.

## Expected Behavior

Tests should run and return a proper test report in html and lcov

## Observed Behavior

No report is generated

## Environment Information
Node v10.15.1
Npm 6.9.0
 run the following script: 

```
  npm install
  npm test
```

Here is the out put that I get now:

```
  Test Express Server on 3000 port
    √ Send Request(Server Test)


  1 passing (62ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by coreyfarrell** [comment]
Providing information requested in the new issue template is not optional.  Please look at https://raw.githubusercontent.com/istanbuljs/nyc/master/.github/ISSUE_TEMPLATE.md and provide the required information.

**Comment by zelein** [comment]
I just noticed this as well.

How I invoke nyc: `nyc --reporter=html --reporter=text mocha`

My mocha.opts:
```
--require mocha-clean
--require source-map-support/register
--reporter spec
--timeout 2000
--delay
--exit
test/integration/
test/module/
```

**Comment by mega6382** [comment]
@coreyfarrell I have added a demo repo, is this ok now?

**Comment by coreyfarrell** [comment]
@mega6382 yes.  I believe you need to configure `extension` to nyc:
```js
  "nyc": {
    "exclude": [
      "**/sentryHelper.*",
      "**/*.test.*"
    ],
    "extension": [
       ".ts"
    ],
    "reporter": [
      "lcov",
      "text"
    ]
},
```

nyc@14 requires that `extension` match the original source filename (`.ts` in your case).  In nyc@15 the `extension` option will include `.ts` by default.

**Comment by mega6382** [comment]
@coreyfarrell Thanks, just checked and it seems that i updated nyc 11 days ago from 13.3.0 to 14.1.1 and it probably started failing after that. 

Thanks for your help, it is working now.
