### ISSUE TITLE
NPM install of nyc@14 having a JSON parse error

### ISSUE THREAD

**Issue by LukastBorges** [istanbuljs/nyc#1123]
## Link to bug demonstration repository
https://github.com/LukastBorges/nyc-bug-demo

## Expected Behavior
Running a `npm i` on the repository should install all dependencies and have no errors.
## Observed Behavior
After upgrading nyc package to 14.x.x this started showing up when running npm:
`npm ERR! Unexpected end of JSON input while parsing near '...,"standard":"^4.3.2",'`
### Troubleshooting steps
- I've tested on a completed isolated repository, and going back to version 13 it does not happen.

## Environment Information

```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 3.64 GB / 16.00 GB
  Binaries:
    Node: 8.15.0 - /usr/local/opt/node@8/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@8/bin/npm
```

**Comment by coreyfarrell** [comment]
I do not receive any error from `npm i` on the demo repo you linked.  Maybe you were connected to a corrupted npm mirror earlier?  Please try again.

**Comment by LukastBorges** [comment]
Really? I've ran with a different network and using the `--cache /tmp/empty-cache` option and despite having the error it was a different one:
```
npm ERR! Unexpected end of JSON input while parsing near '....5.3","phantomjs-preb'
```
It might be a mirror issue after all then. Sorry for rushing into open this issue :/.
Thanks for the time taken into!

**Comment by coreyfarrell** [comment]
The string `phantomjs-preb` is not found inside nyc or any of it's direct/indirect dependencies.  This shows that it is not an issue with nyc.  I suggest posting a support request at https://npm.community/ since this appears to be an npm issue.

**Comment by LukastBorges** [comment]
Okey, thanks man.
