### ISSUE TITLE
Coverage report of built app doesn't map to source files

### ISSUE THREAD

**Issue by evanbb** [istanbuljs/nyc#1125]
## Link to bug demonstration repository

[Repro repo](https://github.com/evanbb/nyc-instrument-and-report-bug)

I think I followed the docs correctly, but it's certainly possible I missed a step 🤣 

## Expected Behavior

According to [this](https://github.com/istanbuljs/nyc#source-map-support-for-pre-instrumented-codebases), running a coverage report for a built app should map back to original source files.

Steps taken in above repo:
1. Create empty app using `create-react-app`
1. Build app, which generates sourcemaps
1. Following [these docs](https://github.com/istanbuljs/nyc/blob/master/docs/instrument.md), instrument build output using `nyc instrument ./static ./static-i`
1. Swap `static` directories so instrumented code is served
1. Run automated tests, aggregating `window.__coverage__`
1. Following [these docs](https://istanbul.js.org/docs/advanced/coverage-object-report/), dump coverage data to `.nyc_output/out.json`
1. Run `nyc report --reporter=html`

## Observed Behavior

The report shows coverage for built files, not source files.

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 242.63 MB / 16.00 GB
Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm

```

**Comment by evanbb** [comment]
For more context, I can run `remap-istanbul` and that generates reports (mostly) correctly, but I'd like to move to the currently supported version of IstanbulJS.

**Comment by bcoe** [comment]
@evanbb try setting the configuration setting "remap-after-coverage" to `false`.

**Comment by evanbb** [comment]
@bcoe thanks - I gave it a go with command below:

`npx nyc report --remap-after-coverage=false --reporter=html`

However, it seems to produce the same result with or without that option set. I also tried setting it in my `package.json`, but that didn't seem to work, either.

I also tried with `--exclude-after-remap=false` as suggested [here](https://github.com/istanbuljs/nyc#source-map-support-for-pre-instrumented-codebases), but no luck 😞

Do those flags need to be set at time of instrumentation instead of at time of reporting?

**Comment by evanbb** [comment]
Hmm, tried running with those options during instrumentation and got the same result 😞

**Comment by bcoe** [comment]
@evanbb mind sharing a repository that's having the issue you're describing?

**Comment by evanbb** [comment]
@bcoe sure thing: https://github.com/evanbb/nyc-instrument-and-report-bug

I stepped into it a bit, and it looked like the reporting logic is trying to reload the sourcemaps from cache here:

**Comment by 7Pass** [comment]
I'm having the same problem.

When using `nyc instrument`, the `window.__coverage__` is generated for the compiled files instead of source files. `nyc report` then shows empty report because the `window.__coverage__` values does not have `contentHash`, only `hash`.

I've also tried adding the instrumentation during the build step using `babel-plugin-istanbul`. Using this approach, `window.__coverage__` is generated for the correct source files. However, `nyc report` again shows empty report because even in this case, `window.__coverage__` does not have `contentHash` value.

So I think we have two separate issues
* How to make `nyc instrument` process source maps?
* How to make `nyc report` accepts coverage data stored in `window.__coverage__`?

**Comment by bfrizbee** [comment]
I am having this exact issue. I didn't see this issue when creating my own so i will close mine because this has exact process I went through even when I tried debugging on my own. I need the coverage to map to the source files because of multiple reasons.

**Comment by bfrizbee** [comment]
Are you supposed to instrument the code before it is transpiled? Because there isn't any clear documentation on that, so maybe that is my issue

**Comment by evanbb** [comment]
this appears to still be an issue - i updated dependencies and spelled out repro steps in the repo linked above - hopefully its something obvious 😆
