### ISSUE TITLE
Instrumentation of typescript file with public modifier fails

### ISSUE THREAD

**Issue by michaeljholmes** [istanbuljs/nyc#1126]
Instrumentation fails when trying to instrument the following file (animal.ts)
*nyc instrument animal.ts Animal -e .ts --exit-on-error*
```javascript
class Animal {
  public name: string;
  public constructor(theName: string) { this.name = theName; }
  public move(distanceInMeters: number) {
    console.log(`${this.name} moved ${distanceInMeters}m.`);
  }
}
```

## Expected Behavior
Instrumented file outputed
## Observed Behavior
error - *Failed to instrument \animal.ts*

When I remove the public modifiers, everything works fine.
```javascript
class Animal {
  name: string;
  constructor(theName: string) { this.name = theName; }
  move(distanceInMeters: number) {
    console.log(`${this.name} moved ${distanceInMeters}m.`);
  }
}
```

**Comment by coreyfarrell** [comment]
To get this working you need to set `parser-plugins` in your nyc config.  Put the following in your package.json:
```js
{
  "nyc": {
    "parser-plugins": [
      "typescript"
    ]
  }
}
```
Note that this completely replaces the default parser plugins, see https://github.com/istanbuljs/istanbuljs/blob/5b4ee889b147fa1ab85ad12a27533510f8588023/packages/istanbul-lib-instrument/src/instrumenter.js#L26-L37 for the full list.  If you copy the other parser plugins from that list you must exclude `flow` as babel does not allow flow and typescript to be combined.
