### ISSUE TITLE
Inconsistent behavior with ./ in .nycrc

### ISSUE THREAD

**Issue by basickarl** [istanbuljs/nyc#1127]
Using nyc version 14.1.1

```
    "exclude": ["./.ignore/**/*"] // doesn't work
    "exclude": [".ignore/**/*"] // works.
```

The `./` works on other fields such as on `"report-dir": "./coverage",`

**Comment by coreyfarrell** [comment]
This is an issue in `test-exclude`, so it effects `exclude` and `include`.  Issue posted at https://github.com/istanbuljs/istanbuljs/issues/402.
