### ISSUE TITLE
Merging multiple .nyc_output from different locations

### ISSUE THREAD

**Issue by danziamo** [istanbuljs/nyc#1129]
Hi, just a small question.

I use this tool to do coverage on ejs templates. Due to specification of the project that i am working, I have multiple .nyc_output directories that shows coverage on the same ejs templates.
Is there any way to merge them and probably generate html report?

Thanks for this amazing tool.

**Comment by bcoe** [comment]
@danziamo you should be able to move all the raw JSON files into a single folder, than run `nyc report` (rather than running the `nyc foo.js` which performs instrumentation).

This might be worth adding documentation for in the README, if you find this approach works for you perhaps you'd be willing to pitch in?

**Comment by coreyfarrell** [comment]
You can also run `nyc merge source-dir dest-file.json` on each directory.  We do this with the istanbuljs monorepo, see https://github.com/istanbuljs/istanbuljs/blob/master/monorepo-merge-reports.js.  In that monorepo each package writes coverage to `packages/${packageName}/.nyc_output`.  Then we run monorepo-merge-reports.js to merge each of those directories to `.nyc_output/${packageName}.json`.  From there we run `nyc report` which runs reports against the root `.nyc_output` (see the posttest script in https://github.com/istanbuljs/istanbuljs/blob/master/package.json).

An example command run by monorepo-merge-reports.js is `nyc merge packages/test-exclude/.nyc_output .nyc_output/test-exclude.json`.

**Comment by danziamo** [comment]
Thanks, that worked for me.

**Comment by yjjnls** [comment]
@coreyfarrell I do as you said, but when I run nyc report finally, it reports nothing.

**Comment by coreyfarrell** [comment]
@yjjnls this issue is closed.  Please open a new issue and include all requested information.
