### ISSUE TITLE
Green coverage % for test files but 0% coverage for code files

### ISSUE THREAD

**Issue by anushreesingh** [istanbuljs/nyc#1131]
My package.json looks like this:

```"scripts": {
    "start": "node ./index",
    "test": "mocha --recursive --exit",
    "coverage": "nyc npm test"
  },
  "nyc": {
    "include": [
      "components**"
    ],
    "extension": [
      ".js"
    ],
    "reporter": [
      "text-summary",
      "lcov"
    ],
    "cache": false,
    "all": true
  }
```

When I run nyc run coverage, all tests run successfully but nyc reports 0% coverage for code called from tests but ~100% coverage for test files: 

<img width="1679" alt="Screen Shot 2019-06-18 at 4 56 08 PM" src="https://user-images.githubusercontent.com/14081864/59668340-e319bb80-91ea-11e9-9d30-a3965474cf85.png">

Can someone help me understand what am i doing wrong here?

**Comment by justinwilaby** [comment]
I'm having the same problem. 97% coverage with v13.1.0 then updating to v14.1.1 results in 0% coverage with no changes in the config.

**Comment by bcoe** [comment]
@anushreesingh could you please provide a minimal reproduction of the issues you are seeing?

@justinwilaby likewise, but also it might be worth opening a new issue; as there are many different test configurations, and there's a good chance you're bumping into a slightly different issue than @anushreesingh.
