### ISSUE TITLE
Support in-place instrumentation (again)

### ISSUE THREAD

**Issue by DanTup** [istanbuljs/nyc#1135]
It used to be possible to instrument in-place, but this is rejected since https://github.com/istanbuljs/nyc/pull/1007.

It's not clear from the PR why, but it broke things for me, and trying to use a different folder is complicated (because there are many paths into the JS folder).

I understand this can be risky, but in my case it's just the transpiled output of typescript. It'd be nice if this was supported, even if you had to pass an extra flag to opt-in to it.

**Comment by coreyfarrell** [comment]
We require a link to a repository showing an example project where this not working.

**Comment by DanTup** [comment]
All you need to do is run `npm instrument` with the same input/output on any project. The code checks for this and exits with an error (as of the PR linked above):

https://github.com/istanbuljs/nyc/blob/4bc9c146d18c988dda2a7c20bce8d861c370245e/lib/commands/instrument.js#L96-L99

I haven't committed the upgrade that breaks this because I need my coverage to work in the meantime. This is a feature request to support this again.

**Comment by coreyfarrell** [comment]
@AndrewFinlay do you have any thoughts?  I know this needs to be blocked if `--delete` is enabled, outside of that I'm just not sure.  It seems dangerous to rewrite files in-place, though it appears that `@babel/cli` allows it (a bug or a feature?).

@DanTup If you provided a link to a repository which uses in-place instrumentation I might be able to suggest a better way.  Maybe `nyc instrument --complete-copy=true src dest` could work for you.

**Comment by DanTup** [comment]
> It seems dangerous to rewrite files in-place

Many things are dangerous, but making them impossible is really restrictive. This feature used to work, and I'm running it on the output of TypeScript so there's really no problem. You could make a `--force` or `--some-really-scary-flags-that-acknowledge-the-danger` flag if you're concerned people won't understand - but taking it away just means people will hang around on old versions if there's no easy way to switch to out-of-place instrumentation.

I did try for some time to make the new version work, but there many places reference this folder (such as all the VS Code test entry points) so I gave up and just rolled back (I'd already spent several hours trying to get this working again after adding webpack - after spending many hours getting it working the first time!).

My setup is super-janky (for a whole host of reasons, involving VS Code, webpack, mismatched source map paths between packed/unpacked and some weird behaviour from nyc depending on which folder it's executed from within):

https://github.com/Dart-Code/Dart-Code/blob/7c64f5e3de13afa1c64f4b0a56877e74d7264c3a/package.json#L1454-L1468

https://github.com/Dart-Code/Dart-Code/blob/7c64f5e3de13afa1c64f4b0a56877e74d7264c3a/src/test/remap_coverage.ts

https://github.com/Dart-Code/Dart-Code/blob/7c64f5e3de13afa1c64f4b0a56877e74d7264c3a/src/test/test_runner.ts#L10-L22

Maybe it can be simplified, but everything I tried (even just trying to eliminate things like all those wonky `cd foo/foo && xxx && cd ../..` calls would break things 😞

**Comment by AndrewFinlay** [comment]
Hi @DanTup & @coreyfarrell,

I've been a bit busy of late so I've had to put my nyc work to the side.  However it turns out the last thing I was working on back in mid May was a switch to allow in-place instrumentation, so I guess that means I agree with Dan that it's needed.  It'll need a bit more work to get it finished with tests, I'll try and find some time to finish it off today.  It should be suitable for a minor release when done.

@coreyfarrell, I was originally thinking of naming the switch 'overwrite' with an alias of '-o', but I think I like Dan's name of 'force' better, your thoughts?

**Comment by coreyfarrell** [comment]
@AndrewFinlay semver-major changes have already been committed to master, we're currently working towards nyc@15.0.0.  I'm thinking `nyc instrument --allow-in-place foo foo`.  Throw an error for same directory if `--allow-in-place` is not enabled or if `--delete` is enabled.  I'd rather we don't have a short alias for this option.  `overwrite` isn't great because `nyc instrument src dest` will already overwrite dest/file.js if it exists and src/file.js is processed.

**Comment by DanTup** [comment]
This all sounds good to me! @AndrewFinlay it's not urgent for me to upgrade, so don't worry about rushing to finish this for me, as long as it's coming in the future it prevents me getting stuck on an old version :-) Thanks!

**Comment by AndrewFinlay** [comment]
@coreyfarrell, I was writing some documentation for this when it struck me that specifying the output directory for this command is a little redundant.  So I'm wondering if the command should still be
`nyc instrument --allow-in-place <source> <dest>` or if `nyc instrument --in-place <source>` was better?

**Comment by papb** [comment]
I would also like to see this feature, and I agree with @AndrewFinlay that `nyc instrument --in-place <source>` is the best option!

**Comment by coreyfarrell** [comment]
@AndrewFinlay `--in-place` and throwing an error if a second argument is given probably makes sense.  Also I forgot to mention in addition to `--delete` I think `--complete-copy` should probably exit with an error if combined with `--in-place`.

**Comment by papb** [comment]
-- comment to counter stalebot --

**Comment by coreyfarrell** [comment]
The fix for this was merged in #1149 (it was an accident that we didn't close this ticket when that merge occurred).  For progress on a new release please subscribe to #1104, this is where I will announce any beta releases and eventually the final release of nyc 15.
