### ISSUE TITLE
Empty html report using version 14+ (fine with v13 and below)

### ISSUE THREAD

**Issue by areel** [istanbuljs/nyc#1136]
## Link to bug demonstration repository
https://github.com/areel/nyc-bug-demo.git

## Expected Behavior
issuing 

 `nyc report --reporter=html`

should generate a full report based on content of 

`./nyc_out/out.json` 

## Observed Behavior
Using versions  14.0.0 and higher an empty html report is produced, 
Using latest releases of 10.X, 11.X, 12.x and 13.x all work as expected

## Steps to observe issue
I have edited the original out.json to have only one instrumented module and edited the reference path to allow drilling into module. Follow steps below to see issue.

- clone repo
- yarn (using version 14.0.0 of nyc)
- yarn report 
- coverage/index.html (does not contain expected content)
- coverage/alert.constants.ts.html (does not exist)
- delete yarn.lock
- delete node_modules
- delete coverage
- edit package.json dev dependency to  be
``` 
"devDependencies": {
           "nyc": "^13.0.0"
}
```
- save package.json !!
- yarn
- yarn report
- code coverage html report is correct
   - index.html has reference to alert.constants.ts.html
   - alert.constants.ts.html exists in coverage folder

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config
- [x] does not occur in latest release of versions 10,11,12 and 13

## Environment Information

```
System:
    OS: Linux 5.0 Manjaro Linux undefined
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
    Memory: 11.33 GB / 31.40 GB
  Binaries:
    Node: 11.6.0 - ~/.asdf/shims/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.asdf/shims/npm

```

**Comment by bcoe** [comment]
@areel would you be able to provide a link to a project that generates the report in `.nyc_output`? as indicated, it seems as though the raw information contains no coverage data.

**Comment by areel** [comment]
When run using _nyc@13.3.0_ the html report contains coverage information for the file alert.constants.ts in alert.constants.ts.html that is available via index.html.

Could you expand on
 
> it seems as though the raw information contains no coverage data

for me, that might give me some insight in order to investigate on my side.

It is not possible to provide the requested link, but I will see if I can create one.

**Comment by bcoe** [comment]
@areel I apologize I was mistaken, I was looking at:

https://github.com/areel/nyc-bug-demo/blob/master/.nyc_output/out.json

It does indicate that the first line of the application was executed once.

**Comment by areel** [comment]
@bcoe Thats all fine, I have created a demo [repo](https://github.com/areel/CRA-TypeScript-Cypress-Istanbul-CRACO.git) that creates an instrumentation _out.json_ and it exhibits the same issue i.e an empty report.

It might still be useful in being able to generate test instrumentation for you.

Be warned there is a lot going on in there. It is the stereotypical TypeScript based demo react app as created via [create-react-app](https://www.npmjs.com/package/create-react-app) with the _--typescript_ flag set. The instrumentation is created by executing tests via the [Cypress](https://www.cypress.io/) framework runner enhanced with [cypress-coverage](https://www.npmjs.com/package/@cypress/code-coverage) to collate and produce the report.
All that being said, everything works correctly if we use a version of nyc less than version 14. 
Just for completeness, this can be observed by following:
- download [repo](https://github.com/areel/CRA-TypeScript-Cypress-Istanbul-CRACO.git)
- yarn
- yarn start (this is using version nyc@^13.0.0
- open another terminal
- yarn cypress:open
- click Run all specs button in cypress control panel
- open coverage/index.html
  - observe code coverage info
- repeat above after modifying nyc entry in package.json to reference version 14+
  - out.json still created but html report is "empty"

hope this helps.

**Comment by coreyfarrell** [comment]
@areel please add `"extension": [".ts"]` to your `nyc` configuration.  This is required in nyc@14 otherwise `.ts` files will be filtered out of the report.  Note that this will be fixed in nyc@15, unfortunately we could not expand the default `extension` list in nyc@14 due to concern that it might break something.

**Comment by areel** [comment]
Can confirm that worked, thanks to both of you for your time.
