### ISSUE TITLE
nyc instrument not all ts files

### ISSUE THREAD

**Issue by haameeen** [istanbuljs/nyc#1137]
I'm trying to get coverage for TS files for user testing, but it does not seem to be working at Instrumentation.
Basically, I'm trying "istanbul instrument" approach which is working for us for JS files; but we have other project with TS files for which istanbul does not support but looks like nyc does as per nyc README.md.
https://github.com/istanbuljs/nyc/blob/master/docs/instrument.md

### Command
- nyc instrument "input_dir\layout.module.ts" "input_dir_instrumented" --extension ".ts" 
- nyc instrument "input_dir\layout.module.ts" "input_dir_instrumented\layout.module.ts" --extension ".ts"
Please find layout.module.ts here: https://github.com/haameeen/Insturment-TypeScript

### Expected Behavior
(All) TS file should be instrumented

### Observed Behavior
Not all TS file should be instrumented. Only certain ~5% done. No pattern found where it does not instrument.
... Failed to instrument C:\Users\Hamin\...\layout.module.ts

### Troubleshooting steps
1 - nyc instrument "inputdir\" "inputdir_instrumented\" --extension ".ts"
2 - open "inputdir_instrumented\" and check all *.ts files
3 - see everything is instrumented

**Comment by coreyfarrell** [comment]
A link to a minimal repository demonstrating your issue is required.

**Comment by haameeen** [comment]
> A link to a minimal repository demonstrating your issue is required.

Would this help? https://github.com/haameeen/Insturment-TypeScript

**Comment by papb** [comment]
@haameeen That link gives a 404 for me...

**Comment by haameeen** [comment]
> @haameeen That link gives a 404 for me...

Is it because I created it as Private? does it need to be public?

**Comment by haameeen** [comment]
> @haameeen That link gives a 404 for me...

Please try now. I've enabled 'Allow GitHub to perform read-only analysis of this repository'. or it needs to be public only?

**Comment by haameeen** [comment]
Does nyc support instrumentation/code coverage for TS files, the way istanbul works for JS files?

**Comment by coreyfarrell** [comment]
Your repo needs to be public otherwise nobody can see it.

nyc does support TS but you have to enable/configure this feature.  Please see https://www.npmjs.com/package/@istanbuljs/nyc-config-typescript.

**Comment by haameeen** [comment]
Ok, made it public now. please try again.

Tried with "npm i -D nyc source-map-support ts-node @istanbuljs/nyc-config-typescript" but no luck.
...
npm WARN ngx-drag-scroll@7.0.0 requires a peer of tsickle@^0.33.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ source-map-support@0.5.12
+ ts-node@7.0.1
+ nyc@14.1.1
+ @istanbuljs/nyc-config-typescript@0.1.3

**Comment by coreyfarrell** [comment]
Your repo does not include a package.json.  It should be possible for someone to git clone your repo then run `npm install && npm test` to see your issue.

**Comment by haameeen** [comment]
> Your repo does not include a package.json. It should be possible for someone to git clone your repo then run `npm install && npm test` to see your issue.

Actually, could you not take the source file I shared in the repo and see why nyc is not able instrument it? 
This is what I also have in my package.json. Do I need .nycrc as well with same content; where?
...
"nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true,
    "check-coverage": true,
    "extension": [
      ".js",
      ".jsx",
      ".ts",
      ".tsx"
    ]
  }
...

Here is the command line I use:

nyc instrument "input_dir\layout.module.ts" "input_dir_instrumented" --extension ".ts" 
nyc instrument "input_dir\layout.module.ts" "input_dir_instrumented\layout.module.ts" --extension ".ts"

**Comment by papb** [comment]
@haameeen - Actually I think you should update your demonstration repository until anyone can clone it and run `npm install` and then `npm test` to see your problem, as coreyfarell said. Your split (and unformatted) explanations take a long time to try to understand...

Your repository should be a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by haameeen** [comment]
@papb , I've updated description with more details, would that help now? Looks like it is similar to this: https://github.com/istanbuljs/nyc/issues/1126

**Comment by haameeen** [comment]
> @haameeen - Actually I think you should update your demonstration repository until anyone can clone it and run `npm install` and then `npm test` to see your problem, as coreyfarell said. Your split (and unformatted) explanations take a long time to try to understand...
> 
> Your repository should be a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

@papb  @coreyfarrell , I've uploaded this new repo for the same issue where I can repro the issue. Please help to take look at that; let me know if addition info is required.

https://github.com/haameeen/nyc-instrument-TypeScript-failed

**Comment by haameeen** [comment]
> Your repo does not include a package.json. It should be possible for someone to git clone your repo then run `npm install && npm test` to see your issue.

Hi @papb @coreyfarrell , I've uploaded this new repo for the same issue where I can repro the issue. Please help to take look at that; let me know if addition info is required.

https://github.com/haameeen/nyc-instrument-TypeScript-failed

Install: npm i -D nyc
Usage: C:\..\Downloads\angular-tour-of-heroes-master>nyc instrument "src" "src_instrumented"

**Comment by papb** [comment]
@haameeen Hello! It seems that your repository is still incomplete. For instance, where is the `app-routing.module.ts` file?

**Comment by haameeen** [comment]
> @haameeen Hello! It seems that your repository is still incomplete. For instance, where is the `app-routing.module.ts` file?

please check now

**Comment by papb** [comment]
I see more files but many files yet seem to be missing...

There are no folders in your repository. Probably some folders should be there? (Like `app`)

Please compare your own github repository with every file and folder you have in your local folder.

**Comment by haameeen** [comment]
> I see more files but many files yet seem to be missing...
> 
> There are no folders in your repository. Probably some folders should be there? (Like `app`)
> 
> Please compare your own github repository with every file and folder you have in your local folder.

I think it didnt upload dirs. I had to drag-drop. pls check now.

**Comment by papb** [comment]
Nice. I managed to reproduce your issue now. Now @coreyfarrell will be able to help you. Good luck!

**Comment by haameeen** [comment]
> Nice. I managed to reproduce your issue now. Now @coreyfarrell will be able to help you. Good luck!

Great thanks. @haameeen Let me know for any additional details required. thanks. 
We've have been using 'istanbul instrument' for JS code for long time; so I hope we can achieve the same with 'nyc instrument' for TS as well.

**Comment by haameeen** [comment]
> Nice. I managed to reproduce your issue now. Now @coreyfarrell will be able to help you. Good luck!

Hi @coreyfarrell , how does is look? is that my setup issue or something needs to be fixed/enhanced?

**Comment by haameeen** [comment]
@coreyfarrell  @papb , did it work? Would it be feasible to fix to add nyc instrument support for TS files?

**Comment by haameeen** [comment]
@coreyfarrell , @papb , any update? Is this fixable or we should look for another solution/tool?

**Comment by papb** [comment]
@haameeen I am not a maintainer, I was just passing by and tried to help you clarify the problem. Because you did not describe it completely at the first time. I can't do anything else, sorry about that, good luck with coreyfarrell. But I think you are being too hurried, open source things take more time... Good luck!

**Comment by haameeen** [comment]
> @haameeen I am not a maintainer, I was just passing by and tried to help you clarify the problem. Because you did not describe it completely at the first time. I can't do anything else, sorry about that, good luck with coreyfarrell. But I think you are being too hurried, open source things take more time... Good luck!

Thanks for the details. Yes, I'm new to this area so was not aware of the timing. In that case I'd just wait for coreyfarrell's findings; hopefully we'd have some fixes. Meantime I'll check for alternates too if there is any similar to nyc.

**Comment by haameeen** [comment]
Looks like it does not work when we add Angular stuff to TS file.

**Comment by haameeen** [comment]
Hello. Do we have any further update/fix for this?

**Comment by Yuanshandai** [comment]
I thinks you should modify : nyc instrument "input_dir\layout.module.ts" "input_dir_instrumented" --extension  .ts

or 
nyc instrument  input_dir\layout.module.ts  input_dir_instrumented --extension  .ts
