### ISSUE TITLE
Question, rather than a bug.

### ISSUE THREAD

**Issue by reduxdj** [istanbuljs/nyc#1139]
How do I get the nyc testrunner to follow absolute paths, or supply a webpack config to use to pre-compile the app before tests are executed?

**Comment by coreyfarrell** [comment]
nyc is not a test runner, you generally still need to use a testing framework like mocha, ava or tapjs.  In general though I don't understand your question,  you have not given enough infromation.  Are you trying to test a node.js app/library or another environment (browser/electron)?

**Comment by reduxdj** [comment]
Hi, thanks, sorry for the mixup. The problem I was having that I solved, was the issue was that running nyc-test runner with mocha and webpack needs a small addition to the require method, that webpack actually extends... For Example:

```js
if (typeof require.context === 'undefined') {
  const fs = require('fs');
  const path = require('path');

  require.context = (base = '.', scanSubDirectories = false, regularExpression = /\.js$/) => {
    const files = {};

    function readDirectory(directory) {
      fs.readdirSync(directory).forEach(file => {
        const fullPath = path.resolve(directory, file);

        if (fs.statSync(fullPath).isDirectory()) {
          if (scanSubDirectories) readDirectory(fullPath);

          return;
        }

        if (!regularExpression.test(fullPath)) return;

        files[fullPath] = true;
      });
    }

    readDirectory(path.resolve(__dirname, base));

    function Module(file) {
      return require(file); //eslint-disable-line
    }

    Module.keys = () => Object.keys(files);

    return Module;
  };
}

const context = require.context('./src', true, /\.jsx?$/);
context.keys().forEach(context);
module.exports = context;
```
This allows me to use absolute paths in m project and use webpack to build my modules for tests.
Again, thanks.
