### ISSUE TITLE
Estimated release date for 14.1.2

### ISSUE THREAD

**Issue by katywings** [istanbuljs/nyc#1146]
##  Expected Behavior
New nyc version with https://github.com/istanbuljs/nyc/commit/914b776215ad3ea54f0e46b4ba2904a8a9d4dfdd would be :heart: 

## Observed Behavior
Current version still having extension = "[]" :D

### Troubleshooting steps
- Install current nyc version
- Try to instrument a project with ts files

Do you know when the 14.1.2 will release? 

Anyways keep up the great work :+1:

**Comment by coreyfarrell** [comment]
There will not be a 14.1.12 release, we are currently working towards 15.0.0.  You can follow #1104 for progress on this.  Although 914b776 is not marked as a breaking change we were concerned about making that change in a non-major version.
