### ISSUE TITLE
Naming report files?

### ISSUE THREAD

**Issue by basickarl** [istanbuljs/nyc#1150]
Hi! I'm curious, is it possible to set the name of the coverage report file being produced?

For example, I have the following .nycrc.cobertura.json configuration file (for one of my tests, the other test has one but has a different report-dir), this produces a file called cobertura-coverage.xml. I will be running two test frameworks and would like to name these reports differently. Is this possible? As stated, I currently need to have the report-dir different for both tests, which is a bit ugly:
```
{
    "extends": "./.nycrc.json",
    "all": false,
    "report-dir": "./coverage_production/server",
    "reporter": ["cobertura"],
    "include": [
        "build_production/server/**/*.js",
        "server/**/*.ts"
    ]
}
```

**Comment by bcoe** [comment]
@basickarl :wave: hey; I understand it's potentially a bit messy, but I think that either using two different report directories, or _as an alternative_ running the first set of tests, moving the reports into a final location, then running the second set of tests is your best bet.

There's already quite a bit of flexibility around managing where temporary files and reports are located, I don't think (as a project) we want to extend this to the files generated by specific reports. nyc supports many reporting formats, and I feel this would ultimately turn into a painful number of configuration options.

Hopefully you can figure out a reasonable work around?
