### ISSUE TITLE
Tests Fail Under NYC, Pass Otherwise...

### ISSUE THREAD

**Issue by busticated** [istanbuljs/nyc#1158]
hey there :wave:

thanks for an awesome tool :pray:

i'm noticing something odd: i have a suite of end-to-end tests that i run against a CLI app. when run under `nyc`, a series of tests fail. when run normally, those same tests pass.

the error output doesn't provide any strong hints though all the tests that fail involve child process streams and interactions via `subprocess.stdin.write` and similar (but at the same time other tests which do the same thing pass so 🤷‍♂ ).

## Link to bug demonstration repository

https://github.com/particle-iot/particle-cli

1. `git clone git@github.com:particle-iot/particle-cli.git`
2. `npm i`
3. open `./test/e2e/library.e2e.js`
4. isolate [this test](https://github.com/particle-iot/particle-cli/blob/a4f5611ef7a7762f20ae81a207de1f3e01b4d87e/test/e2e/library.e2e.js#L168-L186) via `it.only()`
5. `nyc npm run test:e2e`

## Expected Behavior

test passes, coverage is reported

## Observed Behavior

test fails

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config
- [x] found #187 and tried the work-around proposed [here](https://github.com/istanbuljs/nyc/issues/187#issuecomment-193658454)
- [x] not running `yargs@6.2.0`

## Environment Information

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Memory: 215.66 MB / 8.00 GB
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 5.10.0 - /usr/local/bin/npm
  npmPackages:
    @babel/cli: ^7.5.5 => 7.5.5 
    @babel/core: ^7.5.5 => 7.5.5 
    @babel/preset-env: ^7.5.5 => 7.5.5 
    @babel/register: ^7.5.5 => 7.5.5 
    nyc: ^14.1.1 => 14.1.1 
```

**Comment by busticated** [comment]
ah, i forgot you need [some additional setup](https://github.com/particle-iot/particle-cli/blob/feature/coverage/test/README.md) in order to successfully run these tests.

if it helps any, you can see the tests passing over in travis [here](https://travis-ci.org/particle-iot/particle-cli/builds/572951922) - for example, here's the same test [passing](https://travis-ci.org/particle-iot/particle-cli/jobs/572951924#L783)

**Comment by coreyfarrell** [comment]
@busticated it looks like your feature/coverage branch is gone and `master` runs tests under nyc, is this issue resolved?

**Comment by busticated** [comment]
@coreyfarrell 

> is this issue resolved?

no, unfortunately. i've since merged the branch and am not currently running coverage for my end-to-end tests (but am running it for unit and integration tests). i updated the links in my posts here so they should be working again. thanks for taking a look :pray:

**Comment by coreyfarrell** [comment]
Unfortunately my time is extremely limited and your project is very large.  It would help if you pasted the error message produced when you run under nyc or a link to a travis log showing the failure.  I can't make any promises for when I'll be able to actually run your project tests.

**Comment by busticated** [comment]
> Unfortunately my time is extremely limited

i understand, no worries!

> It would help if you pasted the error message produced when you run under nyc

there isn't an error beyond the failing assertion:

```
AssertionError: expected [ '' ] to have a length of 23 but got 1
+ expected - actual

-1
+23
```

...which seems to hint that somehow `nyc` is impacting `stdout` and `stderr` output.

the test itself is:

```js
it('Lists libraries', async () => {
    const args = ['library', 'list'];
    const subprocess = cli.run(args);

    await delay(1000);
    subprocess.stdin.write('\n');
    await delay(1000);
    subprocess.cancel(); // CTRL-C

    const { all, isCanceled } = await subprocess;
    const lines = stripANSI(all).trim().split('\n');

    expect(lines).to.have.lengthOf(23);
    expect(lines[0]).to.equal('Community Libraries');
    expect(lines[11]).to.equal('Press ENTER for next page, CTRL-C to exit.Community Libraries page 2');
    expect(lines[22]).to.equal('Press ENTER for next page, CTRL-C to exit.');
    expect(isCanceled).to.equal(true);
});
```

running the above under `nyc` causes the above mentioned assertion failure. running without `nyc`, the test passes.
