### ISSUE TITLE
Lodash prototype pollution vulnerability

### ISSUE THREAD

**Issue by vidhyadharmaraj** [istanbuljs/nyc#1160]
## https://snyk.io/blog/snyk-research-team-discovers-severe-prototype-pollution-security-vulnerabilities-affecting-all-versions-of-lodash/

It seems the last version of nyc (14.1.1) requires the following packages:

"@babel/generator": "^7.4.4".
"@babel/traverse": "^7.4.5".
"@babel/types": "^7.4.4".

Unfortunately, these packages have a dependency of lodash "^4.17.11". Lodash version 4.17.11 has a prototype pollution vulnerability (as described in the https://github.com/lodash/lodash/wiki/Changelog#v41712) fixed at version 4.17.12.

babel has fixed it with v7.5.5 - https://github.com/babel/babel/issues/10226#issuecomment-512592466

I'm just creating the issue to notify this fact and request a dependency update

### Troubleshooting steps
- [ ] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
# paste the output here

```

**Comment by coreyfarrell** [comment]
We do not create new releases for in-range updates.  nyc is not the problem, it is your yarn.lock or package-lock.json preventing you from getting the latest version of lodash.  Please run `npm --depth 9999 update` or the equivalent yarn command.  Sorry I don't use yarn so I don't know the exact command that is required.
