### ISSUE TITLE
instrument command generates code before imports

### ISSUE THREAD

**Issue by Marc1190** [istanbuljs/nyc#1161]
When I use the following command:
```
npx nyc instrument --compact=false src instrumented
```
nyc generates new files that instrument the src code. The problem is that it initializes the variables before the imports. This is a big problem because if your build scripts check the code format it gives an error.

## Expected Behavior
When the code is instrumented you have to make sure that the variables for test coverage are initialized after the first imports.

## Observed Behavior
instrumentation process adds code before the imports section.

**Comment by coreyfarrell** [comment]
I'm sorry this is not a change we're able/willing to make as it would add much complexity and possibility of error.

```js
import {promisify} from 'util';
import fs from 'fs';

const mkdir = promisify(fs.mkdir);

import path from 'path';
```
This is perfectly valid JS and there are situations where this sort of thing happens, like if you need to call an initialization function from one module before importing another.

You will need to configure your linter to ignore build products, just check the original sources.
