### ISSUE TITLE
random coverage with all=true

### ISSUE THREAD

**Issue by Oloompa** [istanbuljs/nyc#1167]
Has this fix been published to npm ?

https://github.com/istanbuljs/nyc/commit/fc1bbbf490f6ab0272359ce10ceb4987d1716256

I ask cause the random behavior of coverage still happens with all set to true

**Comment by coreyfarrell** [comment]
It has not been released, you can follow #1104 for progress on the release.  Unfortunately my time has been taken over by other commitments for now so I do not currently have an ETA for any release.
