### ISSUE TITLE
Test coverage for a custom test library (like postman) ?

### ISSUE THREAD

**Issue by sebRomeo** [istanbuljs/nyc#1168]
Hi, thanks for such a piece of work !

I didn't really understood how to do that:
* I have a nodeJS process running on `localhost:9999`
* I have a custom test library that are targeting routes of an express api (same behaviour than postman)
* I run my tests like `"nyc npm run test-api"` and test-api is `node -e 'require(`./core-scripts`)(`run-tests`)'`

Here is my config: 

```javascript
module.exports = {
    all: true,
    include: ['**/server/**/*'],
    exclude: ['*.spec.js'],
    reporter: ['json-summary', 'text'],
    'report-dir': './.jarvis'
};
```
And here is a sample of my report:

![image](https://user-images.githubusercontent.com/17770809/64430472-a4dcbb80-d0b8-11e9-8718-b65f22bbad0a.png)

Can you help me understand why all is red and to 0 ?

Thanks for your lights :)

**EDIT**: now I understand that it is not working because the server is not started with `nyc` command. How may I do that ? And how to output the coverage report ?

**Comment by fasatrix** [comment]
Did you instrument the code?

**Comment by sebRomeo** [comment]
Hi, thx for your answer. I was exactly wondering how to do that properly ?

**Comment by fasatrix** [comment]
Ask a developer to use help you as it is not only about running a command , but the application after that will need to be serving the instrumented folder which means it will have to run no the original source code but instrumented... then you run your test against that and the report will be created

**Comment by sebRomeo** [comment]
Much more clear to me now :)
Could be good to have this concept explained in the doc also.

Thank you very much :)

**Comment by fasatrix** [comment]
> Much more clear to me now :)
> Could be good to have this concept explained in the doc also.
> 
> Thank you very much :)

Glad it helped :-)
