### ISSUE TITLE
Split out the caching and source-map-fixing into separate modules.

### ISSUE THREAD

**Issue by jamestalmage** [istanbuljs/nyc#117]
NYC now does 3 things:
1. Installs an (optionally cacheable) transform via `append-transform` that captures coverage and source-map data.
2. Remaps istanbul reports using source-map data.
3. Uses `spawn-wrap` to make all this happen across forked processes.

I think `1` and `2` need to be split out.

**Comment by sindresorhus** [comment]
:+1:

**Comment by novemberborn** [comment]
> Remaps istanbul reports using source-map data.

There's <https://github.com/SitePen/remap-istanbul> but it already does way too many things besides remapping the reports.

Even if 1 and 2 are split out they may still end up coupled to each other. Not sure I see the point, unless they're moved into Istanbul itself maybe.

**Comment by jamestalmage** [comment]
I think `1` would almost certainly depend on `2` (but not necessarily the other way around).

> Not sure I see the point

It would allow all our hard work getting source-maps and caching working to be used in other contexts.

> unless they are moved into Istanbul itself maybe

That may be the ideal solution, but I have got to imagine that there is a good reason that source-map support hasn't found it's way to master yet over there. 

// @gotwarlost

**Comment by novemberborn** [comment]
> It would allow all our hard work getting source-maps and caching working to be used in other contexts.

Sure, assuming those other contexts discover the modules.

**Comment by jamestalmage** [comment]
> Sure, assuming those other contexts discover the modules.

You take the risk of being ignored every time you type `npm publish`. That's just life.

For my part, I am really curious how much overhead `spawn-wrap` and `foreground-child` add? How much faster would AVA be if we used those split out modules and provided a `--coverage` option that called them in every forked process? Our `babel.js` script runs before any user scripts, so we can already provide many of the guarantees that `spawn-wrap` provides for NYC. Of course, that wouldn't cover users who are going to be forking again from within their test files. In that case - they need to use NYC.

**Comment by bcoe** [comment]
@jamestalmage it looks like @gotwarlost has been working on his own source-map library as part of the istanbuljs org, could we look at merging efforts?

**Comment by coreyfarrell** [comment]
Please correct me if I'm wrong but this is resolved by the existence of `caching-transform` and `istanbul-lib-source-maps`?

**Comment by coreyfarrell** [comment]
I think caching is resolved and any further source-map work should be incorporated to istanbul-lib-source-maps.
