### ISSUE TITLE
Coverage report always empty when nyc_output has coverage results

### ISSUE THREAD

**Issue by jidma** [istanbuljs/nyc#1172]
## Link to bug demonstration repository
I tried setting up code coverage in an **Angular 8** project using **Cypress** and **istanbul** **nyc**.

I managed to get the code instrumented (the global variable `__coverage__` is properly set) :

[![enter image description here][1]][1]

and the coverage file generated in `.nyc_output` after running `cypress:open` 

[![enter image description here][2]][2]

But the generated coverage report is empty: 

    $ cat coverage/coverage-final.json
    {}

Same result when I execute the command:

    $ npx nyc report --report-dir ./coverage --temp-dir .nyc_output --reporter=text
    ----------|----------|----------|----------|----------|-------------------|
    File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
    ----------|----------|----------|----------|----------|-------------------|
    All files |        0 |        0 |        0 |        0 |                   |
    ----------|----------|----------|----------|----------|-------------------|

Here is my package.json devDependencies: 

    "devDependencies": {
      "@angular-devkit/build-angular": "^0.803.3",
      "@angular-devkit/build-optimizer": "^0.803.3",
      "@angular/cli": "^8.3.3",
      "@angular/compiler-cli": "8.2.5",
      "@angular/language-service": "8.2.5",
      "@briebug/cypress-schematic": "^2.0.0",
      "@cypress/code-coverage": "^1.10.1",
      "@cypress/webpack-preprocessor": "^4.1.0",
      "@istanbuljs/nyc-config-typescript": "^0.1.3",
      "@types/jasmine": "^3.4.0",
      "@types/jasminewd2": "^2.0.6",
      "@types/node": "^12.7.4",
      "babel-plugin-istanbul": "^5.2.0",
      "codelyzer": "^5.1.0",
      "cypress": "^3.4.1",
      "istanbul-instrumenter-loader": "^3.0.1",
      "istanbul-lib-coverage": "^2.0.5",
      "jasmine-core": "^3.4.0",
      "jasmine-spec-reporter": "4.2.1",
      "karma": "^4.3.0",
      "karma-chrome-launcher": "^3.1.0",
      "karma-cli": "^2.0.0",
      "karma-coverage-istanbul-reporter": "^2.1.0",
      "karma-jasmine": "^2.0.1",
      "karma-jasmine-html-reporter": "^1.4.2",
      "mochawesome": "^4.1.0",
      "ngx-build-plus": "^8.1.4",
      "nyc": "^14.1.1",
      "protractor": "^5.4.2",
      "protractor-html-reporter-2": "^1.0.4",
      "protractor-http-client": "^1.0.4",
      "source-map-support": "^0.5.13",
      "ts-node": "^8.3.0",
      "tslib": "^1.10.0",
      "tslint": "^5.19.0",
      "typescript": "3.5.3"
    }

And my `.nycrc.json`:

    {
        "cache": false,
        "extension": [
          ".ts",
          ".tsx"
        ],
        "exclude": [
          "**/*.d.ts",
          "coverage/**",
          "packages/*/test/**",
          "test/**",
          "test{,-*}.ts",
          "**/*{.,-}{test,spec}.ts",
          "**/__tests__/**",
          "**/node_modules/**"
        ],
        "all": true,
        "check-coverage": true,
        "require": [
          "ts-node/register"
        ],
        "temp-directory": ".nyc_output",
        "sourceMap": false,
        "instrument": false,
        "include": ["src/**/*.ts", "src/**/*.tsx"]
    }

  [1]: https://i.stack.imgur.com/fnBYF.png
  [2]: https://i.stack.imgur.com/Ou6N7.png

## Expected Behavior

Get non empty coverage report

## Observed Behavior

Coverage report is empty

### Troubleshooting steps
- [X ] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
$ npx envinfo@latest --preset nyc
npx: installed 1 in 5.232s

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz
    Memory: 16.55 GB / 31.88 GB
  Binaries:
    Node: 10.16.3 - D:\software\nodejs\node.EXE
    npm: 6.9.0 - D:\software\nodejs\npm.CMD
  npmPackages:
    babel-plugin-istanbul: ^5.2.0 => 5.2.0
    istanbul-instrumenter-loader: ^3.0.1 => 3.0.1
    istanbul-lib-coverage: ^2.0.5 => 2.0.5
    karma-coverage-istanbul-reporter: ^2.1.0 => 2.1.0
    nyc: ^14.1.1 => 14.1.1
    source-map-support: ^0.5.13 => 0.5.13
    ts-node: ^8.3.0 => 8.3.0
    typescript: 3.5.3 => 3.5.3
    typescript-example:  1.0.0

```

**Comment by jidma** [comment]
After some digging I found that when the property `"excludeAfterRemap": true` (seems to be the default value) all the files are excluded here :

> nyc/index.js:

    390:    if (this.config.excludeAfterRemap) {
    391:      map.filter(filename => this.exclude.shouldInstrument(filename))
    392:    }

Even though `this.exclude.shouldInstrument(filename))` returns true for my file.

Chaning to this
> nyc/index.js:

    if (this.config.excludeAfterRemap) {
      map.filter(filename => { return this.exclude.shouldInstrument(filename) }) //added return statement
    }

Fixed the problem:

```
$ npx nyc report --report-dir ./coverage --temp-dir .nyc_output --reporter=text
--------------------|----------|----------|----------|----------|-------------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------|----------|----------|----------|----------|-------------------|
All files           |    43.59 |    14.81 |    42.86 |    41.89 |                   |
 login.component.ts |    37.93 |        8 |       50 |     37.5 |... 15,117,118,120 |
 login.module.ts    |      100 |      100 |      100 |      100 |                   |
 login.service.ts   |    52.94 |      100 |     37.5 |       50 |... 27,28,29,35,36 |
--------------------|----------|----------|----------|----------|-------------------|

```

**Comment by jidma** [comment]
https://github.com/istanbuljs/nyc/blob/f645762397a1033d9578185bda6c4e57d2746032/index.js#L391-L393

**Comment by coreyfarrell** [comment]
Your suggested change makes no sense as these functions are equivalent.

From [MDN - Arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Basic_syntax):
```js
(param1, param2, …, paramN) => expression
// equivalent to: => { return expression; }
```

**Comment by jidma** [comment]
I know it does not make sense and that the two are equivalent but the problem is that I tried both and it only works when the return is there. 

I will later provide video proof of my claim if it can help pinpoint the problem.

**Comment by coreyfarrell** [comment]
The best way to move forward would be for you to provide a minimal reproduction repository.  This would give us the ability to `git clone <your-repo> && cd <your-repo> && npm it` to see it happening.  **Minimal** is a very important part of this, since what you're suggesting makes no sense we need to eliminate as much outside interference as possible.

A video proving this is happening will not help, I'm working on the assumption that your claim is truthful so we need to figure out why.  I suspect this is the result of something else messing with the nyc code, potentially a broken transpile.  This is where a minimal reproduction will be helpful.

As a work-around you could try adding `exclude-after-remap: false` to your nyc config for now, though I suggest you still want to work on identifying the root cause of the broken arrow functions as `(...args) => expression` is a very common construct.

**Comment by jidma** [comment]
> As a work-around you could try adding exclude-after-remap: false to your nyc config for now

Yes that's the workaround I used for now.

I will try to give minimal code that reproduces the problem. But as it's a large and private project it may take some time to extract the relevent part. 

I will close the issue and will repoen it when the minimal code is available.

**Comment by roubles** [comment]
This is what worked for me:

`npx nyc report --report-dir ./coverage --temp-dir .nyc_output --reporter=text --exclude-after-remap false`

**Comment by gkgkgkgk1195** [comment]
Nothing is working for me, I am using chai http to hit the apis and tests are being executed successfully but the result is not reflected in coverage report.
