### ISSUE TITLE
What is the formula nyc is using to calculate the code coverage

### ISSUE THREAD

**Issue by vishalbiradar** [istanbuljs/nyc#1173]
What is the formula nyc is using to calculate the code coverage?
Will you please let us know how nyc framework is calculating the code coverage, statements covered, etc.

**Comment by coreyfarrell** [comment]
The simple answer is that the function I linked calculates the percentage.  The longer answer is that everything in https://github.com/istanbuljs/istanbuljs/ contributes to this (this is a monorepo so see inside the packages directory).
* istanbul-lib-coverage merges coverage data from multiple runs
* istanbul-lib-source-maps repoints the coverage data to original source locations
* istanbul-lib-instrument alters source code so it generates coverage data
