### ISSUE TITLE
nyc returns 0 line coverage when used with ava and Node.js 

### ISSUE THREAD

**Issue by qburst-neswine** [istanbuljs/nyc#1181]
I am using Node.js project with AVA as testing tool and nyc as m code coverage tool. The test cases passes successfully but the code coverage returns 0 for All files. Please see attached screen shot. 

I followed [this](https://medium.com/free-code-camp/testing-your-nodejs-applications-with-ava-js-99e806a226a7) site as reference for integration but nyc doesn't work as mentioned.

Here is the code : https://github.com/qburst-neswine/nyc-test

![Screen Shot 2019-09-17 at 4 58 25 PM](https://user-images.githubusercontent.com/33560858/65037946-6ffc1e80-d96c-11e9-9e9e-a316d22ec755.png)

**Comment by coreyfarrell** [comment]
Seems like `yarn` is doing something to interfere with nyc.  Changing your `cover` script to `node_modules/.bin/nyc npm test` causes coverage to work.

Unrelated note `node_modules/.bin/` is not needed in any scripts.  The script can just be `nyc npm test`, it will automatically find `nyc` inside `node_modules/.bin`.

**Comment by mmiller42** [comment]
This is happening for me even if I avoid using npm and yarn directly, i.e.

```sh
./node_modules/.bin/nyc ./node_modules/.bin/ava
```

Some files report zero coverage while others do not, and sometimes the files that fail change.

**Comment by macarie** [comment]
I have the same problem 😔

I've set up a repo here: https://github.com/macarie/nyc-ava-zero

If it can help:
```sh
~/G/ttt
● node --version
v13.10.0

~/G/ttt
● npm --version
6.14.2

~/G/ttt
● npx ava --version
3.5.0

~/G/ttt
● npx nyc --version
15.0.0
```

**Comment by coreyfarrell** [comment]
@macarie you are experiencing a different issue, see https://github.com/istanbuljs/nyc/issues/1287#issuecomment-597072231.

**Comment by cuducos** [comment]
Same here. 

Just did the changes locally, but I am working with https://github.com/datopian/jsv

I tried in two different ways, [as described in Instanbul docs](https://istanbul.js.org/docs/tutorials/ava/) and [as described in Ava docs](https://github.com/avajs/ava/blob/b4ea43529a6d058a96055735cfa6e7056c009112/docs/recipes/code-coverage.md). Also tried some tricks form this issue (like adding the unnecessary `./node_modules/.bin/`):

```
$ npm test
 jsv (feature/ckan-schema) ✗ npm t

> jsv@0.0.1 test /home/cuducos/Datopian/jsv
> nyc ava
  19 tests passed
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

The steps were basically `npm i -D nyc` and then change `"test": "nyc ava"` (or variants) in the scripts section of `package.json`.

Any ideas about what I might be missing?
Many thanks,

**Comment by mmiller42** [comment]
If it helps any, I have a repo (https://github.com/mmiller42/dynamic-hoc) and a [GitHub Actions build output](https://github.com/mmiller42/dynamic-hoc/runs/1052622154) that reproduces this issue

It even tries to run the coverage both on the source files and on the compiled JS files and it has the same problem with or without esm.

**Comment by cuducos** [comment]
Great idea, @mmiller42! I see you use Yarn, so if it helps to debug, here we have [a _branch_ with the same issue in a `npm`-based project](https://github.com/datopian/jsv/tree/feature/test-coverage) and the [report with zero files on the CI for this last commit](https://github.com/datopian/jsv/runs/1052733170).

**Comment by fizbik** [comment]
Did any previous commenters find a way around this? This is happening to me with nyc 15.1.0 and Ava 5.3.1.

**Comment by hosuaby** [comment]
Problem persiste even now. nyc 17.0.0 and ava 6.1.3
