### ISSUE TITLE
angular + ts projec instrumentation

### ISSUE THREAD

**Issue by SergeyPirogov** [istanbuljs/nyc#1182]
## Link to bug demonstration repository

Hello, I am trying to instrument my app in order to collect coverage from e2e webdriver tests, but nyc covers, not all files.
App repo link: https://github.com/podcast-timecoder/timecoder-ui

## Expected Behavior
All files instrumented

## Observed Behavior
Only few files instrumented

### Troubleshooting steps

1) Download app code
2) install nyc
3) Run 
```
nyc instrument  src instrumented --embed-source true -a true --compact false
```
In my package json i have 
```
"nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "extension": [
      ".ts",
      ".tsx"
    ],
    "exclude": [
      "**/*.d.ts"
    ],
    "reporter": [
      "html"
    ],
    "all": true
  }
```

**Comment by toish** [comment]
Looking into the same thing at the moment, and I've noticed that only files without decorators are being instrumented? Odd behaviour.

**Comment by toish** [comment]
See https://github.com/istanbuljs/istanbuljs/issues/459

**Comment by coreyfarrell** [comment]
I've commented on the linked issue.  @SergeyPirogov sorry I don't currently have time to dig into such a large repository, if the suggestions on the linked issue do not resolve your issue I'll need you to point me to a specific file that is not being instrumented.

**Comment by haameeen** [comment]
this issue looks similar to this one: https://github.com/istanbuljs/nyc/issues/1137
