### ISSUE TITLE
out.json is populated but the cobertura.xml and others are not by cypress test

### ISSUE THREAD

**Issue by fasatrix** [istanbuljs/nyc#1186]
## Link to bug demonstration repository
Hi,
I have instrumented the code using the following command:
npx nyc instrument --compact=false src instrumented

and to be practical I have moved the instrumented folder into src (esier) and I have committed everything into the following repository: https://github.com/fasatrix/nyc-test-folder-outside-src

Please install both package.json. The one in the root and the other within the test folder

To run the tests use "npm run cypress:run script"

## Context
To create the cobertura coverage I am using a Cypress.io plug-in and followed the documentation at this link: https://docs.cypress.io/guides/tooling/code-coverage.html#Instrumenting-code

## Expected Behavior
Cobertura and other coverage types should be created

## Observed Behavior
Despite the out.json file has been create in .nyc_output, cobertura and other coverage types are being created empty

### Troubleshooting steps
Just clone the repo, install dependencies, run the the app and the test

## Additional Notes
If I use the standard configuration and keep the "Cypress" folder at the same level as the "src" one everything works fine (repo fr reference below). However for this project (These are demos with the structure as the actual project which is confidential) I am unable to use this configuration as I need to keep all tests (performance, e2e, cross browsers eyc.) within the "test" folder
https://github.com/fasatrix/nyc-test-folder-inside-src

# Credit 
For the demos I have used this repo: https://github.com/ryota-murakami/react-typescript-todo-example-2019
```

**Comment by fasatrix** [comment]
Hi @bcoe  I understand my issue might not be the highest in the priority list however would you guys be so kind to have a quick to look at it and let me know whether I should find an alternative solution as this might have no solution for quite some time? Thanks a lot

**Comment by coreyfarrell** [comment]
Your project is very complex, I'm not able to devote the time to test it directly.  I did download the `out.json` from your project and used it to run `npx nyc report -r text`.  This produced a reasonable looking report to me.  So is the problem just with cobertura output?
