### ISSUE TITLE
nyc test coverage not working with my project

### ISSUE THREAD

**Issue by duongduckien** [istanbuljs/nyc#1206]
## Expected Behavior
I have already written 12 unit test with mocha, sinon, and chai. but the test coverage doesn't seem work correctly. all the statement isn't covered at all.

here is my nyc config:
```
"nyc": {
    "check-coverage": true,
    "all": true,
    "cache": false,
    "watermarks": {
      "lines": [
        80,
        95
      ],
      "functions": [
        80,
        95
      ],
      "branches": [
        80,
        95
      ],
      "statements": [
        80,
        95
      ]
    },
    "exclude": [
      "src/migrations",
      "src/seeds",
      "tests/",
      "ormconfig.ts",
      "src/app.ts"
    ],
    "include": [
      "src/**/*.ts"
    ],
    "extension": [
      ".ts"
    ],
    "require": [
      "ts-node/register"
    ],
    "reporter": [
      "text-summary",
      "html"
    ],
    "sourceMap": true,
    "instrument": true
  }
```

i don't know why it didn't cover the statement in the test case. did I do wrong the config

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

![Screen Shot 2019-10-15 at 6 08 59 PM](https://user-images.githubusercontent.com/22634319/66826970-ec881a00-ef77-11e9-9ef4-1891a3062afc.png)

![Screen Shot 2019-10-15 at 6 11 23 PM](https://user-images.githubusercontent.com/22634319/66827362-c616ae80-ef78-11e9-864f-c4242b6d369a.png)

![Screen Shot 2019-10-15 at 6 23 02 PM](https://user-images.githubusercontent.com/22634319/66827392-d9c21500-ef78-11e9-9690-e5e2db7d228c.png)

**Comment by duongduckien** [comment]
it's working when I run the test with npm, I ran yarn before.

**Comment by narwajea** [comment]
See https://github.com/istanbuljs/nyc/issues/921 and https://github.com/yarnpkg/yarn/issues/6746.

**Comment by coreyfarrell** [comment]
@duongduckien please test with `nyc@next` and let us know if that works for you.

**Comment by j0nathan-ll0yd** [comment]
@coreyfarrell I am experiencing the same problem. I took your advice and upgraded to `nyc@next`, but the issue persists.

Node Versions: 8.10, 10.16.3
NVM Version: 0.35.1

### tsconfig.json

```json {
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "inlineSourceMap": true,
    "moduleResolution": "node",
    "allowJs": false,
    "noEmit": true,
    "strict": false,
    "isolatedModules": false,
    "esModuleInterop": false
  },
  "include": [
    "src/**/*",
    "typings/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "test/**/*"
  ]
}
```


### package.json.nyc


```json
"nyc": {
    "extension": [
      ".ts"
    ],
    "require": [
      "ts-node/register"
    ],
    "include": [
      "src/**/*.ts"
    ],
    "exclude": [
      "**/*.d.ts"
    ],
    "reporter": [
      "text",
      "html"
    ],
    "all": true,
    "cache": false,
    "sourceMap": true,
    "instrument": true
  }
```

**Comment by coreyfarrell** [comment]
@j0nathan-ll0yd please open a new issue providing all required information.
