### ISSUE TITLE
TypeScript class + namespace declaration merging causes missing branch coverage

### ISSUE THREAD

**Issue by yoursunny** [istanbuljs/nyc#1209]
##  Link to bug demonstration repository
https://gist.github.com/yoursunny/4e1b64118e402164a7d4841ee205a513/368300067d6af681847cfb47dfc58c03bb4344f2
This test case uses nyc+Mocha. The same behavior has been observed with Jest.

## Expected Behavior
`npm test` should report 100% branch coverage.

```ts
export class Main {
  public x: number;

  constructor() {
    this.x = 1;
  }
}

export namespace Main {
  export function f() {
    return 2;
  }
}
```

## Observed Behavior
`npm test` reports line 9 (`export namespace Main`) is missing branch coverage.

### Troubleshooting steps
- [ ] still occurring when I put `cache: false` in my nyc config

## Environment Information
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.74 GB / 7.89 GB
  Binaries:
    Node: 12.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    nyc: ^14.1.1 => 14.1.1
    source-map-support: ^0.5.13 => 0.5.13
    ts-node: ^8.4.1 => 8.4.1
    typescript: ^3.6.4 => 3.6.4
```

---

## Further Information

Invoking the TypeScript compiler (`node_modules/.bin/tsc`) gives this .js output:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
class Main {
    constructor() {
        this.x = 1;
    }
}
exports.Main = Main;
(function (Main) {
    function f() {
        return 2;
    }
    Main.f = f;
})(Main = exports.Main || (exports.Main = {}));
```

The last line contains expression `Main = exports.Main || (exports.Main = {})`.
Since `exports.Main` is already assigned earlier, `exports.Main = {}` branch would never be executed.

*istanbul* should automatically ignore this branch.

**Comment by fent** [comment]
I have a similar (same?) error. the line containing `namespace` is getting marked as not covered.

![image](https://user-images.githubusercontent.com/933490/75121547-0f7fb480-5663-11ea-9f5e-ebec7798abd2.png)

you can see in the screenshot that this happens even if the code inside the function is ran. oddly, there's no such coverage warning if the namespace contains only interfaces and types.

![image](https://user-images.githubusercontent.com/933490/75121638-e1e73b00-5663-11ea-88aa-22c424627d4e.png)

I'm also merging this namespace into an exported function named `Miniget`

**Comment by beenotung** [comment]
A potential (IMO correct) fix is to update the typescript compiler, so that it can generate unconditional code based on static analysis during the code generation phrase.

A workaround is to allow manually ignore certain line for nyc, similar to how tsc treat `// @ts-ignore`

**Comment by yoursunny** [comment]
> A workaround is to allow manually ignore certain line for nyc,

I know about ignoring lines with:

```ts
/* istanbul ignore next */
```

But it would cause too much clutter in the source code.

**Comment by coreyfarrell** [comment]
This cannot be fixed by istanbuljs / nyc.  Branch code is being provided to istanbuljs, and the source-map associates the branch with a source file.  Unfortunately TypeScript generates some code like this which makes 100% coverage difficult or even impossible.

istanbul does not (cannot) perform the level of analysis to identify and ignore "unreachable" code.  This would be hugely complex, slow and error prone.  It would also break a use-case of nyc which is to identify potential unreachable code for removal.
