### ISSUE TITLE
No coverage for typescript compiled project

### ISSUE THREAD

**Issue by repinvv** [istanbuljs/nyc#1210]
https://gist.github.com/repinvv/9440648d1f128dd9d144589e5be7d456

npm i
npm test
## Expected Behavior
This is how it works with nyc@13.3
![image](https://user-images.githubusercontent.com/1575441/68072403-6f8dda80-fd96-11e9-83b1-cf8a825330b1.png)

## Observed Behavior
nyc@14
![image](https://user-images.githubusercontent.com/1575441/68072419-9cda8880-fd96-11e9-838a-3b7514c22bd3.png)

## Environment Information

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 1.83 GB / 7.84 GB
  Binaries:
    Node: 12.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD

**Comment by repinvv** [comment]
the same on another PC:
System:
    OS: Linux 4.4 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
    Memory: 20.86 GB / 31.94 GB
  Binaries:
    Node: 12.0.0 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  npmPackages:
    nyc: ^14.1.1 => 14.1.1
    typescript: ^3.6.4 => 3.6.4

**Comment by coreyfarrell** [comment]
I think you need  to remove the nyc `include` option and set `"extension": [".ts"]`.  `.js` is automatically added to allow nyc to instrument the output of `tsc` but your current configuration is excluding the original source filename which causes it to be removed from the reports.

**Comment by repinvv** [comment]
![image](https://user-images.githubusercontent.com/1575441/67638704-c0b25000-f8f8-11e9-934b-90ef1a30eefb.png)
Still does not work. I expect to see 1 line add.ts and it has to be 100% covered.


Forgot to add, with nyc 13.3 it works, with 14.1.1 it fails.
But with 13.3 there is another issue now, which caused me to go upgrade.

**Comment by DavidSichau** [comment]
I experience the same behaviour that istanbul is only reporting 100% Branch coverage.

**Comment by rhysd** [comment]
I'm also running into this issue with v14.1.1. Configuration is pretty simple:

```json
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "check-coverage": true
  }
```

in my `package.json`. v13.3 did not cause this issue as reported in this issue.

**Comment by coreyfarrell** [comment]
@rhysd this is a known breaking change of 14.x.  Changing the default `extension` list is also considered a breaking change for nyc so adding `.ts` to the defaults is part of nyc@15.  You can get that version using `npm i -D nyc@next`, subscribe to #1104 for updates on progress towards the final release.

@repinvv I've had a moment to clone your gist.  I recommend upgrading to nyc 15 which includes some fixes that apply to your project.  After upgrading make changes to your nyc configuration:
1. Set `"cache": false`
2. Remove `include` and `extension` settings
3. Change `exclude` to `["*.spec.*"]`

**Comment by rhysd** [comment]
@coreyfarrell Thank you for the information. I'll wait for v15 keeping my configuration meantime.

**Comment by repinvv** [comment]
yes, nyc@15 beta works for me. Needs a lot more specified in exclude section, but it works. I wonder if it does instrument more files than needed which might impact its performance, since I don't specify what to include anymore.

**Comment by coreyfarrell** [comment]
As an alternative you could specify `"include": ["*.js", "*.ts"]` if you are worried about sub-directories potentially being included, otherwise the default extension list already restricts what can be included.  Unless you have specific performance issues with the `--all` feature then I'd recommend not worrying about being more strict than you need to.
