### ISSUE TITLE
nyc initial run doesn't create the "temp-dir"

### ISSUE THREAD

**Issue by quoininc-huudatran** [istanbuljs/nyc#1215]
## Expected Behavior

I expect `nyc npm test` to not fail because of missing folder. It should create the temp-dir folder and any missing parent folders.

## Observed Behavior

Running this on a newly cloned project, i get:

    Error: ENOENT: no such file or directory, open '/path/to/project/.nyc_output/2fc6fe6b-7491-43cf-b9ee-1fb468c21839.json'

and

    Error: ENOENT: no such file or directory, scandir '/path/to/project/.nyc_output'

### Troubleshooting steps
- [X] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
# paste the output here
npx: installed 1 in 1.601s

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 1008.22 MB / 16.00 GB
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v8.12.0/bin/npm
  npmPackages:
    babel-core: ~6.26.3 => 6.26.3
    babel-loader: ~7.1.5 => 7.1.5
    babel-plugin-transform-async-to-generator: ~6.24.1 => 6.24.1
    babel-plugin-transform-object-rest-spread: ~6.26.0 => 6.26.0
    babel-preset-env: ~1.7.0 => 1.7.0
    babel-preset-react: ~6.24.1 => 6.24.1
    babel-preset-stage-0: ~6.24.1 => 6.24.1
    babel-regenerator-runtime: ~6.5.0 => 6.5.0
    grunt-babel: ~7.0.0 => 7.0.0
    nyc: ~13.3.0 => 13.3.0
```

**Comment by quoininc-huudatran** [comment]
Ok, i figured out what the issue was. It was in my `package.json` file. I had the following:

```
  "scripts": {
    "pretest": "grunt check build",
    "prepack": "npm run -s coverage",
    "coverage": "nyc npm test",
    "test": "mocha \"lib/**/*.unit.test.js\" \"handlebars/**/*.unit.test.js\" index.unit.test.js"
  },
```

Renaming the `pretest` to `precoverage` fixes the issue... But this doesn't allow me to make sure that's done before the `npm test`. I can live with that since I want my CI to run the coverage, not just the tests.

**Comment by coreyfarrell** [comment]
when `coverage` runs `nyc npm test` this causes `pretest` to run.  Maybe your pretest code is failing to run correctly under nyc.  Impossible for us to know what's going on without a link to a repository.

**Comment by quoininc-huudatran** [comment]
I understand the order of npm run scripts. I think running "grunt" affects the memory stack and messes up the report.

**Comment by coreyfarrell** [comment]
In your npm scripts nyc executes `npm test` in a new process, that executes `npm run pretest` in a separate new process and `grunt` is executed in yet another new process.  Once `npm run pretest` exits after `grunt` exits, then `npm test` spawns a new process for mocha.  So it's not a memory issue because `grunt` is running in an isolated memory space.

In any case without a link to the repository there is nothing further I can advise.

**Comment by quoininc-huudatran** [comment]
That's what I thought, but ok, here's my repo:
https://github.com/WarpWorks/warpjs-utils/blob/master/package.json#L12

**Comment by quoininc-huudatran** [comment]
Bump

**Comment by coreyfarrell** [comment]
Sorry I don't know grunt so it might be up to someone in the community to help with this.  One thing I notice:
https://github.com/WarpWorks/warpjs-utils/blob/master/grunt/config/clean.js

Is this saying that `.nyc_output` is deleted by the test target?  If this is being run after nyc starts it is a problem.  Note deleting this folder is completely unnecessary as nyc deletes and recreates it by default when you run nyc.

**Comment by quoininc-huudatran** [comment]
Oh, that's actually a very good help. This might be what it's happening. I'll test that tomorrow

**Comment by coreyfarrell** [comment]
@quoininc-huudatran did my suggestion fix your issue?

**Comment by quoininc-huudatran** [comment]
I'm sorry, I can't undo the grunt process, but i see how it can be the issue.
