### ISSUE TITLE
the limitation of shebang length

### ISSUE THREAD

**Issue by thonatos** [istanbuljs/nyc#1222]
nyc  will write `shim.js` with the code:

```js
// https://github.com/istanbuljs/spawn-wrap/blob/master/index.js#L21
const shebang = process.platform === 'os390' ?
  '#!/bin/env ' : '#!'

const shim = shebang + process.execPath + '\n' +
  fs.readFileSync(path.join(__dirname, 'shim.js'))
```

while the length of shebang is longer than expected, `shim.js` won't be loaded.

> https://www.in-ulm.de/~mascheck/various/shebang/#length

## Expected Behavior

- generate coverage summary 
- or throw the error with information

## Observed Behavior

```bash
=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```

### Troubleshooting steps

- install node.js into {someDir} 
- export the node.js path
- run nyc with the node

> \`${someDir}\`.length > 128

## Environment Information

- centos 7.x | ubuntu 16.x
- nyc@latest

**Comment by coreyfarrell** [comment]
spawn-wrap is problematic to say the least.  As I think you noticed nyc 15 will not use spawn-wrap by default but it requires node.js 8.  I'm not sure what to suggest here, nor can I say why your tests against node.js 8+ fail in your related PR.

**Comment by thonatos** [comment]
thank you very much. please ignore my test on github, which is used to solve problems we found on the intranet. because the error caused by this restriction is more difficult for users to check, so here is mainly to record.
