### ISSUE TITLE
improve es-modules documentation (was: nyc ignores non-strict mode js files)

### ISSUE THREAD

**Issue by alexkli** [istanbuljs/nyc#1227]
## Description
JS files that are not in strict mode (`'use strict';`) are ignored by nyc and never show up in the report, even with `--all` and explicit inclusion `--include=non-strict-file.js`. When I enable strict mode on the same file, it gets included.

I could not find any documentation that states this requirement or an option to control this.

## Expected Behavior

Coverage is calculated for non strict mode files as well.

## Observed Behavior

Coverage is not done for non-strict mode javascript source files.

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 505.48 MB / 16.00 GB
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
  npmPackages:
    nyc: ^14.1.1 => 14.1.1
```

**Comment by coreyfarrell** [comment]
Please add `es-modules: false` to your nyc config.  Note the issue isn't the lack of `use strict`, the problem is that your code contains reserved words or other syntax that is invalid in strict mode.

It looks like this option is only documented by `nyc --help`.  I'm not sure this is a problem as the option is very rarely needed.

**Comment by alexkli** [comment]
Thanks, `es-modules: false` worked!

I think the documentation can be improved. I actually saw that `--es-modules` option in `nyc --help` before, but the way it's written did not made me think it would apply here :-) Best might be a little note in the readme, as that's also easier to find via search engines than the `nyc --help` output.

**Comment by alexkli** [comment]
It seems the documentation should be improved - see above. I updated the title.
