### ISSUE TITLE
Merge multiple .nyc_output from different path and report nothing

### ISSUE THREAD

**Issue by yjjnls** [istanbuljs/nyc#1233]
I run several tests in different sub directories, such as 
```
workdir/repo1
workdir/repo2
workdir/repo3
......
```
there's a .nyc_output and coverage folder in every repo directory, and I want to merge these coverage results together. As https://github.com/istanbuljs/nyc/issues/1129 said, firstly merge these output together

```
nyc merge workdir/repo1/.nyc_output workdir/.nyc_output/repo1.json
nyc merge workdir/repo2/.nyc_output workdir/.nyc_output/repo2.json
...
```

Then I run `nyc report` in workdir and it shows

```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

my nyc version: 14.1.1

**Comment by coreyfarrell** [comment]
You have provided none of the required information as specified in https://raw.githubusercontent.com/istanbuljs/nyc/master/.github/ISSUE_TEMPLATE.md.  Without that information it is not possible to help you.

**Comment by yjjnls** [comment]
@coreyfarrell 
## Link to bug demonstration repository
https://github.com/yjjnls/nyc-test

## Expected Behavior
run `sh test.sh`

it should merge the two .nyc_output and report a merged result

## Observed Behavior
report nothing
```
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```
## Environment Information
```
  System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 46.21 MB / 8.00 GB
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    npm: 6.7.0 - /usr/local/bin/npm
```

**Comment by coreyfarrell** [comment]
Please create a `package.json` in the root directory of https://github.com/yjjnls/nyc-test.  This needs to include:
```js
{
  "nyc": {
    "extension": [".ts", ".tsx"]
  }
}
```

nyc 14 and above run include/exclude/extension matching during reporting.  nyc 15 is currently in pre-release and has added `.ts` and `.tsx` the default extension list.  FWIW I recommend also configuring an `nyc` dependency in your root package.json to use the same version as the repositories you link.  Using the script as you have to install latest means that you get new semver-major releases without warning.

**Comment by yjjnls** [comment]
that works, thank you

**Comment by yjjnls** [comment]
@coreyfarrell I added the `package.json` and it reports all the result in the submodules. But the merged result is different from the one in the submodule. 

For example, the root nyc report shows that 
```
RsaCryptoSuite.ts           |    70.77 |    81.48 |       72 |    76.79 |... 16,117,118,119 |
```
while in the did-auth-jose, I ran `npx nyc report`, the result
```
RsaCryptoSuite.ts       |    74.36 |      100 |       80 |    74.36 |... 08,109,110,111 |
```
and the coverage html in the root shows that the red block is uncovered, that;s incorrect.

![](https://upload-images.jianshu.io/upload_images/11336404-28b114abceea0b7f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by coreyfarrell** [comment]
Please try the following in your test.sh:
```sh
git submodule update --init

cd did-auth-jose
npm install
npm test
npx nyc merge .nyc_output ../.nyc_output/did-auth-jose.json
cd ../hub-sdk-js
npm install
npm test
npx nyc merge .nyc_output ../.nyc_output/hub-sdk-js.json
cd ..

npx nyc report
```

Running `nyc merge` from the directory of each project potentially has a different result than running it from outside the project directory, one specific thought is that running `nyc merge` from the root directory prevents it from finding files in `did-auth-jose/node_modules/.cache/nyc`.

**Comment by yjjnls** [comment]
@coreyfarrell geat work
