### ISSUE TITLE
some files are missing from coverages

### ISSUE THREAD

**Issue by akoidan** [istanbuljs/nyc#1235]
## Link to bug demonstration repository
- git clone  https://github.com/akoidan/vue-webpack-typescript
- git checkout missing-report
## Expected Behavior
- yarn install
- yarn build:test
- yarn run test:e2e
- open with browser coverage/index.html
- coverage/index.html should contain `src/components/partials/UserComp.vue`

## Observed Behavior

You can also generate this coverage after running the test from `.nyc_output/out.json`. Just do
 - yarn nyc report
 - check that `.nyc_output/out.json` contains that file (UserComp.vue)
 - but the resulting reports in `coverage` directory doesn't information about some files like UserComp.vue

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config
- [x] still occurring if I tag @next version for nyc and istanbul
- [x] still occurring despite the reporter I use (html/json/text etc
## Environment Information

```
npx: installed 1 in 0.796s

  System:
    OS: Linux 5.3 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1.12 GB / 31.25 GB
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.1 - /usr/bin/npm
  npmPackages:
    @babel/plugin-proposal-class-properties: 7.7.0 => 7.7.0 
    @babel/plugin-proposal-decorators: 7.7.0 => 7.7.0 
    @babel/preset-env: 7.7.1 => 7.7.1 
    babel-loader: 8.0.6 => 8.0.6 
    babel-plugin-istanbul: 5.2.0 => 5.2.0 
    babel-preset-typescript-vue: 1.0.2 => 1.0.2 
    istanbul-lib-coverage: 2.0.5 => 2.0.5 
    nyc: 14.1.1 => 14.1.1 
    source-map-support: 0.5.16 => 0.5.16 
    ts-node: 8.5.2 => 8.5.2 
    typescript: 3.7.2 => 3.7.2 
```

**Comment by akoidan** [comment]
This issue still reproduces, I updated all dependencies (from ones that were 1 year ago). The steps to reproduce above are still relevant.

**Comment by coreyfarrell** [comment]
The `.vue` file you linked is not javascript.  To process this file with istanbul requires that either something else first transpile it to javascript, or the necessary babel parser plugins be enabled.  From what I can tell you probably need (at minimum) to add `parserPlugins` option to your:
```js
{
  "parserPlugins": [
    "jsx"
  ]
}
```

Note this will replace the default parser plugins used by `nyc instrument`, the full list of available options is at https://babeljs.io/docs/en/babel-parser#plugins.  You probably need the `typescript` parser plugin as well.

You can use `NODE_DEBUG=nyc npx nyc instrument file.vue` to see the error stack produced by instrumentation.  The plan is for the next semver-major to upgrade this from debug message to critical error (nyc will display the error and exit in failure).
