### ISSUE TITLE
create code coverage report sucessfully, but can't click the following link

### ISSUE THREAD

**Issue by siemens84cn** [istanbuljs/nyc#1241]
Step1:
![image](https://user-images.githubusercontent.com/47802836/70440678-ab226f80-1acd-11ea-8153-2a57da6a397d.png)
Step2:
then i clicked the link “file:///C:/Users/1/Desktop/coverage/lcov-report/api/file:/home/lingcheng/freeform-modeling-tool/src/packages/geom-modeling-kernel/src/api/index.html”，it return “ERR_FILE_NOT_FOUND”.

i hope someone can help me to fix the problem，i am not sure it's a bug of istanbul plugin.

**Comment by siemens84cn** [comment]
run command:"npm run jest --config=jest/jest.config.json -i -- --coverage"
the content of jest.config.json is as following:
{
  "rootDir": "..",
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "json",
    "jsx"
  ],
  "transform": {
    "^.+\\.(ts|tsx)$": "<rootDir>/jest/processors/ts-babel-processor.js",
    "^.+\\.(js|jsx)$": "babel-jest"
  },
  "testRegex": "(/src/packages/.*/src/.*/__test__/.*test\\.[tj]s)",
  "testPathIgnorePatterns": [
    "/node_modules/",
    ".*\\.lib\\.",
    "/build/",
    "perf\\."
  ],
  "reporters": [
    "default",
    "./node_modules/jest-html-reporter"
  ],
  "collectCoverage": true,
  "collectCoverageFrom": [
    "src/packages/geom-modeling-kernel/src/**/*.{js,ts,tsx,jsx}",
    "!src/**/__test__/**",
    "!src/jest/**"
  ],
  "modulePathIgnorePatterns": [
    "<rootDir>/src/packages/brep-frontend/build"
  ],
  "moduleNameMapper": {
    "@xx/geom-modeling-kernel(.*)": "<rootDir>/src/packages/geom-modeling-kernel/src$1",
    "@xx/brep(.*)": "<rootDir>/src/packages/brep-frontend/src$1",
    "@xx/math": "<rootDir>/node_modules/@xx/math"
  }

**Comment by coreyfarrell** [comment]
Please provide all required information as specified in our new issue template. https://raw.githubusercontent.com/istanbuljs/nyc/master/.github/ISSUE_TEMPLATE.md
