### ISSUE TITLE
No coverage report for JSX file

### ISSUE THREAD

**Issue by quoininc-huudatran** [istanbuljs/nyc#1242]
## Link to bug demonstration repository
https://github.com/Quoin/react-utils/tree/master/src

## Expected Behavior
I expect to see code coverage for the JSX file

## Observed Behavior
The test output the test for the JSX file (in this case `error-boundary.jsx`), but in the coverage report, I don't see it. It is neither in the summary nor in the html output. (`reports/coverage/index.html`).

I know the test is run because of this output:
```
  src/error-boundary
    ✓ should be a function with 1 param
```

### Troubleshooting steps
- [X] still occurring when I put `cache: false` in my nyc config

- npm ci
- npm run coverage && npm run coverage-report

## Environment Information

```
# paste the output here
  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 551.17 MB / 16.00 GB
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.2 - ~/.nvm/versions/node/v8.12.0/bin/npm
  npmPackages:
    @babel/cli: ~7.7.5 => 7.7.5
    @babel/core: ~7.7.5 => 7.7.5
    @babel/preset-env: ~7.7.6 => 7.7.6
    @babel/preset-react: ~7.7.4 => 7.7.4
    @babel/register: ~7.7.4 => 7.7.4
    nyc: ~14.1.1 => 14.1.1
```

**Comment by coreyfarrell** [comment]
nyc 14 requires that addition extensions such as `.jsx` be enabled by setting `"extension": [".jsx"]` in your `.nycrc`.  Note that in nyc 15 (currently pre-release) this is no longer an issue as `.jsx` is being added to the default extension list.

**Comment by quoininc-huudatran** [comment]
Ah, i see, i just thought about it... But in the README, it says that `.jsx` is there by default, that's why I didn't add it. But I decided to try it just in case before seeing your reply.

Someone should fix that README.

Thanks for the help.

**Comment by coreyfarrell** [comment]
github.com displays the README.md from `master`, it is accurate to nyc@15.0.0-beta.3.  This is different from 14.1.1.  https://www.npmjs.com/package/nyc always displays the README.md for the most recent stable release.

**Comment by quoininc-huudatran** [comment]
Oh, I see. Sorry, I was expecting master to be the official version (because it is said: `npm i -D nyc` which install `latest`) instead of a next version. My bad.

Would be great that version is displayed at the top of the README, and have links to older versions 
(create a branch from your latest tag 14.1.1). That would be really helpful instead of relying on external (`npmjs`).

Thanks,

**Comment by coreyfarrell** [comment]
This is just the way github and npm work.  Development happens on github, releases are published to npm.  This is not something I can solve without unacceptable burden on the release process.
