### ISSUE TITLE
SyntaxError: Unexpected identifier - tests ends with coverage 0 (tests do not run(?))

### ISSUE THREAD

**Issue by kmdrGroch** [istanbuljs/nyc#1260]
## Link to bug demonstration repository
https://github.com/kmdrGroch/BigMath

PR:
https://github.com/kmdrGroch/BigMath/pull/69

job: https://travis-ci.com/kmdrGroch/BigMath/jobs/271439516  [full error there]
## Expected Behavior

Tests run

## Observed Behavior
SyntaxError: Unexpected identifier
ERROR: Coverage for lines (0.54%) does not meet global threshold (100%)
ERROR: Coverage for functions (0%) does not meet global threshold (100%)
ERROR: Coverage for branches (0%) does not meet global threshold (100%)
ERROR: Coverage for statements (0.54%) does not meet global threshold (100%)

### Troubleshooting steps
Removing `doubleFactorial` implementation, tests, etc. fixes this issue.
Honestly I have no idea why it is crashing since there is no reason to do it.

## Environment Information
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 10.21 GB / 15.92 GB
  Binaries:
    Node: 13.5.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    nyc: 14.1.1 => 14.1.1
    source-map-support: 0.5.16 => 0.5.16
    ts-node: 8.5.4 => 8.5.4
    typescript: 3.7.3 => 3.7.3

note: updating packages do not fix it either
(It also might be mocha problem, but I am really not sure)

**Comment by coreyfarrell** [comment]
Could you try adding `"compact": false` to your .nycrc for troubleshooting?  This might help give a clearer error message.  I should be able to take a closer look at this soon though I'm a little busy at the moment.

**Comment by kmdrGroch** [comment]
`compact: false` seems to fix issue (?)... I don't know how.

**Comment by coreyfarrell** [comment]
I've seen syntax errors when other source transformations are performed on compact sources.  The compact option actually controls how babel generates instrumented output so I have to assume it's ECMA compliant (non-compliance would be a serious bug in babel).

**Comment by kmdrGroch** [comment]
I think it can be an issue by creating invalid comment, since this error starts and ends with some `*   /` although I am not sure
