### ISSUE TITLE
Rename a folder causes nyc report the folder twice and incorrectly

### ISSUE THREAD

**Issue by XLCYun** [istanbuljs/nyc#1265]
## Link to bug demonstration repository
Here is the project I am working on: [ReactifyObject](https://github.com/XLCYun/ReactifyObject)

## Expected Behavior
After I change the name of a folder `setupValue` to `SetupValue`, nyc's output should only report the coverage in folder `SetupValue` now, but it reports `setupValue` and `SetupValue` two folder, and the result is also not correct. 
## Observed Behavior
Here is the file structure:
![image](https://user-images.githubusercontent.com/12883741/71831041-0783a980-30e3-11ea-9c9f-7e6dfbaa5cca.png)

Here is the .html file result: 
![image](https://user-images.githubusercontent.com/12883741/71831003-f044bc00-30e2-11ea-9748-0f2568a13c3e.png)

Changed back to `setupValue`, problem still remained but the coverage result is different:
![image](https://user-images.githubusercontent.com/12883741/71831135-474a9100-30e3-11ea-976b-b54f20352c07.png)

So I try to run nyc in console by:
```
nyc --reporter=lcov --reporter=text --cache=false "npm run test"
```
Problem remained, and I had debugged my test file, the coverage of this folder should be 100%. 

### Troubleshooting steps
I had tried clear .nyc_output, coverage folder, ./node_modules/.cache/nyc and use --cache=false in command, restarted VSCode, problem remained. 

## Environment Information

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 1.04 GB / 7.94 GB
  Binaries:
    Node: 10.16.0 - D:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - D:\Program Files\nodejs\npm.CMD
  npmPackages:
    nyc: ^15.0.0 => 15.0.0
```

**Comment by XLCYun** [comment]
![image](https://user-images.githubusercontent.com/12883741/71832117-3569ed80-30e5-11ea-85f3-1471ca9dac09.png)
This is the text output.

**Comment by coreyfarrell** [comment]
I'm unsure what could cause this, does it happen when you run nyc from CLI / outside VSCode?  Deleting `node_modules/.cache` and `.nyc_output` should clear information from any previous runs, especially as I don't see any transpile / build step for your repo.  Does anything suspicious appear in `git status --ignored`?

**Comment by XLCYun** [comment]
> I'm unsure what could cause this, does it happen when you run nyc from CLI / outside VSCode? Deleting `node_modules/.cache` and `.nyc_output` should clear information from any previous runs, especially as I don't see any transpile / build step for your repo. Does anything suspicious appear in `git status --ignored`?

Yes, it seems so weird. It still happens when I run nyc from CLI or outside VSCode, like git Bash or PowerShell:
![image](https://user-images.githubusercontent.com/12883741/71868055-94f8e500-3147-11ea-905d-18b766d796b1.png)
And I clone this repo in other folder(driver), it still happens. 
Nothing suspicious appear in `git status --ignored`:
![image](https://user-images.githubusercontent.com/12883741/71868226-3f710800-3148-11ea-91db-aa72c4a3f001.png)
I don't use webpack, babel or anything like that in this repo, so it doesn't need and has not a `npm build` config. 
I am stuck here. What can I do to locate this issue?

**Comment by coreyfarrell** [comment]
I think this is a coding error in your project.  In some of your `require` statements you use `SetupValue` and others you use `setupValue`.  I'm guessing this only works because your testing on Windows, if you setup travis-ci to get Linux / OSX testing I suspect your code would fail to run because `require('./setupValue/setupValue')` at https://github.com/XLCYun/ReactifyObject/blob/master/ReactifyObjectTree/ReactifyObjectTreeNode/ReactifyObjectTreeNode.js#L4 would not find `./SetupValue/setupValue.js` outside of Windows.

**Comment by XLCYun** [comment]
> I think this is a coding error in your project. In some of your `require` statements you use `SetupValue` and others you use `setupValue`. I'm guessing this only works because your testing on Windows, if you setup travis-ci to get Linux / OSX testing I suspect your code would fail to run because `require('./setupValue/setupValue')` at https://github.com/XLCYun/ReactifyObject/blob/master/ReactifyObjectTree/ReactifyObjectTreeNode/ReactifyObjectTreeNode.js#L4 would not find `./SetupValue/setupValue.js` outside of Windows.

You are right! Windows does not care about caption, and I didn't notice vscode failed to update the require path and check for it, after correction, it works just fine now. Grateful you for your time.
