### ISSUE TITLE
Plain Node Server

### ISSUE THREAD

**Issue by nile16** [istanbuljs/nyc#1266]
Is istanbuljs supposed to work with a plain Node http-server (without Express)?

**Comment by coreyfarrell** [comment]
yes, nyc will run test coverage for the http server but not for the scripts being served by it (nyc does not run in the browser).

**Comment by nile16** [comment]
Thanks for the answer.

I can't get it to work. There isn't any error but all fields are zeros. Mocha tests works. Any pointers you can give me?

**Comment by coreyfarrell** [comment]
Not without a link to a repository experiencing the issue.

**Comment by nile16** [comment]
Ok, thanks. I don't have a repository for it.
