### ISSUE TITLE
How to get report for protractor e2e test?

### ISSUE THREAD

**Issue by Helen109** [istanbuljs/nyc#1267]
I want to get protractor e2e test code coverage, can I use this one?

**Comment by AndrewFinlay** [comment]
I use nyc to get coverage for Protractor tests.

The `nyc instrument` command works well for creating instrumented client side source that you can serve to your Protractor tests.
I use [this lib](https://github.com/bennyhat/protractor-istanbul-plugin) to collect the coverage data generated during the tests.  You'll need to put an entry into your Protractor config like:
```javascript
    plugins: [{
        inline: require('protractor-istanbul-plugin'),
    }],
```
I mix the test coverage files with a baseline coverage file, see #1202 for how and why to do this.
Then I create coverage reports with `nyc report`.

Hope this helps!

**Comment by Helen109** [comment]
@AndrewFinlay  thank you very much for your answer. May I ask you did this for javascript or typescript? I am working on typescript now.

**Comment by AndrewFinlay** [comment]
We're working with AngularJS so it's all javascript.  
It should be possible to do with typescript though, have a look at the nyc instructions page for more info on how to work with typescript.
