### ISSUE TITLE
How to get code coverage for js jasmin unit test

### ISSUE THREAD

**Issue by Helen109** [istanbuljs/nyc#1268]
**source code: person.js**
function Person(name, dob) {
    this.name = name;
    this.dob = dob;
}
Person.prototype.isMinor = function () {
    var currDate = new Date();
    if ((currDate.getTime() - this.dob.getTime()) / (1000 * 60 * 60 * 24 * 365.25) < 20.0) {
        return true
    } else {
        return false
    }
}
module.exports = Person;

**Test code:person.spec.js**
var Person = require('./person');

describe("A person", function () {
    it("can be a minor", function () {
        var p = new Person("me", new Date("2000-03-06"));
        expect(p.isMinor()).toBe(true);
    });
});

I tried "istanbul cover jasmine person.spec.js" which doesn't work

**Comment by coreyfarrell** [comment]
`istanbul` is a different tool, this is `nyc`.  If anything you would run `nyc jasmine person.spec.js` but I don't know jasmine so I don't know how they run tests.

Additionally in the future please follow our new issue template, link to a reproduction of the issue is needed.
