### ISSUE TITLE
nyc breaks the test translated by ts-node

### ISSUE THREAD

**Issue by shanoaice** [istanbuljs/nyc#1270]
## Link to bug demonstration repository
I used it in one of my project, the link is [here](https://github.com/KsRyY/bethlehem)
I wrote my test file in TypeScript and I transform them at runtime with `ts-node/register`. When I run ava without nyc everything works fine, but when I run ava with nyc, ts-node gave a lot of error.

## Expected Behavior
Run the tests as normal with not error.

## Observed Behavior
ts-node gave a lot of strange error. I suppose that it is related to how nyc processes the test file

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
System:
    OS: Linux 4.4 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1022.06 MB / 7.83 GB
  Binaries:
    Node: 12.14.1 - ~/.nvs/default/bin/node
    Yarn: 1.21.1 - ~/.nvs/default/bin/yarn
    npm: 6.13.4 - ~/.nvs/default/bin/npm
  npmPackages:
    @ava/babel: 1.0.0 => 1.0.0
    nyc: ^15.0.0 => 15.0.0
    ts-node: 8.6.2 => 8.6.2
    typescript: 3.8.0-dev.20200119 => 3.8.0-dev.20200119
```

**Comment by coreyfarrell** [comment]
Can you post an example of the ts-node errors or better yet a link to the log of a failed CI run?

This is a difficult situation as it appears you have 4 transpilers running in your tests - ava is enabling babel, esm and ts-node, then nyc is enabling another copy of babel.  Might be that you need to tell `nyc` to not instrument and instead configure ava to enable `babel-plugin-istanbul`.  I haven't been following recent developments with ava but I know some changes have been made to how it integrates with babel.

**Comment by KsRyY** [comment]
> Can you post an example of the ts-node errors or better yet a link to the log of a failed CI run?
> 
> This is a difficult situation as it appears you have 4 transpilers running in your tests - ava is enabling babel, esm and ts-node, then nyc is enabling another copy of babel. Might be that you need to tell `nyc` to not instrument and instead configure ava to enable `babel-plugin-istanbul`. I haven't been following recent developments with ava but I know some changes have been made to how it integrates with babel.

I didn't have a CI build link, but I will post an error report soon. I will try your solution too, but I've also tried c8 and it is working well.

**Comment by KsRyY** [comment]
Here's the [gist](https://gist.github.com/KsRyY/449fc10f081b1310859bbfeb683d43d0), generated using my repo [KsRyY/bethlehem@`8a9ff76`](https://github.com/KsRyY/bethlehem/commit/8a9ff766aa8948cf2ab63f496a3cabfbe4a20af0)

**Comment by KsRyY** [comment]
Still does not work well when using the babel provider of ava (`@ava/babel`)

**Comment by andywampir** [comment]
I tried to downgrade `nyc` to `14.1.1` and it's partially helps me, now tests runs normally but code coverage always 0
![image](https://user-images.githubusercontent.com/24408703/77822163-0eceb800-7112-11ea-85dc-fe598dbd6664.png)

**Comment by andywampir** [comment]
In my case (i'm writing API wrapper) i just increased ava testing timeout and `nyc@15.0.0` works normally.

@KsRyY Try increase timeout, maybe it helps you too
