### ISSUE TITLE
bug: nyc with mocha not ignoring line using /* istanbul ignore next */

### ISSUE THREAD

**Issue by YoDaMa** [istanbuljs/nyc#1274]
## Link to bug demonstration repository
Our team is in the process of upgrading from Istanbul to NYC for our Typescript project:

[Azure IoT SDK Node](https://github.com/Azure/azure-iot-sdk-node)

I have created a branch within that repository that has the work I am doing to upgrade from Istanbul to NYC. You can see the branch as a PR here: 

https://github.com/Azure/azure-iot-sdk-node/pull/682

One thing I observed while changing our tests is that code coverage on **branches** for our suite of tests under `azure-iot-sdk-node/common/core` dropped to 80%. That didn't make any sense. After looking at what the lcov reporter output, I can see that it is perceiving a lack of coverage on the **semicolons** of the typescript file. This seems off. Here is a screenshot of the lcov report:

![image](https://user-images.githubusercontent.com/8214060/73481430-abfab380-4350-11ea-8a32-7814d1318221.png)

## Expected Behavior
These semicolons are not labelled as branches that have not been tested. 
## Observed Behavior
Our branch coverage in the `common/core` set of files dropped from 96% to 80% with no change in tests / code. 

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Xeon(R) W-2104 CPU @ 3.20GHz
    Memory: 12.34 GB / 31.73 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    source-map-support: ^0.5.16 => 0.5.16
    typescript: 2.9.2 => 2.9.2
```

**Comment by YoDaMa** [comment]
Upon deeper inspection I see that NYC is having trouble dealing with the following transpiled line: 
```
        /* istanbul ignore next */
        _super.call(this, message) || this;
```

istanbul _should_ ignore this line but it is not, and instead getting upset with the branch for `this` which in it's mind is not tested.

**Comment by coreyfarrell** [comment]
I'm not able to reproduce this in a simple use-case.

```js
function _super(message) {
  return this;
}

function Test(message) {
  /* istanbul ignore next */
  _super.call(this, message) || this;
}

console.log(new Test('test'))
```

Running `npx nyc node script.js` on this results in 100% coverage so the ignore hint is honored and `|| this` is not reported as a missed branch.  Do you have any ideas for how this could be reproduced in such a simple use case?

**Comment by YoDaMa** [comment]
Here's what I found on minimal repro:

Simple `node` use case:
```
function _supper(message) {
  return this;
}

var fakeFn = (function (_super) {
  /* istanbul ignore next */
  function InnerTest(message) {
      var _this = _super.call(this, message) || this;
      return _this;
  }
  return InnerTest
}(_supper));

console.log(new fakeFn('test'))
```

Code to run this:
```
npx nyc node script1.js
```


Simple Mocha use-case:
```

var assert = require('chai').assert;

var ArgumentError = (function (_super) {
    function ArgumentError(message) {
        var _this = 
        /* istanbul ignore next */
        _super.call(this, message) || this;
        return _this;
    }
    return ArgumentError;
}(Error));

describe('errors', function() {
    it('test', function() {
      var err = new ArgumentError('test');
    });
});
```

First install mocha. Code to run this: 
```
npm install mocha --save-dev
npx nyc mocha script2.js
```

### Script1 Coverage Picture
On running script1, the results are 100% coverage. 
![image](https://user-images.githubusercontent.com/8214060/73579672-ea1ed280-4437-11ea-951a-4d4df08304a2.png)

### Script2 Coverage Picture
On running script2, using mocha, the results are 50% branch coverage. 
![image](https://user-images.githubusercontent.com/8214060/73579682-f9058500-4437-11ea-8e8c-53c70319c3e3.png)

**Comment by YoDaMa** [comment]
Adding an inline istanbul ignore comment seems to fix the branch issue... but this isn't feasible since the branch is created from transpiling in our code. 
```js
var ArgumentError = (function (_super) {
    function ArgumentError(message) {
        var _this = 
        /* istanbul ignore else  */
        _super.call(this, message) || /* istanbul ignore next  */ this;
        return _this;
    }
    return ArgumentError;
}(Error));

describe('errors', function() {
    it('test', function() {
      var err = new ArgumentError('test');
    });
});
```

**Comment by coreyfarrell** [comment]
Moving the hint before `var _this` fixes it as well:
```js
/* istanbul ignore next */
var _this = _super.call(this, message) || this;
return _this;
```

I believe this is the "correct" fix here.

**Comment by YoDaMa** [comment]
I see what you're saying @coreyfarrell, but look at the code that is being transpiled: 

```ts
export class ArgumentError extends Error {
  constructor(message?: string) {
    /* istanbul ignore next */
    super(message);
    this.name = 'ArgumentError';
    this.message = message;
    Error.captureStackTrace(this, this.constructor);
    // Set the prototype explicitly.
    // https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
    Object.setPrototypeOf(this, ArgumentError.prototype);
  }
}
```

Which is transpiled into: 

```js
var ArgumentError = /** @class */ (function (_super) {
    __extends(ArgumentError, _super);
    // TODO (YM): This ignore statement needs to be moved back into the constructor once the bug in istanbul is fixed.
    function ArgumentError(message) {
        var _this = 
        /* istanbul ignore next */
        _super.call(this, message) || this;
        _this.name = 'ArgumentError';
        _this.message = message;
        Error.captureStackTrace(_this, _this.constructor);
        // Set the prototype explicitly.
        // https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
        Object.setPrototypeOf(_this, ArgumentError.prototype);
        return _this;
    }
    return ArgumentError;
}(Error));
exports.ArgumentError = ArgumentError;
```

Ignoring all the other code... the lines:

```ts
/* istanbul ignore next */
super(message);
```

are transpiled into:

```js
var _this = 
/* istanbul ignore next */
_super.call(this, message) || this;
```

Could this be something typescript does differently? Maybe... But the istanbul ignore next worked in older versions of istanbul that we were using. So I think this might be a bug there.

**Comment by YoDaMa** [comment]
@coreyfarrell any updates on how to fix this?

**Comment by coreyfarrell** [comment]
Any updates would be posted here.  I don't know what to tell you, typescript is changing the context of your comments by moving it from before a statement to the middle of a statement.  Note it's commonly difficult to get 100% coverage when TypeScript is transpiling code to ES5.

`istanbul` used `esprima` to parse code and `escodegen` to output instrumented code.  `nyc` uses `babel` for these things.  The fact that `istanbul` was able to handle this incorrectly placed comment is well beyond my control.  nyc really isn't a "new version" of istanbul, it's a replacement.

**Comment by YoDaMa** [comment]
The choice of location for the transpiled comment is one thing, and could be looked at in Typescript. 

I'm trying to root cause why it would work in `nyc` in one way but not the other. If you run the pure node snippet with `nyc` the comment works. How are the coverage mechanisms here different for `nyc`?

i.e. this will have 100% branch coverage
```js
function _supper(message) {
  return this;
}

var fakeFn = (function (_super) {
  function InnerTest(message) {
      /* istanbul ignore next */
      var _this = _super.call(this, message) || this;
      return _this;
  }
  return InnerTest
}(_supper));

console.log(new fakeFn('test'))
```

and this will have 50% branch coverage
```js
var assert = require('chai').assert;

var ArgumentError = (function (_super) {
    function ArgumentError(message) {
        var _this = 
        /* istanbul ignore next */
        _super.call(this, message) || this;
        return _this;
    }
    return ArgumentError;
}(Error));

describe('errors', function() {
    it('test', function() {
      var err = new ArgumentError('test');
    });
});
```

Is this an issue with how `nyc` works with `mocha`?

**Comment by coreyfarrell** [comment]
This has nothing to do with mocha, the problem is that your mocha example has the comment in the wrong place.

Correct:
```js
/* istanbul ignore next */
var _this = _super.call(this, message) || this;
```

vs incorrect:
```js
var _this =
/* istanbul ignore next */
_super.call(this, message) || this;
```

**Comment by YoDaMa** [comment]
@coreyfarrell drat you're totally right.

**Comment by YoDaMa** [comment]
This is still a bug so I'd appreciate it left open. It's also a very common piece of code from Typescript transpiling (`super`ing an inherited class's constructor).

**Comment by msolefonte** [comment]
Sorry to reopen but I think I am facing exactly the same problem. This case with `/* istambul ignore else */`. I am using `nym@15.1.0` together with `mocha@8.1.3`:

![](https://i.ibb.co/LC8RVFK/proof1.png)

If not related enough, notify and I'll create a new issue.

**Comment by vitaly-t** [comment]
Same issue, just added update [here](https://github.com/microsoft/TypeScript/issues/36859).

**Comment by msolefonte** [comment]
I forgot to update, but I solved it in my case. Hope I can help someone.

The problem was that I had a flag enabled in TSC to remove comments from the code, so the JS version (the one that is actually executed by NYC did not read any "/* istambul */" flag. Easy to solve problem once I find it.

**Comment by vitaly-t** [comment]
@msolefonte How did you solve the issue with `|| this` coverage in the constructor? That was the issue originally posted here.

**Comment by msolefonte** [comment]
> @msolefonte How did you solve the issue with `|| this` coverage in the constructor? That was the issue originally posted here.

This was in reference to my reply, two comments above. I considered it related but not the exact same problem. I replied now because I forgot at the moment, but I got notified of your reply.

Sorry for the inconvenience if any.
