### ISSUE TITLE
How to collect code coverage with Istanbul when executing an HTTP API utilizing Express

### ISSUE THREAD

**Issue by kirksl** [istanbuljs/nyc#1275]
I am trying to collect code coverage when testing endpoints and really having a lot of difficulty with this.  I've found very few posts and even fewer where anyone talks about solving this.  The most notable post being the following without any actionable solution.  I tried my best to put to work what it suggested without success.

https://github.com/istanbuljs/nyc/issues/1168

I've recapped everything i've tried in this SO post.
https://stackoverflow.com/questions/59977566/how-to-collect-code-coverage-with-istanbul-when-executing-an-http-api-utilizing

Greatly appreciate insight on this and if Istanbul Middleware is the only option to get this to work?  I've avoided going down that path until now to avoid getting to invasive with developer code.

**Comment by kirksl** [comment]
Closing as we've solved this through arduously searching online and learning how to do lower level code coverage and specific techniques.  It would be awesome if this type of detail was documented.
https://github.com/kirksl/karate-istanbul

**Comment by ShaunEgan** [comment]
This was super helpful, thanks @kirksl
