### ISSUE TITLE
Can no longer get NYC to use absolute paths in lcov.info

### ISSUE THREAD

**Issue by solymosi** [istanbuljs/nyc#1277]
File paths in `lcov.info` used to be absolute before 15.0.0. This has changed in the following PRs:
* https://github.com/istanbuljs/nyc/pull/1212
* https://github.com/istanbuljs/istanbuljs/pull/492

It looks like these PRs do such a good job of "adding support for relative path option" that they remove the possibility to use absolute paths altogether, since `this.cwd` is now always set as the `projectRoot` for the `lcovonly` module, which uses `path.relative` without the option to turn this feature off.

Is there some way to continue using absolute paths in `lcov.info`?  
If this would need changes in the code, I'm happy to prepare a PR.

**Comment by coreyfarrell** [comment]
nyc is complex with many options, my preference is to avoid unnecessary options as every option increases the learning curve.  That is why I requested the removal of `--relative=true` from the linked PR's.  I'm thinking that we could create a report alias such that `nyc report -r lcovabsolute` would produce output with absolute filenames.  This would avoid creation of a new 'global' option / having to explain that it only applies to the lcov report.

CC @bcoe

**Comment by solymosi** [comment]
@coreyfarrell &ndash; thanks for your feedback!

Speaking of global options, is there a way to pass in options to a particular reporter that is exposed somewhere &ndash; e.g. the `nyc` key in `package.json` or similar? That would be an obvious place to put this option.

Short of that I would also be fine with a separate `lcovabsolute` reporter as long as there is something that allows me to generate `lcov.info` files with absolute paths.

**Comment by solymosi** [comment]
I ended up publishing my own plugin:  
https://www.npmjs.com/package/nyc-report-lcov-absolute

It's not the most beautiful code I've ever written but it gets the job done.

**Comment by bogem** [comment]
A [comment](https://github.com/istanbuljs/istanbuljs/issues/529#issuecomment-618074852) from https://github.com/istanbuljs/istanbuljs/issues/529 helped me to resolve the issue. I just added this line to the jest config of packages in my monorepo:
```js
coverageReporters: [['lcov', { projectRoot: '../..' }]],
```

**Comment by RobbieTheWagner** [comment]
@PaulRBerg did you ever find a solution? We have the same issue where we have several separate reports, with the paths to the files being relative to each monorepo workspace, so when we try to merge them, we end up with 3 entries for the same file, all with different paths.

**Comment by PaulRBerg** [comment]
@RobbieTheWagner I can't remember unfortunately.
