### ISSUE TITLE
Any plans supporting deno? 

### ISSUE THREAD

**Issue by tatomyr** [istanbuljs/nyc#1278]
While exploring **deno.land** ecosystem, I found it lacking a test coverage utility.  Does the community have a certain opinion on extending the library to cover this flaw?

**Comment by coreyfarrell** [comment]
I hadn't heard of deno before now.  nyc has some pretty unforgiving requirements on low level node.js functionality (including in some cases "internal" functionality of node.js).  I do not have time to investigate what it would take for nyc to support deno.  An easier path forward might be to try getting deno patched to support https://github.com/bcoe/c8 (it looks like deno is based on v8 so this should be possible).
