### ISSUE TITLE
Enable `--exit-on-error` by default, document the option

### ISSUE THREAD

**Issue by xuld** [istanbuljs/nyc#1280]
Just create `test.js` with content below and run `nyc node test.js`
```js
var await;
```

NYC exits with an empty report:
```
 ----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 | 
----------|---------|----------|---------|---------|-------------------
```

nyc@15.0.0 (installed today)

**Comment by coreyfarrell** [comment]
Please run with `nyc --es-modules=false test.js` or set `"es-modules": false` in your nyc configuration.  By default nyc has babel use the more strict parser which views `await` as a reserved word.

**Comment by xuld** [comment]
I do use ES6 syntax. So I requires `es-modules` to be true.

`await` should be a contextual keyword.

Consider this valid es6 module code:
```js
let await;
export async function fn(){ 
    await fn();
}
```

**Comment by coreyfarrell** [comment]
From node.js 13.8.0 running ES module code (script.mjs):
```
var await;
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:66:18)
    at async link (internal/modules/esm/module_job.js:37:21)
```

Additionally babel rejects this.  `var await;` is not valid in ES modules, or if it is there is a bug in node.js / v8 and in babel.

**Comment by xuld** [comment]
If it is rejected by babel, It's better to print the synatx error in cli.
Currently nyc exits normally, with an empty report, no errors showed.

**Comment by coreyfarrell** [comment]
I've renamed this bug to more accurately reflect the issue.  I think the fix has to be deferred to nyc 16 (this is potentially breaking).  For now you can add `--exit-on-error=true` to your nyc command or set `"exit-on-error": true` in your nyc config.  This will cause nyc to print `Failed to instrument ${filename}` and exit with error upon instrumentation failure.  You can get additional details by setting `NODE_DEBUG=nyc`, this debug works with or without enabling `exit-on-error`.
