### ISSUE TITLE
nyc exit with code 1 and spawn EACCESS, no stack trace

### ISSUE THREAD

**Issue by osher** [istanbuljs/nyc#1282]
## Link to bug demonstration repository

consider a single project file: `test.js`. 
The file content:
```
console.log("OK")
```
When I run
```
$ nyc test.js
```

## Expected Behavior
should run and report 100% coverage.

## Observed Behavior
```
spawn EACCESS
```

### Troubleshooting steps
The run succeeds only after:
1. `chmod +x test.js`
   and
2.  adding shebang to the file
```
#!/usr/bin/env node
```

I encountered the problem when I tried to add `nyc` to a project that does not use a test runner, but wrote it's own test module as `./test/index.js` that is run in CI like `note test`.

## Environment Information

```

  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 433.68 MB / 15.40 GB
  Binaries:
    Node: 8.16.1 - ~/.nodenv/versions/carbon/bin/node
    npm: 6.13.4 - ~/.nodenv/versions/carbon/bin/npm
  npmPackages:
    nyc: ^15.0.0 => 15.0.0 

```

**Comment by coreyfarrell** [comment]
This is the expected behavior.  You must either make index.js executable (`chmod +x index.js` and add shebang) or use `nyc node index.js` to execute.

**Comment by osher** [comment]
The run succeeds only after:

1. `chmod +x test.js`
   and
2. adding shebang to the file
  ```
  #!/usr/bin/env node
  ```

I encountered the problem when I tried to add nyc to a project that does not use a test runner, but wrote it's own test module as `./test/index.js` that is run in CI like `note test`.

**Comment by osher** [comment]
ah. gotcha.

**Comment by coreyfarrell** [comment]
I don't know what `note` is?

**Comment by osher** [comment]
heh. lol. you got me there ... it meant `node test`...
