### ISSUE TITLE
nyc coverage is not working with AMD modules.

### ISSUE THREAD

**Issue by vishnukk** [istanbuljs/nyc#1285]
We are trying to run the coverage with nyc for AMD modules.

```
// AerUtility.js
define(function () { 
     .  .  .
     .  .  .
});
```
Mocha test looks like the following code
```
const { expect } = require('chai');
var requirejs = require('requirejs');

var path = require('path');

var projectdirectory = path.resolve(__dirname, '..');

requirejs.config({
  nodeRequire: require,
  paths: {
    'dir': `${projectdirectory}/apps/webProj/resources/js`
  }
});


describe('Utility', function () {
  var aerUtility;
  before((done) => {
    requirejs(['dir/utility/AerUtility'], function (_Module) {
      aerUtility = _Module;
      done();
    });
  });

  it('Transform Aer Fields Request', function () {
     .. .
     ....
  });
});
```

It simply shows zero coverage. as shown below

![image (19)](https://user-images.githubusercontent.com/3330481/75132502-2b379900-56fd-11ea-816d-2d678837411f.png)
Following cmd is used.
```
./node_modules/.bin/nyc --all mocha --recursive  apps/unittest/test/*test.js"

```
Any pointers to fix this issue?

**Comment by coreyfarrell** [comment]
By default nyc only hooks `require`.  Depending on how `requirejs` loads modules into node.js you may need to enable `--hook-run-in-context` or `--hook-run-in-this-context`.

**Comment by vishnukk** [comment]
Thanks, using --hook-run-in-this-context it worked.
