### ISSUE TITLE
nyc doesn't fail for a low test coverage

### ISSUE THREAD

**Issue by piotr-s-brainhub** [istanbuljs/nyc#1288]
## Link to bug demonstration repository
https://github.com/brainhubeu/tdd-js,
this PR https://github.com/brainhubeu/tdd-js/pull/3

## Expected Behavior
`yarn test` command should fail (in the same way as https://github.com/brainhubeu/tdd-js/pull/4 already fails) because the test coverage is lower than the limit specified in `package.json`

## Observed Behavior
`yarn test` returns 0 exit code

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information
```
⟩ npx envinfo@latest --preset nyc
npx: installed 1 in 1.482s

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
    Memory: 1.17 GB / 16.00 GB
  Binaries:
    Node: 12.5.0 - ~/.nvm/versions/node/v12.5.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v12.5.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.5.0/bin/npm
  npmPackages:
    nyc: ^15.0.0 => 15.0.0
```

**Comment by coreyfarrell** [comment]
`watermarks` do not set the thresholds for `check-coverage`, they set the red/yellow/green levels for reports.  The default for `nyc --check-coverage` is to verify 90% of lines.  To enforce 100% coverage you want to add to your nyc config:
```js
"functions": 100,
"lines": 100,
"statements": 100,
"branches": 100
```

**Comment by piotr-s-brainhub** [comment]
@coreyfarrell 

it helped, thanks
