### ISSUE TITLE
how to create an npx preset?

### ISSUE THREAD

**Issue by oprogramador** [istanbuljs/nyc#1290]
I can run `npx envinfo@latest --preset nyc`:
```
⟩ npx envinfo@latest --preset nyc
npx: installed 1 in 1.139s

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
    Memory: 2.11 GB / 16.00 GB
  Binaries:
    Node: 12.5.0 - ~/.nvm/versions/node/v12.5.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v12.5.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.5.0/bin/npm
  npmPackages:
    nyc: ^15.0.0 => 15.0.0
```

How can I write my own npx preset so when replacying `nyc` with my library name, I could obtain my custom result?

**Comment by coreyfarrell** [comment]
Please see https://github.com/tabrindle/envinfo#readme - it's actually an `envinfo` preset, npx is just being used to install and run an npm package.  I didn't actually do the work to get the nyc preset added to that package so I can't really give more advice but I think you should find what you need at the envinfo repository.

**Comment by oprogramador** [comment]
thanks
