### ISSUE TITLE
code coverage report not correct

### ISSUE THREAD

**Issue by harpal-sgh** [istanbuljs/nyc#1291]
git repo - https://github.com/harpal-sgh/code-coverage-nyc

## Expected Behavior
It should report coverage

## Observed Behavior
Getting 0% for statements, functions and lines 
======================== Coverage summary ===============================
Statements   : 0% ( 0/34 )
Branches     : 100% ( 0/0 )
Functions    : 0% ( 0/4 )
Lines        : 0% ( 0/34 )

command to run tests : npm run test-nyc

**Comment by neilpalima** [comment]
Encountered this as well. 14.1.1 is working fine though.

**Comment by coreyfarrell** [comment]
It looks like your tests are run on AWS instead of being run by a local copy of node.js?
