### ISSUE TITLE
Instrumenting with nyc produces invalid Typescript

### ISSUE THREAD

**Issue by jedateach** [istanbuljs/nyc#1292]
## Link to bug demonstration repository

https://github.com/jedateach/nyc-typescript/runs/515835523

## Expected Behavior

Instrument command produces valid typescript that has no errors

## Observed Behavior

When instrumenting this file:
https://github.com/jedateach/nyc-typescript/blob/master/src/constants.ts

We get this output:
https://github.com/jedateach/nyc-typescript/blob/master/instrumented/constants.ts#L49

Then trying to run a typescript compiler using `tsc instrumented/index.ts`, gives:

```sh
instrumented/comparitor.ts:98:3 - error TS2539: Cannot assign to 'cov_1qahgqgynf' because it is not a variable.

98   cov_1qahgqgynf = function () {
     ~~~~~~~~~~~~~~

instrumented/constants.ts:49:3 - error TS2539: Cannot assign to 'cov_1im0zfgwer' because it is not a variable.

49   cov_1im0zfgwer = function () {
```

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

```
npx: installed 1 in 1.263s

  System:
    OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.26 GB / 32.00 GB
  Binaries:
    Node: 8.16.2 - ~/.nvm/versions/node/v8.16.2/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.2/bin/npm
  npmPackages:
    nyc: ^15.0.0 => 15.0.0 
    source-map-support: ^0.5.16 => 0.5.16 
    ts-node: ^8.6.2 => 8.6.2 
    typescript: ^3.8.3 => 3.8.3 

```

**Comment by coreyfarrell** [comment]
Thank you for this report, I understand the conflict now.

It is necessary for instrumented code to contain `function cov_XXXXXX() {...}` as this causes the function body to be hoisted even if another transformation causes coverage to be called before the declaration of `cov_XXXXXX`.  Prior versions of istanbuljs (including nyc 14) used `var cov_XXXXXX = ...`, this caused the variable to be hoisted but `cov_XXXXXX === undefined` until the declaration was executed.  Setting `cov_XXXXXX = function () { return actualCoverage; }` is needed for performance reasons.

I believe the solution to this conflict is for istanbul-lib-instrument to inject a line `// @ts-ignore` before setting `cov_XXXXXX` to the final function.  In a local experiment this ts-ignore hint got `tsc` to tolerate this code which violates TypeScript but is very much valid JavaScript.  I'm not going to be available for a couple days but I will try to work on a patch for this soon.

**Comment by codefoster** [comment]
Thanks! You might be entirely correct, but unless I'm mistaken, there is no such thing as valid JavaScript that is not also valid TypeScript, right? TypeScript should certainly be fine with the `function cov_XXXXXX() {...}` syntax. Perhaps there's simply a compile option in the tsconfig that would allow it not to be strict about something. I don't even know what it's having a problem with though. Can you point me to where in `istanbul-lib-instrument` the relevant section is?

**Comment by coreyfarrell** [comment]
https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/src/visitor.js#L550 is the line which generates code that offends TypeScript.  The generated code is (clipped for briefness):
```js
function cov_XXXXXX() {
 // Clipped initialization of actualCoverage
 cov_XXXXXX = function () {
   return actualCoverage;
 }
 return actualCoverage;
}
```

So TypeScript does not allow `cov_XXXXXX` to be re-assigned, JavaScript does.  If TypeScript has a configuration option to allow this I don't think it's appropriate for istanbuljs to require that users set it when we can just inject a ts-ignore hint into the generated code.

**Comment by codefoster** [comment]
Got it. Thanks.

**Comment by jedateach** [comment]
Do you guys have a CI platform checking nyc/istanbul against increasingly newer versions of typescript?

**Comment by coreyfarrell** [comment]
We have a couple specific tests for TypeScript but I'm sure it could be improved.  I do not know or use TypeScript so I do my best to help deal with TS bugs but I am a JavaScript developer.  As far as getting more tests this is an open source project, PR's accepted.  It would be best for a TS developer to champion TS test expansion.

**Comment by codefoster** [comment]
FWIW, we ended up getting nyc to work very well in our TypeScript code base. It's at https://github.com/retaildevcrews/helium-typescript.

**Comment by coreyfarrell** [comment]
@codefoster you are using `ts-node/register/transpile-only`, I'm guessing that `ts-node/register` would experience this issue until the `ts-ignore` I'm added gets released.

**Comment by codefoster** [comment]
Ah. That's helpful. Thanks.
