### ISSUE TITLE
Code Coverage report is not accurately displaying covered lines based on unit tests

### ISSUE THREAD

**Issue by bharney0** [istanbuljs/nyc#1294]
Minimum repro can be seen in this repo: https://github.com/bharney0/nyc-mocha-vscode-extension

## Expected Behavior
When running code coverage report I expect that the methods that have been called and spied method with expect tests should show as covered in code coverage report.

Method is called and tests pass, but coverage does not reflect the passing tests
![image](https://user-images.githubusercontent.com/51799435/77468013-32b89380-6dca-11ea-9190-e0954fee8d04.png)

## Observed Behavior
When running code coverage report the methods that are tested do not show as covered in code coverage report.

### Troubleshooting steps
Repro the problem following these steps:
1. Open repo to root directory and `npm install`
2. Close VSCode if open and run `npm run test` from bash/cmd line in root directory
3. Navigate to ./coverage/index and look at alert.ts code coverage file
4. Code coverage does not reflect the actual methods that are tested.
5. Notice that in test `isMarkdownFileCheck` is tested and spy expects that the method is called.
![image](https://user-images.githubusercontent.com/51799435/77466390-6f36c000-6dc7-11ea-8ff0-d11f421d77e1.png)
6. But in code coverage report, the `isMarkdownFileCheck` line is marked as not covered
![image](https://user-images.githubusercontent.com/51799435/77466642-c9378580-6dc7-11ea-9bd4-fb98d401b48a.png)
7. Both cases for return values are checked, but test shows uncovered lines
![image](https://user-images.githubusercontent.com/51799435/77467867-f2f1ac00-6dc9-11ea-872c-f1ed3e1e7163.png)
![image](https://user-images.githubusercontent.com/51799435/77467789-d5bcdd80-6dc9-11ea-9e4b-88e9b687f71b.png)

## Environment Information

```
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 5.94 GB / 15.93 GB
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    nyc: ^15.0.0 => 15.0.0 
    ts-node: ^8.8.1 => 8.8.1
    typescript: ^3.6.4 => 3.8.3
```

**Comment by JoramM** [comment]
I have the same Issue after upgrading from nyc v14.1.1 to v15.0.0. The coverage report seems to be wrong. I have quite a number of files which had 100% coverage before. Now some of them are at 50 to 70%. I am also working with Tyescript.
