### ISSUE TITLE
Coverage summary not shown in Node v12.14.1 (and possibly other node versions)

### ISSUE THREAD

**Issue by AliabbasMerchant** [istanbuljs/nyc#1297]
## Link to bug demonstration repository
https://github.com/postmanlabs/postman-code-generators

## Expected Behavior
Coverage summary should properly show the figures and %.

## Observed Behavior
When run locally using Node v12.14.1, it is showing Unknown%. However, when travis runs it (on Node v8), it shows correct coverage stats: https://travis-ci.com/github/postmanlabs/postman-code-generators/jobs/305203146#L5015

## Environment Information
My local env info:  
```
  System:
    OS: Linux 5.4 Fedora 31 (KDE Plasma) 31 (KDE Plasma)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 9.40 GB / 19.46 GB
  Binaries:
    Node: 12.14.1 - /usr/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  npmPackages:
    istanbul: 0.4.5 => 0.4.5 
    nyc: 14.1.1 => 14.1.1
```

**Comment by fedealconada** [comment]
Any news on this?
