### ISSUE TITLE
Document coverage file format(s)

### ISSUE THREAD

**Issue by brettz9** [istanbuljs/nyc#1311]
Might you document the format, even if just a wiki page, for the main fields in use in the JSON files created in `.nyc_output`--or make clear if it is not a stable format?

While some fields are semantically named and clear, it wasn't immediately clear to me about `s` and `f`. It looks now to me like the values of `s` may be visit counts while the keys of `s` can map to the keys of the same file's `statementMap`, giving line/col info. And it looks like `f` also contains visit counts and may map to `fnMap` with the function name also with location info (and then `b` with `branchMap`, though a two-item array, apparently for if and else counts?).

However, I think it would be more reassuring to know if this were stable and had official docs.

Thanks!

**Comment by coreyfarrell** [comment]
Thanks for this request.  So this format is stable - it hasn't changed recently and any breaking change would face resistance.  Your assumptions about `s`, `f` and `b` are all correct.

As for documenting it I think the start would be https://github.com/istanbuljs/schema/issues/1 which calls for a JSON schema to be written.  This would include defining `description` for each field.  Past that I would assume we could use a tool to generate markdown documentation from the schema though I haven't done a search for a specific tool.

**Comment by brettz9** [comment]
Re: JSON Schema to Markdown, there is this: https://github.com/adobe/jsonschema2md

However, since jsdoc can be redundant with JSON schema (at least for common schema needs), and still useful I think to have the jsdoc in source (unless you were planning to move to TypeScript), we might use [jsdoc-jsonschema](https://github.com/brettz9/jsdoc-jsonschema) to auto-generate the schemas from the source files (I could add a binary feature so there was no need for a separate Node script).

(There is also a tool to generate [jsdoc from json-schema](https://github.com/n3ps/json-schema-to-jsdoc) but I personally think the source files make the most sense as an authority, especially since it is easier to build separate JSON schema files than to update the jsdoc of source based on a schema.)
