### ISSUE TITLE
Regression with windows commands in 15.1.0?

### ISSUE THREAD

**Issue by Jabark** [istanbuljs/nyc#1326]
## Link to bug demonstration repository
As this is environment specific, not relevant

## Expected Behavior
When I install nyc and run `nyc npm run test` my tests run as expected

## Observed Behavior
`'nyc' is not recognized as an internal or external command,
operable program or batch file.`

### Troubleshooting steps
- [ ] Run `npm i nyc@15.1.0 --save-dev` on your Windows environment
- [ ] Observe that no `nyc.cmd` file has been placed in `node_modules/.bin`
- [ ] Try to run `nyc` commands
- [ ] Observe the above error
- [ ] Run `npm i nyc@15.0.1 --save-dev` to revert to the previous version
- [ ] Observe that `nyc.cmd` file has now been placed in `node_modules/.bin`
- [ ] Try to run `nyc` commands
- [ ] Observe that everything is working as expected

## Environment Information
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 16.86 GB / 31.76 GB
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    nyc: ^15.1.0 => 15.1.0
```

**Comment by dailydevin** [comment]
This issue appears to still be a problem in 15.1.0.  Reverting to 15.0.1 fixes.
