### ISSUE TITLE
nyc uses invalid process id when writing the coverage file

### ISSUE THREAD

**Issue by dcermak** [istanbuljs/nyc#1332]
## Link to bug demonstration repository

[open-build-service-api](https://github.com/SUSE/open-build-service-api), see for instance the latest github actions run: https://github.com/SUSE/open-build-service-api/actions/runs/171531758

## Expected Behavior

nyc used to write the coverage file and the reports. I would expect it to do that still.

## Observed Behavior

nyc fails with:
```
Error: ENOENT: no such file or directory, open '/home/runner/work/open-build-service-api/open-build-service-api/.nyc_output/59aaed6d-7f11-4881-8f2d-b1a70837404a.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at NYC.writeCoverageFile (/home/runner/work/open-build-service-api/open-build-service-api/node_modules/nyc/index.js:414:8)
    at EventEmitter.onExit (/home/runner/work/open-build-service-api/open-build-service-api/node_modules/nyc/index.js:372:14)
    at EventEmitter.emit (events.js:198:13)
    at emit (/home/runner/work/open-build-service-api/open-build-service-api/node_modules/signal-exit/index.js:78:11)
    at processEmit [as emit] (/home/runner/work/open-build-service-api/open-build-service-api/node_modules/signal-exit/index.js:158:5)
```

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information

run the following script: `yarn run coverage`
``` ShellSession
$ yarn run coverage
# lots of output and eventually
/home/dan/obs.ts/node_modules/mocha/lib/runner.js:910
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/dan/obs.ts/.nyc_output/fdf71a5d-2236-4d6e-9e78-4d12c0870e1e.json'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1355:35)
    at NYC.writeCoverageFile (/home/dan/obs.ts/node_modules/nyc/index.js:414:8)
    at EventEmitter.onExit.alwaysLast (/home/dan/obs.ts/node_modules/nyc/index.js:372:14)
    at EventEmitter.emit (events.js:315:20)
    at emit (/home/dan/obs.ts/node_modules/signal-exit/index.js:78:11)
    at processEmit [as emit] (/home/dan/obs.ts/node_modules/signal-exit/index.js:158:5) {
  syscall: 'open',
  code: 'ENOENT',
  errno: -2,
  path: '/home/dan/suse/.nyc_output/fdf71a5d-2236-4d6e-9e78-4d12c0870e1e.json'
}
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have no idea why nyc suddenly decides to choose `fdf71a5d-2236-4d6e-9e78-4d12c0870e1e` as the uuid, because the `.nyc_output` directory contains the following:
``` ShellSession
$ la .nyc_output/
total 692
drwxr-xr-x 1 dan users    104 Jul 17 12:41 .
drwxr-xr-x 1 dan users   1032 Jul 17 12:41 ..
-rw-r--r-- 1 dan users 708336 Jul 17 12:41 6bf06195-79f9-44ed-99dd-8c79a025779b.json
drwxr-xr-x 1 dan users    102 Jul 17 12:41 processinfo
```

Unfortunately I have no idea how to debug this further. I have tried fiddling with my config and changing the way mocha is invoked, tweaking sourcemap support but all to no avail, nyc still fails every single time and now even on the CI (it started failing before on my machine, but since it worked on the CI, I thought it was a local misconfiguration).

**Comment by dcermak** [comment]
I've played around with this a bit more and added a `console.log(this.processInfo)` to line 106 of nyc's `index.js`, which results in the following output:
```ShellSession
$ yarn run coverage
yarn run v1.22.4
$ nyc mocha
ProcessInfo {
  parent: null,
  pid: 17220,
  argv: [
    '/usr/bin/node12',
    '/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/node_modules/.bin/nyc',
    'mocha'
  ],
  execArgv: [],
  cwd: '/home/dan/suse/gitlab.suse.de/dcermak/obs.ts',
  time: 1594983774728,
  ppid: 17209,
  coverageFilename: null,
  externalId: '',
  uuid: '99e654d9-85ea-4589-a54c-0103c1562519',
  [Symbol(nodes)]: [],
  [Symbol(label)]: null,
  [Symbol(coverageMap)]: null,
  [Symbol(processInfo.directory)]: '/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/.nyc_output/processinfo'
}
ProcessInfo {
  parent: null,
  pid: 17243,
  argv: [
    '/usr/bin/node12',
    '/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/node_modules/.bin/mocha'
  ],
  execArgv: [],
  cwd: '/home/dan/suse/gitlab.suse.de/dcermak/obs.ts',
  time: 1594983779081,
  ppid: 17220,
  coverageFilename: null,
  externalId: '',
  uuid: '882a982e-54fa-4d1a-9cff-32b4c13122ff',
  [Symbol(nodes)]: [],
  [Symbol(label)]: null,
  [Symbol(coverageMap)]: null,
  [Symbol(processInfo.directory)]: '/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/.nyc_output/processinfo'
}

# snip mocha output

/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/node_modules/mocha/lib/runner.js:910
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/.nyc_output/882a982e-54fa-4d1a-9cff-32b4c13122ff.json
# rest of the failure
```
So this looks like mocha is executed in a second node process that doesn't reuse the same uuid.

**Comment by coreyfarrell** [comment]
nyc uses a new UUID per process, this is expected/required behavior.  The only time I've seen this error is when tests delete the `.nyc_output` directory.  This directory is created by the parent `nyc` and must not be deleted while tests are being run.

```
Error: ENOENT: no such file or directory, open '/home/dan/obs.ts/.nyc_output/fdf71a5d-2236-4d6e-9e78-4d12c0870e1e.json'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1355:35)
```

This error is a bit misleading, `writeFileSync` calls `openSync` with the `w` flag which tells it to create the file if it doesn't exist.  This still fails though if trying to create a file in a directory which does not exist.

nyc could possible catch the fs error and produce a clearer error but I think this is a legitimate (unrecoverable) error.

**Comment by dcermak** [comment]
Ok, after spending a while littering the nyc codebase with `console.log` and `console.trace` and running this through `strace`, I think I've got a rough clue what is going on:
nyc writes the coverage file always on exit by attaching to the `onExit` event, however it does not ensure that the corresponding temporary directory actually exists. In my case what happens is this:
1. `yarn run coverage` launches a whole bunch of processes, eventually one actually launches NYC.
2. the main process (in this example it'll have pid 852) constructs a `NYC` object with the uuid `4486420b-d013-4e88-bcca-a2cc75f0e3f7`
3. the main process immediately exits and writes the coverage file
4. a bunch of additional processes is spawned **after** the coverage file is written, one of these has pid `866` and constructs a new `NYC` object with the uuid `b73bb2c3-bf81-4501-9170-8d6491717676`. It is constructed with the following stack trace (line numbers can be off as I've sprinkled the code with `console.log()`):
```
Trace:
    at new NYC (/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/node_modules/nyc/index.js:109:13)
    at Object.<anonymous> (/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/node_modules/nyc/lib/wrap.js:28:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at /home/dan/suse/gitlab.suse.de/dcermak/obs.ts/node_modules/node-preload/preload-path/node-preload.js:9:24
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/dan/suse/gitlab.suse.de/dcermak/obs.ts/node_modules/node-preload/preload-path/node-preload.js:8:13)
```
this child process however does get its own uuid and since it does not go through the main entry point, it's temporary directory is never created.
5. the `onExit()` event is called for the child `866`, but as it never called `createTempDirectory()`, the directory does not exist and writing the coverage file fails.


Any ideas what the culprit here is? To me it looks like either a timing issue or somehow the child process is no longer getting the correct `processInfo` from the parent.

**Comment by coreyfarrell** [comment]
The main nyc process creates the temporary directory before spawning and child processes.  Something in your project must be deleting the temporary directory.  Another possibility I noticed you are using `mock-fs`, are you remembering to run `mockFs.restore()` after your tests?  nyc runs code when your test process is exiting so if I'm understanding the mock-fs readme then not restoring normal fs would break nyc.

**Comment by dcermak** [comment]
I'm an idiot and your guess was spot on: https://github.com/SUSE/open-build-service-api/commit/365d978c2eacc2ca670ab83e5fb711c30c610ad4

Sorry for wasting your time and thank you very much for your help!
