### ISSUE TITLE
[Question/Feature Request] is it possible to enforce "creeping" code coverage thresholds?

### ISSUE THREAD

**Issue by GrayedFox** [istanbuljs/nyc#1336]
## Description
Aloha, thank you for the fine work. I've recently integrated nyc into a personal project using mocha and codecov and it's been a breeze.

I have set a low threshold for now (33% for all) but I was wondering if there might be any way to enforce a "creeping" threshold, i.e. some check that requires each pull request to raise the total coverage by N% until we hit that magical triple digit number. I could just do this by hand and bump the thresholds inside my .nycrc.json file with each PR, but I was wondering if this functionality might already be a part of (or worth building into) nyc.

### User Story
As a developer I would like to set a creeping threshold that requires each merge to master increase the total code coverage by N%, until we reach 100% coverage (or some other threshold).

### Requirements
- existing config parameters could be extended to accept an object, array, or even simply a string containing an operator
- a minimum threshold could still be set and serve as the "global base"
- different increment values could be set per type, allowing nyc to signal to contributors what the project maintainers feel is more important for their codebase
- an increment without any minimum could be set, with nyc keeping track of what the new minumum coverage value by storing/keeping that value somewhere (i.e. in the temp-dir or even writing it to the `.nycrc` config file)

```json
{
  "check-coverage": true,
  "branches": {
    "minimum": 30,
    "increase": 5
  },
  "lines": "33+10",
  "functions": 33,
  "statements": "+5",
  "temp-dir": "./coverage/temp"
}
```

### Pros

This would (in my opinion) offer a nice middle ground between passing `--all true` and then excluding any files the developer doesn't want to necessarily effect the code coverage score (yes I know that's a bit gamey, but maybe they just want to touch core logic first).

It could also encourage a sort of "own any code you touch" philosophy, which I am a fan of. Perhaps there are no unit tests for file X at the moment, and with `all` defaulting to false, this file won't effect the coverage percentages - but the next time a developer touches that file they need to take ownership of it and ensure unit tests are now implemented **and** that coverage goes up.

### Cons

- could be a bit too much of work for not much profit
- developers can pretty much do this want anway (if they really want to) by writing the any increments to their nyc config file as part of an npm build/publish/whatever script

Thoughts?

**Comment by coreyfarrell** [comment]
You might be able to get what you want by configuring codecov thresholds, see https://docs.codecov.io/docs/commit-status.  nyc can not provide direct assistance with tracking coverage from one build to the next, this is something which needs to be done externally.

nyc supports using `nyc.config.js` to provide configuration but if this can accomplish exactly what you want.  Maybe you could query codecov "what was the latest coverage results" then have nyc.config.js provide settings with increased thresholds.  `nyc.config.js` can export a promise:
```js
module.exports = new Promise(async resolve => {
  const previousCoverage = await getPreviousCoverageSomehow();
  resolve({
    all: true,
    lines: Math.min(100, previousCoverage.lines + 5)
    // etc..
  });
});
```

Since this requires an external service to track previous coverage it is out of scope for nyc itself.

**Comment by GrayedFox** [comment]
Fair enough, I'll post a solution here if I figure out a way to store the value somehow in a CI environment variable - that would be handy since it would work around having to add another service of some sort. Cheers!
