### ISSUE TITLE
Proposal: Use Node's native coverage when available or specified

### ISSUE THREAD

**Issue by vassudanagunta** [istanbuljs/nyc#1343]
## Expected Behavior

1. `nyc node test.js` should work when `test.js` imports [ES6 modules](https://hacks.mozilla.org/2015/08/es6-in-depth-modules/)

2. Likewise `nyc mocha` and other similarly invoked test frameworks should work when the tests import ES6 modules. 

3. Be able to generate coverage using `tsc` transpiled Typescript (or any other transpiler for that matter) rather than requiring the use of `ts-node` and `--require ts-node/register`.
   - Simpler
   - Does not force people with already established use of `tsc` to figure out how to also integrate `ts-node` into their builds just to get test coverage reports.
   - `ts-node` does not support ES6 modules.
 
4. Tools that integrate with `nyc`/`Istanbul` such as Webstorm inherit all of the above automatically.   

`nyc` I believe was supposed to make Istanbul use simple and "just work". In at least the above cases, and possible many others, @bcoe's [`c8`](https://github.com/bcoe/c8)'s use of Node's built-in coverage reporting fulfills that promise far better.

## Observed Behavior

Empty coverage reports (a few lines all zeros) or errors.

### Troubleshooting steps

I'll not try to remember and record the day and a half of trial and error after error here because I've learned that this is a known issue, though I'm not sure if it's a [ts-node problem](https://github.com/TypeStrong/ts-node/issues/935) or an `nyc` limitation (because it can't hook into into `import`s like it does `require`?)

I did confirm nyc is able to instrument the files using `nyc instrument`.

Then by chance on the Istanbul homepage I saw:

> Like nyc, c8 just magically works:
> ```
> npm i c8 -g
> c8 node foo.js
> ```

I installed `c8` and boom, it worked instantly, and yes, magically. Whether running a homemade `test.js`, Mocha based-tests, or even non-test code. No [special `nyc` configuration for Typescript](https://github.com/istanbuljs/nyc#typescript-projects) (it automatically picked up the source-maps), no need to install ts-node and inject it into the mocha command line (`--require ts-node/register`).

But only on the command line. I use Webstorm, which has specific integrations with `nyc` and so does not pick up the coverage report from `c8` even though it reports using the same Istanbul's reporters Webstorm reads. 

## Proposal

*Merge `c8` into `nyc`, or have `nyc` wrap `c8` and it's original code, so that all tools that work with `nyc` will transparently benefit from the optional improved compatibility of [Node's native coverage instrumentation](https://nodejs.org/dist/latest-v10.x/docs/api/cli.html#cli_node_v8_coverage_dir).*

I can wait and hope the Webstorm folks [integrate with C8](https://youtrack.jetbrains.com/issue/WEB-45069). But in my above hunt for a solution I've come across many other people in other situations whose woes I suspect would disappear if Node's native functionality were leveraged, either optionally or automatically. 

## Environment Information

```
  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
    Memory: 81.98 MB / 8.00 GB
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  npmPackages:
    eslint-plugin-babel: ^5.3.1 => 5.3.1 
    source-map-support: ^0.5.19 => 0.5.19 
    typescript: ^4.0.2 => 4.0.2 
```

**Comment by vassudanagunta** [comment]
@bcoe I would very much appreciate your thoughts on this.

**Comment by coreyfarrell** [comment]
Please see [@istanbuljs/esm-loader-hook](https://github.com/istanbuljs/esm-loader-hook).  This adds the ability to get experimental support for Node.js ES modules to nyc.  The situation with this additional module will only improve, in particular it relies on functionality which is flagged as experimental by Node.js itself.

At this time I have not considered integrating c8 into nyc.  There are a few issues I have with the node native coverage (really issues with v8) which lead me to think that both projects have a place.  In particular v8 native coverage sometimes does not detect all branches and it does report per-statement coverage.

**Comment by vassudanagunta** [comment]
Thanks for the reply.  Ok. I gave the esm-loader-hook a shot. It works if I invoke it directly on some JS:

```
npx cross-env 'NODE_OPTIONS=--experimental-loader @istanbuljs/esm-loader-hook' nyc test/test.js
```

But invoking it on `mocha` exactly as directed by the esm-loader-hook instructions produces:

```
$ npx cross-env 'NODE_OPTIONS=--experimental-loader @istanbuljs/esm-loader-hook' nyc mocha
(node:12502) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12503) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /Users/vas/Repos/projects/TextPlainly/TextPlain.js/node_modules/mocha/bin/mocha
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:101:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:31)
    at async Loader.import (internal/modules/esm/loader.js:164:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

**Comment by vassudanagunta** [comment]
Also, feel free to close this issue if you wish.

**Comment by coreyfarrell** [comment]
@vassudanagunta I think the issue you saw with `Unknown file extension ""` may have been a bug in specific versions of node.js.  Maybe try again with current version of 14.x or 15.x?  Keep in mind this is all experimental so issues like this are expected from time to time.

Another thought mocha says it supports all [node flags](https://mochajs.org/#about-node-flags) which are supported by the current version of node, maybe you could try:
```
npx nyc mocha --experimental-loader=@istanbuljs/esm-loader-hook
```

**Comment by coreyfarrell** [comment]
c8 is a great tool but it is a separate project.  I'm going to close this issue as nyc will not be merging with c8, both tools have their place and in some niche cases c8 might not be best (likewise in some niche cases nyc is not best).  I think the current situation is best where package maintainers choose which tool is best for their usage.

**Comment by vassudanagunta** [comment]
@coreyfarrell, sorry for my not following up earlier. I've been occupied by other things in these crazy times.

> Another thought mocha says it supports all [node flags](https://mochajs.org/#about-node-flags) which are supported by the current version of node, maybe you could try:
> 
> ```
> npx nyc mocha --experimental-loader=@istanbuljs/esm-loader-hook
> ```

This works!  Thank you!

**Comment by andersk** [comment]
`@istanbuljs/esm-loader-hook` no longer works in Node.js ≥ 16.12.0 due to an incompatible change in the experimental ESM loader hook API (istanbuljs/esm-loader-hook#6).

**Comment by cblanquera** [comment]
Hello from 2025 💃 . Just to note that the following is working for me on node v22 and testing ESM code.

```bash
NODE_OPTIONS="--experimental-loader @istanbuljs/esm-loader-hook" nyc ts-mocha -r tsx tests/*.test.ts
```
