### ISSUE TITLE
NYC changes semantics of the program

### ISSUE THREAD

**Issue by QuXing9** [istanbuljs/nyc#1350]
## Description:

Hello, I have an issue that I cannot resolve without your help.

When I use Nodejs to run the following program.js, the test is running OK. e.g: `node program.js` 
When I use  NYC to get the coverage of the program, the test is failing due to timeout. e.g: `nyc node program.js`

After analyzing, I find that NYC changed the semantics of the program. In program.js, `v1 > v0` returns False since the character `b > a`.  But, after instrumenting, `v1 > v0` returns True since the character `1 > 0`. And then, the program enters an infinite loop.

Does NYC have an argument to limit program execution time? When the limit is exceeded, the process is killed.
If not, Do you have some ways to break this infinite loop?

## program.js:

```js
var v0 = function (v1){
	var b = 1;
};
var v1 = function (v1){
	var a = 1;
};

console.log(v0<v1);

while(v0 < v1){
};
```

## NYC instrument

```js
cov_4ps048zci();
cov_4ps048zci().s[0]++;
var v0=function(v1){
	cov_4ps048zci().f[0]++;
	var b=(cov_4ps048zci().s[1]++,1);
};
cov_4ps048zci().s[2]++;
var v1=function(v1){
	cov_4ps048zci().f[1]++;
	var a=(cov_4ps048zci().s[3]++,1);
};
cov_4ps048zci().s[4]++;
console.log(v0<v1);
cov_4ps048zci().s[5]++;
while(v0<v1){};
```

**Comment by coreyfarrell** [comment]
nyc does change the output of `fn.toString()`, restoring the original `fn.toString()` is out of scope.  If this is a requirement of your project I recommend looking into `c8`.  Another option if this occurs in limited number of functions you could tell istanbul to ignore those two functions:
```js
/* istanbul ignore next */
var v0 = function (v1){
	var b = 1;
};
/* istanbul ignore next */
var v1 = function (v1){
	var a = 1;
};

console.log(v0<v1);

while(v0 < v1){
};
```

> Does NYC have an argument to limit program execution time? When the limit is exceeded, the process is killed.
> If not, Do you have some ways to break this infinite loop?

NYC does not have a feature for limiting program execution time.  I'd suggest looking to your testing framework for this (mocha, tap, etc).  That is where this sort of test timeout would be implemented.
