### ISSUE TITLE
Using NYC with ecomcon

### ISSUE THREAD

**Issue by visaudi** [istanbuljs/nyc#1352]
Thank you for your time and making this such a powerful tool. I don't expect anyone to go to deep into this, I'm glad to receive suggestion of where to look in the source and what to investigate.

I was using NYC without econcom and everything was checking coverage just fine. Econcom allows one to enable comments conditionally allowing one to test things like closures more effectively. Once I started using it it said a file that was completely covered was not covered at all.

## Link to bug demonstration repository

The repo is private, but here is a link to econcom:

https://github.com/douglascrockford/ecomcon/

I'm glad to make a demo repository too if you want. Just let me know if you find that helpful.

## Expected Behavior

I would expect everything in adapters.js to be passing.

## Observed Behavior

![image](https://user-images.githubusercontent.com/2923982/93226899-1110e700-f731-11ea-8748-3ef167ca7bc5.png)

## Environment Information

```

"nyc": {
    "all": true,
    "cwd": "../hams/build/test",
    "include": [],
    "exclude": [
      "for-db.js",
      "tools/*.js"
    ]
  },

```

## Requests

Feel free to make any requests for me to check anything or to ask any questions.

Glad to build a demo repo, too.

**Comment by coreyfarrell** [comment]
I suspect ecomcon is hijacking the `require` process instead of injecting itself, thus blocking nyc from injecting coverage counters.  I don't know how/if this can be solved, I don't have time to dig into ecomcon.

**Comment by visaudi** [comment]
Do you want me to do some leg work to figure out what’s going on?

What should I find out for you?

Thanks so much!

**Comment by coreyfarrell** [comment]
I don't know what to suggest as I know nothing about ecomcon.  One comment nyc has some rough edges with the cwd setting, it's better to ensure `process.cwd()` contains all code.  Source maps should not point outside the cwd either.
