### ISSUE TITLE
Could JS engines be used as the test runner?

### ISSUE THREAD

**Issue by QuXing9** [istanbuljs/nyc#1356]
Hi! I tried to use js engines such as javascriptcore and chakra as the test runners, But nyc failed to get the coverages. After changing the test runner to nodejs, nyc got the coverages successfully.  So I want to ask how to use the JS engine as the test runner correctly? Thx~

**Comment by coreyfarrell** [comment]
nyc only provides direct support for node.js.  Other engines likely have different methods for hooking calls to `require` and nyc does not support those hooks.  Without additional maintainers we are not able to expand support to other engines.
