### ISSUE TITLE
Apply source-maps in top-level process.

### ISSUE THREAD

**Issue by jamestalmage** [istanbuljs/nyc#137]
Right now we save source-maps to the cache, and apply them at the time of report creation. This prevents having to repeatedly extract the sourcemap, and did improve performance.

However, it has become a repeated failure point. [This](https://github.com/gotwarlost/istanbul/pull/521) may be another example. Instead of waiting for report creation, I am starting to think that we should load up all the reports and apply the source-maps at the end of execution (similar to how we would if a `--reporter` is specified).

**Comment by bcoe** [comment]
@jamestalmage more food for thought, it would be awesome to apply source-maps to stack traces.

**Comment by seanpoulter** [comment]
That's what I'm reading the issues for now @bcoe -- applying source-maps to stack traces. **How can I help?**

**Comment by bcoe** [comment]
@seanpoulter sorry for the slow response, am at GitHub issue overload 😛 

There has been some prior art with regards to supporting source-maps in stack traces:

https://github.com/istanbuljs/nyc/pull/393 (thanks @kpdecker!)

It would be great to have another person try out the functionality; it would also be awesome to add a post on https://github.com/istanbuljs/istanbuljs.github.io.

**Comment by seanpoulter** [comment]
Understandably overwhelmed @bcoe.
I'll have a look over the coming week.

**Comment by bcoe** [comment]
I've been making a few stability fixes recently around source-maps, and I think we're actually in a pretty healthy place using the cached approach -- closing this since we haven't seen activity in quite some time.
