### ISSUE TITLE
Sample on how to use the NYC report directly from Node

### ISSUE THREAD

**Issue by uxkjaer** [istanbuljs/nyc#1374]
I've written a NPM package that takes it's origins in the istanbul-middleware package. I've altered the code to be es6 compliant and use NYC instead. However I couldn't figure out how to create the HTML reports directly by calling the istanbul packages, so currently the code works by adding the .nyc_output folder directly to the source of the developers repository and then use a child process to run NYC report and then host that as static files. I would love for it not to be so invasive and use the internal classes to generate the report. Main reason for this is to enable selenium testing and also UIveri5 which is a end-to-end testing tool in the SAP ecosystem.
I was hoping someone could help me with a sample. 

You can check out the package on https://github.com/uxkjaer/nyc-middleware

**Comment by coreyfarrell** [comment]
nyc is not an API, it's a program.  If you wish to generate reports from coverage data that is in memory you will need to use `istanbul-lib-report` and `istanbul-reports` directly.  In the case of nyc this is done starting at the `async report` method, see https://github.com/istanbuljs/nyc/blob/91ae8b8764cef361fe6add31ae0802dc221fb577/index.js#L446.  Obviously this loads JSON files from .nyc_output so you will need to write your own code to do the same but this is the functional example.

Unfortunately the documentation is poor / does not exist for some of the underlying libraries but hopefully the nyc code will help you get started.
