### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by Loksly** [istanbuljs/nyc#1375]
https://istanbul.js.org/ is down

## Expected Behavior

website is active

## Observed Behavior

404 error

**Comment by denissabramovs** [comment]
same here

**Comment by coreyfarrell** [comment]
Thank you for the report, I'm looking into this issue but have not yet found resolution.  For now you can still access the documentation site via https://istanbuljs.github.io/.  I will comment again and close this issue when istanbul.js.org is working again.

**Comment by coreyfarrell** [comment]
istanbul.js.org is fixed.
