### ISSUE TITLE
bin/nyc.js return once start

### ISSUE THREAD

**Issue by hzk007** [istanbuljs/nyc#1376]
Hi, When I use this command to generate a report, I found it returns with this picture..
npx nyc report -t output --reporter html --report-dir output-html
![image](https://user-images.githubusercontent.com/41773976/102595323-5e4a8d80-4152-11eb-9625-006354c592e3.png)

![image](https://user-images.githubusercontent.com/41773976/102595179-2b07fe80-4152-11eb-83f9-b857a9156744.png)

**Comment by coreyfarrell** [comment]
`nyc report` is handled in https://github.com/istanbuljs/nyc/blob/master/lib/commands/report.js.  This return is correct, it ensures that `nyc report` does not try executing your tests.
