### ISSUE TITLE
nyc: no coverage results while using "excludeNodeModules: false"

### ISSUE THREAD

**Issue by Raag007** [istanbuljs/nyc#1378]
Hello, 

We are using Lerna Mono Repos for our project, and using `nyc` and `mocha` for code coverage reports. 
We have the below packages setup. 
`package1` -> Public package which gets published to registry.
`package2` -> Private package where we have our tests for `package `

Each package is having a`.nycrc.json` file which extends to root `.nycrc.json`

After `lerna bootstrap` -  `package2` will have `package1` symlink in it's `node_modules`

We want to do something like below in `.nycrc.json`: 
```
{
	"all": true,
	"reporter": ["cobertura", "text"]
	"include": ["dist/out/**", "node_modules/package1/src/**"],
	"exclude": ["**/{test,tests}/**"],
	"excludeNodeModules": false
}
```
But we are not getting any code coverage results. 

Are we missing something? Please let me know if you have any questions.

Thanks in advance!

**Comment by v-anvodn** [comment]
Hello, is anyone seeing this issue?

**Comment by coreyfarrell** [comment]
If your `dist/out/**` has source-maps pointing to original source paths then you need to add the original source paths to your `include` option.

As an alternative you might be able to set `"excludeAfterRemap": false`.

If not we will need a minimal reproduction.
