### ISSUE TITLE
Output to file instead of stdout

### ISSUE THREAD

**Issue by anton-johansson** [istanbuljs/nyc#1380]
I'm trying to configure `nyc` + `ava` for my CI tool (Gitlab). I want two separate reports so Gitlab can read them properly. I can get `ava` to report the contents in xUnit format to a file, but I cannot figoure out how to get `nyc` to output the summary to a file instead of standard out. When it outputs to standard out, it will be included in my `ava` report. Here is my command so far:

```shell
$ mkdir --parents .ava && nyc ava --tap | tap-xunit > .ava/xunit.xml
```

My current workaround is to run unit tests and code coverage in two separate steps, which is bad because it takes more time (I have to run unit tests twice).

Ideas?

**Comment by coreyfarrell** [comment]
You can tell nyc to be silent during the test execution, then have it run reports separately.
```js
nyc --silent ava --tap | tap-xunit > .ava/xunut.xml && nyc report
```

The `--silent` argument tells it not to output reporting, then `nyc report` does it separately.  Then you could redirect the `nyc report` output to a report.

**Comment by anton-johansson** [comment]
That is genious, thanks a lot @coreyfarrell!
