### ISSUE TITLE
NYC fails here due to incorect this reference

### ISSUE THREAD

**Issue by sofiha-sven** [istanbuljs/nyc#1382]
In function
https://github.com/istanbuljs/nyc/blob/91ae8b8764cef361fe6add31ae0802dc221fb577/index.js#L388

there is an not allowed use of this. this will be invalid (not nyc)

https://github.com/istanbuljs/nyc/blob/91ae8b8764cef361fe6add31ae0802dc221fb577/index.js#L392
https://github.com/istanbuljs/nyc/blob/91ae8b8764cef361fe6add31ae0802dc221fb577/index.js#L399

Better use:
```
     // Remove any files that should be excluded but snuck into the coverage
    Object.keys(coverage).forEach((absFile) => {
      if (!this.exclude.shouldInstrument(absFile)) {
        delete coverage[absFile]
      }
    }, this)

    if (this.cache) {
      Object.keys(coverage).forEach( (absFile) => {
        if (this.hashCache[absFile] && coverage[absFile]) {
          coverage[absFile].contentHash = this.hashCache[absFile]
        }
      }, this)
    } else {
      coverage = this.sourceMaps.remapCoverage(coverage)
    }
```

**Comment by sofiha-sven** [comment]
this may happen as a side effect when testing code which contains the following code fragement

    Array.prototype.forEach = function (callback, thisArg) {
      var T, k
    
      if (this === null) {
        throw new TypeError(' this is null or not defined')
      }
    
      // 1. Let O be the result of calling ToObject passing the |this| value as the argument.
      var O = Object(this)
    
      // 2. Let lenValue be the result of calling the Get internal method of O with the argument "length".
      // 3. Let len be ToUint32(lenValue).
      var len = O.length >>> 0
    
      // 4. If IsCallable(callback) is false, throw a TypeError exception.
      // See: http://es5.github.com/#x9.11
      if (typeof callback !== 'function') {
        throw new TypeError(callback + ' is not a function')
      }
    
      // 5. If thisArg was supplied, let T be thisArg; else let T be undefined.
      if (arguments.length > 1) {
        T = thisArg
      }
    
      // 6. Let k be 0
      k = 0
    
      // 7. Repeat, while k < len
      while (k < len) {
        var kValue
    
        // a. Let Pk be ToString(k).
        //   This is implicit for LHS operands of the in operator
        // b. Let kPresent be the result of calling the HasProperty internal method of O with argument Pk.
        //   This step can be combined with c
        // c. If kPresent is true, then
        if (k in O) {
          // i. Let kValue be the result of calling the Get internal method of O with argument Pk.
          kValue = O[k]
    
          // ii. Call the Call internal method of callback with T as the this value and
          // argument list containing kValue, k, and O.
          callback(kValue, k, O)
        }
        // d. Increase k by 1.
        k++
      }
      // 8. return undefined
    }

**Comment by coreyfarrell** [comment]
The nyc code you referenced is correct so this likely means your replacement `Array.prototype.forEach` does not properly handle the second argument (thisArg).  The second argument being `this` means that `Array.prototype.forEach` is supposed to run the callback using the provided `this`.  nyc cannot support situations where JavaScript built-in's are replaced by broken implementations.

**Comment by sofiha-sven** [comment]
Thank you for your feedback.
I will try to get rid of that replacement, which is however the standard ECMA-262 implementation

https://reference.codeproject.com/book/javascript/Reference/Global_Objects/Array/forEach

just out of curriosity: is there a reason for using the different call styles "_() =>{}_" and "_function(arg){}_" ?

**Comment by coreyfarrell** [comment]
The link shows `callback.call(T, kValue, k, O);` and explains why in a comment, the code you posted has `callback(kValue, k, O)`.  This is the cause of the failure.

The different callbacks are evidence that nyc has been around for a while.  Eventually this code will probably change to use for-of syntax but that's not a priority as the current code is not broken.

**Comment by sofiha-sven** [comment]
Thank you, my bad, I missed that point. 

This really helps a lot. Keep up the good work!
