### ISSUE TITLE
Is it possible to see which tests are calling a specific method?

### ISSUE THREAD

**Issue by BTBP** [istanbuljs/nyc#1383]
Hello,

I would like to know if it's possible to find out which tests are calling specific lines of code.

For example, I would like to know what tests are calling 'sayHello'  

Line	| Times	| Code
...
100	| 1x	| sayHello(val) {
101	| 1x	| 	if (val) {
102	| 1x	| 		console.log('hello');
103	|       | 	} else {
104	|       | 		console.log('goodbye');
105	| 	| 	}
106	| 	| }

Thanks.

**Comment by coreyfarrell** [comment]
This is not possible for nyc to do.  We count the number of times each statement is run but we do not know anything about the call stack.  Also given that nyc is test framework agnostic we have no way to determine which test is running, nevermind the overhead of doing this everywhere would be completely prohibitive.  My advice (what I do) is add code such as the following when you want to know how something is run:
```js
try {
	throw new Error('hit');
} catch (error) {
	console.error(error);
}
```

This will print a backtrace to stderr every time it is hit.
