### ISSUE TITLE
NYC fails to instrument files that have private class methods (#method(){})

### ISSUE THREAD

**Issue by tcf909** [istanbuljs/nyc#1387]
Example problem_file.js:
```
class a {
 #method(){}
}  
```
```
nyc --all --cache=false node ./problem_file.js
```
## Expected Behavior
To have the file show up in the listed output.

## Observed Behavior
The file does not show up in the list

### Troubleshooting steps
If you look at the node_module/.cache you see the file was not actually instrumented.

## Environment Information
System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 79.61 MB / 16.00 GB
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  npmPackages:
    nyc: ^15.1.0 => 15.1.0
```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------

```

**Comment by tcf909** [comment]
Figured out I needed additional babel modules (which I hope will be included by default in the future).

My commands to resolve:
```
yarn add --dev @istanbuljs/nyc-config-babel @babel/register @babel/plugin-proposal-private-methods @babel/preset-env
echo '{ 
  "extends": "@istanbuljs/nyc-config-babel"
}' > .nycrc
echo '{
  "presets": ["@babel/env"],
  "plugins": ["istanbul", "@babel/plugin-proposal-private-methods"]
}' > .babelrc
```

**Comment by ljharb** [comment]
I'd assume that, lacking the babel method, nyc would error out with a syntax error.

**Comment by coreyfarrell** [comment]
nyc uses babel internally and does allow for configuration of the `parserPlugins` that are used.  By default this does not include `classPrivateMethods` as no version of node.js supported that when the latest release was cut.  This can be added at https://github.com/istanbuljs/schema/blob/c7747f7a7df8a2b770036834af77dfd0ee445733/index.js#L121-L141 along with any additional babel parser plugins which would be needed to parse code supported directly by any release of node.js.  The full list of parser plugins are at https://babeljs.io/docs/en/babel-parser#plugins.

For reference the best way in the mean time to support this for your project is to create `nyc.config.cjs`:
```js
'use strict';

const {parserPlugins} = require('@istanbuljs/schema').defaults.nyc;
module.exports = {
  parserPlugins: [
    ...parserPlugins,
    'classPrivateMethods'
  ]
};
```

I've created https://github.com/istanbuljs/schema/issues/16 for this since the fix would go in that module.

**Comment by tcf909** [comment]
Awesome. Much better fix than what I had implemented.

Do you know when the next version will be released so the work around won't be necessary?

**Comment by tcf909** [comment]
Also, for the record, where do your babel plugins come from? Do I need to also install them, and where do the names actually come from (meaning, on the babel plugin page as well as npm repo they are dash separated, but the plugins listed are all camel case). How does the list actually get used?

For instance, adding 'classPrivateMethods' does indeed work, but where on earth is it getting the code to do the translations from at that point (given I do not have the babel plugin installed via npm)?

Thanks

**Comment by coreyfarrell** [comment]
babel parser plugins are all built-in, babel does not support 3rd party parser plugins so the complete list for the current version of `@babel/parser` is at https://babeljs.io/docs/en/babel-parser#plugins.  Normal babel plugins are a different thing from parser plugins.

I've made a new in-range release of `@istanbuljs/schema` which sets nyc's default babel parser features to match the capabilities of node.js 15.8.0.
