### ISSUE TITLE
Package Dependency update

### ISSUE THREAD

**Issue by brad-bergeron-tm** [istanbuljs/nyc#1389]
Bug demonstration repository: N/A 

The current version of yargs in the project, 15.0.2 contains a known security vulnerability with a package it is dependent on: y18n (^4.0.0): https://snyk.io/vuln/SNYK-JS-Y18N-1021887. 

Please update yargs to 16.2.0 to remove the security vulnerability.

**Comment by coreyfarrell** [comment]
`^4.0.0` allows install of 4.0.1 where the vulnerability is fixed.  This is how semver ranges work, you need to update your local install (possibly regenerate package-lock.json).
