### ISSUE TITLE
Numeric separators (1_000_000_000_000) cause file to not be instrumented.

### ISSUE THREAD

**Issue by jwickens** [istanbuljs/nyc#1392]
Numeric separators (1_000_000_000_000) in a source file will cause that file to not be instrumented.

```js
const MY_NUMBER = 1_000;
```

This is valid in Node.js and several browsers: https://caniuse.com/mdn-javascript_grammar_numeric_separators

However any file containing this will not be included in code coverage reports.

Discovered on nyc version 14.1.1 and nodejs 12.16.3

**Comment by coreyfarrell** [comment]
nyc 14.1.1 is not current.  Numeric separators are supported in 15.x.
