### ISSUE TITLE
COVERAGE FAILS FOR LOCAL NODE MODULE

### ISSUE THREAD

**Issue by jagdeepak-prat** [istanbuljs/nyc#1397]
https://github.com/jagdeepak-prat/nyc_coverage_failure

## Expected Behavior
I am trying to get coverage report with 
"chai": "^4.3.4",
"mocha": "^8.3.2",
 "nyc": "^15.1.0"

I have a dummy_node_module dependency which is also developed locally. 
I am trying to get the coverage report for a file in the dependency along with coverage report for the main project.
So, I put a .nycrc with following config:
{
"include": [
      "index.js",
      "node_modules/dummy_node_module/index.js"
 ],
"excludeNodeModules": false
}

When I install the dependency after pushing it to git, it gives me the coverage report properly. 
the dependencies looks like following: 
  "dependencies": {
    "dummy_node_module": "git+https://github.com/jagdeepak-prat/dummy_node_module.git"
  }

## Observed Behavior

But when I try to install it with a file path like so,
"dependencies": {
    "dummy_node_module": "file:../dummy_node_module"
  }

It doesn't account for the files in "dummy_node_module". 

## Environment Information
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 1.22 GB / 16.00 GB
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  npmPackages:
    nyc: ^15.1.0 => 15.1.0 
![Screen Shot 2021-03-16 at 2 27 04 PM](https://user-images.githubusercontent.com/56348675/111282412-fb3e9900-8663-11eb-8ba3-9947b89d7fc4.png)
![Screen Shot 2021-03-16 at 2 27 51 PM](https://user-images.githubusercontent.com/56348675/111282425-fe398980-8663-11eb-9320-88a0bc4d66c0.png)

**Comment by coreyfarrell** [comment]
The `file:` install method uses a symbolic link, so nyc understands the real file location as `../dummy_node_module`.  Collecting coverage for files outside the project root is not supported.  If you were to have the files in say `packages/dummy_node_module` then you could add that directory to your include list, this is how monorepos are often setup.

**Comment by jagdeepak-prat** [comment]
yes. That's true. Thanks @coreyfarrell for the quickest reply on any issue ever. :) 
I will close the issue now.
