### ISSUE TITLE
nyc related failure in tap AppVeyor tests

### ISSUE THREAD

**Issue by jamestalmage** [istanbuljs/nyc#140]
https://ci.appveyor.com/project/isaacs/node-tap-5bjxi/build/20/job/3ym11uvlr09i0nwc#L535

**Comment by bcoe** [comment]
@jamestalmage get a chance to dig into this at all? perhaps try with the current master which has upgraded a few dependencies.

**Comment by bcoe** [comment]
@jamestalmage ever get anywhere with this, is it still cropping up on newer builds?

**Comment by jamestalmage** [comment]
Oh, man. I don't know. Let's close this. I haven't hacked on `node-tap` in a while so I really don't know.

Myself or someone else can reopen if it comes up again.
