### ISSUE TITLE
Upgrade yargs to avoid dependency issue 

### ISSUE THREAD

**Issue by charlierudolph** [istanbuljs/nyc#1402]
I'm a maintainer of [cucumber-js](https://github.com/cucumber/cucumber-js) as we use this tool and recently were alerted of the following issue with a dependency of nyc:

```
$ yarn audit
yarn audit v1.22.10
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ y18n                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.0.5||>=4.0.1 <5.0.0||>=3.2.2 <4.0.0                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > yargs > y18n                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1654                        │
└───────────────┴──────────────────────────────────────────────────────────────┘
1 vulnerabilities found - Packages audited: 732
Severity: 1 High
✨  Done in 0.89s.
```

It appears `yargs` has fixed their dependency requirement in version 16.2.0: https://github.com/yargs/yargs/commit/ae001f34c968e8f4cda2a832d85b114753f4dee0

**Comment by ldttmt** [comment]
Any update on this? Our library is also waiting for this.

**Comment by peterwj** [comment]
IF you're using yarn, you can manually edit your `yarn.lock` like this:

```
diff --git a/yarn.lock b/yarn.lock
index e43c65774..4b60837aa 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -11092,9 +11092,9 @@ y18n@^3.2.0:
   integrity sha512-uGZHXkHnhF0XeeAPgnKfPv1bgKAYyVvmNL1xlKsPYZPaIHxGti2hHqvOCQv71XMsLxu1QjergkqogUnms5D3YQ==

 y18n@^4.0.0:
-  version "4.0.0"
-  resolved "https://registry.yarnpkg.com/y18n/-/y18n-4.0.0.tgz#95ef94f85ecc81d007c264e190a120f0a3c8566b"
-  integrity sha512-r9S/ZyXu/Xu9q1tYlpsLIsa3EeLXXk0VwlxqTcFRfg9EhMW+17kbt9G0NrgCmhGb5vT2hyhJZLfDGx+7+5Uj/w==
+  version "4.0.3"
```

Then re-run `yarn` to regenerate the lockfile.  I'm sure there's a similar procedure available for `package-lock.json` as well.

**Comment by coreyfarrell** [comment]
yargs pulls y18n using semver range which allows a non-vulnerable version.  This is not a bug in nyc, the problem is your lockfile.  The sure fire way to resolve your lockfile is to delete it and reinstall to generate a new one.

**Comment by ldttmt** [comment]
Not sure why this is closed? Is there a timeline where nyc will use yargs version v16+?. We have other dependencies that use args 16.2.0 so now we have 2 versions of yargs and y18n in our node_modules.

**Comment by coreyfarrell** [comment]
yargs 16+ drops support for versions of node which nyc supports.  yargs will not be upgraded until nyc 16 which does not yet have an ETA.  nyc 16 will be a major release dropping old versions of node and upgrading to babel 8 (which is not yet available).
