### ISSUE TITLE
Open to using `const` for constant references?

### ISSUE THREAD

**Issue by jameswomack** [istanbuljs/nyc#149]
In pieces of code such as https://github.com/bcoe/nyc/blob/master/lib/source-map-cache.js#L105, _nyc_ has sets of references at the top of a function, all declared with the `var` :key:word. However, not all of the references are intended to be variable. In the case of `SourceMapCache.prototype._rewriteFunctions`, we have `f`, `fnMap` & `index`, where `index` is necessarily variable and it's two siblings are essentially constant. 

:information_source: I find that is becomes faster for everyone, especially newcomers, to read the code when declarations have as much semantic power :zap:   as possible. Using `const` adds semantic power :zap:  because tells someone that they can rely on the reference to be stable for the rest of it's lifetime :+1:. `const` also has a low barrier to entry because it's been supported in Node.js for ages (certainly for each of the version in the Travis YAML file) & it's common in many other programming languages. I've provided some additional thoughts & research on `const` [here](http://womack.io/2016/01/05/Const-ant-Craving/).

So, are you, the core contributors to NYC, open to using `const` in modules in the lib folder? I can do the initial legwork including providing some contribution notes regarding use of `const`. There seems to be sufficient tests to ensure that the behavior of _nyc_ remains constant :musical_score: :clap:.

**It gets reassigned for each key in `fileReport.fnMap`

**Comment by bcoe** [comment]
@jameswomack I'm happy to entertain this change, and would love the help :+1: 

I don't think we're concerned about supporting all the way back to `0.8`, @jamestalmage and @isaacs might want to way in on this? I don't thin tap is making an attempt to support `0.8` any more?

**Comment by isaacs** [comment]
I do still support 0.8, since the npm cli has to work there.  But const was supported in 0.8, wasn't it?

```
$ nave use 0.8 node -e 'const foo = "bar";console.log(foo);foo=1;console.log(foo)'
Already installed: 0.8.28
using 0.8.28
bar
bar
```

**Comment by bcoe** [comment]
@isaacs gotcha, it existed prior to `0.10` but wasn't announced as a feature?

**Comment by isaacs** [comment]
No idea!  I never bother to read feature announcements, because I always forget and have to check anyway.

**Comment by jameswomack** [comment]
@bcoe I've used `const` in 0.8 w/o issues as well. Maybe I can open a PR w/ proposed changes on a subset of the project?

**Comment by bcoe** [comment]
@jameswomack happy to accept that pull.

**Comment by bcoe** [comment]
I've started moving files over to `const` 👍

**Comment by jameswomack** [comment]
@bcoe awesome
