### ISSUE TITLE
JSON5 Vulnerability - Prototype Pollution in JSON5 via Parse Method

### ISSUE THREAD

**Issue by raQai** [istanbuljs/nyc#1505]
## Link to bug demonstration repository
https://github.com/advisories/GHSA-9c47-m6qq-7p4h

## Expected Behavior
Audit passing

## Observed Behavior
Audit failing

### Troubleshooting steps
```
% npm audit --audit-level=high

json5  2.0.0 - 2.2.1
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix`
node_modules/json5
```

**Comment by chungleu** [comment]
Have you tried using a [package resolution?](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) or the npm equivalent '[overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)'? This lets you override a child dependency version without having to wait for a higher one to be updated.

We had the same issue with nyc and this seemed to work for us:
```
  "resolutions": {
    "nyc/istanbul-lib-instrument": "^5.2.1"
  },
```

**Comment by raQai** [comment]
Yea thanks for the advice :slightly_smiling_face: `npm audit fix` actually resolves the failure but I just wanted to open this issue since it was not yet addressed in `nyc` itself which it probably should :)
