### ISSUE TITLE
Add the ability to specify a custom tempDirectory

### ISSUE THREAD

**Issue by kentcdodds** [istanbuljs/nyc#171]
The `NYC` constructor already accepts the option. But this needs to be exposed and utilized in the CLI. I almost had things working, but then had to get back to work.

My use case is I have frontend and backend code that's tested separately and I want to be able to track coverage on them separately. So I already specify the `--report-dir` for them, but to be able to utilize `check-coverage`, I need to be able to specify a custom `tempDirectory`.

I had to slightly alter both the `bin/nyc.js` and `bin/wrap.js`. Basically this got me most of the way there:

In **nyc.js**

``` diff
if (argv._[0] === 'report') {
  // run a report.
  process.env.NYC_CWD = process.cwd()

  report(argv)
} else if (argv._[0] === 'check-coverage') {
  checkCoverage(argv)
} else if (argv._.length) {
  // wrap subprocesses and execute argv[1]
  if (!Array.isArray(argv.require)) argv.require = [argv.require]

  var nyc = (new NYC({
    require: argv.require,
+    tempDirectory: argv.tempDirectory,
  }))
  nyc.reset()

  if (argv.all) nyc.addAllFiles()

  var env = {
    NYC_CWD: process.cwd(),
    NYC_CACHE: argv.cache ? 'enable' : 'disable',
+    NYC_TEMP_DIRECTORY: argv.tempDirectory,
  }
  if (!argv.tempDirectory) {
      throw new Error('no temp directory in nyc')
  }
  if (argv.require.length) {
    env.NYC_REQUIRE = argv.require.join(',')
  }
  sw([wrapper], env)

  foreground(nyc.mungeArgs(argv), function (done) {
    if (argv.checkCoverage) {
      checkCoverage(argv, function (done) {
        if (!argv.silent) report(argv)
        return done()
      })
    } else {
      if (!argv.silent) report(argv)
      return done()
    }
  })
} else {
  // I don't have a clue what you're doing.
  yargs.showHelp()
}

function report (argv) {
  process.env.NYC_CWD = process.cwd()

  ;(new NYC({
    reporter: argv.reporter,
    reportDir: argv.reportDir,
+    tempDirectory: argv.tempDirectory,
  })).report()
}


function checkCoverage (argv, cb) {
+  var tempDirectory = argv.tempDirectory || './.nyc_output'
  foreground(
    process.execPath,
    [
      require.resolve('istanbul/lib/cli'),
      'check-coverage',
      '--lines=' + argv.lines,
      '--functions=' + argv.functions,
      '--branches=' + argv.branches,
      '--statements=' + argv.statements,
-     path.resolve(process.cwd(), './.nyc_output/*.json')
+     path.resolve(process.cwd(), tempDirectory + '/*.json')
    ],
    cb
  )
}
```

In **wrap.js**:

``` diff

;(new NYC({
  require: process.env.NYC_REQUIRE ? process.env.NYC_REQUIRE.split(',') : [],
  enableCache: process.env.NYC_CACHE === 'enable',
+  tempDirectory: process.env.NYC_TEMP_DIRECTORY,
})).wrap()
```

I think I'm missing something somewhere, but like I said, I've run out of time to work on this. Also want to make sure this is something you want to do :-)

Thanks!

**Comment by bcoe** [comment]
@kentcdodds hey :) where does this stand. Do you want to take a stab at this feature, should we try to encourage someone else to implement this feature

**Comment by kentcdodds** [comment]
Would be awesome to set it up as a `first-timers-only` issue :+1: though, I'm not certain I know all that needs to happen for it to be implemented...

**Comment by gitgrimbo** [comment]
This feature would also help me - is it planned to be added?

**Comment by JaKXz** [comment]
@gitgrimbo good point - perhaps a PR to document it would close this issue? :)

**Comment by bcoe** [comment]
@gitgrimbo @kentcdodds doing a bit of cleanup of old issues; passing an alternate `--temp-directory` should now be supported in all scenarios, feel free to open a new issue if you bump into any bugs.
