### ISSUE TITLE
Implement --all without requiring modules

### ISSUE THREAD

**Issue by novemberborn** [istanbuljs/nyc#183]
Currently when `--all` is used we require all modules that match a glob pattern. This causes these files to be instrumented and a baseline coverage to be established in the main process.

Requiring all modules has a few problems:

* The files may need to be transpiled, so `--require` needs to be used
* The files may throw when loading because they're in the wrong environment (#175, #172)
* If the subprocess has its own require hook we may end up installing duplicate hooks (#181)

Instead what we should do:

1. Get a list of modules matching the glob pattern, without requiring them
2. Run the subprocesses
3. Built the coverage report for the subprocesses
4. For all modules found in step 1, that are not in the coverage report, synthesize coverage reports directly in nyc without instrumenting the files. We can generate these for the actual source and no transpiling should be necessary

Once we do this we may even be able to remove the `--require` flag, shifting transpilation responsibilities to the subprocess.

**Comment by bcoe** [comment]
this should be addressed in https://github.com/istanbuljs/nyc/pull/286
