### ISSUE TITLE
--silent (and probably all option) are read when they should not ?

### ISSUE THREAD

**Issue by MoOx** [istanbuljs/nyc#201]
```
  "test-with-coverage": "nyc npm -s test",
```

I want npm to be silent, not nyc. Minor issue but wanted to report it :)
Maybe option should be first?

**Comment by danez** [comment]
I have the same issue, it also happens when specifying `--reporter xunit` for mocha. nyc thinks its its reporter. 
What seems to work for us is this:

```
nyc --reporter html -- npm -s test -- --reporter xunit
```

**Comment by JaKXz** [comment]
@danez that might actually be expected behaviour, because the `--` delimiter is what lets you pass arguments to `npm run` scripts. 

@MoOx could you try [belatedly]:

```json
"test-with-coverage": "nyc npm run test -- -s"
```

**Comment by danez** [comment]
I think this would supply `-s`to whatever is called in `npm test`

I think it should be:
```
"test-with-coverage": "nyc -- npm -s test"
```

**Comment by JaKXz** [comment]
@danez passing `-s` to the `npm test` command is what I was trying to go for. The `--` delimiter is not recognized by nyc, and I don't think that line will work. It's meant for passing [different arguments to existing npm run scripts](https://docs.npmjs.com/cli/run-script).

**Comment by bcoe** [comment]
@MoOx @JaKXz I think we should definitely make nyc's parsing a bit more clever, so that it doesn't look at flags once after the bin it's instrumenting:

`nyc -f banana npm -s` should not parse `-s`, we just need to get a bit more clever with our parsing algorithm.

**Comment by bcoe** [comment]
@MoOx @danez cleaning up some old issues; I believe this should have been addressed when we pulled in `yargs-parser` and started using it to pass arguments to nyc and the instrumented bin.
