### ISSUE TITLE
TS support w/ webpack

### ISSUE THREAD

**Issue by havenchyk** [istanbuljs/nyc#229]
I'm following this issue https://github.com/bcoe/nyc/issues/176 and wondering, how can I set coverage for my tests in `ava` with help of nyc.

What I did is:
- transpile my tests from TS to es2015 with sourcemaps
- run `nyc ava`

and I've got something like this 

![img](http://i.imgur.com/FAZ04Li.png)

**Comment by novemberborn** [comment]
Could you provide more detail regarding your setup? Where does WebPack come in?

nyc can't figure out source-mapped coverage for WebPack inputs.

**Comment by havenchyk** [comment]
@novemberborn sorry, I meant **without**  Wepback. At #176 the question was mostly about webpack, but I don't use it and would like to know in general, how to set up code coverage. I'll share my soon.

**Comment by JimmyBoh** [comment]
I am also working on this, coverage support for Typescript files without the use of webpack (I have a `dist` folder that contains the pre-transpiled javascript). I will share my experiences shortly.

**Comment by JimmyBoh** [comment]
[Here is my repo](https://github.com/JimmyBoh/storm) for a node module where it is currently implemented. My basic setup is all TS files are in `src` and they transpile into `dist`. I even got it working with [Coveralls.io](https://coveralls.io/github/JimmyBoh/storm).

The crazy thing is that I see the same thing as @havenchyk when I run `nyc ava` from the command line. It only works when I run `gulp test`, [which uses `gulp-shell` to run the **exact same command**](https://github.com/JimmyBoh/storm/blob/master/gulpfile.js#L34).

Is there any reason why it would work from `gulp-shell` and not straight from the command line?

**Comment by felixfbecker** [comment]
@JimmyBoh Thank you so much for sharing this, I did it like you did in your repo and finally got it working.

**Comment by bcoe** [comment]
\o/ happy new year everyone.
