### ISSUE TITLE
Syntax Error occuers when npm command is wrapped in shell script

### ISSUE THREAD

**Issue by nana4gonta** [istanbuljs/nyc#230]
I'm trying to output the TypeScript code coverage.
But, the following error occurs when npm command is wrapped like nodenv. 
(Although I don't put execution results, `npm run test` succeeds.) 

package.json:

```
{
  "devDependencies": {
    "espower-typescript": "^5.0.1",
    "istanbul": "^0.4.3",
    "mocha": "^2.4.5",
    "nyc": "^6.4.0",
    "power-assert": "^1.3.1",
    "typescript": "^1.8.9"
  },
  "scripts": {
    "coverage": "nyc npm test && istanbul report --root artifacts/coverage/ --dir artifacts/coverage/ lcov",
    "pretest": "tsc",
    "test": "mocha --compilers ts:espower-typescript/guess test/**/*.ts"
  }
}      
```

run npm scripts:

```
$ npm run coverage

> test_nyc@1.0.0 coverage /private/tmp/test_nyc
> nyc npm test && istanbul report --root artifacts/coverage/ --dir artifacts/coverage/ lcov

/Users/xxx/.anyenv/envs/nodenv/shims/npm:3
[ -n "$NODENV_DEBUG" ] && set -x
     ^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module.replacementCompile (/private/tmp/test_nyc/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/private/tmp/test_nyc/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/private/tmp/test_nyc/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at Function.runMain (/Users/xxx/.node-spawn-wrap-9620-df7e14677e16/node:40:10)
    at Object.<anonymous> (/private/tmp/test_nyc/node_modules/nyc/bin/wrap.js:17:4)
```

Error is output in this line in the case of nodenv, but any other shell scripts that wraps `npm` becomes errors.

**Comment by addaleax** [comment]
@nana4gonta Thanks for the report! As long as you consistently use `nodenv`, you should be able to work around this by using `nyc $(nodenv which npm) test` instead of `nyc npm test` in your package.json.
Or, if you only want to apply this for when you run the script manually, set `PATH="$(dirname $(nodenv which npm)):$PATH"` in your shell (you can copy-paste that, at least if it’s bash).

@bcoe I am afraid this is my `npm` patch for spawn-wrap at work… this would be fixable on the nyc/spawn-wrap side but I’d like wait moment and think/talk about it before suggesting yet *another* horrible patch on top of the others.

**Comment by novemberborn** [comment]
@addaleax I'm using nodenv myself (version 1.0.0) and nyc@6.4.0 works fine. Just ran this locally: <https://github.com/novemberborn/x690/blob/0414cd992cce2f9ab6fd610c6c85729d09888176/package.json#L21>

This is with node v5.10.1 and npm v3.8.6 (installed through `npm i -g npm@next` some time ago).

**Comment by addaleax** [comment]
@novemberborn You’re right, this *should* work… @nana4gonta Could you maybe post the outputs of `echo $PATH` and `npm run env | grep ^PATH` (no nyc or anything)? That might be very helpful in debugging this.

**Comment by nana4gonta** [comment]
@addaleax 
I tried `nyc $(nodenv which npm) test`, but same error occuers.

`echo $PATH`:
```
/Users/xxx/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-update2/bin
:/Users/xxx/.dnx/bin
:/Users/xxx/bin
:/usr/local/opt/go/libexec//bin
:/Users/xxx/.composer/vendor/bin
:/Users/xxx/.anyenv/envs/rbenv/shims:/Users/xxx/.anyenv/envs/nodenv/shims
:/Users/xxx/.anyenv/envs/rbenv/bin
:/Users/xxx/.anyenv/envs/nodenv/bin
:/Users/xxx/.anyenv/envs/rbenv/shims
:/Users/xxx/.anyenv/envs/nodenv/shims
:/Users/xxx/.anyenv/bin
:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

`npm run env | grep ^PATH`:
```
PATH=/usr/local/lib/node_modules/npm/bin/node-gyp-bin
:/private/tmp/test_nyc/node_modules/.bin
:/usr/local/Cellar/node/5.10.0/bin
:/Users/xxx/.anyenv/envs/nodenv/libexec
:/Users/xxx/.anyenv/envs/nodenv/plugins/nodenv-vars/bin
:/Users/xxx/.anyenv/envs/nodenv/plugins/nodenv-update/bin
:/Users/xxx/.anyenv/envs/nodenv/plugins/node-build/bin
:/Users/xxx/.anyenv/envs/nodenv/libexec
:/Users/xxx/.anyenv/envs/nodenv/plugins/nodenv-vars/bin
:/Users/xxx/.anyenv/envs/nodenv/plugins/nodenv-update/bin
:/Users/xxx/.anyenv/envs/nodenv/plugins/node-build/bin
:/Users/xxx/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-update2/bin
:/Users/xxx/.dnx/bin
:/Users/xxx/bin
:/usr/local/opt/go/libexec//bin
:/Users/xxx/.composer/vendor/bin
:/Users/xxx/.anyenv/envs/rbenv/shims
:/Users/xxx/.anyenv/envs/nodenv/shims
:/Users/xxx/.anyenv/envs/rbenv/bin
:/Users/xxx/.anyenv/envs/nodenv/bin
:/Users/xxx/.anyenv/envs/rbenv/shims
:/Users/xxx/.anyenv/envs/nodenv/shims
:/Users/xxx/.anyenv/bin
:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

And, my env is node v5.10.0, npm v3.8.6 on OSX.

**Comment by addaleax** [comment]
This is really weird, everything looks good. There is a `/usr/local/Cellar/node/5.10.0/bin/npm`… right? Is the installation in `/usr/local/Cellar/node/5.10.0` from a manually downloaded tarball or `nodenv install`?

**Comment by nana4gonta** [comment]
I don't know why there is `/usr/local/Cellar/node/5.10.0/bin/`.
I installed node v5.10.0 using Homebrew, and nodenv using [anyenv](https://github.com/riywo/anyenv).

**Comment by nana4gonta** [comment]
And, Although it is not nodenv, I have no choice but to run `npm` is wrapped in shell script.
(`npm` is `exec node` shell script that give node-cli is made with `require('npm')` arguments)
(I'm sorry, I cannot paste code :( )

I wonder if nyc can support this case.

**Comment by addaleax** [comment]
> (`npm` is `exec node` shell script that give node-cli is made with `require('npm')` arguments)

Are you talking about a shell script that you wrote, or something installed by nodenv? If it’s something by you, and you can’t publish code from it, then I’m not sure we can help you.

nyc currently makes the assumption that `npm` is not a shell script, but some JS file executed using `node`. We’ve had some trouble with `nyc npm run …` in the past, and so, unfortunately, had to treat `npm` commands in a special way.

If there’s no shell script by yourself, you can try adding a `"which-npm": "which npm && head $(which npm)"` script to your package.json and run it with `npm run which-npm`; The output should indicate the `npm` executable that `nyc` would try to run, and what kind of file it is.

Also, if this happens to be specific to Homebrew, I might not be able to help much here…

**Comment by nana4gonta** [comment]
>(npm is exec node shell script that give node-cli is made with require('npm') arguments)
> Are you talking about a shell script that you wrote, or something installed by nodenv? If it’s something by you, and you can’t publish code from it, then I’m not sure we can help you.

> nyc currently makes the assumption that npm is not a shell script, but some JS file executed using node. 

Sorry, https://github.com/bcoe/nyc/issues/230#issuecomment-210289972 is talking about my env(want to run code, not OSX).
Regarding my env case, I will be looking for another way.


And, though about nodenv, Here is the result of `npm run which-npm`:
```
> which npm && head $(which npm)

/Users/xxx/.anyenv/envs/nodenv/shims/npm
#!/usr/bin/env bash
set -e
[ -n "$NODENV_DEBUG" ] && set -x

program="${0##*/}"
if [ "$program" = "node" ]; then
  for arg; do
    case "$arg" in
    -e* | -- ) break ;;
    */* )
```

I tried a few command and found:
- Homebrew insert `/usr/local/Cellar/node/5.10.0/bin/` `npm run env` probably.
- npm use abobe `/Users/xxx/.anyenv/envs/nodenv/shims/npm` when `nodenv` use `system`.
```
$ nodenv shell 5.10.1
$ npm run which-npm

> which npm && head $(which npm)

/Users/xxx/.anyenv/envs/nodenv/versions/5.10.1/bin/npm
#!/bin/sh
// 2>/dev/null; exec "`dirname "$0"`/node" "$0" "$@"
;(function () { // wrapper in case we're in module_context mode

  // windows: running "npm blah" in this folder will invoke WSH, not node.
  /*global WScript*/
  if (typeof WScript !== 'undefined') {
    WScript.echo(
      'npm does not work when run\n' +
        'with the Windows Scripting Host\n\n' +
```

It seems to solve "Do not use `system` if you use `nodenv`"...

**Comment by addaleax** [comment]
Ah yes, that makes sense that things fail only when `nodenv` uses the `system` installation… is that workaround acceptable for you?

I think I’ll make a PR for nodenv that would address this, too.

**Comment by nana4gonta** [comment]
Thanks.
Because I happen to use `system`, I will specify node version so It's OK.

**Comment by addaleax** [comment]
nodenv/nodenv#48 – It’s at least worth a shot.

**Comment by fulax** [comment]
Hello, we have this issue too. Our "node" and "npm" PATH executables are small scripts that wrap them to add the node's --max_old_space_size parameter for GC collection.

    jenkins@jenkins:~$ cat /usr/local/bin/node 
    #!/bin/sh
    exec /usr/bin/nodejs --max_old_space_size=2048 "$@"
    jenkins@jenkins:~$ cat /usr/local/bin/npm
    #!/bin/sh
    exec /usr/local/bin/node /usr/bin/npm "$@"

So, `nyc` fails with

    jenkins@jenkins:~/jobs//pgsql-orm/workspace$ ./node_modules/.bin/nyc npm run test
    /usr/local/bin/npm:2
    exec /usr/local/bin/node /usr/bin/npm "$@"
                                          ^^^^
    SyntaxError: Unexpected string

Which I'm fine with, considering the current issue.

But, if I explicitly use the /usr/bin/npm executable on the command line, I get the exact same error:

    jenkins@jenkins:~/jobs/FrontMisc/jobs/pgsql-orm/workspace$ ./node_modules/.bin/nyc /usr/bin/npm 
    run test
    /usr/local/bin/npm:2
    exec /usr/local/bin/node /usr/bin/npm "$@"
                                          ^^^^
    SyntaxError: Unexpected string

I'm confused, the path seems to be ignored while explicitly specified. Or am I missing something?

**Comment by bcoe** [comment]
@fulax 👋 the underlying issue is going to most likely be with the library [spawn-wrap](https://www.npmjs.com/package/spawn-wrap), mind opening an issue here? I'm sure @isaacs would happily accept a patch too, if you get a chance to do any digging.
