### ISSUE TITLE
Feature request: standalone configuration file

### ISSUE THREAD

**Issue by gdeoliveira** [istanbuljs/nyc#234]
While working on projects that do not have a `package.json` file present it would be nice to still be able to pass options to `nyc`. Would you consider adding support for an alternative standalone configuration file similar to `istanbul`'s `.istanbul.yml`?

**Comment by sindresorhus** [comment]
You can add a package.json file with just the nyc config:

```json
{
  "nyc": {
    "exclude": [
      "**/*.spec.js",
      "build"
    ]
  }
}
```

**Comment by jamestalmage** [comment]
I agree with @sindresorhus. The contents of an nyc config are just not substantial enough to warrant their own file. It drives me crazy that even a minimal project needs nearly 10 files, only two of which (`index.js` and `test.js`) contain code. I don't want to pile more files in the base dir of projects for no good reason.

**Comment by bcoe** [comment]
@gdeoliveira does @sindresorhus' approach of an empty package.json do the trick for you?

**Comment by gdeoliveira** [comment]
Just to clarify I wasn't proposing to move the configuration of the tool to a separate file when a `package.json` file is available, merely that it would be nice to be able to configure `nyc` on a non-node project via a secondary/alternative configuration file.

@bcoe It's a nice workaround but I think I'll stick to passing the options directly to the tool for the time being.

**Comment by bcoe** [comment]
Let's continue this discussion here: https://github.com/istanbuljs/nyc/issues/287
