### ISSUE TITLE
perfect release process

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/nyc#249]
## The Problem

It's important that we bundle dependencies for `nyc`; since nyc loads before other libraries, and has many dependencies itself, it can cause problems when these dependencies use a singleton pattern.

By bundling dependencies, we circumvent this problem because dependencies are loaded from a separate location on disk.

Unfortunately, if `nyc` is bundled with `npm > 2.x`, there is a flat directory structure, which does not avoid the singleton problem.

## Potential Solutions

* explicitly clear the require cache, rather than trying to bundle dependencies.
* find (or create) a library that solves this singleton problem ... this actually sounds kind of fun.
* other suggestions?

What do folks think? @novemberborn @jamestalmage

**Comment by jamestalmage** [comment]
> Unfortunately, if nyc is bundled with npm > 2.x, there is a flat directory structure, which does not avoid the singleton problem.

I don't think bundled deps are flattened though:

```
mkdir nyc-bundle-test
cd nyc-bundle-test
npm init -y
npm install nyc
ls node_modules
```

The `ls` command produces:

```
nyc
lodash
```

And sure enough, `lodash` is not bundled.

Without bundling, `node_modules` would contain a whole lot more.

It seems to me, we should just write an extra test that checks the following:

```js
var pkg = require('./package.json');
var assert = require('assert');

var dependencies = pkg.dependencies.slice().sort(); // optionally filter lodash if that's intentional
var bundled = pkg.bundleDependencies.slice().sort();

assert.deepEqual(bundled, dependencies);
```

**Comment by jamestalmage** [comment]
https://github.com/gajus/bundle-dependencies

**Comment by bcoe** [comment]
@jamestalmage story checks out, even with a fresh publish using `node 6.0.0 and npm 3.8.6` I wonder why we had a couple weird regressions in the last publish then?

https://github.com/bcoe/nyc/issues/245
https://github.com/bcoe/nyc/issues/246

**Comment by jamestalmage** [comment]
Hmm. Not sure.

Did you maybe `npm install` with with `npm@3` and `npm publish` with `npm@2`?

If `npm@2` bundles expecting everything to be nested, but `npm@3` installs the flat directory structure, that would cause some transitive dependencies to be missed. But that doesn't explain `foreground-child`, so really, no idea.

The better solution might be to rely on something like [`np`](https://github.com/sindresorhus/np) to cut releases. It deletes `node_modules`, reinstalls, then runs the tests. Also, it might be worth enforcing that `npm@3` is uses to perform those tests. That way we aren't bundling a deep tree of dependencies, but a deduped one. We want to avoid sharing singletons with the module under test, but there's no reason for us to take the performance hit of not deduping our internal stuff.

**Comment by bcoe** [comment]
CC: @thangngoc89 trying to figure out why bundle-dependencies behaves differently for you on V2 vs V3 of npm.

**Comment by thangngoc89** [comment]
@bcoe Thanks you. Please tell me if I can do anything to help with this.

**Comment by novemberborn** [comment]
@bcoe there's something else that's weird with the bundled dependencies.

When I install nyc (`npm i nyc`), the `package.json` files for the bundled dependencies contain a `_resolved` prop that points at an IP address. E.g. for `strip-bom` I see <http://52.202.166.115/s/strip-bom/_attachments/strip-bom-3.0.0.tgz>. Looks like 6.4.2 was pointing at <http://52.90.65.171>.

If you then generate a shrinkwrap for projects that include nyc, those sources end up in the shrinkwrap. I had to [edit them out](https://github.com/novemberborn/source-map-fixtures/commit/b4a2f808d5ab47fa31d32f3c20cf75c2e2d92d6d) for my `source-map-fixtures` package.

Happy to report this with `npm` directly, but maybe it's something with how you're publishing `nyc`.

**Comment by bcoe** [comment]
@novemberborn I'm currently benchmarking an alternate registry, which would explain where that IP address was coming from. Without shrink-wrapping myself, I didn't realize that this URL would be hard-coded as a result of bundling dependencies.

**Comment by bcoe** [comment]
@novemberborn @thangngoc89 give `npm i nyc@next` a spin, hopefully addresses the URL issue and doesn't introduce a regression with `mock-fs`.

**Comment by novemberborn** [comment]
@bcoe URL issue is still there with `6.4.4.`.

**Comment by bcoe** [comment]
I'm now using the `bundle-dependencies` module to keep better track of what we've bundled, I've also switched back to using `npm@3.x` for `nyc@7.x`, as the tarball size was ballooning without deduping.

Let's keep this open, and address any singleton bugs we run into one by one.

**Comment by bcoe** [comment]
@thangngoc89 when you get a moment could you try `nyc@7.x`:

`npm cache clear; npm i nyc@next --save-dev`

**Comment by bcoe** [comment]
I've added `bundle-dependencies` for better tracking bundling, and we're opting to bundle dependencies after a `npm 3.x` install now, to cut down on package size.
