### ISSUE TITLE
Files reported twice with different case

### ISSUE THREAD

**Issue by JimmyBoh** [istanbuljs/nyc#269]
I created a yeoman generator that creates Typescript projects with support for `nyc` and `ava` out of the box. Below is the output I am receiving when trying to get the coverage results (run `npm test` or `gulp coverage`):

![image](https://cloud.githubusercontent.com/assets/2332163/15943903/0ed11424-2e59-11e6-9c55-bb6cce4f418b.png)

The same thing also happens when opening an lcov report in the browser. See [this project as the current example](https://github.com/JimmyBoh/bio-sim). It is currently reporting a lowercase `c:\` path and an uppercase `C:\` path.

You can install the template with `npm i -g generator-jb-module`.

**Comment by JimmyBoh** [comment]
Any insight as to where to begin? Is this a bug with `nyc` or `istanbul`?

**Comment by addaleax** [comment]
Hm. Does this still happen with nyc 7.x.x? What Node.js version are you using? (If v6: does this happen with pre-v6 versions, too?)

**Comment by JimmyBoh** [comment]
```
"nyc": "^6.4.4",
```

```
>node -v
v6.2.1
```


Let me update `nyc` and try again.

**Comment by JimmyBoh** [comment]
Yep:
![image](https://cloud.githubusercontent.com/assets/2332163/16880607/0d722edc-4a84-11e6-8643-c4149814b62e.png)

**Comment by JimmyBoh** [comment]
Maybe the map files are pointing to the source files with the wrong case?

**Comment by addaleax** [comment]
It’s a long shot, but it really might be worth trying this out with Node v4. There have been changes to `fs.realpath`, which is used in the module loader, and I know that there has been some case-related Windows weirdness based on it. I think that particular issue only applied to certain kinds of drives, so it’s probably not that, but it’s the only guess I have.

**Comment by JimmyBoh** [comment]
I'll test it out with older versions of node and report back. Thanks!

**Comment by JimmyBoh** [comment]
Well I have no idea what was causing that:

| Node Version | Working Correctly |
|:------------:|:-----------------:|
|     4.4.7    |         ✓         |
|     6.0.0    |         ✓         |
|     6.2.1    |         ✓         |
|     6.3.0    |         ✓         |

It was probably just `nyc@6.4` with an older version of node.

I'll re-open if it occurs again.

Thanks for your suggestions!

**Comment by JimmyBoh** [comment]
Well, it just re-appeared. First within the terminal of Visual Studio Code, and now also appearing in the regular `cmd` windows as well. Is there a cache that `nyc` reads from that I should try clearing?

**Comment by JimmyBoh** [comment]
Well, it just re-appeared. First within the terminal of Visual Studio Code, and now also appearing in the regular `cmd` windows as well. Is there a cache that `nyc` reads from that I should try clearing?

**Comment by JimmyBoh** [comment]
From jimmyboh/bio-sim#2:

> @JimmyBoh I'm not seeing duplicate file reports (istanbuljs/nyc#269) with this setup. Could you try `npm cache clear` before `npm i -D nyc`?

Trying that now...

**Comment by JimmyBoh** [comment]
Might be an outdated version of `ava`.

Checking now...

**Comment by JimmyBoh** [comment]
I've done some research, and this is definitely a bug, but _where_ the bug exists depends on your perspective.

**Summary of the Issue:** On Windows files are being reported twice, with duplicates having zero coverage. _This only occurs when the `--all` flag is specified!_

**Within `nyc`:**
If you do not specify the `--all` flag then everything works fine. Files are loaded based on which tests are run. The absolute paths to these files begin with **an uppercase drive letter**. From what I learned these paths enter `nyc` in the [`_handleJS` method](https://github.com/istanbuljs/nyc/blob/2b64cf8c937eeb9545b41f451f32a369dc587bae/index.js#L288-L291).

If you do specify the `--all` flag, then before the `_handleJS` method gets called all of the files matching the `includes`/`excludes` are added via the [`addAllFiles` method](https://github.com/istanbuljs/nyc/blob/2b64cf8c937eeb9545b41f451f32a369dc587bae/index.js#L156-L174). These files begin with **a lowercase drive letter**.

**Within external dependencies:**
So why the difference in drive letters? When specifying `--all` there are two possible "culprits". 

The first is [`glob`](https://github.com/isaacs/node-glob) which is used in the [`walkAllFiles` method](https://github.com/istanbuljs/nyc/blob/2b64cf8c937eeb9545b41f451f32a369dc587bae/index.js#L220-L231) but that specifies the `cwd` exactly and it matches what we gave it. So I'd say that it is working as expected. _"Goood glob!"_

The second possible offender is [`istanbul-lib-hook`](https://github.com/istanbuljs/istanbul-lib-hook) which is used in the [`_addHook` method](https://github.com/istanbuljs/nyc/blob/2b64cf8c937eeb9545b41f451f32a369dc587bae/index.js#L293-L297) (which happens to be the only place where `_handleJS` is called). I'm not sure what happens within this module, but it does result in different cased drive letters being passed in to the `_handleJS` method. Most likely `istanbul-lib-hook` is working fine, since nothing jumped out at me when I saw the code. So what is it then?

**Within Node.js**
Turns out this issue is actually rooted all the way down inside Node.js. nodejs/node#6624 documents the various cases, but here is the `tl;dr` from what @thorn0 said:

> In `cmd`: 
```cmd
d:\dev\foo>node test
__dirname D:\dev\foo
__filename D:\dev\foo\test.js
require.resolve("./test") D:\dev\foo\test.js
require("path").resolve("test.js") d:\dev\foo\test.js
process.cwd() d:\dev\foo
```

The basic gist is that things aren't consistent with Node.js on Windows.

**Conclusion:**
So where is the real bug? Who should fix it? That would be up to the @istanbuljs team. Whether it is fixed in `istanbul-lib-hook` may or may not fix it (and if it does fix it, what else might it break?). The other fix (that I will gladly make a PR for) requires one new line right within the `_handleJS` method, and makes everything work perfectly. _Ahhh, that feels nice..._

I will create the PR and we can discuss it's validity further.

**Comment by addaleax** [comment]
Aaaah, right, nodejs/node#6624 was what I had in mind… thanks for the digging!

**Comment by bcoe** [comment]
@JimmyBoh great digging! sounds like something that would be worth patching in Node itself potentially -- the danger with istanbul getting overly creative, e.g., down-casing, is that it could break case-sensitive file-systems.

Let's keep this open and track https://github.com/nodejs/node/issues/6624

**Comment by JimmyBoh** [comment]
@bcoe Thanks! I agree that this should be patched on Node itself, but it seems like they are hesitant to change it for backwards compat.

My change doesn't force any particular case, just overrides the provided absolute path to use the internally specified path (`this.cwd`).
