### ISSUE TITLE
work with Istanbul, knock ES2015 support out of the park

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/nyc#282]
@gotwarlost is putting a bunch of hard work into getting Istanbul to v1, inspired partially by @dtinth's work on `__coverage__`.

I think we should move `nyc` over to this, and I have a few questions:

1. what's the best way to instrument files:
  * @gotwarlost it sounded like we could use something similar to our [existing approach](https://github.com/bcoe/nyc/blob/master/lib/instrumenters/istanbul.js#L11), but have it intelligently apply ES2015 transforms?).
  * alternatively, it sounded like we could use something closer to `__coverage__`'s approach of installing it as a babel plugin?
  * in both cases, are source-maps now applied before the coverage JSON report is output?
2. would it be possible to merge some of the existing works in progress:
  * @novemberborn, @dtinth it feels like you could work together with @gotwarlost and combine work on `istanbul-lib-instrument`, `copenhagen`, and `__coverage__`; let's come to a consensus and we'll make it the canonical library in `nyc`.
3. how can be better support other transforms (like TypeScript) @JaKXz would love to have you involved during these planning phases.

**Comment by gotwarlost** [comment]
The way I was thinking about this was:

* For folks already using Babel, instrument code using the Babel plugin so we don't have to deal with source maps at all and get "native" coverage for ES6 code.
* All others would use the "old" style of hooking istanbul after transforming to ES5 in which case, source maps etc. come into play.
* ES5 node code path uses old style as usual w/o needing source maps and such

**Comment by novemberborn** [comment]
For folks targeting Node v4 or v6 they may not even transpile code of course. Though it looks like `istanbul-lib-instrument` will work fine with ES6 now, so that's not an issue.

**Comment by bcoe** [comment]
- [ ] make sure we test some raw `v4` and `v6` source, with the new instrumenter.
- [ ] get this sucker pulled in https://github.com/istanbuljs/babel-plugin-istanbul

**Comment by bcoe** [comment]
closing in favor of:

https://github.com/istanbuljs/nyc/pull/286

https://github.com/istanbuljs/babel-plugin-istanbul
