### ISSUE TITLE
Update `istanbul` dependency per https://nodesecurity.io/advisories/118

### ISSUE THREAD

**Issue by ntwb** [istanbuljs/nyc#284]
The `minimatch` NPM module has been patched due to a regular expression denial of service:
- https://nodesecurity.io/advisories/118

- `nyc` uses the `istanbul` which uses the `fileset` module which depends on `minimatch`

- `istanbul`'s `fileset` issue: https://github.com/gotwarlost/istanbul/issues/653

- `fileset` pull request here: https://github.com/mklabs/node-fileset/pull/25

Once both upstream issues are resolved and new releases of `fileset` and `istanbul` have been released then `nyc` can be updated and a new release released.

**Comment by bcoe** [comment]
@ntwb have this on my radar for the weekend 👍

**Comment by bcoe** [comment]
@ntwb this should be addressed here:

https://github.com/istanbuljs/nyc/pull/286

available in `npm cache clear; npm i nyc@next`

**Comment by ntwb** [comment]
Nice, thanks @bcoe 👍

**Comment by ntwb** [comment]
FWIW: Fileset 2.0.2 was just released
