### ISSUE TITLE
nyc makes stack traces unreadable

### ISSUE THREAD

**Issue by jantimon** [istanbuljs/nyc#285]
When adding nyc to my ava test runs I receive wrong file numbers in stack traces
as shown in the following examples:

**Without nyc**

``` bash
ava -v
```

returns:

```
TypeError: this.getModuleNameById is not a function
      mymodule/index.js:137:52
```

**With nyc**

``` bash
nyc ava -v
```

returns:

```
TypeError: this.getModuleNameById is not a function
    mymodule/index.js:9:7575
```

(my error was neither in line 9 nor in column 7575 but in line 137)

**Comment by novemberborn** [comment]
Yea, this is a known issue, although looking through the issue list it's not explicitly tracked.

Code coverage works by transforming the original source code. Stack traces need to be translated in order to be accurate. nyc doesn't attempt to do this. It's tricky because AVA does and it's unclear how between the two of them stack trace conversion would interact.

**Comment by jantimon** [comment]
Could a sourcemap solve this?

**Comment by novemberborn** [comment]
Yes, and I prototyped a solution in <https://github.com/bcoe/nyc/pull/217>. I'm not entirely sure we can get source maps out of istanbul though, and I haven't had the time to research the interaction of multiple [`source-map-support`](https://github.com/evanw/node-source-map-support) installations within the same process.

**Comment by jantimon** [comment]
I see - sounds way more complicated than I thought..

**Comment by bcoe** [comment]
see also: https://github.com/istanbuljs/nyc/issues/137

**Comment by bcoe** [comment]
CC: @gotwarlost it would be nice to consolidate Istanbul and nyc's source-map handling, and to address issues such as stack traces 💯

**Comment by kpdecker** [comment]
Actually pretty simple to make this work with the typescript compiler (using ts-node).

Hacked this into `NYC.prototype._transformFactory`
```
      if (instrumenter.lastSourceMap) {
          instrumented += "\n" + convertSourceMap.fromObject(instrumenter.lastSourceMap).toComment();
      }
```

And added `produceSourceMaps: 'inline'` to the istanbul instrumenter and everything seemed to go through with no other changes to source-map-support or anything else.

Glad to PR this after testing in babel and vanilla, etc. If this isn't missing something obvious.

**Comment by kpdecker** [comment]
(Deleted prior comment)
It appears that this was throwing and causing the non-instrumented path to trigger, which then defaulted to the original source map, vs. the new one. Continuing investigation.

**Comment by lxe** [comment]
If you already use babel, one way to allow error stack traces to work with node-sourcemap-support is to use https://github.com/istanbuljs/babel-plugin-istanbul, and set [nyc's "sourceMap" and "instrument" settings to false](https://github.com/istanbuljs/babel-plugin-istanbul#mocha-on-nodejs-through-nyc).

**Comment by sompylasar** [comment]
https://github.com/istanbuljs/nyc/issues/619#issuecomment-331108866

**Comment by bcoe** [comment]
closing in favor of #619.
