### ISSUE TITLE
expose more Istanbul-specific configuration options

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/nyc#287]
- [x] eyeball the current Istanbul CLI, enumerate other config options that we might like to support (we can gradually add more as folks request them).
- [ ] should we add support for `.nycrc` configuration file, for folks accustomed `.istanbul.yml`?
- [ ] should we read both an `nyc` and an `istanbul` stanza from a package.json?

**Comment by EvNaverniouk** [comment]
Any reason not to accept reading existing `.istanbul.yml` files? Or allowing a `--config .nycrc` option in the API?

**Comment by bcoe** [comment]
closing in favor of: https://github.com/istanbuljs/nyc/issues/320
