### ISSUE TITLE
combine functionality of append-transform and istanbul-lib-hook

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/nyc#292]
we should figure out how we want to combine the functionality of these two libraries. Currently nyc lacks functionality surrounding the vm module.

_any work we put towards this should be against this branch: https://github.com/istanbuljs/nyc/pull/286_

CC: @gotwarlost, @novemberborn, @jamestalmage

**Comment by gotwarlost** [comment]
I'll take a crack at this. If I get stuck I'll ping you guys for help :)

**Comment by bcoe** [comment]
@gotwarlost awesome, let me know anything I can do to help -- also be liberal with opening additional tickets. I'd love to get this to the point where we're comfortable with pointing the existing Istanbul user-base at the nyc bin.

**Comment by gotwarlost** [comment]
One question: how is the `addFile` method used? Is this part of the public API for `nyc`? No one calls this in `nyc` itself apart from `addAllFiles`

**Comment by bcoe** [comment]
@gotwarlost looks like you're correct. we should rename this `_addFile` I think, and move it so it's nested directly below the method `addAllFiles`? -- make it stand out more as a private helper function, rather than an API method... I think we could do pass through NYC and give several methods this treatment.

**Comment by bcoe** [comment]
@gotwarlost this is out the door \o/
