### ISSUE TITLE
add `instrument` command line option

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/nyc#293]
We should add a command line option that allow an arbitrary file to be instrumented and returns the output. @gotwarlost it sounded like this is one of the glaring features missing in nyc, that's required for front-end Istanbul users?

**Comment by gotwarlost** [comment]
Yes, this is one of the commands istanbul supports for browser testing. I still owe you a complete list of smaller things that may be missing. I will work on this list today/ tomorrow.
