### ISSUE TITLE
nyc report exit code is 0 even when coverage requirements where not reached

### ISSUE THREAD

**Issue by tp** [istanbuljs/nyc#295]
Executing `nyc report --lines 100` reports a coverage of only 81.82% for some file, but the exit code of that process is still 0.

It would be very helpful for integration into CI if the exit code would be non-0 in order to quickly abort when detecting coverage below out requirements.

**Comment by tp** [comment]
Can be solved by appending `&& nyc check-coverage --lines 100`.

**Comment by bcoe** [comment]
@tp you can also run the initial instrumentation step, with a `--check-coverage` flag.

`nyc --check-coverage --lines=100 mocha test/*.js`
