### ISSUE TITLE
Flakey and wrong coverage reports with increasing test count

### ISSUE THREAD

**Issue by hoschi** [istanbuljs/nyc#299]
I use nyc to gather coverage reports from running my tests with AVA. With increasing test count the coverage reports are wrong and change on each run. I tried nyc@next, different Babel setups, babel-istanbul instead of the `__coverage__` plugin and node versions. Also I tried to use or disable cache behaviour of AVA and nyc, which doesn't change something. I then saw that with different setups the problem only occures when test count goes over 60:
* <50 all fine, no matter which setup e.g. babel es2015 + node 5 vs babel es2015-node6 + node 6
* ~60 after 5 runs the coverage varies about 3-4 lines
* >200 really flakey and never right

When I run AVA with `-c 1` (means only one process for a test file, parallel test cases in file) I get steady results, but wrong. They show less files in coverage report, around 50% of the real code which was covered. With more concurrent processes I get more files covered and the results get more flakey.

I have now no idea where to go further to get this fixed :(

.babelrc
```
{
    "presets": ["react", "es2015-node6/object-rest"],
    "plugins": [
        "transform-object-rest-spread"
    ],
    "env": {
        "NYCESSIX": {
            "plugins": [
                "__coverage__",
                ["resolver", {
                    "resolveDirs": ["src"]
                }]
            ]
        },
    }
}
```

test-simple script in package.json
```
ava -c 16 --require './src/test/setup/avasetup.js'
```

AVA and nyc config from package.json
```
  "ava": {
    "files": [
      "src/**/*.test.js"
    ],
    "source": [
      "src/"
    ],
    "babel": "inherit"
  },
  "nyc": {
    "exclude": [
      "**/*.test.js"
    ]
  }
```

src/test/setup/avasetup.js for CSS modules
```
var path = require('path');
var basePath = path.resolve(__dirname, '../../');
var hook = require('css-modules-require-hook');

// setup CSS modules for SCSS files
hook({
    extensions: '.scss',
    // generate easy assertable names, which be still distinguishable enough between modules
    generateScopedName: '[name]_[local]',
    rootDir: basePath,
    preprocessCss: function (css) {
        // basepath above doesn't work, replace file names, so they are findable by hook
        var modified = css.replace(/from 'assets/g, `from '${basePath}/assets`);
        return modified;
    }
});

function noop () {
    return null;
}

require.extensions['.css'] = noop;
require.extensions['.png'] = noop;
require.extensions['.jpg'] = noop;
```

nyc command to run tests and create report (AVA cache gets removed every time before this command runs through gulp):
`NODE_ENV=NYCESSIX nyc --require babel-core/register --source-map=false --instrument=false --reporter=html --report-dir reports/coverage/ npm run test-simple`

versions:
```
node: 6.2.1
npm: 3.9.3
nyc: 6.6.1
babel-core@6.10.4
babel-loader@6.2.4
babel-plugin-__coverage__@11.0.0
babel-plugin-resolver@0.0.7
babel-plugin-transform-object-rest-spread@6.8.0
babel-polyfill@6.9.1
babel-preset-es2015-node6@0.2.0
babel-preset-react@6.11.1
ava: 0.15.2 (git://github.com/avajs/ava.git#6d636f238ab02914f54be595994130c88ed52a59)
enzyme: 2.3.0
react: 15.2.0
```

**Comment by bcoe** [comment]
@jamestalmage @novemberborn have you seen any similar behavior to this? almost sounds like a race condition when coverage output is being written to disk.

**Comment by bcoe** [comment]
@hoschi if you could figure out a way to reproduce this in a repository you can share, this would be a big help.

**Comment by hoschi** [comment]
@bcoe I can't publish the original repo and can't create 200 tests in a fresh repo. I have no idea how to give you a test repo :-(

**Comment by jamestalmage** [comment]
> almost sounds like a race condition when coverage output is being written to disk.

Or that there is something wrong with our combine coverage logic (the behavior of `-c 1` makes me suspect it's not a race condition).

Impossible to figure out without a reproduction.

**Comment by jamestalmage** [comment]
@hoschi - 200 tests or 200 test files?

**Comment by bcoe** [comment]
@hoschi I was just doing a bit of digging for your other ticket, I think the culprit might be the babel cache which was interfering noticeably with my ability to instrument tests.

Try running with `BABEL_DISABLE_CACHE=1 npm run test-simple` I think you'll find things behave better... we should probably document this in the README if this is the culprit.

**Comment by jamestalmage** [comment]
also try #301 and see if it fixes anything

**Comment by hoschi** [comment]
I'm off because for holiday, but I check your suggestions and report back in two weeks.

**Comment by hoschi** [comment]
After upgrading nyc to 7.0.0 and switching to babel-plugin-istanbul this works now :)
