### ISSUE TITLE
Unknown coverage after update to 7.0.0

### ISSUE THREAD

**Issue by melihovv** [istanbuljs/nyc#311]
nyc 6.6.1
![image](https://cloud.githubusercontent.com/assets/8608721/16763416/5d3af2a0-4831-11e6-94da-2c2bd1faabd3.png)

after update to nyc 7.0.0
![image](https://cloud.githubusercontent.com/assets/8608721/16763496/ab447444-4831-11e6-84fc-759a069820e4.png)

Project https://github.com/melihovv/grammar_review_tool
Windows 7 x64
node -v
v6.3.0
npm -v
3.10.3

**Comment by bcoe** [comment]
@melihovv this actually looks like a bug in both cases, there should be an entry for every line for every file that's covered -- it looks like in both instances 0 files are being instrumented.

@addaleax just fixed some issues surrounding empty reports on Windows, which might relate to this.

**Comment by addaleax** [comment]
Yeah, sounds a lot like it’s the same as #300. Could you manually update `node_modules/nyc/node_modules/spawn-wrap` to 1.2.4 and verify that that solves the problem?

**Comment by melihovv** [comment]
@addaleax Yeah. After update spawn-wrap to 1.2.4, all is good. Thanks!

**Comment by bcoe** [comment]
@addaleax awesome, I'll get a patch release out the door with this ASAP. keeping this open until I do.

**Comment by bcoe** [comment]
@melihovv, give:

`npm cache clear; npm i nyc@next`  a spin, should have the fix.

**Comment by melihovv** [comment]
@bcoe yeah, it works.
