### ISSUE TITLE
Flag to show uncovered files doesn't work

### ISSUE THREAD

**Issue by hoschi** [istanbuljs/nyc#312]
When I run 
`NODE_ENV=NYCESSIX nyc --all --source-map=false --instrument=false --reporter=html --report-dir reports/coverage/ npm run test-simple`
I don't see uncovered files in generated report. Only when I run 
`NODE_ENV=NYC nyc --all --source-map=true --instrument=true --reporter=html --report-dir reports/coverage/ npm run test-simple`
 these files show up in reports, as expected.

I have the same setup as in #299 just with upgraded versions and babel-plugin-istanbul instead of babel-plugin-__coverage__. Additionally here is the babelrc file with NYC environment settings:
```
{
    "presets": ["react", "es2015-node6/object-rest"],
    "plugins": [
        "transform-object-rest-spread"
    ],
    "env": {
        "NYC": {
            "sourceMaps": "inline",
            "plugins": [
                ["resolver", {
                    "resolveDirs": ["src"]
                }]
            ]
        },
        "NYCESSIX": {
            "plugins": [
                "istanbul",
                ["resolver", {
                    "resolveDirs": ["src"]
                }]
            ]
        },
    }
}
```

nyc: 7.0.0
babel-plugin-istanbul: 1.0.3
Linux

**Comment by JaKXz** [comment]
As mentioned in the docs, you need to set `NODE_ENV=test` before calling `nyc`. 

I also recommend moving some of that config to your package.json

**Comment by bcoe** [comment]
@hoschi we haven't yet implemented `--all` for `babel-plugin-istanbul`, would love help! see https://github.com/istanbuljs/babel-plugin-istanbul/issues/4
