### ISSUE TITLE
Instrumentation issue

### ISSUE THREAD

**Issue by kentcdodds** [istanbuljs/nyc#316]
On [this project](https://github.com/mzabriskie/react-example/tree/d68610f81cc48c5f4d25d2958b82ba59603d3c43) I'm getting this report:

<img width="618" alt="screen shot 2016-07-14 at 9 22 49 pm" src="https://cloud.githubusercontent.com/assets/1500684/16862713/57a48e76-4a09-11e6-8549-ccc60c5f7ce4.png">

As you can see, the first `ImportDeclaration` is apparently incorrectly interpreted as an `IfStatement` and it's indicating that the `else` is not covered.

nyc version: 7.0.0
node version: 6.3.0

Let me know if I can provide any more useful information to help figure out what's going on here. Thanks!

**Comment by JaKXz** [comment]
Using `babel-plugin-istanbul` [version...]?

**Comment by kentcdodds** [comment]
Ah, yes, `babel-plugin-istanbul` version `1.0.3` (latest)

**Comment by kentcdodds** [comment]
Incidentally, on that project I've configured it to use `all` [here](https://github.com/mzabriskie/react-example/blob/d68610f81cc48c5f4d25d2958b82ba59603d3c43/package.json#L63), but that doesn't seem to be working in the output. I've gotten it to work successfully [elsewhere](https://github.com/kentcdodds/starwars-names/blob/FEM/03.2-add-coverage/package.json#L34) however. I haven't had time to dig into that separate issue, but if anyone wants to take a swing at it, that'd be neat 👍

**Comment by gotwarlost** [comment]
Thanks for reporting this issue. This is fixed in `istanbul-lib-instrument@1.1.0-alpha.3` via https://github.com/istanbuljs/istanbul-lib-instrument/commit/4274e38622af84ed9e2229e3dcf9a4d75ef2ec91

**Comment by bcoe** [comment]
@kentcdodds give:

`npm cache clear; npm i nyc@next`  a spin, should have the fix.

**Comment by kentcdodds** [comment]
That worked! And it also found another issue that the previous version had not:

<img width="516" alt="screen shot 2016-07-16 at 9 08 10 am" src="https://cloud.githubusercontent.com/assets/1500684/16895478/db4f983e-4b34-11e6-89a6-884562ebea00.png">


Before, it didn't show I hadn't covered that `else` yet 👍

**Comment by gotwarlost** [comment]
@kentcdodds - even the previous version would have _computed_ that multiple `else`-s weren't covered but it was plastering all the indicators one on top of another at the top of the report :)

**Comment by kentcdodds** [comment]
Oh, that makes sense now. Cool!
