### ISSUE TITLE
Reporting failure with class defined inside a function

### ISSUE THREAD

**Issue by BenoitAverty** [istanbuljs/nyc#325]
I have a very strange behavior when using nyc.

Here is the script inside my package.json : 
`cross-env BABEL_ENV=test nyc --reporter=lcov mocha --compilers js:babel-core/register --recursive`

And here is a bit of my tested code;

```javascript
import React from 'react';

const connect = () => (Component) => {
  // class ConnectedComponent extends React.Component {
  //   render() {
  //     return <Component {...this.props} />;
  //   }
  // }

  function ConnectedComponent(props) {
    return <Component {...props} />;
  }

  return ConnectedComponent;
};

export default () => null;
```

When I run my tests using this code, it fails for obvious reasons (I export a dummy function instead of the "connect" function). When I replace the last line with `export default connect`, then the test pass but nyc throws the following error : 

```
D:\...\node_modules\nyc\node_modules\istanbul-lib-coverage\lib\file.js:169
        var line = statementMap[st].start.line,
                                   ^

TypeError: Cannot read property 'start' of undefined
    at D:\...\node_modules\nyc\node_modules\istanbul-lib-coverage\lib\file.js:169:36
    at Array.forEach (native)
    at FileCoverage.getLineCoverage (D:\...\node_modules\nyc\node_modules\istanbul-lib-coverage\lib\file.js:168:29)
    at FileCoverage.computeSimpleTotals (D:\...\node_modules\nyc\node_modules\istanbul-lib-coverage\lib\file.js:261:23)
    at FileCoverage.toSummary (D:\...\node_modules\nyc\node_modules\istanbul-lib-coverage\lib\file.js:318:22)
    at ReportNode.getCoverageSummary (D:\...\node_modules\nyc\node_modules\istanbul-lib-report\lib\summarizer.js:81:42)
    at D:\...\node_modules\nyc\node_modules\istanbul-lib-report\lib\summarizer.js:90:33
    at Array.forEach (native)
    at ReportNode.getCoverageSummary (D:\...\node_modules\nyc\node_modules\istanbul-lib-report\lib\summarizer.js:85:28)
    at fillTemplate (D:\...\node_modules\nyc\node_modules\istanbul-reports\lib\html\index.js:116:24)

```

Also, there is an even stranger thing : when I comment out the inner function and put the class instead, then I have the same error (cannot read property start...), even though I kept the export default () => null.

I think this is related to nyc 7.0.0 but I'm not sure yet, I'll try to test with nyc 6 when I have some time.

I'm using nyc v7.0.0 and babel-plugin-istanbul v1.1.0.

**Comment by gotwarlost** [comment]
I'm going to bet that the problem is here (this piece of logic was cribbed from remap-istanbul and I think it leads to `null` weirdness).

https://github.com/istanbuljs/istanbul-lib-source-maps/blob/master/lib/transformer.js#L42-L49

@BenoitAverty - could you please run a quick test for us? Remove those lines from the source map library installed under node_modules of your app and see if things improve. If yes, we will know the root cause and can get rid of those lines for real.

**Comment by BenoitAverty** [comment]
Thanks for the quick reply. Unfortunately your test does not seem to improve my situation. I commented out all the highlighted lines you provided and it didn't change the error message. I also commented out the lines above just to try and make it fail differently but no change.

**Comment by BenoitAverty** [comment]
The issue seems to be present in NYC 6 too.

**Comment by BenoitAverty** [comment]
some more weird stuff : 
This doesn't trigger the error
```javascript
import React from 'react';

const connect = () => (Component) => {
  // class ConnectedComponent extends React.Component {
  //   render() {
  //     return <Component {...this.props} />;
  //   }
  // }

  function ConnectedComponent(props) {
    return <Component {...props} />;
  }

  return ConnectedComponent;
};

export default (() => connect)();
```

But this does : 
import React from 'react';

const connect = () => (Component) => {
  class ConnectedComponent extends React.Component {
    render() {
      return <Component {...this.props} />;
    }
  }

  // function ConnectedComponent(props) {
  //   return <Component {...props} />;
  // }

  return ConnectedComponent;
};

export default (() => connect)();

**Comment by BenoitAverty** [comment]
Could be related to istanbuljs/babel-plugin-istanbul#22

**Comment by BenoitAverty** [comment]
Fixed (related to istanbuljs/babel-plugin-istanbul#22)
