### ISSUE TITLE
filepath bug with nyc & mocha & babel-register@6.11.5

### ISSUE THREAD

**Issue by helloyou2012** [istanbuljs/nyc#329]
- `nyc@7.0.0`
- `mocha@2.4.5`
- `babel-register@6.11.5`

In `.nyc_output` json file content, file path should `nyc-mocha-chai/src/index.js` but `nyc-mocha-chai/src/src/index.js`.

Demo: https://github.com/d-band/test-boilerplates/tree/master/nyc-mocha-chai

**Comment by kripod** [comment]
Same for me, and things get even worse when I have a `test` directory with multiple test-containing folders in it which import from `./../[../]src`.

**Comment by kripod** [comment]
Using `babel-plugin-istanbul` has magically solved my problem.

**Comment by SparserLogic** [comment]
I fixed it by turning off the instrumentation and source maps with the following flags:

`nyc --source-map=false --instrument=false`

**Comment by saadtazi** [comment]
Same issue here: see [travis-ci](https://travis-ci.org/saadtazi/until-promise/jobs/147329164). Works well locally on my Mac (clean npm install + same node version).

node 6.3.1, npm 3.10.3
nyc 7.1.0

**Comment by edmundito** [comment]
I am just setting up nyc for the first time (7.1.0) and I am running into the same issue.

@kripod I've tried adding `babel-plugin-istanbul`, but then I get:

```
node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

TypeError: /Users/edmundito/project/js/path/to/file.js: Cannot read property 'start' of undefined

    at cloneLocation (/Users/edmundito/project/node_modules/babel-plugin-istanbul/node_modules/istanbul-lib-instrument/dist/source-coverage.js:21:22)
    at SourceCoverage.addBranchPath (/Users/edmundito/project/node_modules/babel-plugin-istanbul/node_modules/istanbul-lib-instrument/dist/source-coverage.js:105:34)
```

Using the latest babel-register as well. npm 2.15.18

**Comment by saadtazi** [comment]
Ok, I am on something: I forced some package versions, and I have it back to green:

working branch: https://github.com/saadtazi/until-promise/tree/fix-coveralls
diff: https://github.com/saadtazi/until-promise/compare/fix-coveralls?expand=1

`COVERALLS_SERVICE_NAME=local COVERALLS_REPO_TOKEN=g5vwMBJ6cPFrKnoeUUxen7EuXbaGkJfQ0 npm run ci`

I'll try to narrow down which combination of package(s) is causing the issue... More to come.

**Comment by bcoe** [comment]
@gotwarlost seem to have this cropping up more after a recent release, anything jump out at you?

**Comment by saadtazi** [comment]
With my project [until-promise](https://github.com/saadtazi/until-promise)
* babel-register 6.11.5 + nyc 6.6.1 : crashes
* babel-register 6.11.5 + nyc 6.2.1 : crashes
* babel-register 6.7.2  + nyc 6.2.1 : works
* babel-register 6.7.2  + nyc 6.6.1 : works

I did a `rm -rf node_modules` between each tests

**Comment by bcoe** [comment]
@saadtazi so things are now working properly on the newest version of nyc?

**Comment by saadtazi** [comment]
It seems like an update to `babel-register` (between 6.7.2 and 6.11.5) is causing the issue. Let me try with `babel-register 6.11.5 + nyc 7.1.0`...

**Comment by saadtazi** [comment]
It might worth mentioning that I have the following `nyc` config in my package.json:

```
"nyc": {
    "include": [
      "src/**/*"
    ]
  }
```

**Comment by edmundito** [comment]
I tried a few things, but the only thing I can confirm that it works with updating all the way to babel-register 6.9.0 (and having the rest of the babel dependencies up to date).

It has to be one of the 2 changes introduced over the weekend:
https://github.com/babel/babel/commits/master/packages/babel-register

**Comment by kripod** [comment]
@edmundito I got it working with the configuration below.

package.json:

```json
{
  "scripts": {
    "test": "cross-env NODE_ENV=test nyc ava --verbose && eslint ./src ./test ./bench",
    "coverage": "nyc report -r text-lcov -r html > ./coverage.lcov",
  },
  "dependencies": {
    "babel-runtime": "^6.9.2",
  },
  "devDependencies": {
    "ava": "^0.15.2",
    "babel-plugin-istanbul": "^1.0.3",
    "babel-plugin-syntax-flow": "^6.8.0",
    "babel-plugin-transform-class-properties": "^6.11.5",
    "babel-plugin-transform-flow-strip-types": "^6.8.0",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-plugin-typecheck": "^3.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2016": "^6.11.3",
    "babel-preset-stage-2": "^6.11.0",
    "nyc": "^7.1.0-candidate3"
  },
  "ava": {
    "babel": "inherit"
  },
  "nyc": {
    "require": [
      "babel-register"
    ],
    "sourceMap": false,
    "instrument": false
  }
}
```

.babelrc:

```json
{
  "presets": [
    "es2015",
    "es2016",
    "stage-2"
  ],
  "plugins": [
    "transform-runtime",
    "transform-class-properties",
    [
      "typecheck", {
        "disable": {
          "production": true
        }
      }
    ],
    "syntax-flow",
    "transform-flow-strip-types"
  ],
  "env": {
    "test": {
      "plugins": ["istanbul"]
    }
  }
}
```

**Comment by saadtazi** [comment]
Kudos to @JaKXz , he [fixed my setup](https://github.com/saadtazi/until-promise/pull/3/files) and everything is working now! Long story short, and like @kripod mentionned, using `babel-plugin-istanbul` solves the problem.

**Comment by danez** [comment]
babel-register 6.11.6 was just released, which reverted the commit that caused the problem. Sorry guys for the troubles.

**Comment by aureooms** [comment]
Works for me now.

**Comment by helloyou2012** [comment]
Problem solved. There are two ways:

1. Using `babel-register@6.11.6`
2. Using `babel-plugin-istanbul`

**Comment by kripod** [comment]
It looks like `@babel/register` 7.0.0-beta.37 brings this problem back...
