### ISSUE TITLE
NYC 7.1.0 has not been published to NPM correctly

### ISSUE THREAD

**Issue by ntwb** [istanbuljs/nyc#331]
I can see the 7.1.0 tag at https://github.com/istanbuljs/nyc/releases/tag/v7.1.0 and:
* "bcoe tagged this 18 hours ago"

And https://www.npmjs.com/package/nyc
* `bcoe published 18 hours ago`
* `7.1.0-candidate3 is the latest of 81 releases`

**Comment by bcoe** [comment]
@ntwb accidentally published to `latest` rather than `next`, `7.1.0` is now published.

**Comment by ntwb** [comment]
That bcoe 👍
