### ISSUE TITLE
--all not reporting coverage for all files.

### ISSUE THREAD

**Issue by kentcdodds** [istanbuljs/nyc#333]
[Here's an example](https://github.com/kentcdodds/starwars-names/tree/FEM/09.0-community). I've dug through the nyc code locally for over an hour and can't quite figure out what's going on, but if I add a file called `foo.js` in the `src` directory, it doesn't appear in the report :-( Any ideas?

**Comment by JaKXz** [comment]
@kentcdodds just guessing, would using a glob in `include` be better? I usually do `src/**` but I'm not sure if it's actually different.

**Comment by bcoe** [comment]
@kentcdodds `--all` isn't working with `babel-plugin-istanbul` currently:

https://github.com/istanbuljs/babel-plugin-istanbul/issues/4

would love to figure out a good approach for this.

**Comment by JaKXz** [comment]
I think this has been fixed since at least v8+, if not v7 using the `"all": true` config, and #388 fixes the CLI args precedence, right @bcoe?

**Comment by danez** [comment]
AFAIK the all option only works if nyc is doing the instrumentation itself, not if the instrumentation is done outside of nyc, like the babel plugin.

**Comment by JaKXz** [comment]
@danez I believe that's been fixed too... unless I'm remembering wrong I've got it working in a couple projects. See the [config section of the README](https://github.com/istanbuljs/nyc#configuring-nyc).

**Comment by danez** [comment]
@JaKXz I just tested with https://github.com/researchgate/webpack-watchman-plugin but only two files show up in the coverage report out of 5. The config is exactly like it is in the README, except the `require: []` but that doesn't do anything.

**Comment by JaKXz** [comment]
@danez looks like you're right and I just had confirmation bias, my bad!

One thing I did notice in your repo is that you have `NODE_ENV` set after you call `nyc` and you'll want to do that before. I tried that locally and it didn't fix it (to my surprise) so I'm not sure what's wrong. @bcoe any ideas?

**Comment by bcoe** [comment]
@JaKXz, @danez `--all` is not implemented in `babel-plugin-istanbul`:

https://github.com/istanbuljs/babel-plugin-istanbul/issues/4

Long story short, since we skip the instrumentation step in `nyc`, we never perform the walk of all files that facilitates `--all`; would love help figuring out an implementation.

**Comment by JaKXz** [comment]
Right. Let's move the discussion there then to avoid more duplicating :)

**Comment by bcoe** [comment]
@JaKXz @kentcdodds I could still use help with documenting the feature better, but we now have the core bits and pieces in place to support `--all` with the babel plugin, as discussed in:

https://github.com/istanbuljs/babel-plugin-istanbul/issues/4
