### ISSUE TITLE
Not returning the correct path to tested files

### ISSUE THREAD

**Issue by GarthDB** [istanbuljs/nyc#338]
Running nyc on [my project](https://github.com/topmarks/topmark-scrollspeed) the mocha tests of the `src` directory:

```sh
/topmark-scrollspeed/src
├── frames-util.js
└── scrollspeed.js
```

but the .nyc_output files have the wrong paths in the data (it adds an extra `src` directory in the path:

```sh
{"/topmark-scrollspeed/src/src/frames-util.js":
```

**Comment by drawnepicenter** [comment]
I have the same issue:

    src
    ├── cmds
    │   ├── acronym.js
    │   ├── anagram.js
    │   ├── comp.js

but my output is `src/cmds/cmds`.

As a workaround I've been fixing my lcov report with sed before submitting to coveralls/codeclimate.

**Comment by bcoe** [comment]
@GarthDB @drawnepicenter this looks like a similar issue to this:

https://github.com/istanbuljs/nyc/issues/329

Could you make sure you're running the most up-to-date version of babel-register, and let me know if the problem persists.

**Comment by GarthDB** [comment]
Thanks @bcoe - that clears it up for me.
