### ISSUE TITLE
2 json files generated in .nyc_output

### ISSUE THREAD

**Issue by chalda** [istanbuljs/nyc#339]
Hi,
I am trying to switch from babel-istanbul + mocha to nyc + mocha to improve test coverage (specifically for branches).

So I can do "html" reporter  and that works fine, but if i add lcov as a reporter i get:
nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32
        writer.println('FN:' + [meta.decl.start.line, meta.name].join(','));
                                         ^

TypeError: Cannot read property 'start' of undefined
    at node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32:42

Ive been tweaking around with nyc settings and so far I have this:

``` json
"nyc": {
    "extension": [
      ".js",
      ".jsx"
    ],
    "include": [
      "client/**/*.js",
      "client/**/*.jsx"
    ],
    "exclude": [
      "bundle.js",
      "production.min.js",
      "app.jsx",
      "dev-tools.jsx",
      "DevTools.jsx",
      "**/*.spec.*.js"
    ],
    "sourceMap": false,
    "instrument": false,
    "report-dir": "./coverage/unit",
    "cache": false,
    "reporter": [
      "lcov",
      "cobertura",
      "text-summary",
      "html"
    ]
  },
```

And I have many many many variations of the incantations for mocha/istanbul/nyc/babel-istanbul. the most successful so far has been:

"nyc": "cross-env NODE_ENV=test nyc mocha --require babel-register --require ./setup_jsdom.js  --colors --recursive 'client/*_/_.spec.unit.js'",

Ive also tried both the babel-istanbul-plugin and the **coverage** plugin. babelrc for reference:

``` json
{
  "presets": ["es2015", "react"],
  "plugins": ["transform-object-rest-spread", "rewire", "transform-decorators-legacy", "transform-class-properties"],
    "env": {
    "test": {
      "plugins": ["__coverage__"],
      "sourceMaps": "inline"
    }
  }
}
```

anyway I am pretty sure the issue arrises because there are .json files with the coverage structure in .nyc_ouput. both are generated every time I run the tests. one is completely empty "{}", the other one looks like the stuff I need.

<img width="467" alt="screen shot 2016-08-04 at 2 18 49 pm" src="https://cloud.githubusercontent.com/assets/1203046/17413255/8431c990-5a4e-11e6-9261-40ef9b6f57f5.png">

I've toggeled various nyc conf settings like removing the .jsx extension/include paths, only having 1 reporter etc. still 2 files. The istanbul reporter is reading the empty one and chokes it seems.

**Comment by JaKXz** [comment]
Thanks for the report @chalda, can you provide a minimal reproduction in a gist or repo?

**Comment by bcoe** [comment]
@JaKXz @chalda a reproduction would be great, it is probably an issue similar to this:

https://github.com/istanbuljs/istanbul-lib-instrument/pull/16

nyc creates a JSON file for each sub-process that it monitors, so it's not unusual to see multiple files in `.nyc_output`.

**Comment by chalda** [comment]
ill try to export the minimum to recreate the issue with my configuration will take a bit since I need to crop out all client related code :)

**Comment by chalda** [comment]
https://github.com/chalda/nyc_babel_mocha_coverage_bug also works for #340. might be the same bug :)

**Comment by JaKXz** [comment]
@chalda could you update your example to use the instructions in the README?

**Comment by bcoe** [comment]
@chalda mind giving the next release of nyc a spin?

`npm cache clear; npm i nyc@next`

It should have fixes for this bug you were seeing, let me know and if so I'll close this ticket.

**Comment by bcoe** [comment]
@chalda any updates on this issue?

**Comment by bcoe** [comment]
@chalda there have been a lot of updates to the instrumenter over the past year; I think this issue should have been addressed.

Please feel free to reopen with a reproduction case if you're still bumping into issues.
