### ISSUE TITLE
nyc fails with "Unexpected token ILLEGAL" when `exec`ing shell script

### ISSUE THREAD

**Issue by boennemann** [istanbuljs/nyc#34]
As first reported via https://twitter.com/boennemann/status/619103847043203072

I'm trying to instrument the integration tests for https://github.com/semantic-release/semantic-release.
They are running a shell script to start the npm-registry-couchapp before tap/nixt tests are running against it. Everything works fine, but once I run them with nyc I get this error (multiple times):

```
[eval]:1
/private/tmp/node-spawn-wrap-17602-9d862ee799ec/node
                                   ^
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:426:26)
    at node.js:567:27
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

Steps to reproduce:

```bash
git clone git@github.com:semantic-release/semantic-release.git
cd semantic-release
git fetch origin  next:next
git checkout next
npm install
npm run build && npm run test:build
npm run test:unit # nyc built in, passes and reports coverage
npm run test:integration # passes
nyc npm run test:integration # fails
```

You need couchdb installed. Sorry for the bloated test case, will try to reduce it if this doesn't get you anywhere.

The relevant script is here: https://github.com/semantic-release/semantic-release/blob/next/test/registry/start.sh
Which gets `exec`d here: https://github.com/semantic-release/semantic-release/blob/next/test/registry/index.js#L9

**Comment by bcoe** [comment]
CC: @isaacs

**Comment by bcoe** [comment]
@boennemann haven't forgotten about this issue, but have been absolutely swamped lately. The most likely source of this issue is probably going to be somewhere in:

https://github.com/isaacs/spawn-wrap

Thanks for the test case, will dig into this as soon as I pop a few things off my stack.

**Comment by bcoe** [comment]
@boennemann hope the semantic-release project is going well, I really liked hearing about the project at NodeConf Adventure.

**Comment by boennemann** [comment]
@bcoe Thanks for the update! I absolutely understand that things take their time :+1: 
I've updated the original post, because the repo location changed.

Also thank you for the kind words :blush: Things are shaping up nicely and talking to you and the other npm folks directly helped a lot with it!

**Comment by bcoe** [comment]
@boennemann finally dug into this issue, see:

https://github.com/tapjs/spawn-wrap/issues/10

By simply ignoring `start.sh` in `spawn-wrap`, I was able to run your integration tests:

<img width="613" alt="screen shot 2016-02-28 at 11 56 59 am" src="https://cloud.githubusercontent.com/assets/194609/13381624/26cb718a-de15-11e5-9d65-7e200a9e76de.png">

**Comment by bcoe** [comment]
@boennemann could you create an up-to-date reproduction of this issue? @addaleax offered to help dig into the issue.

Alternatively, if everything is working well now perhaps we can close this?

**Comment by bcoe** [comment]
@boennemann feel free to reopen if you bump into this again, or have a chance to dust off this old issue.
