### ISSUE TITLE
text summary + % coverage reported, HTML report broken

### ISSUE THREAD

**Issue by chalda** [istanbuljs/nyc#340]
So I feel like I have the nyc running correctly with mocha/babel i am getting better coverage reports then prior setup with babel-istanbul.

Statements   : 84.39% ( 1871/2217 )
Branches     : 61.06% ( 218/357 )
Functions    : 91.5% ( 506/553 )
Lines        : 84.4% ( 1867/2212 )

<img width="1076" alt="screen shot 2016-08-05 at 10 34 15 am" src="https://cloud.githubusercontent.com/assets/1203046/17439955/6ae9007a-5af8-11e6-8b15-d547db54f9ba.png">

However the HTML reports are broken. It seems to report the correct number of lines hit (100% branch coverage, unlike instanbul 70% covereage because of "else" branches). But the actual html for each file (even plain js ones sometimes!)

<img width="1229" alt="screen shot 2016-08-05 at 10 38 17 am" src="https://cloud.githubusercontent.com/assets/1203046/17440016/bdd47526-5af8-11e6-8e6a-ad756ceeec44.png">

interestingly enough it generates a coverage report for my preload jsdom script that is used by mocha with a --require jsdom_preload.js flag. There is some weirdness going on for sure.

Also I have this as part of my NYC config:

``` javascript
    "include": [
      "/client/**/*.js",
      "/client/**/*.jsx"
    ],
    "exclude": [
      "**/*.spec.*.js"
    ],
```

but the spec files are still getting included. the jsdom file is included int he coverage too and its at the top level with client so it shouldn't be getting matched.

<img width="488" alt="screen shot 2016-08-05 at 10 44 31 am" src="https://cloud.githubusercontent.com/assets/1203046/17440206/a1f31636-5af9-11e6-8659-c8a5eb6b78df.png">

Ive switched between 3 babel plugins now: istanbul, __ coverage __ and coverage (fork of __ ) and running into different sets of issues with all 3. Really sort of frustrated with running around in circles having issues no matter what combination of tooling and configuration I try.

**Comment by bcoe** [comment]
@chalda this sounds like a similar class of problem to:

istanbuljs/istanbul-lib-instrument#16

CC: @gotwarlost 

I'll work on cutting a new release of nyc this weekend, and hopefully we can address your problems. As in #339, if you could get us a reproduction case it would be wonderful.

**Comment by chalda** [comment]
@bcoe yup working on it. fairly large project so trying to isolate a bare minimum of the code necessary to run through the setup.

**Comment by bcoe** [comment]
@chalda mind also checking if `nyc@next` solves this issue for you:

`npm cache clear`, `npm i nyc@next`

**Comment by bcoe** [comment]
I think this is most likely fixed by recent updates to the istanbuljs core libraries; @chalda please feel free to re-open with a reproduction if you're still bumping into issues.
