### ISSUE TITLE
Nyc integration with Gulp 

### ISSUE THREAD

**Issue by radhikakhetan** [istanbuljs/nyc#342]
When I do **nyc npm test**  , it is failing with the error no GruntFile found. But I am using Gulp in my repo. How can I integrate it with gulp for getting the coverage ?

**Comment by bcoe** [comment]
@radhikakhetan you got things sorted out?

**Comment by maxkoryukov** [comment]
hmm... interesting , but no answer, no resolution comment..

@radhikakhetan , could you share your **gulp-nyc** solution???
