### ISSUE TITLE
Can not use custom reporter for mocha

### ISSUE THREAD

**Issue by pjangam** [istanbuljs/nyc#346]
I am using command `nyc --all node_modules/mocha/bin/_mocha -- test --reporter mocha-allure-reporter` from command line. Please let me know if I am doing anything wrong.
Command works when I remove `--reporter mocha-allure-reporter` which works with mocha independently.

**Comment by JaKXz** [comment]
I suggest using a [`mocha.opts`](https://mochajs.org/#mochaopts) file.

Also, with `nyc`, you don't need to use the `_mocha` executable which exposes some coverage information, the plain `mocha` executable will be fine. See: https://github.com/saadtazi/until-promise/issues/3 

There's also a discussion on this in the [gitter](https://gitter.im/istanbuljs/nyc) channel.

**Comment by bcoe** [comment]
@pjangam I think you can do something as simple as this:

`nyc --all node_modules/mocha/bin/_mocha -- test --reporter mocha-allure-reporter`

Let me know if you run into any issues.

**Comment by pjangam** [comment]
Thank you @JaKXz and @bcoe for inputs. I have started using  mocha.opts file for now. I will surely see difference in mocha and _mocha.
@bcoe What you replied with is exactly my command and I get 
>  cannot resolve path (or pattern) '--reporter' error 

on it.
See error stack in attachment.
[errorStack.txt](https://github.com/istanbuljs/nyc/files/419786/errorStack.txt)

**Comment by pjangam** [comment]
closing this as opts file solved my issue.
