### ISSUE TITLE
nyc@8 tries to instrument test.js when no include or exclude specified

### ISSUE THREAD

**Issue by JaKXz** [istanbuljs/nyc#351]
compare https://github.com/JaKXz/type-convert/pull/2 with the master branch.

Looks like a bug to me @bcoe since there isn't any `include` or `exclude` specified in my `nyc` stanza and nyc@7 didn't try to instrument the `test.js` file.

**Comment by bcoe** [comment]
Hey @JaKXz interesting, it should default to https://github.com/istanbuljs/test-exclude/blob/master/index.js#L73

would love your help debugging.

**Comment by bcoe** [comment]
@JaKXz found the culprit; we serialize to subprocesses as a comma separated environment variable; our globs have a comma so this logic broke things.
