### ISSUE TITLE
100% branch coverage misreported as 99.6%

### ISSUE THREAD

**Issue by isaacs** [istanbuljs/nyc#357]
This is probably a bug somewhere in Istanbul, but I'm not sure where.  Apologies for posting here, but I'm not too familiar with the actual test coverage bits of nyc or how they work.

Here's a test coverage report: http://static.izs.me/tap-parser-coverage/

As you can see from the html output, it seems like every branch in the file is traversed.

## Expected Behavior

100% branch coverage, or some indication of which branch is not being traversed.

## Observed Behavior

99.6% branch coverage, and no indication of any branches not being traversed.

## Bonus Points! Code (or Repository) that Reproduces Issue

https://github.com/tapjs/tap-parser/tree/v2

## Forensic Information

**Operating System:** Darwin urdva.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

**Environment Information:** https://gist.github.com/isaacs/db9779740cdcd8c929df3dd910b01a69

**Comment by isaacs** [comment]
More data, if it helps:

http://static.izs.me/tap-parser-coverage/.nyc_output/
http://static.izs.me/tap-parser-coverage/coverage/

**Comment by JaKXz** [comment]
@isaacs I'm seeing an indication of the `try/catch` statements not being covered:

![screenshot 2016-08-16 14 44 41](https://cloud.githubusercontent.com/assets/2642545/17711515/ff6df1b8-63bf-11e6-8a9a-72e8e446761e.png)

but, it's supposed to be ignored... interesting. @gotwarlost is there an istanbul comment for disabling between two lines?

**Comment by isaacs** [comment]
Aha!  @bcoe spotted the issue.  There was a `|| true` that wasn't being traversed.  The yellow highlight was impossible for me to see.

Maybe there's a feature request buried here, for the istanbul html reports to provide some kind of fast way to jump to any highlighted areas?

**Comment by isaacs** [comment]
The offending line was here: https://www.dropbox.com/s/fegvzoc8o6ikpye/Screenshot%202016-08-16%2017.40.28.png?dl=0

**Comment by JaKXz** [comment]
So this can probably be closed and a new issue can be opened in the reporter library to be a little clearer, right?

**Comment by bcoe** [comment]
@isaacs feel free to reopen, sounds like this was more of a UX issue than an underlying instrumentation error -- might be worth opening an issue on istanbuljs/reports on the topic of contrast.

**Comment by isaacs** [comment]
Yeah, definitely!  I'll re-open it there.
