### ISSUE TITLE
nyc/istanbul key

### ISSUE THREAD

**Issue by kennetpostigo** [istanbuljs/nyc#360]
Hey,

I'm using istanbul to check code coverage on a library I'm working on. I keep getting this "E" icon all over the coverage report and I'm not sure what they mean. I thought maybe it means that I'm not testing for a case where a branch may be true or false but I am checking for this case and The "E" icon continues to appear. 
The Icon seen in the image below.
<img width="269" alt="screen shot 2016-08-22 at 5 59 13 pm" src="https://cloud.githubusercontent.com/assets/8888991/17873214/2c6f5f36-6892-11e6-8846-6ae4124e40eb.png">

If the code looks a little odd to you its because I'm using flow. 

Heres the test cases for this:
```js
test('LinkedList.pop() with one element', t => {
  var testLinkedList = new LinkedList();
  testLinkedList.push('Hello!');
  t.is(testLinkedList.pop().data, 'Hello!');
});

test('LinkedList.pop() with empty LinkedList', t => {
  var testLinkedList = new LinkedList();
  t.is(testLinkedList.pop(), null);
});

test('LinkedList.pop() with multiple existing elements', t => {
  var testLinkedList = new LinkedList();
  testLinkedList.push('Hello!');
  testLinkedList.push('yo?!?!');
  t.is(testLinkedList.pop().data, 'yo?!?!');
});

```

If Im missing something please let me know.

**Comment by JaKXz** [comment]
If you mouseover the `E` the tooltip should tell you what the problem is :)

**Comment by kennetpostigo** [comment]
@JaKXz it says "else path not taken". Still not really sure what that means. Else path of a current test not taken. Or If the tests don't ever hit that path?

If thats the case than I'm certain its wrong because I added a log statement and the branch gets hit in a test.

**Comment by JaKXz** [comment]
It means you haven't covered what happens when you have a list with `length > 1` and `this.tail` is falsy.
