### ISSUE TITLE
TypeError on nyc report --reporter=lcov (8.1.0)

### ISSUE THREAD

**Issue by alexjeffburke** [istanbuljs/nyc#373]
## Expected Behavior

An lcov report generated without error on the console.
## Observed Behavior

Running `nyc report --reporter=lcov` seems to generate report output files but I then receive the TypeError as listed in the stack trace below.
## Forensic Information

nyc version 8.1.0

/XXX/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32
        writer.println('FN:' + [meta.decl.start.line, meta.name].join(','));
                                         ^

TypeError: Cannot read property 'start' of undefined
    at /XXX/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32:42
    at Array.forEach (native)
    at LcovOnlyReport.onDetail (/XXX/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
    at LcovReport.(anonymous function) [as onDetail](/XXX/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
    at Visitor.(anonymous function) [as onDetail](/XXX/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/XXX/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /XXX/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
    at visitChildren (/XXX/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/XXX/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:126:5)

**Comment by bcoe** [comment]
@alexjeffburke could you link me to a repo, or snippet of code that is running into this issue?

**Comment by alexjeffburke** [comment]
Just got this together for you - there is a branch named 'feature/switch-to-nyc' in https://github.com/alexjeffburke/unexpected-mxhr. This is one of the ones that instruments a file for the browser then does a separate pass generating coverage while in phantomjs and finally reports using nyc. You'll see the above in the process of running `npm run coverage`. Thanks.

**Comment by alexjeffburke** [comment]
@bcoe Was there anything else you need from me? I wasn't sure if the raw coverage file would be useful though my guess is it's something about the parsing of it for the report. Is the format known to have changed?

**Comment by bcoe** [comment]
@alexjeffburke this should be enough to work from 👍 I hope to have some OSS cycles this weekend.

**Comment by ZhangHarvey** [comment]
I have the same  problem! But the nyc version is `10.0.0`. It makes me unable to use  Travis-Ci. I'm going crazy. Please help me as soon as  possible. Thx a lot~

**Comment by bcoe** [comment]
@ZhangHarvey could you link the repo that is having issues?

**Comment by ZhangHarvey** [comment]
@bcoe  https://github.com/ZhangHarvey/sas-crypto

**Comment by bcoe** [comment]
@ZhangHarvey I see that you're using the `__coverage__` babel plugin, `babel-plugin-istanbul` is the successor, and seems to fix your problems:

https://github.com/istanbuljs/babel-plugin-istanbul

Here's the output I got:

<img width="621" alt="screen shot 2016-12-03 at 10 49 48 pm" src="https://cloud.githubusercontent.com/assets/194609/20864550/d1231f04-b9aa-11e6-8458-ff5f7057b7ab.png">

**Comment by ZhangHarvey** [comment]
Follow your advice, it works!  Thanks again~

**Comment by bcoe** [comment]
@alexjeffburke I've isolated this issue to `browserify-istanbul` using an older version of the Istanbul instrumenter API. I'm closing this issue in favor of:

https://github.com/devongovett/browserify-istanbul/pull/40

If anyone is interested (@alexindigo, @devongovettl, @alexjeffburke) I would love to document the usage of `browserify-istanbul` in one of the tutorials [here](https://github.com/istanbuljs/istanbuljs.github.io).
