### ISSUE TITLE
Check coverage against specific files

### ISSUE THREAD

**Issue by boxfoot** [istanbuljs/nyc#377]
I am working on a project where we are slowly catching up with code coverage on a very large codebase.  We'd love to put in a minimum coverage test as part of our CI but it's hard because the threshold is so low currently that it's somewhat meaningless.

I'd love to be able to pass a `--files` parameter into `nyc --report` and `nyc --check-coverage` so that the test only applies to files that have been touched in this branch/PR.  (We could use `git diff --name-only` to generate the list of files, for example)

Curious if the `nyc` team would be open to a feature like this, and then I can poke around on how to do it.

**Comment by JaKXz** [comment]
You can accomplish this by `include`ing say one folder at a time:

```json
"all": false,
"include": [
  "src/app/moduleA/submodule/*.js", //add more here
  "src/app/moduleA/submodule2/*.js"
],
"check-coverage": true,
"lines": 90 //etc
```

or `exclude`ing in a similar manner. Let me know how it goes :)

**Comment by boxfoot** [comment]
Thanks @JaKXz , cool to know this exists, but I'm having some problems.

1) When I specify includes in `package.json`, nyc works as expected:

```
"all": false,
"include": [
  "src/app/file.js"
],
"check-coverage": true,
"lines": 90 //etc

// ==> Only outputs coverage data for `src/app/file.js`
```

But specifying with `-in` on the command line doesn't seem to work, and I'm not sure why:

```
nyc -n src/app/file.js tape ...
// ==> still outputs coverage for all files touched by tests
```

For my use case, specifying on the command line will be key, can't go dynamically changing `package.json` all the time.  I can't figure out *why* this is happening, though.  I added a `console.log` within `nyc` to tell me what the final configuration is, and it seems to have the same parameters in either case:

```
{ _: [],
  include: [ 'arc/app/file.js' ],
  require: [ 'babel-register' ],
  instrument: false,
  sourceMap: false,
  exclude:
   [ 'test/**',
     'test{,-*}.js',
     '**/*.test.js',
     '**/__tests__/**',
     '**/node_modules/**' ],
  instrumenter: './lib/instrumenters/noop',
  hookRunInContext: true,
  cwd: 'C:\\Users\\me\\git\\my-project',
  '$0': 'node_modules\\nyc\\bin\\nyc.js' }
```

Happy to share info to help with debugging, but I can't figure out what to show.


Smaller issues:

* It looks like multiple includes need to be specified on the command line with e.g. `-n file1.js -n file2.js`.  it would be convenient to be able to just write `-n file1.js file2.js` but not a huge deal since I can use easily insert the `-n` programmatically
* It seems like the approach you're recommending is to only calculate coverage for the files we want to `include`.  For my use case, it would be helpful to calculate all the coverage (so we can e.g. report automatically on how we're progressing towards global coverage) and also check against coverage for these files only.  It seems like currently I would have to run `nyc` twice to achieve this -- once for global coverage, once for specific files.  It would be handy to be able to run `nyc` once (to calculate global coverage) and then run `nyc check-coverage` but have it pick out the files I care about from the previously-generated coverage file.  Does that make sense?

**Comment by bcoe** [comment]
@boxfoot I just confirmed that `-n` seems to be working as expected, using a line something like this:

`"coverage": "nyc -n uuid.js npm test"`

Would you be able to provide a sample project with `-n` failing, so that I can test against it; is it possible that you have an old version of nyc installed globally; what is `nyc --version`?

With regards to needing to provide the `-n` prefix, unfortunately the command becomes ambiguous without this, it would be hard to tell the difference between:

`nyc -n file2.js file3.js` and `nyc -n file2.js tape`.

I think running nyc twice to get this output is probably going to be your best bet; maybe have two npm scripts; one which you run periodically to see how the overall progress is going `npm run coverage-all`, and one which you run in CI to make sure you haven't regressed below a certain threshold for coverage?

**Comment by boxfoot** [comment]
@bcoe OK, it took me a while to come back to this but I figured it out...

My `include` options are being ignored because I'm using babel-plugin-istanbul to do the instrumentation, and while the plugin respects nyc options in package.json, it ignores command line options.

(whew!  I thought I was going a bit crazy, glad to have figured that out.)

So my next step is going to be seeing if there's some way to pass those through.  Alternatively, I may look for a way to programmatically add my includes to package.json/babelrc before running nyc.

(And I still think it would be helpful to have an option for `report` and `check-coverage` to limit to certain files just for that stage, even if there is more coverage data available)

**Comment by boxfoot** [comment]
OK, just reporting back that I have a work-around in place:

* `precover-branch` script checks for changed files with `git diff` and adds to package.json nyc configuration
* `cover-branch` script runs coverage
* `postcover-branch` restores package.json configuration

It's a bit hackish but gets the job done for now until there's something more elegant.

**Comment by alpersogukpinar** [comment]
I've made a change and opened a pull-request for that problem at babel-plugin-istanbul project. @boxfoot @bcoe 
https://github.com/istanbuljs/babel-plugin-istanbul/pull/84

**Comment by bitjson** [comment]
I'm trying to check coverage against specific **source-mapped** files, but I'm not sure if there's currently a best way to exclude them. (Not the function of the `exclude`/`include` options mentioned above.)

Basically I'm running tests against a bundle (single javascript file), and I'd like to exclude components of the bundle from coverage testing (below, `node_modules/tslib` and `build/temp`):

<img width="953" alt="screen shot 2017-02-27 at 9 19 04 pm" src="https://cloud.githubusercontent.com/assets/904007/23388900/d61aa9e8-fd32-11e6-919a-924c586120ce.png">

All of my tests are importing and testing a single javascript file, but there are artifacts in the bundle which are not in the scope of my project to test (dependencies in `node_modules` and `build/temp`).

Does anyone know of a good way to exclude those source-map-resolved files from coverage reporting?

[Here's the test](https://travis-ci.org/bitjson/typescript-starter/jobs/206030281#L240) which should read 100% code coverage. (PR: https://github.com/bitjson/typescript-starter/pull/13)

**Comment by bcoe** [comment]
@boxfoot sorry for the painfully slow response! thanks to @alpersogukpinar the behavior you're looking for should now be supported in `babel-plugin-istanbul`.

@bitjson, if you're still running into issues mind opening a new issue 👍 (so that we can wrap this one up).
