### ISSUE TITLE
I can't seem to get --all option working

### ISSUE THREAD

**Issue by benhunsaker** [istanbuljs/nyc#378]
## Expected Behavior
I would like all the files specificied in the included array be instrumented and reported on from coverage stand point. Even if none of the test reference that file

## Observed Behavior
Only the files specified in my tested are be reported by.

## Forensic Information
I have tried the terminal flag `--a` and the package.json `"all": true` setting but I can seem to get files I need reported that are not being tested right now.
 
MacOS X

[`npm ls` output](https://gist.github.com/benhunsaker/7f701b06e7faf2fa64d5fd4c593f8076)

**Comment by bcoe** [comment]
@benhunsaker I believe this is the same problem we're seeing in https://github.com/istanbuljs/nyc/issues/378, which I'm closing this ticket in favor of.

Basically, we don't currently have a way with `babel-plugin-istanbul` to add all files in the project. There's a question as to whether this is `babel-plugin-istanbul`'s responsibility even. Would love to have your thoughts added to #378 and to https://github.com/istanbuljs/istanbul-lib-instrument/pull/11

**Comment by simonbuchan** [comment]
@bcoe I assume you meant #333
