### ISSUE TITLE
Configuring with Jasmine

### ISSUE THREAD

**Issue by JeSuis** [istanbuljs/nyc#390]
Has anyone setup nyc with Jasmine?
The docs say to point it to a js file directly, but I'm loading everything through jasmine. 

`"coverage": "DATA_ENV='production' TEST='true' JASMINE_CONFIG_PATH=test/support/jasmine.json ./node_modules/.bin/istanbul cover jasmine",`

**Comment by JeSuis** [comment]
I figured this out if anyone else is wondering, you would just do `nyc jasmine` instead of `nyc tap jasmine` or `nyc cover jasmine`

**Comment by dietergeerts** [comment]
How can you add a jasmine reporter? I previously had a jasmine.js file where I had `new Jasmine() .... .addReporter .... .execute()`, but that doesn't work anymore this way. Or do you need to call the jasmine.js file in another way? I tried `nyc jasmine.js`
