### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by evilebottnawi** [istanbuljs/nyc#400]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
No errors
## Observed Behavior
```shell
/path/to/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/file.js:253
        for (i = 0; i < retArray.length; i += 1) {
                                ^

TypeError: Cannot read property 'length' of undefined
    at /path/to/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/file.js:253:33
    at Array.forEach (native)
    at FileCoverage.merge (/path/to/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/file.js:249:26)
    at /path/to/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/coverage-map.js:54:26
    at Array.forEach (native)
    at CoverageMap.merge (/path/to/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/coverage-map.js:51:29)
    at /path/to/node_modules/nyc/index.js:417:9
    at Array.forEach (native)
    at NYC._getCoverageMapFromAllCoverageFiles (/path/to/node_modules/nyc/index.js:416:23)
    at NYC.report (/path/to/node_modules/nyc/index.js:425:18)
```
All works good in `8.1.0` version, but got error in `8.3.0` maybe regression error?
## Forensic Information

**Operating System:** Latest debian docker image.
**Environment Information:** https://gist.github.com/evilebottnawi/c28140a2774d794b73f3e1ba7a71f84d

**Comment by bcoe** [comment]
@evilebottnawi would you be able to provide some sample code that reproduces this?

**Comment by evilebottnawi** [comment]
@bcoe 
```js
import execa from 'execa';
import test from 'ava';

test.only.serial('should successfully run npm command `build:development`', (t) => {
    t.notThrows(
        execa('npm', ['run', 'build:development'])
            .then(() => execa('npm', ['run', 'clean']))
    );
});
```

**Comment by evilebottnawi** [comment]
@bcoe in `8.2.0-candidate1` all works fine, but in `8.2.0-candidate2` i have error.

**Comment by evilebottnawi** [comment]
After a detailed investigation i came to this error throws when `istanbul-lib-instrument` >= `1.1.2`. In `1.1.1` all works fine. I continue my investigation.

**Comment by mourner** [comment]
Can you try removing the `.nyc_output` (or any cache you might have) directory and running the coverage again?

**Comment by mourner** [comment]
@evilebottnawi can you describe the full set of minimal steps to reproduce the behavior?

**Comment by evilebottnawi** [comment]
@mourner Give time, I'll create a repository reproducing the error, it will be all the easier

**Comment by mourner** [comment]
@evilebottnawi any luck?

**Comment by evilebottnawi** [comment]
@mourner I'm trying to understand, I have two independent test, which tested a single file, and sometimes an error occurs, I am now trying to go through the code line by line

**Comment by mourner** [comment]
@evilebottnawi any chance you could set up a test case? I don't think we can address the issue if we can't reproduce it.

**Comment by evilebottnawi** [comment]
@mourner sorry for long answer, today i am work on this

**Comment by evilebottnawi** [comment]
@mourner reproduced looks like bug in `ava` or `babel` (i have poor knowledge about nyc and source maps from `babel`). Be good if you help :smile: Repo: https://github.com/evilebottnawi/nyc-error
```shell
git clone https://github.com/evilebottnawi/nyc-error
cd nyc-error/
npm i
npm run ava
```

**Comment by mourner** [comment]
I see the following output and it seems not related to `nyc` at all:

```
  ✖ No tests found in tools/lib/__tests__/wpcli-test.js, make sure to import "ava" at the top of your test file
  ✖ No tests found in tools/__tests__/npm-commands-test.js, make sure to import "ava" at the top of your test file
```

So, should these two issues be closed here?

**Comment by evilebottnawi** [comment]
@mourner I have a different output (see first message), if I use own version of `babel` I get `error`, I just can not imagine what exactly the problem can be with `babel` or `nyc`, or maybe babel generated bad source map :sob:

**Comment by mourner** [comment]
OK, managed to reproduce the issue. It goes away if you do `nyc --require babel-register` instead of just `nyc`. I have no idea what's going on there.

**Comment by evilebottnawi** [comment]
@mourner ok, give me time to understand more deeply into this, because it began after a small change https://github.com/istanbuljs/istanbul-lib-instrument/commit/5b401f5b08c3eb6fd45fcf654d8fe22001c57cb8 . If i return https://github.com/istanbuljs/istanbul-lib-instrument/commit/5b401f5b08c3eb6fd45fcf654d8fe22001c57cb8#diff-d33be8f45f830ae507ad314d33ec8158R41 all increment in the initial position (before PR), all works well

**Comment by mourner** [comment]
@evilebottnawi my wild guess is that somehow ava runs different versions of `nyc` and then tries to merge incompatible results.

**Comment by evilebottnawi** [comment]
@mourner Yes agree very strange error, try to solve it, according to the top of the `+1`. It happened not just me

**Comment by evilebottnawi** [comment]
@sindresorhus maybe you can us to clarify the situation or to help it

**Comment by mourner** [comment]
Allelujah, I seem to have found the root bug! It's here. https://github.com/istanbuljs/istanbul-lib-source-maps/blob/master/lib/mapped.js

**Comment by evilebottnawi** [comment]
@mourner can you fixed?

**Comment by mourner** [comment]
@evilebottnawi PR up at https://github.com/istanbuljs/istanbul-lib-source-maps/pull/6.

**Comment by evilebottnawi** [comment]
@mourner very very thanks :+1:

**Comment by bcoe** [comment]
@evilebottnawi @mourner could you please give this a spin:

`npm cache clear; nyc@next`

I've released @mourner's changes to istanbul-lib-source-maps.
