### ISSUE TITLE
Allowing to put the config in a config file

### ISSUE THREAD

**Issue by mohsen1** [istanbuljs/nyc#409]
Instead of putting `"nyc"` object in `package.json` I like to put my nyc config in a config file and use a CLI switch to refer to it:

``` 
nyc --config=nyc.json npm t
```

Have you considered this?

**Comment by bySabi** [comment]
It´s alredy implemented, https://github.com/istanbuljs/nyc#configuring-nyc

**Comment by mohsen1** [comment]
I didn't notice it in the docs. Thanks for your reply!

**Comment by bcoe** [comment]
@mohsen1 let me know if it does the trick for you 👍
