### ISSUE TITLE
failed to instrument with error: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by Mosho1** [istanbuljs/nyc#412]
I'm trying to run coverage through this flow: TypeScript -> ES6 -> Buble -> ES5. All tests pass but I get these errors and `Unknown` coverage. What could be the cause?

## Expected Behavior

Should run coverage

## Observed Behavior

Doesn't run coverage, fails with the above error

## Forensic Information

**Operating System:** windows 10
**Environment Information:** information about your project's environment, see instructions below:

node v6.7.0
npm v3.10.3

**Comment by LukeSheard** [comment]
I'm also seeing this issue with Typescript. How did you solve this?

**Comment by Mosho1** [comment]
@LukeSheard Sourcemaps were not built correctly, resulting in an attempt to parse the import statements.
