### ISSUE TITLE
NYC wont run test if stubbing console.log

### ISSUE THREAD

**Issue by knuterik91** [istanbuljs/nyc#417]
Hi! 
I have made a test that checks for any console.log messages. 
running tests on mocha works, but when trying to use nyc for collecting code coverage, it seems like no tests has been run. 
But if I comment out stubbing of the console.log, then everything works just fine. 

This is not a big issue for me, because I can just comment out the stubbing of console.log. But I'm interested in why it doesn't work, when stubbing console.error and console.warn works just fine. 

Here my stubbing code. 

```
import sinon from 'sinon';
export function expectNoConsole() {
    beforeEach(() => {
        sinon.stub(console, 'error', (warning => {throw new Error(warning) }));
        sinon.stub(console, 'warn', (warning => {throw new Error(warning) }));
        //sinon.stub(console, 'log', (warning => {throw new Error(warning) }));
    });
    afterEach(() => {
        console.error.restore();
        console.warn.restore();
        //console.log.restore();
    });
}`
```

this code gets called from every test file in the first describe block.  

[this its how the result looks like when stubbing console.log](http://i68.tinypic.com/2zhia1g.png)

[and this its how the result looks lik when not stubbing the console.log](http://i64.tinypic.com/1zwkscm.png])

**Comment by bcoe** [comment]
@knuterik91 if I"m reading this correctly, any `console.error`, `console.warn`, or `console.log` running would result in throwing an exception?

I wonder if this is preventing some lines from being hit in the codebase that would otherwise be executed. What if you instead did:

```js
// don't print anything when console is called.
sinon.stub(console, 'error', (warning => {));
sinon.stub(console, 'warn', (warning => {}));
sinon.stub(console, 'log', (warning => {}));
```

Does this work?

**Comment by knuterik91** [comment]
@bcoe I tried your suggestion, doing that makes nyc run and gathers code coverage. :) But the problem is that i want to fail my tests if there is any console.log in the code, or if my code is throwing any errors or warnings.  

to make my self more clear: nyc works as expected when stubbing console.warn and console.error as I have done in my first post. But the problem is with this: `sinon.stub(console, 'log', (warning => {throw new Error(warning) }));`

**Comment by knuterik91** [comment]
@bcoe I have come up with a quick fix that works for me, In package.json where I have my nyc script I create a new environment variable. So my function looks like this now: 

    import sinon from 'sinon';

    export function expectNoConsole() {
      const isCodeCoverage = process.env.NODE_ENV_NYC === "nyc";

      beforeEach(() => {
        if (isCodeCoverage) {
          sinon.stub(console, 'error', (warning => { throw new Error(warning) }));
          sinon.stub(console, 'warn', (warning => { throw new Error(warning) }));
        }
        else {
          sinon.stub(console, 'error', (warning => { throw new Error(warning) }));
          sinon.stub(console, 'warn', (warning => { throw new Error(warning) }));
          sinon.stub(console, 'log', (warning => { throw new Error(warning) }));
        }
      });

      afterEach(() => {
        if (isCodeCoverage) {
          console.error.restore();
          console.warn.restore();
        }
        else {
          console.error.restore();
          console.warn.restore();
          console.log.restore();
        }
      });
    }

If I run mocha I will get feedback if there is any console.logs in my code and if I just want to collect code coverage, then I can run Nyc without stubbing the console.log :)

**Comment by bcoe** [comment]
@knuterik91 👍 I'm glad you found a way to get things working for you.
