### ISSUE TITLE
How to find branches

### ISSUE THREAD

**Issue by tunnckoCore** [istanbuljs/nyc#418]
It's not an issue, more of a question and not only `nyc` related. Am I'm missing some additional useful tool or reporter? How to find where the branch is when everything other is 100% and there's no uncovered lines.

In most of the times I get 100% for the all - statements, functions, branches, lines. But sometimes I got 96% or 98% branches. And there's no fix, reviewed the code even one full hour line by line and with tons of tests - there's no increase and no decrease and in such cases I just go with changing --branches to 96 or 98. Is there more detailed reporter (than the default) out there? Or some service that I don't know? Or some other analyzer tool/service?

And I always be curious why "uncovered" is only based on "lines coverage".

**Comment by addaleax** [comment]
Just in case you don’t already know that `nyc report -r html` should give you a set of HTML files (e.g. `coverage/index.html`) that contains markers for taken and not-taken branches (including branches resulting from the `?:` ternary operator).

**Comment by tunnckoCore** [comment]
Hm, yea this works. Thought to try it.

That's cool, but is it possible to make the default (or any other) works the same way (to shows better results such as the html reporter)? Or is it possible through reporter - we can create new one if there's no such already.

**Comment by bcoe** [comment]
@tunnckoCore if you run run:

```{
  "scripts": {
    "test": "nyc --reporter=html --reporter=text mocha test.js"
  }
}```

You'll always generate an HTML report, which you can keep open in a browser tab. Would that do the trick for you?

**Comment by tunnckoCore** [comment]
@bcoe yea it will. The question is other, I can do it in a few ways, but in anyway it adds one more step to the flow.

I'll just review the code and reporters more deeply and maybe will create one new reporter that do the job correctly.
