### ISSUE TITLE
Bundled dependency metadata contains private registry URLs, breaks shrinkwrapped installs

### ISSUE THREAD

**Issue by rgrove** [istanbuljs/nyc#421]
## Expected Behavior

nyc's bundled dependencies should not have private registry URLs in their metadata.

## Observed Behavior

Whoever built nyc 8.3.1 apparently used a private registry (npm-registry.whitewater.ibm.com) to install bundled dependencies. As a result, the `package.json` metadata for these bundled dependencies that gets distributed with nyc contains private registry URLs that cannot be accessed by most users.

I'm not entirely clear on all the ways npm deals with bundled dependencies internally, but my workflow involves using `npm shrinkwrap --dev` in order to lock down known good versions. The private registry URLs end up in my shrinkwrap file and cause CI builds to fail when the CI server tries to fetch tarballs from the private registry and can't.

![1610190fon7](https://cloud.githubusercontent.com/assets/1465/19539101/725a0698-960c-11e6-8bc8-d4d63d583cc5.jpg)

## Forensic Information

**Operating System:** macOS 10.12
**Environment Information:** 

https://gist.github.com/rgrove/dc330460efa56a076df89577aa7e2568

**Comment by bcoe** [comment]
@rgrove sorry about that; long-standing issue with shrink-wrapped installs and a bad publish on my part. This should now be corrected in `nyc@8.3.2`.

**Comment by rgrove** [comment]
Thanks!
