### ISSUE TITLE
What exactly does babel-plugin-istanbul support that nyc doesn't?

### ISSUE THREAD

**Issue by olalonde** [istanbuljs/nyc#423]
I just tried using `nyc` for the first time on a large babel project and it seemed to work fine without the `babel-plugin-istanbul`. What am I missing out on?

Here's the scripts I'm using:

```json
  "scripts": {
    "test": "nyc npm run test:fast",
    "build": "npm run clean && babel ./src --out-dir ./lib --copy-files",
    "clean": "rimraf ./lib",
    "lint": "eslint src/ test/",
    "pretest": "npm run lint",
    "start": "node ./lib/bin/server.js",
    "start:watch": "babel-watch ./src/bin/server.js",
    "test:fast": "NODE_ENV=test babel-tape-runner test/**/*.test.js",
    "test:custom": "NODE_ENV=test babel-tape-runner test/custom.js",
    "test:watch": "nodemon --exec npm -- run --silent test:fast || true",
    "test:watch:custom": "nodemon --exec npm -- run --silent test:custom || true",
  },
```

**Comment by bcoe** [comment]
@olalonde if you're running `html` reports, nyc's source-map used to sometimes have bugs mapping lines to the ES2015 transpiled code. tldr; babel-plugin-istanbul fairly consistently returns more accurate line #s -- having said this, this seems like a bug that should be fixed upstream in the source-map libraries eventually.

The other advantage, I believe, is that `babel-plugin-istanbul` better fits some developers workflows around webpack, etc.
