### ISSUE TITLE
Getting the coverage % number programmatically?

### ISSUE THREAD

**Issue by olalonde** [istanbuljs/nyc#424]
I'm trying to statically generate a coverage badge after a build (without using a third party service like coveralls). I am therefore looking for a way to get the total coverage percentage programmatically. Is there any library API, CLI option or JSON file in .nyc_output I can use to get that number?

**Comment by bcoe** [comment]
@olalonde I haven't personally used it, but there's a reporter of type `json` you should be able to use to fetch this information. You could also run the `lcov-text` reporter, and use an `lcov` parser:

https://www.npmjs.com/package/lcov-parse

Do either of these approaches do the trick for you?

**Comment by olalonde** [comment]
Yes, thanks.
