### ISSUE TITLE
Getting ENOENT error when using "html" or "lcov" reporter

### ISSUE THREAD

**Issue by mbchoa** [istanbuljs/nyc#440]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
Output index.html file when using the "html" reporter
Output lcov.info file when using the "lcov" reporter

## Observed Behavior
Terminal output returns an error

### Terminal output:

```bash
fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/michaelchoa/project/node_modules/nyc/node_modules/istanbul-reports/lib/html/assets'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at copyAssets (/Users/michaelchoa/project/node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:156:16)
    at /Users/michaelchoa/project/node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:173:9
    at Array.forEach (native)
    at HtmlReport.onStart (/Users/michaelchoa/project/node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:172:21)
    at LcovReport.(anonymous function) [as onStart] (/Users/michaelchoa/project/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:24:24)
    at Visitor.(anonymous function) [as onStart] (/Users/michaelchoa/project/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at Tree.visit (/Users/michaelchoa/project/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:157:13)
    at /Users/michaelchoa/project/node_modules/nyc/index.js:438:10
```

### nyc package.json config:

```json
"nyc": {
    "lines": 100,
    "statements": 100,
    "functions": 100,
    "branches": 100,
    "include": [
      "server/controllers/**/*.js",
      "helpers/**/*.js"
    ],
    "exclude": [
      "**/*.spec.js",
      "node_modules"
    ],
    "require": [
      "babel-register"
    ],
    "reporter": [
      "text-summary",
      "text",
      "html"
    ],
    "all": true,
    "sourceMap": false,
    "instrument": false
  }
```
## Forensic Information

**Operating System:** the operating system you observed the issue on.
MacOS Sierra 10.12
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

### https://gist.github.com/mbchoa/96bbc7f45271fc0569d371537f226973

**Comment by mbchoa** [comment]
I was able to fix this by removing node_modules folder and reinstalling modules.  I also cleaned the cache before grabbing modules again.

Also noting that I was using yarn v0.16.1.

**Comment by Chaoste** [comment]
I'm facing the same problem. I tried removing node_modules, updating yarn, clearing yarns cache, etc. 

I'm callign it like this: "nyc _mocha --opts mocha.opts Nexboard/test/unit Portal/test/unit". I could show you my nyc config and mocha.opts, but I don't think, that this is the problem here.

**Comment by bcoe** [comment]
@Chaoste mind opening a new issue with your specific log output 👍

**Comment by JaKXz** [comment]
@Chaoste this might just be a simple typo, you want to use the regular `mocha` binary with `nyc` as opposed to `_mocha` which _I believe_ is used under the hood and not really meant to be used externally.
