### ISSUE TITLE
Coverage doesn't show files with 0% coverage

### ISSUE THREAD

**Issue by jennylia** [istanbuljs/nyc#452]
nyc --reporter=json npm test
would not generate coverage for all files.
For javascript files with no tests, (therefore no coverage), it will not show in the test reports.

Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
nyc --reporter=json npm test should show coverage for all files, even if test doesn't exist.

## Observed Behavior
nyc --reporter=json npm test should show coverage for files with no test.

## Bonus Points! Code (or Repository) that Reproduces Issue

create some js code in your project with no tests (no coverage)
then do nyc --reporter=json npm test
and nyc report
The files with no test will not show

## Forensic Information

**Operating System:** the operating system you observed the issue on.
On a mac
node --version
v7.0.0
npm --version
3.10.8

Thanks for your time.

**Comment by bcoe** [comment]
Hey @jennylia, you can get this behavior by adding `--all` to your command:

`nyc --all --reporter=json npm test`

If this doesn't do the trick, please feel free to re-open this ticket 👍

**Comment by jennylia** [comment]
@bcoe it does the trick, but in this case, it will also generate coverage for various .spec.js file, even with this in my .npmrc:

```
"exclude": [
    "src/**/*.spec.js",
    "node_modules"
  ]

```

**Comment by bcoe** [comment]
@jennylia make sure you're on the newest version of `nyc` (9.0.1) and give this a shot:

```
"exclude": [
    "**/src/**/*.spec.js"
  ]
```

**Comment by jennylia** [comment]
All the test files are still included in the nyc report.

**Comment by mrchief** [comment]
@bcoe Using "nyc": "^10.3.2" and it still doesn't work. 

```
  "nyc": {
    "check-coverage": true,
    "lines": 99,
    "statements": 99,
    "functions": 99,
    "branches": 99,
    "sourceMap": false,
    "instrument": false,
    "cache": true,
    "reporter": [
      "html",
      "text-summary"
    ],
    "all": true,
    "exclude": [
      "**/*.test.js",
      "**/node_modules/**"
    ]
  }
```

**Comment by bcoe** [comment]
@mrchief `--all` works for most common cases, my guess would be their's an edge-case in your configuration. Could you please open a new issue, with a link to code that reproduces the issue if possible.

**Comment by mrchief** [comment]
@bcoe I found #594. I'll continue discussion there.

**Comment by JudithVanDongen-Kramp** [comment]
I had this error when I converted to ES6 modules. Reverting to CommonJS fixed the issue for me.
