### ISSUE TITLE
What kinds of reporter can I use?

### ISSUE THREAD

**Issue by TonyPythoneer** [istanbuljs/nyc#453]
In this document, I hadn't seen what kinds of `reporter` user can use.

I look up this commander by help. It only shows the default is `text`.

Would you explain clearly in this document? Thx.

**Comment by TonyPythoneer** [comment]
Finally, I know what kinds of reporter I can use. -- link: https://github.com/istanbuljs/istanbul-reports/tree/master/lib

But it's still unclearly, I hope it can show the output style and paste the picture on README at least.

**Comment by bcoe** [comment]
@TonyPythoneer let's add a section to the README.md that links to the istanbul reports project, rather than just saying "we support all of istanbul's reporters".
