### ISSUE TITLE
No colors when not executed via a tty

### ISSUE THREAD

**Issue by ngryman** [istanbuljs/nyc#456]
## Expected Behavior

To have a colored output.

## Observed Behavior

Colors have gone 👻 

## Proposed fix

I think you do that on purpose when no `tty` is detected, which is perfectly fine because it makes easier to process the output if needed.
That said, in some use cases (like mine) one might just want to forward your output. To do so it would be nice to have a flag to force colored output (others do `--ansi` or `--colors`).

Thanks!

## Bonus Points! Code (or Repository) that Reproduces Issue

```js
import { spawn } from 'child_process'

spawn('nyc ava', { stdio: 'inherit' })
```

## Environmentt

```
$ node --version
v6.9.1
$ npm --version
3.10.8
```

**Comment by mlrawlings** [comment]
Have you tried passing `--color` as a command line flag? Or `FORCE_COLOR` as an environment variable?

https://github.com/chalk/supports-color#info

If that does work, it would probably be worth adding this to the docs somewhere. Maybe under [Running Reports](https://github.com/istanbuljs/nyc#running-reports)?

**Comment by ngryman** [comment]
@mlrawlings `--color` works indeed! Thanks 👌
It would be worth mentioning it in the docs.

**Comment by bcoe** [comment]
@ngryman 👍 if you're bored feel free to take a stab at the docs :) otherwise let's leave this open as a feature request.

**Comment by xenithorb** [comment]
`--color` doesn't work anymore. Where's the love for CI pipelines?

**Comment by electrovir** [comment]
I ran into this same issue. Apparently the flags are order sensitive. I'm only using two CLI flags, `--colors` and `--nycrc-path`:

- If I put `--colors` after my `--nycrc-path` cli flag, `nyc` errors out
- If I put `--colors` _before_ my `--nycrc-path` cli flag, everything works great and I get colors.
