### ISSUE TITLE
/* istanbul ignore next */ not working in v10.0.0

### ISSUE THREAD

**Issue by chapati23** [istanbuljs/nyc#464]
First of all: Big thanks for investing so much time in this project!! :)

ignoring statements doesn't work for me unfortunately, see screenshot:

<img width="558" alt="screen shot 2016-12-06 at 19 44 10" src="https://cloud.githubusercontent.com/assets/117495/20939238/44d932ea-bbee-11e6-99df-853a643addd7.png">

any ideas?

**Environment Information:**
mac OS 10.12.1
output.txt => https://gist.github.com/chapati23/8b3fa09df6070be8e1caf4f4400e6ee4

**Comment by bcoe** [comment]
@chapati23 curious are you using babel-plugin-istanbul, or nyc directly?

Thanks for taking the time to open an issue, we will dig into this (it's probably an issue with `istanbul-lib-instrument`, which nyc relies on).

**Comment by chapati23** [comment]
@bcoe we use nyc directly, this is our npm task:
```shell
nyc ava && nyc report --reporter=html && open coverage/index.html || xdg-open coverage/index.html
```
the ava config is pretty straightforward and based on [this blogpost](https://shift.infinite.red/testing-the-bejeezus-out-of-react-native-apps-with-ava-330f51f8f6c3#.9n84jil60):
```json
  "ava": {
    "files": [
      "App/**/*.test.js"
    ],
    "require": [
      "babel-register",
      "babel-polyfill",
      "react-native-mock/mock",
      "./testSetup"
    ],
    "babel": "inherit"
  }
```

**Comment by bcoe** [comment]
@chapati23 @CWSpear thanks for reporting this issue 👍 I'm thinking it might somehow be an interaction between nyc and babel, but not quite sure. It would be a big help if someone could add a failing test to either `nyc` or:

https://github.com/istanbuljs/istanbul-lib-instrument

**Comment by tivac** [comment]
@bcoe I ran into this porting from istanbul, and I think I've narrowed it down some.

https://github.com/tivac/nyc-not-ignoring/

**Comment by bcoe** [comment]
@chapati23 I've been trying to reproduce your specific issue with the latest babel/nyc:

```js
/* istanbul ignore next */
const foo = ({state}) => {
  console.log(state)
}
```

Seems to instrument appropriately:

<img width="517" alt="screen shot 2017-01-01 at 10 56 36 pm" src="https://cloud.githubusercontent.com/assets/194609/21585462/9d485032-d075-11e6-9372-e54d475720bc.png">

are you still seeing these issues still?

**Comment by chapati23** [comment]
@bcoe define "latest", do you mean the master-branch of `nyc`? i'm on 10.0.0 and seeing this issue

**Comment by chapati23** [comment]
@bcoe just tried with master-branch: still the same issue unfortunately

**Comment by bcoe** [comment]
@chapati23 my hunch is that `(state: any)` in the babel transform, and in turn the ignore is getting applied to the wrong statement.

I think it would be worth trying https://github.com/istanbuljs/babel-plugin-istanbul, which tends to be more accurate performing mappings from the transpiled code to the original code.

**Comment by chapati23** [comment]
thanks @bcoe, using babel-plugin-istanbul did the trick :)

**Comment by winit30** [comment]
Hi chapati23

What is your configuration? I am using jest and enzyme for react-native unit testing but istanbul igore not working for me. Could you please help me for this.
