### ISSUE TITLE
Question: Can't cover constructor?

### ISSUE THREAD

**Issue by reggi** [istanbuljs/nyc#465]
Hey! Sorry about this. I have no clue what's going on here. Thanks for checking this issue out! Hopefully this could help anyone else having the same issue.

Here's the code I'm testing:

```js
import { Axios as AxiosRoot } from 'axios'
import { cloneDeep } from 'lodash'

export default class Axios extends AxiosRoot {
  constructor () {
    super()
    this.defaults = cloneDeep(this.defaults)
    this.interceptors = cloneDeep(this.interceptors)
    return this
  }
}
```

here's my test:

```js
import test from 'ava'
import Axios from './index'

test('one', (t) => {
  let axios = new Axios()
  t.is(typeof axios.get, 'function')
  t.is(typeof axios.put, 'function')
  t.is(typeof axios.post, 'function')
  t.is(typeof axios.delete, 'function')
})

test('two', (t) => {
  class Tester extends Axios {
    constructor () {
      super()
      this.hi = 'hello'
    }
    extra () {
      return '5'
    }
  }
  let tester = new Tester()
  t.is(typeof tester.extra, 'function')
})
```

I'm expecting this to be fully-covered.

> sh -c 'node --version; npm --version; npm ls' > output.txt

here's the output https://gist.github.com/reggi/dbb3fe8ea351c5deb50e398e1d4e25be

![screen shot 2016-12-08 at 1 07 08 am](https://cloud.githubusercontent.com/assets/296798/20999503/ff9c8e20-bce2-11e6-8899-9029828cf978.png)
![screen shot 2016-12-08 at 1 07 19 am](https://cloud.githubusercontent.com/assets/296798/20999504/ffa015f4-bce2-11e6-8173-cab53f311956.png)

Can someone tell me what's the deal with this little yellow bracket?

**Comment by reggi** [comment]
Any ideas on why this isn't working?

**Comment by Malgalad** [comment]
That's https://github.com/istanbuljs/nyc/issues/374

**Comment by reggi** [comment]
This was fixed with implementing this and using `babel-plugin-istanbul`.

https://github.com/istanbuljs/nyc#use-with-babel-plugin-istanbul-for-es6es7es2015-support
