### ISSUE TITLE
Exception when using array spread in tests (with Babel)

### ISSUE THREAD

**Issue by omichelsen** [istanbuljs/nyc#471]
I can't run nyc with mocha if I use array spread like this: `[...Array(3)]`

I get the following error: `TypeError: Cannot read property '0' of undefined`

When running just mocha everything executes fine. My coverage script looks like this: `"coverage": "cross-env NODE_ENV=test nyc mocha",`

### `.nycrc`

```
{
    "require": [
      "babel-register"
    ],
    "include": [
      "src/**/*.js*"
    ],
    "exclude": [
      "src/**/*.spec.js*"
    ],
    "extension": [
      ".jsx"
    ],
    "reporter": [
      "lcov",
      "text-summary"
    ],
    "sourceMap": false,
    "instrument": false
}
```

### `.babelrc`

```
{
  "presets": [
    "latest",
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread"
  ],
  "env": {
    "test": {
      "plugins": [
        "istanbul"
      ]
    }
  },
  "ignore": [
    "node_modules"
  ]
}
```

### `mocha.opts`

```
--compilers js:babel-register
--require jsdom-global/register
--require test/setup.js
src/**/*.spec.js*
```

I'm using the latest releases of all libs and running on Node 7.2.1.

**Comment by bcoe** [comment]
@omichelsen sounds like a bug with the [istanbul-lib-instrument](https://github.com/istanbuljs/istanbul-lib-instrument), would definitely love to get this patched ASAP.

**Comment by bcoe** [comment]
@omichelsen mind trying the latest release of `nyc`? I'm unable to reproduce this issue with my test script:

```js
;[...[1, 2, 3]]

function Foo () {

}

module.exports = function () {}
```

My `.babelrc` looks like this:

```json
  "babel": {
    "presets": [
      "es2015"
    ],
    "env": {
      "test": {
        "plugins": [
          [
            "istanbul",
            {
              "exclude": "src/**/*.spec.js"
            }
          ]
        ]
      }
    }
  }
```

One thing I notice, is that the `es2015` preset uses `transform-es2015-spread`.

**Comment by omichelsen** [comment]
Thanks for looking into this. Do you mean v10.0.1 because I think you need to publish to npm?

**Comment by bcoe** [comment]
@omichelsen I'm testing with `v10.0.0`; `v10.0.1` is blocked by some regressions I've found in one of it sub-dependencies.

**Comment by omichelsen** [comment]
I found the problem, removing the following from `.babelrc` fixed it for me:

```json
  "env": {
    "test": {
      "plugins": [
        "istanbul"
      ]
    }
  },
```

And my line numbers seem correct, so don't really know what is going on. Maybe the documentation for `nyc` needs to be updated, because I think I followed the instructions pretty close?

**Comment by SpainTrain** [comment]
I was seeing the same error and use `@next` (currently `nyc@10.1.2-candidate.0`) appears to have solved the issue for me.

**Comment by bcoe** [comment]
@SpainTrain `next` and `latest (npm cache clear; npm i nyc@latest)` should currently be identical, mind trying out the latest release and confirming that things are still working for you?

@omichelsen unless you re-enable nyc's instrument and sourceMap, I think this would mean you're not getting any test coverage reported?

**Comment by omichelsen** [comment]
I just installed nyc@10.1.2 and everything magically started working with the config from my first post. Thanks so much!

**Comment by bcoe** [comment]
@omichelsen awesome ... I'm not 100% sure what I pulled in to fix this for you, but this might have been the culprit:

https://github.com/istanbuljs/istanbul-lib-coverage/commit/22e154c

The reports we're outputting look reasonable, and you haven't had any additional hiccups?

**Comment by omichelsen** [comment]
No, works like a charm!
