### ISSUE TITLE
Not playing nicely with import syntax

### ISSUE THREAD

**Issue by bcruddy** [istanbuljs/nyc#478]
## Expected Behavior
Imports should be covered

## Observed Behavior
Imports are not 100% covered - maybe checking the imports themselves?

## Bonus Points! Code (or Repository) that Reproduces Issue
No bonus points here - sorry. Further explanation through - I'm trying to use import syntax and nyc/istanbul is telling me there's an `else`, `if`, and `else` statement missing on the `import React from 'react'` line at the beginning of the file. The code runs so I'm positive it isn't an actual functional issue. Here's the actual `npm test` script:

    ./node_modules/.bin/nyc ./node_modules/.bin/mocha --check-leaks --globals 'window,document,navigator' --recursive --compilers \"js:babel-core/register\" --require ./ $(find test -path '*_spec.js')

## Forensic Information

![image](https://cloud.githubusercontent.com/assets/5150154/21562024/af89d304-ce42-11e6-9334-6d89adc68b91.png)

**Operating System:** the operating system you observed the issue on.
macOS Sierra 10.12.1 (16B2555)

**Environment Information:** information about your project's environment, see instructions below:

https://gist.github.com/bcruddy/4618195e2f596eb391e7356f9b680ba8

**Comment by bcoe** [comment]
@bcruddy did you figure out this issue, curious why you closed the ticket.

**Comment by bcruddy** [comment]
@bcoe, closed by mistake. Still unsure why imports are not being covered.

**Comment by bcruddy** [comment]
The issue was in my babel configuration

**Comment by bcoe** [comment]
@bcruddy interesting, for my reference what did you change?

**Comment by bcruddy** [comment]
@bcoe this is unhelpful but for the life of me I cannot remember. We're making some big changes so there's a lot in the air. If I can think of it I'll be sure to leave it as a comment here.
