### ISSUE TITLE
Instrumentation not working as expected

### ISSUE THREAD

**Issue by darrickc** [istanbuljs/nyc#481]
My understanding is that when I run nyc npm test my javascript source will be instrumented for me. This is probably true in simple cases but doesn't seem to happen in my more complicated case. We are using mocha and testing a library that we are providing. We run npm install to load our source into node_modules and then when we run npm test our tests require our libs in node_modules. 

If I run nyc instrument on our source before running npm install then nyc reports our source properly. 

node: 4.2.6, npm: 2.15.0

I've tried several different things to try to get nyc to auto-instrument node_modules with no success. Is my only option to manually instrument before npm install?

[output.txt](https://github.com/istanbuljs/nyc/files/688150/output.txt)

**Comment by bcoe** [comment]
@darrickc we exclude `node_modules` by default, but you should be able to explicitly instrument those files:

https://github.com/istanbuljs/test-exclude#including-node_modules-folder

**Comment by darrickc** [comment]
Fantastic! That worked. I added     
`"exclude": ["!**node_modules**"],`
to my nyc config within package.json and that provided what I wanted. Plus much more. I tried to trim it down with (and other alternatives)
`"exclude": ["!**node_modules/javascript-client-sdk/src/js/*.js"]`
Is it possible to only instrument/report on individual modules?

I also tried adding the files of interest in an include array.

**Comment by darrickc** [comment]
It looks like the include array does work! I was forgetting to clear out my coverage directory after every run! Thanks!

**Comment by JaKXz** [comment]
@darrickc if you want to see the discussions on it, see istanbuljs/test-exclude#13, istanbuljs/test-exclude#10, and I think istanbuljs/test-exclude#18. 

Motion to close this issue?

**Comment by bcoe** [comment]
@darrickc @JaKXz is there anything we could clarify in the nyc docs do you think?

**Comment by JaKXz** [comment]
@bcoe perhaps a section on the website on how the underlying libs work together? That extends the scope a bit, but does give this kind of information a home.

**Comment by darrickc** [comment]
I would recommend explicitly adding that you can reverse node_modules with `"exclude": ["!**node_modules**"],`
