### ISSUE TITLE
FYI: not that good README.md

### ISSUE THREAD

**Issue by halt-hammerzeit** [istanbuljs/nyc#486]
> Istanbul's state of the art command line interface, with support for:
applications that spawn subprocesses.
ES2015 transforms, via babel-plugin-istanbul, or source-maps.

So what does it even do.
Why would anyone need that.

> When produce-source-map is set to true, then the instrumented source files will include inline source maps for the instrumenter transform. When combined with source-map-support, stack traces for instrumented code will reflect their original lines.

Then why isn't it `true` by default. Should this even be enabled? Does something else need to be installed?

> You'll have to configure your custom require hook to inline the source map in the transpiled code. For Babel that means setting the sourceMaps option to inline.

An example is always better than describing it with words

> babel-plugin-istanbul can be used to enable better first-class ES6 support.

Can? Or should? Why would I even read this section?

> Note: With this configuration, the Istanbul instrumentation will only be active when NODE_ENV or BABEL_ENV is test.
We recommend using the cross-env package to set these environment variables in your package.json scripts in a way that works cross-platform.

So, should I set some env variable? Or is it fine as it is?

> disable nyc's instrumentation and source-maps:

Why?

**Comment by halt-hammerzeit** [comment]
You've been notified

**Comment by bcoe** [comment]
@halt-hammerzeit patches welcome 👍
