### ISSUE TITLE
Function name is lost when running NYC with Mocha and Typescript

### ISSUE THREAD

**Issue by avik-so** [istanbuljs/nyc#489]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
Tests which are run in Mocha should be able to access the `function.name` property when running with `nyc`.
I would expect tests which pass when running mocha alone, would also pass when running `nyc` before `mocha`.

## Observed Behavior
Function names are returned as "" when `nyc` is run before mocha.

## Bonus Points! Code (or Repository) that Reproduces Issue
Repo that reproduces the issue.
https://github.com/avik-so/nyc-func-name-test

## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

RESULTS OF output.txt are in the repo:  https://github.com/avik-so/nyc-func-name-test/blob/master/output.txt

**Comment by bcoe** [comment]
@avik-so thanks for this; I believe this is fixed in `istanbul-lib-instrument` already, and just needs to be pulled into nyc; I've been holding off on the release for a bit, having not had a chance to dig into:

https://github.com/tapjs/spawn-wrap/issues/44

With @isaacs yet, we have some PTO days soon; and hopefully we can get a release cut.

**Comment by avik-so** [comment]
Thanks. Where would I need to make this change if I wish to fix it on my local machine?  Do I just need to reference instanbul-lib-instrument next/latest in the package.json?

**Comment by bcoe** [comment]
@avik-so would love your help testing:

`npm cache clear; npm i nyc@next`

If everything is working as expected with our smoke tests, I'll promote the release soon.

**Comment by avik-so** [comment]
I updated https://github.com/avik-so/nyc-func-name-test and the test passes!

I also added nyc@next to a branch of my actual project and all tests pass as well!

Thank you so much!

**Comment by bcoe** [comment]
@avik-so awesome \o/ this fix is `latest` now too 👍
