### ISSUE TITLE
Allow eager instantiation of the instrumentation library

### ISSUE THREAD

**Issue by evantorrie** [istanbuljs/nyc#491]
Please use the template provided below, when reporting bugs:
-----
## Expected Behavior

When [mockery](https://github.com/mfncooper/mockery) is used for test mocks, I don't want to see warnings about all of nyc/istanbul's modules that are `require`d appearing prior to the first test.

## Observed Behavior

Some mocking libraries hook require and by default warn when there is a required
module which has not been explicitly registered, e.g. [mockery](https://github.com/mfncooper/mockery).  
It is standard procedure to call `mockery.enable()` in a unit test prior to
requiring the code under test since obviously you want the hooks to be in place at the time that the 

With lazy instantiation of the instrumenter, all of the instrumenter
library's `require`s generate mockery warnings at test time.

## Bonus Points! Code (or Repository) that Reproduces Issue

See https://gist.github.com/evantorrie/d702ccd2e0ac2f30deb76e336128bddd

**Comment by bcoe** [comment]
@evantorrie thanks for the thorough issue! hoping to have some time to dig into OSS this week, and will hopefully get to this. Would also happily accept a pull request.
