### ISSUE TITLE
File shows 100% coverage despite no tests when imported as a module

### ISSUE THREAD

**Issue by bennewton999** [istanbuljs/nyc#495]
I'm new to NYC and Istanbul, so forgive me if I'm missing something obvious here.

## Expected Behavior

Expect the file app.js to show 0% coverage as I have no tests covering it yet. 

## Observed Behavior

When app.js is imported as a module into page1.js, which I do have a test for, app.js shows 100% coverage.

With line 1 of page.js
```----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
All files       |    33.33 |    16.67 |    16.67 |    44.44 |                |
 app            |      100 |      100 |      100 |      100 |                |
  app.js        |      100 |      100 |      100 |      100 |                |
 app/components |    28.57 |    16.67 |    16.67 |     37.5 |                |
  page1.js      |       80 |       50 |       50 |      100 |                |
----------------|----------|----------|----------|----------|----------------|
```
When line 1 of page1.js is commented out, (the import of app.js) The test shows correct coverage.
```----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
All files       |    23.53 |    16.67 |    14.29 |       30 |                |
 app            |        0 |      100 |        0 |        0 |                |
  app.js        |        0 |      100 |        0 |        0 |            4,6 |
 app/components |    28.57 |    16.67 |    16.67 |     37.5 |                |
  page1.js      |       80 |       50 |       50 |      100 |                |
----------------|----------|----------|----------|----------|----------------|
```
## Bonus Points! Code (or Repository) that Reproduces Issue

**app.js** (misc js)

```javascript
import './styles/app.css';

console.log('hello world!!!');

const test = () => console.log('Hello again');```
**page1.js
```javascript
import '../app';

console.log('page 2');

const helloWorld = (name = 'Ben') => `Hello World, this is ${name}`;

// export default helloWorld;

const helloWorld2 = (name = 'Ben') => `Hello World, this is not ${name}`;
```
**package.json
```"nyc": {
    "all": true,
    "sourceMap": false,
    "instrument": false,
    "include": [
      "app/**/*.js"
    ],
    "exclude": [
      "**/*.spec.js",
      "app/dist"
    ],
    "require": [
      "babel-register",
      "ignore-styles"
    ],
    "reporter": [
      "lcov",
      "text",
      "text-summary"
    ],
    "check-coverage": true,
    "cache": false
  }```

**test.js (test)
```import { helloWorld, helloWorld2 } from '../app/components/page1.js';


require('chai').should();

describe('helloWorld()', () => {
  it('returns hello world message with Ben as default', () => {
    helloWorld().should.equal('Hello World, this is Ben')
  });

  it('returns hello world message with passed name argument', () => {
    helloWorld('Frank').should.equal('Hello World, this is Frank')
  });
})
```

## Forensic Information

**Operating System:** OSX Yosemite 10.10.5
**Environment Information:** information about your project's environment, see instructions below:

https://gist.github.com/bennewton999/20dc77d6ecb83a94f3cf51df3ba60497

**Comment by bennewton999** [comment]
This is probably more appropriate for the [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul/issues?q=is%3Aissue+is%3Aclosed) issues.  My apologies.

**Comment by nickfreemandesign** [comment]
@bennewton999 you did a great job documenting your troubles here. im also trying to learn what constitutes 'coverage' in instanbul's little output deal. is there another issue you opened somewhere else you can reference here for all the stragglers on this breadcrumb trail?

**Comment by bennewton999** [comment]
@nickfreemandesign - It's been a while, so I don't remember the specifics.  Here is a link to the issue I opened in the  [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul/issues?q=is%3Aissue+is%3Aclosed) repo.

https://github.com/istanbuljs/babel-plugin-istanbul/issues/85#issuecomment-273366096

Hope this helps!
