### ISSUE TITLE
--all should exclude the "coverage" directory by default

### ISSUE THREAD

**Issue by EvgenyOrekhov** [istanbuljs/nyc#496]
## Expected Behavior

When using the `--all` flag nyc should not report the coverage of the "coverage" directory that was generated in the previous runs.

## Observed Behavior

When using the `--all` flag nyc reports the coverage of the "coverage" directory.

## Bonus Points! Code (or Repository) that Reproduces Issue

The issue can be reproduced in any repository.
The first run is good, because there is no "coverage" directory yet.
The second one reports the coverage of the "coverage" directory.

```
nyc --all --reporter=text --reporter=html mocha
nyc --all --reporter=text --reporter=html mocha
```

## Forensic Information

**Operating System:** Ubuntu 16.10.
**Environment Information:** https://gist.github.com/anonymous/6169422c46cddfac763a8ec93f19fcc7

**Comment by bcoe** [comment]
@EvgenyOrekhov I was noticing this the other day while testing `--all`, I agree this should probably be in the default exclude list!

If you feel like contributing, would happily take a patch here:

https://github.com/istanbuljs/test-exclude
