### ISSUE TITLE
Question: How to coverage Typescript using Tape

### ISSUE THREAD

**Issue by kevincaradant** [istanbuljs/nyc#497]
Hi

I'm a little bit lost with all the libraries between karma, mocha etc

I decided to use Tape.

This is my scripts in the package.json:
```
"scripts": {
        "start": "npm run build",
        "clean": "rimraf bin && rimraf coverage",
        "lint": "tslint './src/**/*.ts' ",
        "check": "npm run lint -s && dependency-check ./package.json",
        "pretest": "tsc",
        "test": "tape bin/tests/**/*.spec.js | tspec",
        "test:watch": "onchange \"tests/**/*.ts\" \"src/**/*.ts\" -i -p -- npm run test",
        "compile": "tsc",
        "compile:watch": "onchange \"src/**/*.ts\" -i -p -- npm run compile",
        "build": "npm run compile",
        "postbuild": "npm run check -s && npm run test -s",
        "coverage": "nyc npm run test",
        "coveralls": "npm run coverage -s && coveralls < coverage/lcov.info",
        "postcoveralls": "rimraf ./coverage",
        "prepublish": "npm run build -s",
        "deploy": "git pull --rebase origin master && git push origin master",
        "patch": "npm version patch && npm publish",
        "minor": "npm version minor && npm publish",
        "major": "npm version major && npm publish",
        "postpublish": "git push origin master --follow-tags",
        "autocl": "auto-changelog"
    },
```

My .nyc file:
```
{
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "tests/**/*.spec.js",
    "bin/**/*.spec.js",
    "bin/**/*.map"
  ],
  "reporter": [
    "lcov",
    "text-summary"
  ],
  "extension": [
    ".ts"
  ],
  "require": [
      "ts-node/register"
   ],
  "all": true,
  "check-coverage": true
}
```

**Can I coverage cleanly using my way with npm run test and npm run coverage ?**
Or what I have to do ? 

Thank you in advance, sorry if it's trivial.

`npm run coverage` comand:
This is my output:
![image](https://cloud.githubusercontent.com/assets/6093175/22076461/718c00ea-ddb0-11e6-88ba-1c14dce9a338.png)

**Comment by bcoe** [comment]
@kevincaradant nyc should work just fine with tape, my guess is that something is getting lost in translation in the transpilation step -- maybe we're ultimately excluding the source files.

I'm looping in @JaKXz who's had a bit more experience on this end of things than me. Is this a library that we can check-out and experiment with?

**Comment by kevincaradant** [comment]
@bcoe ,Thanks glance a look at my issue.

This is my repository ( in building for dev branch ):
https://github.com/kevincaradant/generate_check_md5/tree/dev

Go in the `dev` branch otherwise you will be with babel and not typescript.
Then, write the command `yarn` 
Than you can: `npm run test` and `npm run coverage`

Let me know if you need something else.

For information: 
nyc: V10.0.0
tape: V4.6.3
Node: V7.4.0
OS: Ubuntu 64bits

**Comment by kevincaradant** [comment]
Any news about this issue ?
I'm motivated to have again a coverage which works :)
Maybe it's a bad use from me.

**Comment by JaKXz** [comment]
@kevincaradant I took a brief look tonight, and it seems the underlying complexity to get `nyc`, `tape`, _and_ `typescript` to play nice is very high. 

In the short term, I'd recommend AVA's typescript recipe (since the assertion API is very similar to `tape`): https://github.com/avajs/ava/blob/master/docs/recipes/typescript.md

I can take a more in depth look only later in the week (unfortunately I was very ill last week and have lots to catch up on ATM).

**Comment by kevincaradant** [comment]
@JaKXz, thank you to try to have a look knowing that you was sick.  I understand now,  you will have some works to catch up.  
I will try to look ava or tap.

The main problem is that I use mock-fs to mock my files in my unit tests. So,  I know sometimes,  some unit testing doesn't work properly with this library.  I hope ava or tap will work. Otherwise,  I will be patient waiting a fix with nyc for tape and ts  :).

**Comment by bcoe** [comment]
@kevincaradant would love your help further documenting typescript related configurations, once you have a chance to dig into things further.

we have tutorials [here](https://github.com/istanbuljs/istanbuljs.github.io/tree/development/content/docs/tutorials) that I'd love to see us build out further.

**Comment by kevincaradant** [comment]
I was looking for use ava or tap.  But I met some different problems and any workaround satisfied me.  I would a compilation on the fly and use mock-fs in more,  I would keep nyc so I will try to help you if to be honest,  I didn't understand really that you want.  I will try to look your tutorials tomorrow :).  I will back to you if I need some info

**Comment by kevincaradant** [comment]
I was looking for use ava or tap.  But I met some different problems and any workaround satisfied me.  I would a compilation on the fly and use mock-fs in more,  I would keep nyc so I will try to help you but to be honest,  I didn't understand really that you want.  I will try to look your tutorials tomorrow :).  I will back to you if I need some info

**Comment by bcoe** [comment]
@kevincaradant did you ever make any progress on this?

**Comment by zixia** [comment]
It seems `nyc` will not work with `tape` right now?

**Comment by JaKXz** [comment]
Since @Bibliofile's comment, you can simplify it even further with the nyc-config typescript package.

1. `npm i -D @istanbuljs/nyc-config-typescript`
2. 

```
"nyc": {
  "extends": "@istanbuljs/nyc-config-typescript"
}
```

**Comment by verhovsky** [comment]
`ts-node` [doesn't work with ESM modules](https://github.com/TypeStrong/ts-node/issues/1007). My package must be an ESM module because I want to use [top-level `await`](https://v8.dev/features/top-level-await#new) which *requires* ESM modules. As far as I can tell, I can't use `nyc`.
