### ISSUE TITLE
Why is it called nyc?

### ISSUE THREAD

**Issue by epoberezkin** [istanbuljs/nyc#498]
Google suggested: http://www.hotelbuyukkeban.com/blog/istanbul/new-york-and-istanbul-10-surprising-things-they-have-in-common/

**Comment by mrchief** [comment]
That's it! You found the reason! :rofl:

**Comment by bcoe** [comment]
@epoberezkin @mrchief the answer is here:

https://www.youtube.com/watch?v=Gi0Rt0slfy4

**Comment by pke** [comment]
This doesn't explain why a code coverage tool is called istanbul in the first place. Where can I find some info about that?

**Comment by ORESoftware** [comment]
@pke carpets cover things, Istanbul is a city where carpets are made, therefore let's call a code coverage library Istanbul :) that seems to be the logic :)

and of course, `nyc` the other code coverage library that borrows heavily from Istanbul, was simply named after another big city lol

**Comment by mrchief** [comment]
@ORESoftware That doesn't make sense. A carpet **covers-up** or **hides** things. Code coverage tools **expose** untested code. 😝

**Comment by bcoe** [comment]
I think this issue has been _covered_ 😄
