### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by mrchief** [istanbuljs/nyc#499]
Is it possible to use nyc programmatically? Like say:

```
import nyc from 'nyc'

const results = nyc.test(...) // either pass files, options here or blank params load from package.json

console.log(results.passed) // true|false
console.log(results.errors) // errors array
console.log(results.coverage.statements) // 88
console.log(results.coverage.branches) // 65
```

**Comment by mightyiam** [comment]
Perhaps use istanbul.

**Comment by mrchief** [comment]
- Will the numbers match between nyc and istanbul?
 - Can you point me to any examples/docs?

**Comment by mightyiam** [comment]
I don't have any experience with istanbul. Only basic usage of nyc. It just makes sense to me that since nyc seems a CLI for istanbul, that if one would like to use the API, then one would use istanbul.

**Comment by bcoe** [comment]
If your application does something like this at the start:

```js
;(new NYC(config)).wrap()
```

`nyc` will begin instrumenting any files you require from that point forward, and will populate `global.__coverage__`; you can write this object to disk and use nyc to render it at a later date.

Another option option to you would be using [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) to instrument your files, if you're using babel in your tool-chain.

You could also look at [istanbul-api](https://github.com/istanbuljs/istanbul-api) which combines many of the components used by nyc itself.

**Comment by mrchief** [comment]
@bcoe Sounds great! I'll explore these and post my experience here.

**Comment by JaKXz** [comment]
@mrchief I believe `jest` uses the Istanbul APIs underneath to provide their built in coverage, e.g. https://github.com/facebook/jest/blob/master/scripts/mapCoverage.js

**Comment by bcoe** [comment]
@mrchief I'm going to close this now; but feel free to hit us up with questions in gitter.

**Comment by ORESoftware** [comment]
is there a way to use istanbul programmatically in the same way you'd use babel-register or ts-node?

something like:

`require('istanbul').cover({})`
