### ISSUE TITLE
Short and common module name makes for poor web searching

### ISSUE THREAD

**Issue by haysclark** [istanbuljs/nyc#500]
Searching for examples online is very challenging due to the extremely short name and the fact that New York City is going to dominate search results.  In general, while I truly like nyc as a tool, the module name leaves something to be desired.

Google > nyc framework webstorm

**Comment by bcoe** [comment]
@haysclark I hear you, when I picked the name:

* I was looking for something short that wouldn't add much noise if appended to the front of an npm script.
* I wanted something that was clever and related to the name Istanbul (It's a stretch, but I was thinking of the They Might Be Giants song Istanbul).

There's been some discussion [specifically here](https://github.com/gotwarlost/istanbul/issues/706) about whether we potentially publish `nyc` under the name `istanbul-cli`; once it's closer to [feature parity](https://github.com/istanbuljs/nyc/issues/309)

... having said this, the `nyc` library itself has some momentum at this point. And I think I'm more interested in kicking forward the retirement of Istanabul 1.0, as a means of reducing confusion.

**Comment by haysclark** [comment]
@bcoe Thank you for the excellent reply.
