### ISSUE TITLE
--all fails with ts-node (Typescript)

### ISSUE THREAD

**Issue by cvle** [istanbuljs/nyc#504]
First of all, great job with this project!

So I have prefect code coverage using `ts-node` and `nyc@10.1.2`. It was quiet easy to setup.

```js
{
  "reporter": [
    "lcov",
    "text"
  ],
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": [
    "src/**/*.d.ts",
    "src/**/*.spec.ts",
    "src/**/*.spec.tsx"
  ],
  "extension": [
    ".ts",
    ".tsx"
  ],
  "require": [
    "ts-node/register"
  ]
}
```

But when I use `{ all: true }` it fails like this:

```bash
/home/vagrant/projects/typescript/reassemble/node_modules/ts-node/src/index.ts:321
          throw new TypeError(
                ^
TypeError: Unable to require `.d.ts` file.
This is usually the result of a faulty configuration or import. Make sure there is a `.js`, `.json` or another executable extension and loader (attached before `ts-node`) available alongside `assemble.
d.ts`.
    at getOutput (/home/vagrant/projects/typescript/reassemble/node_modules/ts-node/src/index.ts:321:17)
    at /home/vagrant/projects/typescript/reassemble/node_modules/ts-node/src/index.ts:343:18
    at Object.compile (/home/vagrant/projects/typescript/reassemble/node_modules/ts-node/src/index.ts:476:19)
    at Object.m._compile (/home/vagrant/projects/typescript/reassemble/node_modules/ts-node/src/index.ts:406:44)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/vagrant/projects/typescript/reassemble/node_modules/ts-node/src/index.ts:409:12)
    at NYC._readTranspiledSource (/home/vagrant/projects/typescript/reassemble/node_modules/nyc/index.js:160:26)
    at NYC.addFile (/home/vagrant/projects/typescript/reassemble/node_modules/nyc/index.js:144:21)
    at /home/vagrant/projects/typescript/reassemble/node_modules/nyc/index.js:176:11
    at /home/vagrant/projects/typescript/reassemble/node_modules/nyc/index.js:244:5
```

Any idea why and how can we fix it?

**Comment by cvle** [comment]
The other way I tried was to do the register in mocha using `--compilers tsx:ts-node/register,ts:ts-node/register`. Setting `{ all: true }` doesn't fail but it is more like a no op. 

I'm coming from https://github.com/gotwarlost/istanbul and it works over there. This is the only thing keeping me from migrating all my projects from `istanbul` to `nyc`.

**Comment by cvle** [comment]
Sorry my bad. It works when I do the require in mocha! Time to migrate all my projects!

**Comment by bcoe** [comment]
@cvle nice! had a conversation with @wbyoung about this exact same issue earlier today:

https://github.com/istanbuljs/nyc/issues/509

Where do you think we should document this caveat? would love help updating the README ... also, if you're feeling _really ambitious_, it would be amazing to get a TypeScript tutorial up [here eventually](https://github.com/istanbuljs/istanbuljs.github.io/tree/development/content/docs/tutorials) for other folks.

**Comment by juanpicado** [comment]
@cvle what do you meant with the **require** thing?

**Comment by juanpicado** [comment]
Ahh, now I get it, the fix is remove the `require` from the `nyc` options body.

```json
"require": [
   "ts-node/register"
],
```
and do it in this way

```
mocha --require ts-node/register
````

**Comment by JaKXz** [comment]
@juanpicado would you like to make a contribution to our docs? :) 

I haven't used TypeScript in a while, so it would be nice to keep [the tutorial](https://github.com/istanbuljs/istanbuljs.github.io/tree/development/content/docs/tutorials) up to date on this for the latest versions of nyc and ts-node etc.

**Comment by juanpicado** [comment]
Sure ! There it goes

**Comment by felixfbecker** [comment]
Even with the register as part of mocha, I get the same error as with the register as part of nyc
```
node_modules/typescript/lib/typescript.js:89057
        ts.Debug.assert(outputText !== undefined, "Output generation failed");
                 ^
Error: Debug Failure. False expression: Output generation failed
    at Object.transpileModule (node_modules/typescript/lib/typescript.js:89057:18)
    at getOutput (node_modules/ts-node/src/index.ts:247:23)
    at Object.compile (node_modules/ts-node/src/index.ts:528:11)
    at Object.m._compile (node_modules/ts-node/src/index.ts:422:43)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:425:12)
    at NYC._readTranspiledSource (node_modules/nyc/index.js:161:26)
    at NYC.addFile (node_modules/nyc/index.js:145:21)
    at node_modules/nyc/index.js:177:11
    at node_modules/nyc/index.js:246:5
```

**Comment by liuxh0** [comment]
The solution from @juanpicado helps, but it does not solve the problem.

If I require ts-node in mocha instead of in nyc, the option `all` has no effect. All my ts files that is not imported by `*.spec.ts` will not be included. See #603

**Comment by ilyadoroshin** [comment]
`"exclude": ["**/*.d.ts"]` helped me

**Comment by grayrattus** [comment]
I had similar problem with typescript globals.d.ts
After removing 
`"require": [
   "ts-node/register"
]`
from `nyc` options body, everything worked. I tried many different solutions and this is the only one that worked, thanks!

**Comment by quoininc-huudatran** [comment]
> `"exclude": ["**/*.d.ts"]` in .nycrc helped me

is failing my test coverage because i need a `global.d.ts`.

**Comment by diephil** [comment]
> `"exclude": ["**/*.d.ts"]` in .nycrc helped me

It did the trick for me, thanks @ilyadoroshin !
