### ISSUE TITLE
Make nyc's tests faster

### ISSUE THREAD

**Issue by JaKXz** [istanbuljs/nyc#505]
@istanbuljs/nyc does anyone have any energy to refactor the test suite to enable some parallelism?

Feedback cycles for me are around ~5 minutes, which is a bit much since our number of tests is < 1000.

I'd be open to some remote pairing on this or if you're in T.O. IRL pairing :)

**Comment by bcoe** [comment]
I was actually talking to @isaacs a bit about this this week; `node-tap` [supports parallel tests](http://www.node-tap.org/parallel/) so we should be able to experiment with this feature in nyc.

I was also thinking though, that our test-suite is a little clunky; I wonder if we could brainstorm any abstractions that would make tests a bit cleaner -- even just adding some tooling to make it possible to run a single test would be a good first step.

**Comment by JaKXz** [comment]
@bcoe with version tap v10, I noticed you can use the mocha style `.only` on a `describe` or `it` block, so that definitely helps.

**Comment by bcoe** [comment]
some of this work has landed.
