### ISSUE TITLE
Measuring code coverage on top of JerryScript

### ISSUE THREAD

**Issue by zherczeg** [istanbuljs/nyc#506]
Hi,

we would like to measure javascript code coverage using the istanbul tool. The javascript is executed by JerryScript (https://github.com/jerryscript-project/jerryscript) which is a pure ES 5.1 engine. Could you tell me how difficult to port the Istanbul tool to JerryScript? Is the core ES5 compatible?

Thank you,
Zoltan

**Comment by tilmannOSG** [comment]
Basically we want to find out what level of runtime support is required to run JavaScript code instrumented with Istanbul on top of JerryScript. 
We have a lightweight Node.js-like framework called IoT.js (http://github.com/Samsung/iotjs) running on top of JerryScript which provides some basic modules like file system access, the question is whether that's already sufficient to write out the gathered coverage data to a JSON file.  
Note that we only want to run instrumented code on JerryScript, there's no need for us to run Istanbul itself on top of JerryScript (that can be run on the traditional Node.js stack on top of V8 on a Linux host).  
So the idea would be to instrument some JavaScript sources with Istanbul and then execute those sources with JerryScript on a Linux host (potentially also on a MCU if the instrumented code fits within the memory constraints of the device). Then process the gathered coverage data to create a nice HTML report.  
Any idea how difficult this would be? :)  
Thanks in advance!

**Comment by bcoe** [comment]
@tilmannOSG @zherczeg I think what you might want to look at is our sibling library [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul):

1. you would setup a project to use babel, using the `babel-plugin-istanbul` transpile step.
2. this step will create ES 5.1 compatible code that tracks coverage information (the information will be stored in a global variable named `__coverage__`.
3. output this `__coverage__` file to disk, and you can use `nyc` to load it back up, an output reports.

**Comment by tilmannOSG** [comment]
@bcoe Thanks for the quick reply!  
Yesterday @dbatyai managed to successfully use Istanbul to gather coverage data with for our IoT.js tests running on top of JerryScript, seems to work very well :)

**Comment by bcoe** [comment]
@tilmannOSG @dbatyai this is awesome, don't suppose I could convince you to write a tutorial for https://github.com/istanbuljs/istanbuljs.github.io, would be happy to draw attention to your projects.

**Comment by dbatyai** [comment]
Sure, I'll try to throw together a quick tutorial sometime soon.

**Comment by bcoe** [comment]
@dbatyai thanks for taking the time to pull together a tutorial; I'll work on getting this merged soon -- am reaching an almost infinite number of open pull requests 😛
