### ISSUE TITLE
Immediate failure without further info

### ISSUE THREAD

**Issue by BridgeAR** [istanbuljs/nyc#51]
I ran into a strange bug that will kill nyc right away without any error message.

Just comment [this line](https://github.com/NodeRedis/node_redis/blob/0ec2c43603ccbad95185475447f832f3f44866bd/test/node_redis.spec.js#L141) out and running that test will kill nyc (that line should actually be deleted but the tests won't run afterwards anymore).

**Comment by bcoe** [comment]
I wonder if removing this line is perhaps resulting in an exit code that nyc is not properly catching -- did you ever figure out any solution to this problem?

**Comment by BridgeAR** [comment]
The tests runs properly if executed by mocha without nyc.

**Comment by BridgeAR** [comment]
I just checked if the refactoring has helped but this is still an issue with 5.0.1.

**Comment by novemberborn** [comment]
@BridgeAR 

I've checked out <https://github.com/NodeRedis/node_redis/commits/0ec2c43603ccbad95185475447f832f3f44866bd/> locally and installed dependencies. Node 5.2.0, npm 3.3.12, Redis server 3.0.5.

Before commenting out the line `npm test` sees 1751 tests passing and 13 pending. It's the same when I do comment out the line. Coverage is reported in both cases. This is with both `nyc@3.2.2` and `nyc@5.0.0`.

If I check out [`master`](https://github.com/NodeRedis/node_redis/commits/16a1d69c8230c247ce05af025bf41c3af47f9a12/) there are 1849 passing tests, 12 pending and 1 failing. It's still the same when I comment out the line you mentioned. This is both with `nyc@4.0.1` and `nyc@5.0.0`.

Could you provide more details on your environment?

Also, [this line](https://github.com/NodeRedis/node_redis/blob/0ec2c43603ccbad95185475447f832f3f44866bd/test/node_redis.spec.js#L40) sets up the `client` that is used when the line is commented out. Why does it apply `createClient` to the `createClient` function, rather than the `redis` module?

**Comment by BridgeAR** [comment]
@novemberborn I use the same setup and I'm still able to reproduce this. I did not check the individual commit but the latest master (both nyc and node_redis) with this test:
```js
it.only("return an error in the callback", function (done) {
    var client = redis.createClient('/tmp/redis.sock');
    client.quit(function() {
        client.get("foo", function(err, res) {
            assert(err.message.indexOf('Redis connection gone') !== -1);
            assert.strictEqual(client.offline_queue.length, 0);
            done();
        });
    });
});
``` 
And my output looks like:
```
  The node_redis client
    ✓ return an error in the callback
-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
 __root__/   |    39.37 |    28.95 |    41.03 |    39.27 |                |
  index.js   |    39.37 |    28.95 |    41.03 |    39.27 |... 3,1274,1277 |
 lib/        |    45.95 |        0 |       40 |    45.95 |                |
  command.js |      100 |      100 |      100 |      100 |                |
  utils.js   |    33.33 |        0 |       25 |    33.33 |... 36,51,52,54 |
-------------|----------|----------|----------|----------|----------------|
All files    |    39.66 |    28.27 |    40.96 |    39.57 |                |
-------------|----------|----------|----------|----------|----------------|

npm ERR! Test failed.  See above for more details.
```
The redis module is not the client itself and there's a factory function for new clients. This is called with apply, eventhough it could also be null.

**Comment by novemberborn** [comment]
@BridgeAR did you edit the output? I get:

```
npm test

> redis@2.4.2 pretest /private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.YJ6YDvjg/node_redis
> optional-dev-dependency hiredis


> redis@2.4.2 test /private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.YJ6YDvjg/node_redis
> nyc ./node_modules/.bin/_mocha ./test/*.js ./test/commands/*.js --timeout=8000



  The node_redis client
    using options: detect_buffers: false;
      using hiredis and /tmp/redis.sock
        when connected
          commands after using .quit should fail
            ✓ return an error in the callback


  1 passing (332ms)

-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
 __root__/   |    40.38 |    28.95 |    41.03 |    40.28 |                |
  index.js   |    40.38 |    28.95 |    41.03 |    40.28 |... 3,1274,1277 |
 lib/        |    45.95 |        0 |       40 |    45.95 |                |
  command.js |      100 |      100 |      100 |      100 |                |
  utils.js   |    33.33 |        0 |       25 |    33.33 |... 36,51,52,54 |
-------------|----------|----------|----------|----------|----------------|
All files    |    40.63 |    28.27 |    40.96 |    40.53 |                |
-------------|----------|----------|----------|----------|----------------|


> redis@2.4.2 posttest /private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.YJ6YDvjg/node_redis
> jshint .
```

**Comment by BridgeAR** [comment]
I did not edit the output but the tests before running them. As you can see, there's no "1 passing (Nms)" and npm errors out. Redis will also keep running, since the test run dies right away without ending the redis-server as usual.

**Comment by novemberborn** [comment]
Ah, that makes sense. Curious it doesn't output any of the messages between `The node_redis client` and `✓ return an error in the callback`, nor does the latter have the correct indentation. Do you get the same output running `mocha` directly?

What if you change the `test` script to `"test": "nyc mocha ./test/*.js ./test/commands/*.js --timeout=8000",`?

**Comment by novemberborn** [comment]
And while we're on the subject of unexpected differences in our respective setups, any chance you have a global `mocha` installed? (I don't.)

**Comment by BridgeAR** [comment]
`mocha` is not installed global.

Here's the output for different ways of running npm test:

```
> nyc mocha ./test/*.js ./test/commands/*.js --timeout=8000



  The node_redis client
    ✓ return an error in the callback
-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
 __root__/   |    39.37 |    28.95 |    41.03 |    39.27 |                |
  index.js   |    39.37 |    28.95 |    41.03 |    39.27 |... 3,1274,1277 |
 lib/        |    45.95 |        0 |       40 |    45.95 |                |
  command.js |      100 |      100 |      100 |      100 |                |
  utils.js   |    33.33 |        0 |       25 |    33.33 |... 36,51,52,54 |
-------------|----------|----------|----------|----------|----------------|
All files    |    39.66 |    28.27 |    40.96 |    39.57 |                |
-------------|----------|----------|----------|----------|----------------|


> redis@2.4.2 posttest /home/ruben/repos/redis
```
```
> nyc ./node_modules/.bin/_mocha ./test/*.js ./test/commands/*.js --timeout=8000



  The node_redis client
    ✓ return an error in the callback
-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
 __root__/   |    39.37 |    28.95 |    41.03 |    39.27 |                |
  index.js   |    39.37 |    28.95 |    41.03 |    39.27 |... 3,1274,1277 |
 lib/        |    45.95 |        0 |       40 |    45.95 |                |
  command.js |      100 |      100 |      100 |      100 |                |
  utils.js   |    33.33 |        0 |       25 |    33.33 |... 36,51,52,54 |
-------------|----------|----------|----------|----------|----------------|
All files    |    39.66 |    28.27 |    40.96 |    39.57 |                |
-------------|----------|----------|----------|----------|----------------|

npm ERR! Test failed.  See above for more details.
```
```
> mocha ./test/*.js ./test/commands/*.js --timeout=8000



  The node_redis client
    ✓ return an error in the callback


  1 passing (314ms)


> redis@2.4.2 posttest /home/ruben/repos/redis
```

So there's a difference in each of those.

**Comment by novemberborn** [comment]
`nyc mocha` is the recommended invocation. `./node_modules/.bin/_mocha` is the child process spawned by `mocha` itself. And that seems to work, so that's good.

What is the output for running `./node_modules/.bin/_mocha ./test/*.js ./test/commands/*.js --timeout=8000` (without `nyc`)?

I wonder if you were to rimraf `node_modules` and reinstall, does even the `_mocha` invocation magically work? Maybe it got corrupted at some point.

**Comment by BridgeAR** [comment]
Using the mocha child process works as expected. And the output is the same as bevor after a rimraf.

**Comment by novemberborn** [comment]
I'm inclined to think the problem is due to running `_mocha` rather than `mocha`. Unfortunately I can't reproduce the issue myself.

**Comment by BridgeAR** [comment]
@novemberborn as far as I see it using _mocha is also not working as it should. The output x Tests passing  / failed including the error messages is missing.

I'll push a test case to travis if I find the time to see how travis handles it.

**Comment by bcoe** [comment]
@BridgeAR we've made quite a few changes to the spawning parts of `nyc` since this issue was opened, is this something you're still seeing?

**Comment by bcoe** [comment]
@BridgeAR feel free to reopen this with a reproduction test-case. we've almost completely changed around the guts of nyc since last October, so there's a good chance this issue was addressed.
