### ISSUE TITLE
Error on ubuntu

### ISSUE THREAD

**Issue by GurpreetSran** [istanbuljs/nyc#513]

**Comment by bcoe** [comment]
@GurpreetSran out of curiosity what version of `nyc` are you using:

```
  ├─┬ find-up@1.1.2 
  │ ├── path-exists@2.1.0 
  │ └─┬ pinkie-promise@2.0.1 
  │   └── pinkie@2.0.4 
```

`path-exists` is shipped with nyc, and should be found regardless of platform.

**Comment by GurpreetSran** [comment]
strange, not an issue anymore. losing it. Thanks
