### ISSUE TITLE
Promise rejected with: 'cov_2itgu9hdrb is not defined

### ISSUE THREAD

**Issue by farhan2106** [istanbuljs/nyc#514]
I got the following bugs.

`Promise rejected with: 'cov_2itgu9hdrb is not defined'`

I am using Nightmare.js for browser automation. After investigation, the above error is thrown when I use `Nightmare.evaluate` api. When I remove any references to `Nightmare.evaluate` it is able to do coverage properly.

Am not sure it is an error with **nyc** or **nightmare**.

## Forensic Information
`
v6.9.1
3.10.8
/Users/farhanghazali
└── (empty)
`

**Comment by bcoe** [comment]
@farhan2106 could you share a minimal reproduction of this bug with nightmare.js? I think you've probably found a legitimate edge-case with the instrumenter, which is returning a line counting variable rather than a promise.

**Comment by farhan2106** [comment]
@bcoe I have created a sample project to replicate the error.

[`github project`](https://github.com/farhan2106/temporary-nyc-error)

Again, if we comment out the `Nightmare.evaluate` api, it will be able to generate the report properly.

The sample code is from [Nightmare js github](https://github.com/segmentio/nightmare) itself

**Comment by JaKXz** [comment]
@farhan2106 I have some capacity this weekend, I will try to get back to you on this soon! Thanks for your patience.

**Comment by farhan2106** [comment]
@JaKXz Thanks for the help :)

**Comment by JaKXz** [comment]
@farhan2106 so I'm able to reproduce the issue, which is good.

I tried disabling `nyc`'s instrumentation and going with `babel-plugin-istanbul` but they both produce the same error. Now I have to dive into the stack trace - but you can follow my progress here: https://github.com/JaKXz/temporary-nyc-error/tree/fix/cov-error

**Comment by duytran** [comment]
@JaKXz I have same issue with @farhan2106, Is issue fixed? thank you.

**Comment by JaKXz** [comment]
Thanks for the ping @duytran, I'm unfortunately not available to look deeper. FWIW my fork is still alive: https://github.com/JaKXz/temporary-nyc-error/tree/fix/cov-error and you should be able to reproduce the error there. If you're able, feel free to dig into the issue and for many bonus points try to add a failing test :) though that is a _lot_ of bonus points, because the issue might be in the `istanbuljs` repo

**Comment by duytran** [comment]
@JaKXz thank for reply :)! I will try look around. Thank you.

**Comment by bcoe** [comment]
@duytran @farhan2106 doing some issue cleanup; sorry that I haven't gotten to this bug yet -- will try to get a test around it as soon as possible.

**Comment by duytran** [comment]
Thank @bcoe!

**Comment by keithkml** [comment]
Nightmarejs converts functions passed to `evaluate` into strings, then `eval`s them within the Electron/Chrome context. This means when the function is actually executed, Istanbul's coverage info variables are not present in scope.

The solution is to use Istanbul's [coverage comment syntax](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md#ignoring-code-for-coverage-purposes):

```js
browser
  .goto('http://...')
  .evaluate(
    /* istanbul ignore next */ 
    () => document.getElement('my-div').innerText
  )
  ...
```

**Comment by JaKXz** [comment]
@keithkml great find. Thank you for your explanation. It would definitely be worth documenting this in a gotchas section or something. Making this comment to myself to get on it, or, for anyone who wants an easy contribution :)

**Comment by epyx25** [comment]
Without the fix I was getting

> [Error: Evaluation failed: ReferenceError: cov_1khzuukk7w is not defined
        at evaluate (<anonymous>:1:30)]

The line `/* istanbul ignore next */` solves the problem
 ```JS
   const evaluateRes = await page.evaluate(
      /* istanbul ignore next */
      (selector) => {return selector}, this.selector
    )
```

I am trying to make a base scraper class, where the inherited scraper classes have different evaluate method.
@keithkml  or someone could you explain who could I make this work too?
```JS
class ScraperBase{
  evaluate(selector) {
   return selector
  }

  run() {
    const browser = await puppeteer.launch()
    const page = await browser.newPage();
    // ...
   const evaluateRes = await page.evaluate(
      /* istanbul ignore next */
      this.evaluate, this.selector
    )  
  }
}
```

Now I am getting 
> [Error: Evaluation failed: ReferenceError: cov_1khzuukk7w is not defined

again

**Comment by coreyfarrell** [comment]
@epyx25 in the example you posted you need:
```js
class ScraperBase{
  /* istanbul ignore next */
  evaluate(selector) {
   return selector
  }

// ...
}
```

It's important that you prevent instrumentation of the body of the function that will be sent to the browser, so the `/* istanbul ignore next */` goes before the function declaration.
