### ISSUE TITLE
coverage.json

### ISSUE THREAD

**Issue by yangli1990** [istanbuljs/nyc#518]
## Expected Behavior
Expect a coverage.json file in the coverage folder

## Observed Behavior
No coverage.json

## Bonus Points! Code (or Repository) that Reproduces Issue

```bash
./node_modules/.bin/nyc ./node_modules/.bin/_mocha --compilers js:babel-core/register \"app/**/*.js\"
```

```rc
{
  "lines": 90,
  "statements": 90,
  "functions": 90,
  "branches": 90,
  "include": [
    "app/**/*.js"
  ],
  "exclude": [
    "**/*.spec.js",
    "app/routes/test/**/*.js",
    "**/*.asset.js"
  ],
  "reporter": [
    "json-summary",
    "lcov",
    "text-summary"
  ],
  "sourceMap": true,
  "cache": true,
  "instrument": true,
  "check-coverage": true,
  "report-dir": "./coverage"
}
```

**Comment by JaKXz** [comment]
Is `json-summary` a valid reporter? I thought it was just `json`.

**Comment by yangli1990** [comment]
@JaKXz yes json-summary is valid. Json and json-summary were producing some json files, however neither matched the format of coverage.json. On the other hand, I just realised that the random hashed json in the generated .nyc_output is the coverage.json that I'm looking for. Is there a way to configure this to fall in the "report-dir" folder?

**Comment by JaKXz** [comment]
One thing I've noticed is that you're using the `_mocha` executable in your test command, but you can simplify (assuming this is inside your package.json scripts) to:

```bash
nyc mocha --compilers js:babel-register app/**/*.js
```

Not sure if that'll get you what you want in `report-dir` but it might be worth a shot. I also recommend looking at [`mocha.opts`](https://mochajs.org/#mochaopts)

**Comment by bcoe** [comment]
@yangli1990 to change the location of the output folder, you should be able to set the command line flag `--temp-directory`.

The files output in `.nyc_output` are the raw JSON value of the `__coverage__` variable populated during coverage collection -- I believe json-summary is a styled copy of this information (it doesn't reflect the format stored in `__coverage__`.

What is your goal? perhaps there's a report we're missing., or perhaps an additional command line option that prints the combined output of `.nyc_output` to a `coverage.json` would be usesful? I'd love to know your use-case.

**Comment by yangli1990** [comment]
@bcoe thanks for responding.
I want to be able to read & measure the coverage on my jenkins, however right now .nyc_output outputs some random file with a hash and sometimes it outputs two (I believe it does this when i use the config all = true) I have no way to extracting this information in a nice way. For now, I've written a hack which transforms the output file into a coverage.json file.

**Comment by seanpoulter** [comment]
Adding some notes since they haven't come up yet:

  - The **.nyc_outputs** directory contains the temporary files to create reports later using `nyc report`. Since you have files in this directory, you can try running creating the JSON summary report:
    ```
    nyc report json-summary
    ```

  - That json-summary report will create a a file called [coverage-**summary.json**][rpt] not coverage.json. I found this issue while looking for information why the json reporter saves as coverage-**final.json** instead of coverage.json.

[rpt]: https://github.com/istanbuljs/istanbul-reports/blob/master/lib/json-summary/index.js#L8

**Comment by bcoe** [comment]
@yangli1990 it seems like it might be a nice enhancement to add a command to nyc that lets you combine coverage output into a single file; would definitely consider adding this in the future.

Great first contribution if someone wants to give it a shot 👍

**Comment by bcoe** [comment]
closing this issue as a duplicate, @yangli1990 will flag you in the new issue.

**Comment by yangli1990** [comment]
thank you @bcoe

**Comment by shellscape** [comment]
@bcoe link to new issue number?

**Comment by seanpoulter** [comment]
Lucky for us @shellscape, there's only one other issue that matches a search for `is:issue involves:yangli1990`. @bcoe mentioned him [in this comment](https://github.com/istanbuljs/nyc/issues/515#issuecomment-301283940).

**Comment by shellscape** [comment]
@seanpoulter solid search-fu, I was not aware of the `involves` parameter.
