### ISSUE TITLE
question on istanbul-middleware support

### ISSUE THREAD

**Issue by grawk** [istanbuljs/nyc#519]
We (nodejs@PayPal) are currently relying upon istanbul-middleware to capture coverage metrics along with selenium automation. Unfortunately it seems that istanbul-middleware isn't being maintained within this org.

My question is: are there any plans to bring that module into this org and support it? if not, would you be opposed if I (or someone else here at PayPal) joins your org to do the same?

For reference: https://github.com/gotwarlost/istanbul-middleware/issues/31

Thanks for your time!

**Comment by winksaville** [comment]
I maybe wrong, but as I understand it the istanbul-middleware's purpose is to allow collection of coverage data on the client side, which is something I like to be able to do easily.

Am I correct that is the purpose of the istanbul-middleware?

**Comment by bcoe** [comment]
@grawk sorry for the frustratingly slow response! definitely suffering from a bit of a ticket overload.

I certainly wouldn't oppose bringing istanbul-middleware into the org; and would love help maintaining it (since it's not a library I use on a regular basis).

I would start by pinging @gotwarlost on Twitter and in an issue, to see if he'd be willing to transfer it over to the org.

**Comment by a-sharma11** [comment]
Any updates on this one? We use istanbul-middleware to capture express app code coverage of integration tests. This would be very helpful for us.

**Comment by ivanhm** [comment]
Same here ^^

**Comment by coreyfarrell** [comment]
I'm not aware of a way to have express instrument code though I think https://github.com/nodecg/express-transform-bare-module-specifiers could be forked and made into a generic express babel 7 middleware, then babel-plugin-istanbul could be configured as a plugin.

I do something similar to this using the `fastify` web server, I wrote `fastify-babel` and use that to run the web server for my browser based testing.
