### ISSUE TITLE
lcov report visualization incorrect

### ISSUE THREAD

**Issue by bboe** [istanbuljs/nyc#521]
## Expected Behavior

Lines that are covered should not appear in red.

## Observed Behavior

Lines that are covered sometimes appear in red.

## Bonus Points! Code (or Repository) that Reproduces Issue

a.js

```es6
import React from 'react';

class A extends React.Component {
  a() {
    const b = 1;
  }
  render() {
    return <div>Blah</div>;
  }
}
export default A;
```

a_spec.js

```es6
import React from 'react';
import ReactTestUtils from 'react-addons-test-utils';

import A from './a';

describe.only('<A />', () => {
  it('renders', () => {
    const renderer = ReactTestUtils.createRenderer();
    renderer.render(<A />);
  });
});
```

package.json

```json
{
  "babel": {
    "presets": [
      "es2015",
      "react"
    ]
  },
  "description": "Testing an issue with the coverage output",
  "dependencies": {
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.22.0",
    "babel-register": "^6.22.0",
    "mocha": "^3.2.0",
    "nyc": "^10.1.2",
    "react": "^15.4.2",
    "react-addons-test-utils": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "license": "UNLICENSED",
  "name": "coverage_test",
  "nyc": {
    "reporter": [
      "lcov",
      "text"
    ]
  },
  "repository": "gist:8a2bd8d15cf49b9d770f3fcde222c779",
  "scripts": {
    "test": "nyc mocha --compilers js:babel-register a_spec.js"
  }
}
```

Running `npm test` after installing the above files produces the following visualization for the coverage of `a.js`:

![image](https://cloud.githubusercontent.com/assets/48100/22836412/205de1b6-ef71-11e6-8f7d-a17834c1ebc0.png)

Note that the render function is definitely called and the visualization even shows line 8 as being executed 1 time. I'm not sure if this is a problem directly with nyc, or istanbul, or with an external library, but I figured I'd start here. Below are the contents of the text-lcov output when I run `./node_modules/.bin/nyc report --reporter=text-lcov`

```
TN:
SF:/Users/bboe/Desktop/nyc/a.js
FNF:0
FNH:0
DA:1,1
DA:5,0
DA:8,1
LF:3
LH:2
BRF:0
BRH:0
end_of_record
TN:
SF:/Users/bboe/Desktop/nyc/a_spec.js
FN:6,(anonymous_1)
FN:7,(anonymous_2)
FNF:2
FNH:2
FNDA:1,(anonymous_1)
FNDA:1,(anonymous_2)
DA:1,1
DA:2,1
DA:4,1
DA:6,1
DA:7,1
DA:8,1
DA:9,1
LF:7
LH:7
BRF:0
BRH:0
end_of_record
```

Note: If I replace `const b = 1;` with some other statements like `return;` then the problem goes away.

## Forensic Information

**Operating System:** Mac OS Sierra
**Environment Information:**

v6.2.1
3.10.4

https://gist.github.com/bboe/5ae951b6cf213ba3b1458f5573244edb

**Comment by JaKXz** [comment]
Looks to me like you're missing `babel-plugin-istanbul`. Could you try installing and configuring it as documented, and hopefully you'll be in better place? :)

**Comment by bboe** [comment]
@JaKXz that solved it. Thanks! It's incredible how close to accurate it was without that plugin.

**Comment by bcoe** [comment]
@bboe I'd love for it to be 100% accurate without the plugin, but we've never quite nailed the source-map remapping -- not quite sure where in the stack the lines get shuffled.
