### ISSUE TITLE
Coverage not present for some files

### ISSUE THREAD

**Issue by j5concur** [istanbuljs/nyc#523]
## Expected Behavior

Code called by all tests will have coverage reported.

## Observed Behavior

Coverage for one file is not reported.

Using istanbul (not nyc) with this command:

`istanbul cover _mocha test/**/*.spec.js -- --recursive --require test/setup.js --compilers js:babel-register`

I get this coverage summary:

```
=============================== Coverage summary ===============================
Statements   : 100% ( 247/247 )
Branches     : 98.88% ( 88/89 )
Functions    : 100% ( 41/41 )
Lines        : 100% ( 223/223 )
================================================================================
```

With this nyc command:

`nyc mocha test/**/*.spec.js --recursive --require test/setup.js`

I get:

```
=============================== Coverage summary ===============================
Statements   : 100% ( 119/119 )
Branches     : 100% ( 45/45 )
Functions    : 100% ( 17/17 )
Lines        : 100% ( 112/112 )
================================================================================
```

## Bonus Points! Code (or Repository) that Reproduces Issue

Sorry, don't have one for you.

## Forensic Information

**Operating System:** OS X 10.11
**Environment Information:**
https://gist.github.com/j5concur/e75201f6c7c588e8976765b663cb0bff

.babelrc

```
{
  "presets": [
    "react", "stage-0", "es2015"
  ],
  "plugins": [
  	["react-transform", {
          "transforms": [{
            "transform": "react-transform-catch-errors",
            "imports": ["react", "@concur/nui-logger/lib/components/NuiRedBox"]

      }]
    }]
  ],
  "env": {
    "test": {
      "plugins": [
        "istanbul"
      ],
      "sourceMaps": "inline"
    }
  }
}
```

.nycrc

```
{
  "extension": [
    ".jsx"
  ],
  "require": [
    "babel-core/register"
  ],
  "reporter": [
  	"lcov",
  	"html",
  	"text-summary"
  ],
  "sourceMap": false,
  "instrument": false
}
```

**Comment by j5concur** [comment]
Forgot to mention that this seems similar to  #476 ... and now I'm getting more than one file missing from the coverage report :(

**Comment by j5concur** [comment]
I did a couple of rounds of deleting my node_modules directory and doing npm install, then followed the ES2015+ tutorial more closely.  My nyc test command is now:

`cross-env NODE_ENV=test nyc mocha test/**/*.spec.js --recursive --require test/setup.js`

**Comment by j5concur** [comment]
require has also been set to `babel-register` in .nycrc ... after these changes, coverage looks complete.

**Comment by bcoe** [comment]
@j5concur great; sorry I've been a bit slow to answer tickets the past couple weeks! I'm glad you got this sorted out.
