### ISSUE TITLE
Ability to prevent recording code coverage by anything but dedicated tests

### ISSUE THREAD

**Issue by Xerkus** [istanbuljs/nyc#525]
Currently, code that is run by anything, eg when module is require'd, is recorded as covered.
False coverage makes that metric fairly useless, which is a problem.

I was looking for a way to prevent recording coverage for parts of code unless it was executed from specific tests and found none. Unless i missed something, i would like to make a feature request.

Consider this simplified example:

```js
class TlvMap extends Map {
    defineTlv(tag, name) {
        const tlv = Object.create(null);
        tlv.name = name;
        tlv.tag = tag;
        this.set(tlv.tag, tlv);
        this.set(tlv.name, tlv);
    }

    removeTlv(tagOrName) {
        if (!this.has(tagOrName)) {
            return;
        }
        const tlv = this.get(tagOrName);
        this.delete(tlv.tag);
        this.delete(tlv.name);
    }
}
exports.TlvMap = TlvMap;

const defaults = new TlvMap();
defaults.defineTlv(0x0005, 'dest_addr_subunit', { type: 'int', octets: 1 });
// repeat ~60 times
exports.defaults = defaults;
```
Declared class here will get like 80-90% coverage just by `require()`. It is a false coverage as class is actually untested.

Some kind of ability to mark parts of that source as requiring targeted coverage will be very useful.
Imagine it worked like this:
```js
/** istanbul require targeted */
// now, nothing is going to be recorded, unless targeted (see example below)
class TlvMap extends Map {
    defineTlv(tag, name) {
        const tlv = Object.create(null);
        tlv.name = name;
        tlv.tag = tag;
        this.set(tlv.tag, tlv);
        this.set(tlv.name, tlv);
    }

    removeTlv(tagOrName) {
        if (!this.has(tagOrName)) {
            return;
        }
        const tlv = this.get(tagOrName);
        this.delete(tlv.tag);
        this.delete(tlv.name);
    }
}
/** istanbul require targeted end */
// coverage for code below on require() is expected
exports.TlvMap = TlvMap;

const defaults = new TlvMap();
defaults.defineTlv(0x0005, 'dest_addr_subunit', { type: 'int', octets: 1 });
// repeat ~60 times
exports.defaults = defaults;
```
and then  in tests
```js
describe('Tlv', () => {
    (nyc || istanbul).coverageTarget(['../lib/tlv.js']);
    it('TlvMap must...', () => {});
    (nyc || istanbul).coverageTarget(false);
});
```
I guess it will be a breaking behavior for other use cases, so new flag is needed
`nyc --targeted-coverage --check-coverage mocha`

I suppose this issue belongs to some other istanbul project, not sure which.

**Comment by bcoe** [comment]
@Xerkus let's keep this open for the time being; I'm collapsing a bunch of the Istanbul repos into a mono-repo; at this time I think this would be a better home for this issue.

I understand what you're looking for, and think this would probably make sense as a separate tool -- I do think most of the building blocks necessary exist in Istanbul to pull it off.

**Comment by coreyfarrell** [comment]
I appreciate what you are trying to accomplish but unfortunately this is not possible in the way you've designed this source.  The way NYC works is it modifies the code to include coverage counters, so before a statement the generated code will increment a counter saying that statement was run.  This cannot do more or it would significantly increasing overhead of the instrumented code.

My advice is to not accept 80-90% coverage, if you aim for 100% coverage this will generally not be an issue.  That said simply having 100% coverage doesn't always indicate perfect testing.  This is why I generally prefer to work with smaller / single purpose modules - it's easier to scrutinize testing.

One option would be to split your example code into two sources.  One source that contains `class TlvMap`, another that contains the `default` instance.  Then your test for the default instance could use `istanbul-lib-coverage` to reset the hit counter of the `class TlvMap` file from the test which verifies the default instance.  If following this path I'd recommend putting the default instance tests in it's own test file (being a separate process will prevent you from purging coverage from other tests).
