### ISSUE TITLE
100% coverage on all files, but no files listed.

### ISSUE THREAD

**Issue by caalberts** [istanbuljs/nyc#526]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
I was expecting to see coverage on individual files and the coverage to be less than 100%

## Observed Behavior

| File | % Stmts | % Branch | % Funcs | % Lines | Uncovered Lines |
| ----------|----------|----------|----------|----------|----------------|
| ----------|----------|----------|----------|----------|----------------|
| All files |      100 |      100 |      100 |      100 |                |
| ----------|----------|----------|----------|----------|----------------|

## Forensic Information

**Operating System:** OS X 10.11.6 
**Environment Information:** Node v5.5.0

package.json:
```
  "scripts": {
    "test:coverage": "NODE_ENV=test nyc mocha app/test --require app/test/jsdom-setup --recursive --compilers js:babel-register --require ignore-styles"
  },
  "babel": {
    "presets": ["es2015"],
    "env": {
      "test": {
        "plugins": ["istanbul"]
      }
    }
  },
  "nyc": {
    "require": [
      "babel-register"
    ],
    "sourceMap": false,
    "instrument": false
  }
```

**Comment by bcoe** [comment]
@caalberts would you be able to provide a repo that exhibits this behavior? I'm sure we can figure out an approach to supporting `jsdom`.

**Comment by caalberts** [comment]
I can't as it's a private repo. How does requiring `jsdom` lead to this issue?

**Comment by bcoe** [comment]
@caalberts just a hunch; another weird thing I see, you shouldn't have `--compilers js:babel-register` in your `test:coverage` command, since you have it required in your `nyc` configuration.
