### ISSUE TITLE
Feature request: enforce multiple thresholds

### ISSUE THREAD

**Issue by nicosommi** [istanbuljs/nyc#527]
Hello,

Just an idea that I had today when I ran into the commit -n scenario (this is the N time with N > 50), when trying stuff in a project and commit a partial advance.  I want to have a different coverage threshold on certain files (jsx in this case) because of a decision (let's say 50%). But I want 90% on the rest of my code. And I think that it may apply also, as a second scenario, for environment dependent thresholds.
I'm thinking in something like: 
```json
"nyc": {
  "thresholds": {
    "dev": [
        {
          "include": ["**/*.js"],
          "exclude": ["**/*.jsx"],
          "lines": 90,
          "statements": 90,
          "functions": 90,
          "branches": 90
        },
       {
          "include": ["**/*.jsx"],
          "exclude": ["**/*.js"],
          "lines": 50,
          "statements": 50,
          "functions": 50,
          "branches": 50
        }
    ],
   "prod": [
        {
          "include": ["**/*"],
          "exclude": [],
          "lines": 90,
          "statements": 90,
          "functions": 90,
          "branches": 90
        }
    ]
  }
}
```

This way, when I run the CLI with a --threshold=dev argument it will enforce that threshold.

## Expected Behavior
Support multiple enforce threshold configurations with include/exclude globs. As I said this can be also useful if we have different threshold among different environments. You may want to stop using -n in development branches when doing a git commit that is just a checkpoint for the day, because you can play in a wider range. And, if that didn't brake the test, it is conceptually ok because you know that your tech debt on that environment is higher. And also, it is annoying to waste some time waiting for that, and even maybe receive unuseful alerts from the CI server.

## Observed Behavior
Currently it works with a global threshold enforcement configuration.

## Bonus Points! Code (or Repository) that Reproduces Issue
Since this is not an issue but an idea, it just the regular behavior. I will avoid the rest of the template because of this.

Thanks for even reading!

**Comment by nicosommi** [comment]
I just realized I can override those configurations via CLI args. Closing this.

**Comment by bcoe** [comment]
@nicosommi 👍 awesome; did this approach work for you?
