### ISSUE TITLE
Covering code loaded with `jsdom` and `systemjs`

### ISSUE THREAD

**Issue by unional** [istanbuljs/nyc#529]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
Able to walk through the code loaded by:

```ts
// pseudo code simplified
new Promise(resolve =>{
  jsdom.env({
    scripts: [ 'systemjs' ],
    done(err, win) {
      resolve(win)
    }
  })
}).then(win => {
  const sys = win.SystemJS
  sys.config({ ... })
  return sys;
}).then(async sys => {
  const target = await sys.import('target')
  // do testing
})
```

## Observed Behavior
Not covered (pretty much expected)
Is there a way to configure `nyc` to trace code like this?

## Forensic Information
Window 2012 R2

node: 7.5.0
npm: 4.0.5

**Comment by bcoe** [comment]
@unional would you be able to provide a minimal repo that would let us dig into `jsdom`/`systemjs` support?

I'm sure there are approaches that we can use to support this.

**Comment by unional** [comment]
Repo: https://github.com/unional/issues/tree/nyc-systemjs

Steps: 
```sh
git clone https://github.com/unional/some-issues.git
cd some-issues
git checkout nyc-systemjs
npm install
npm run coverage
```

Thanks for looking into this! 🌷

**Comment by bcoe** [comment]
@unional sorry it's taken so long to get to this (put out a new major release of yargs, and have been doing some work around monorepos to try to consolidate some of the work on istanbuljs).

Thanks for providing this reproduction!

**Comment by JaKXz** [comment]
@unional I took a quick look at your repo and it looks like https://github.com/istanbuljs/nyc/issues/176#issuecomment-286738545 might help. Could you try giving that a shot and reporting back?

**Comment by unional** [comment]
Sure I can give it a try, but what does it solve? It seems like a solution to get coverage with `mocha` and `webpack`. But I do get coverage already with `ava` and `nyc`. It's just that when loading through `jsdom` and `systemjs` the coverage are not recorded.

**Comment by unional** [comment]
I have created a tool [`domture`](https://github.com/unional/domture) that makes testing using jsdom a bit easier.
It using the technique described here thus has the same problem.

I still don't know if this can be fixed because I notice that `ava` can't pickup the dependency graph either.

What I mean is this:

```ts
// src/a.ts
export function foo() { ... }
// src/a.spec.ts
// load `foo` thru jsdom/systemjs
```
when I run `ava` in watch mode and the file `a.ts` is changed, tests in `a.spec.ts` is not rerun.
Normally it would because `ava` detects `a.spec.ts` has dependency of `a.ts`

**Comment by sergueyarellano** [comment]
Same problem here. 

Any updates on the issue @unional ?

Any alternative to systemjs for loading amd modules with path, shim configs, etc?
I'm going to try requirejs, but don't know if it's gonna work in node...

**Comment by sergueyarellano** [comment]
Finally I tried requirejs in node after struggling with systemjs coverage hooks.

I get lots of `Shim config not supported in Node, may or may not work` when importing libraries like jquery

Although you can configure the node environment as follows:

```
const { JSDOM } = require('jsdom');
const dom = new JSDOM(`<!DOCTYPE html>`);
window = dom.window;
document = window.document;

Object.keys(window).forEach(function (key) {
  if (!global[key]) {
    global[key] = window[key];
  }
});
```

cheers

**Comment by unional** [comment]
@sergueyarellano what you did is essentially what `jsdomify` and `browser-env` does, and is explicitly discouraged by the jsdom team.

**Comment by bcoe** [comment]
@unional @sergueyarellano me thinks to get this working an additional plugin would be required for jsdom. What you basically want is that when JSDom loads a block of JavaScript, you should hook into this step and run the JavaScript through the [istanbul instrumenter](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-lib-instrument) -- I think you'd probably be better to do this in an additional helper module rather than nyc itself.

Could be a fun project (and I'd happily link to and document it in nyc and on the istanbul website).

**Comment by felixfbecker** [comment]
@unional have you tried what @bcoe suggested? Very interested in something like domture (was about to write it myself when I saw yours) but need coverage support.

**Comment by unional** [comment]
@felixfbecker have not get the chance to work on @bcoe idea. The idea sounds good. Need to see if there is such a hook and create it if needed. Do you want to give it a try?

**Comment by morris** [comment]
Here's what I use right now to have coverage on any script run by jsdom. It just maps URLs encountered in vm.runInContext to local files:

```
const webroot = "public";
const originalRunInContext = vm.runInContext;

vm.runInContext = function(code, context, options) {
  // this should probably only match on localhost, still WIP
  if (options && options.filename && options.filename.match(/^https?:\/\//i)) {
    let filename = url.parse(options.filename).path;
    if (filename.match(/\/$/)) filename += "index.html";
    // this is optional but gives coverage on inline <script> tags
    if (options.lineOffset > 0) {
      filename += "." + options.lineOffset + ".js";
      fs.writeFileSync(path.resolve(path.join(webroot, filename)), code);
    }

    return originalRunInContext.call(vm, code, context, {
      ...options,
      filename: path.resolve(path.join(webroot, filename))
    });
  }
  return originalRunInContext.call(vm, code, context, options);
};
```

Needs nyc's sourceMap and hookRunInContext set to true. Does not work with --all, though.

**Comment by jfoclpf** [comment]
is this issue solved? How can I cover a file loaded by JSDOM?
