### ISSUE TITLE
is there a way to set the name of lcov.info files

### ISSUE THREAD

**Issue by skarfacegc** [istanbuljs/nyc#531]
I'd like to run nyc & mocha on several different sets of files then run a unified report across all of them to show coverage.

eg.
```
nyc --reporter=lcov --lcov-name=model-lcov.info mocha test/model/**/*.test.js 
nyc --reporter=lcov --lcov-name=controller-lcov.info mocha test/controller/**/*.test.js
nyc --reporter=lcov --lcov-name=view-lcov.info mocha test/view/**/*.test.js
nyc mocha report --reporter=text-summary 
```
Looking for something similar to --lcov-name (or way to accomplish same).

**Comment by bcoe** [comment]
@skarfacegc if you do this:

`nyc npm run t1 npm run t2 npm run t3`

where:

```{
  "scripts": {
     "t1": "mocha test/model/**/*.test.js ",
     "t2": "mocha test/controller/**/*.test.js",
     "t3": " mocha test/view/**/*.test.js"
  }
}```

`nyc` will output the combination of all tests runs to the `.nyc_output` folder, and you will be able to print a combined report.

**Comment by skarfacegc** [comment]
So there's no way to run multiple instances of nyc (if I want to parallelize my build for example) and generate a report that's an aggregate of multiple runs?

Yes, I'd need to deal with cleaning out the old between runs, but build systems are generally pretty good at that.  I see that the[ lcovonly ](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/lib/lcovonly/index.js#L8) reporter takes a filename option, but I can't figure out how to set it through nyc.

**Comment by Rush** [comment]
@skarfacegc have you been able to generate the lcov report in a different directory? Istanbul has an option `--dir custom-coverage-dir`, for example `--dir coverage/api`

**Comment by Rush** [comment]
Oh, never mind, there's `--report-dir`

**Comment by JaKXz** [comment]
Closing this issue since it seems resolved and stale.
