### ISSUE TITLE
nyc mocha tests not running 

### ISSUE THREAD

**Issue by hilarybarr** [istanbuljs/nyc#533]
I run mocha tests without any issues:
```
mocha --compilers ts:ts-node/register
Customer test
    ✓ should return correct prefix
   ...
```
Then I run it with nyc
nyc cover mocha --compilers ts:ts-node/register

nothing happens in the console, the test are not running (sometimes it shows Error: spawn cover ENOENT because cover failed the previous time)

Can you teach me where to look at? any error log?

## Expected Behavior
Need to see mocha tests run

## Observed Behavior
nothing happens in the log, or "Error: spawn cover ENOENT".
I tried adding "./node_modules/.bin/" before both nyc / mocha scripts, no help.
I don't even have an error log to look at.

**Operating System:** 
Mac OSX 

**Environment Information:** 
https://gist.github.com/hilarybarr/74879b5d09104eaf7f1b6c60e3d7ed76

**Comment by hilarybarr** [comment]
fixed it with 
`nyc --reporter=text --reporter=html mocha --compilers ts:ts-node/register`

**Comment by JaKXz** [comment]
@hilarybarr glad you got it sorted :) in case you need an example config to get coverage working with mocha + Typescript, I recently helped update this piece: http://azimi.me/2016/09/30/nyc-mocha-typescript.1.html

**Comment by bcoe** [comment]
@mohsen1, @JaKXz ... I don't suppose we could repost this tutorial on `istanbul.js.org`, this would rock.

**Comment by JaKXz** [comment]
Just for posterity, this now lives here as well :) https://istanbul.js.org/docs/tutorials/typescript/
