### ISSUE TITLE
Need Help Trying to Understand Why Coverage is Reporting as 0%

### ISSUE THREAD

**Issue by wrumsby** [istanbuljs/nyc#536]
I'm trying to work out why I'm seeing different results for coverage when running locally (OS X 10.12; nvm; yarn, node 7.4.0) vs running on a build agent (Windows 10, nodist, yarn node 7.4.0) as part of a TeamCity 10.0.4 build.

If I have the following scripts in my `package.json`:

```
"cover": "cross-env BABEL_ENV=test nyc --check-coverage --reporter=teamcity npm test",
"test": "mocha test/**/*.js"
```

running `npm run cover` locally will output:

```
##teamcity[blockOpened name='Code Coverage Summary']
##teamcity[buildStatisticValue key='CodeCoverageAbsBCovered' value='129']
##teamcity[buildStatisticValue key='CodeCoverageAbsBTotal' value='1340']
##teamcity[buildStatisticValue key='CodeCoverageAbsRCovered' value='26']
##teamcity[buildStatisticValue key='CodeCoverageAbsRTotal' value='388']
##teamcity[buildStatisticValue key='CodeCoverageAbsMCovered' value='26']
##teamcity[buildStatisticValue key='CodeCoverageAbsMTotal' value='377']
##teamcity[buildStatisticValue key='CodeCoverageAbsLCovered' value='118']
##teamcity[buildStatisticValue key='CodeCoverageAbsLTotal' value='1287']
##teamcity[blockClosed name='Code Coverage Summary']
```

when run as a TeamCity build step I get:

```
[npm run cover] ERROR: Coverage for lines (0%) does not meet global threshold (5%)
[npm run cover] ERROR: Coverage for functions (0%) does not meet global threshold (5%)
[npm run cover] ERROR: Coverage for branches (0%) does not meet global threshold (5%)
[npm run cover] ERROR: Coverage for statements (0%) does not meet global threshold (5%)
```

It doesn't seem to matter if I use the [Node.js NPM runner](https://github.com/jonnyzzz/TeamCity.Node) or the PowerShell runner.

But if I run `npm run cover` directly on the build agent, in the same working directory as the above build (i.e. I go onto the build agent, `cd` into the work directory for the build and run `npm run cover`) then I _do_ get the same result as running this script "locally" (i.e. on my development machine).

Also note that at some point the build _was_ correctly reporting coverage, but I can't tell what has changed to stop this working (since we're using Yarn I don't think it is because of dependencies changing). I suspected that warnings associated with my tests might be somehow preventing this information being logged properly, but removing those warnings still reports 0% coverage.

While this error appears to be build agent or build configuration specific a couple of things have me scratching my head:

* other npm scripts run properly (e.g. `npm run lint`, `npm test`)
* when setting up nyc locally it does seem that misconfiguration or errors can lead to coverage being measured as 0%, but those errors are quite opaque -- what sort of things should I be looking for if I'm getting 0% coverage?

## Expected Behavior

Coverage reports when running via build are the same on build agent as on local development machine or when running directly in PowerShell.

## Observed Behavior

Build reports coverage is 0% for all metrics.

## Forensic Information

**Operating System:**

Windows 10

**Environment Information:** 

Node and npm versions and output from `npm ls`:

https://gist.github.com/wrumsby/af734de419d5b797aaf7d8494c5b4c75

TeamCity 10.0.4

Build step configuration is very simple:

|  Property | Value |
| -------- | ----- |
| Runner type | Node.js NPM |
| npm commands | run cover |
| Working directory | %base.directory% |

The _clearest_ difference here is the working directory, but trying:

```
npm run cover --prefix %base.directory%
```

from the checkout directory still reports coverage correctly.

**Comment by wrumsby** [comment]
So, configuring the build agent to run as an admin seems to resolve the issue here.

**Comment by bcoe** [comment]
@wrumsby awesome (also weird) I wonder what was happening to you here.

Let me know if you bump into any more issues.
