### ISSUE TITLE
Cannot get report for non-covered parts of conditions

### ISSUE THREAD

**Issue by ozum** [istanbuljs/nyc#538]
## Expected Behavior

Less than 100% coverage.

## Observed Behavior

100% coverage.

## Forensic Information

**Operating System:** MacOS 12.12.2
**Environment Information:** node v7.7.1, nyc 10.1.2

(I moved this case from https://github.com/gotwarlost/istanbul/issues/784)

Hi,

I use `mocha` & ~~`istanbul`~~ `nyc` for some projects and `lab` for some others.

For the very simplified example below `nyc` reported 100% coverage whereas `lab` reported less than 100%.

## nyc

`$ istanbul cover _mocha`

```js
const Code    = require('code');
const expect  = Code.expect;

const util = require('../util');

describe('deneme', () => {
  it('should return true', (done) => {
    expect(util.deneme('a')).to.true();
    done();
  });

  it('should return false', (done) => {
    expect(util.deneme()).to.false();
    done();
  });
});
```

## lab

`$ lab --coverage --reporter html > report.html` 

```js
const Lab  = require('lab');
const Code = require('code');

const lab      = Lab.script();
const describe = lab.describe;
const it       = lab.it;
const expect   = Code.expect;

const util = require('../util');

exports.lab = lab;
describe('deneme', () => {
  it('should return true', (done) => {
    expect(util.deneme('a')).to.true();
    done();
  });

  it('should return false', (done) => {
    expect(util.deneme('b')).to.false();
    done();
  });
});
```

## Function

```js
// util.js file
function deneme(a) {
  return (a && a.startsWith('a')) ? true : false;
}

module.exports = {
  deneme
};
```

Although two branches are executed by tests and as a result tests seem to cover 100% of the code, second part of the condition is never tested/executed.

`lab` reported that first part of the condition `a` is always true, so that second part `a.startWith('a')` is never executed. Please see screenshot below:

![screen shot 2017-03-23 at 16 31 14](https://cloud.githubusercontent.com/assets/1497060/24249946/d416dece-0fdd-11e7-8d94-9337b432daf7.png)

A third test should be added for this case:

```js
  it('should return false for undefined', (done) => {
    expect(util.deneme()).to.false();
    done();
  });
```

Not in this simple example, but in more complex situations it helped me hunt some hard to catch bugs.

Is it possible to detect condition coverage in `nyc`?

Kind Regards,

**Comment by JaKXz** [comment]
Sorry for the delayed response @ozum but nyc does not do static analysis, just instruments and reports code coverage. Thanks for the issue!

**Comment by ozum** [comment]
@JaKXz No problem for the late.

Isn't my case related to code coverage, because in that tests do not cover second part of the condition?

**Comment by JaKXz** [comment]
Yes branches, statements, functions, and line coverage are measured and reported.

**Comment by ozum** [comment]
In that case, `nyc` should report below 100%. However it is reporting 100%.

`return (a && a.startsWith('a')) ? true : false;` (false condition never executed in tests).
