### ISSUE TITLE
Nyc not producing any coverage info on Jenkins (RHEL) build server, works fine on Mac OS & Ubuntu

### ISSUE THREAD

**Issue by wicked539** [istanbuljs/nyc#539]
Expected Behavior

I recently tried to integrate Nyc coverage reports into the build process of one of our apps. It works perfectly fine on my local Mac OS dev machine:

$ nyc mocha src/test/javascript/**/*.spec.js

Generates coverage report as expected (All files |    90.79 |    60.29 |    83.12 |    90.79 |, and so on... ).

## Observed Behavior

However, I am unable to get Nyc to produce any coverage information on our build server (running Red Hat Enterprise Linux 7.2). The tests are executed just fine, but the output of nyc itself is just an empty list (All files |  Unknown  |  Unknown |  Unknown |  Unknown |).

I set up a vagrant box running Ubuntu 14.04 LTS and built the same project, and it worked fine (just as on my Macbook itself). 

I figured it might be an issue with the project itself, so I also integrated Nyc into the build process of another project (which does not use anything fancy like Babel), but the result was the same: Works on MacOS & Ubuntu, does not work on RHEL.

## Bonus Points! Code (or Repository) that Reproduces Issue

The only difference between environments that i can think of is the OS, as mentioned above. Is there some kind of a "verbose" switch I can use to try to collect some more information?

## Forensic Information

**Operating System:** 
$ cat /etc/*-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"

**Environment Information:** 
$ node -v
v6.9.1

$ npm -v
4.0.3

$ npm ls
...
├─┬ nyc@10.1.2
...

Node, Npm and Nyc versions are the same on all three OS that I tried (RHEL, Mac OS, Ubuntu).

**Comment by bcoe** [comment]
@wicked539 sorry for the slow reply; have had somewhat of a backlog of issues that we're working through.

We use the npm module `os-homedir` to store temporary runtime information for nyc; I recommend checking the folder that it returns in the RHEL environment, and checking whether the npm bin would have write permission to it.

**Comment by wicked539** [comment]
Thanks for your reply!

I added a pre-build shell script to my jenkins job:

`touch $(target/node/node -e "const osHomedir = require('os-homedir');console.log(osHomedir());")/foo.txt`
`ls -lah $(target/node/node -e "const osHomedir = require('os-homedir');console.log(osHomedir());")/foo.txt`

And in the build's output, it shows that the file was created successfully:

`-rw-r--r-- 1 jenkins_zoe jenkins_zoe 0 May 17 09:04 /home/jenkins_zoe/foo.txt`

So yes, the user running the build does have write permissions to that folder.

**Comment by bcoe** [comment]
@wicked539 what version of RHEL are you running? also out of curiosity, do you have a RHEL instance you can try manually running the tests on, rather than having to kick of  a Jenkins build each time.

**Comment by wicked539** [comment]
@bcoe as stated above, we're running RHEL 7.2. Also, the result is the same when i run the build manually (by logging into the server).

**Comment by emanuelez** [comment]
Was the reason for this ever found? I stumbled upon it as well.

**Comment by JaKXz** [comment]
If this is still an issue with the latest version of nyc, please open a new issue with a link to a minimal reproduction repo.
