### ISSUE TITLE
support for --root option

### ISSUE THREAD

**Issue by borisovg** [istanbuljs/nyc#542]
nyc doesn't seem to have support for `--root` option?

I keep all my test stuff in ./tests (including separate package.json and all coverage output) and run istanbul from this directory with `--root ../` set.

**Comment by bcoe** [comment]
@borisovg would definitely entertain adding this 👍

**Comment by Speedy37** [comment]
While implementing the `--root` option, I found that the `NYC_CWD` environment variable does almost exactly that (it still looks upwards for package.json).

**Comment by Rush** [comment]
I'm trying migrate from istanbul and I'm also missing this feature.

**Comment by borisovg** [comment]
Closing since this was fixed by  #620

**Comment by Rush** [comment]
@borisovg since it's closed does it mean it has been released?

**Comment by borisovg** [comment]
@Rush I'm using `nyc` 11.2.1 and `--cwd` is listed in the help output (in the bug I linked to it was decided that it is sufficient replacement for `--root`. I tried it today with my code and it seems to work fine.

**Comment by bcoe** [comment]
@Rush should be working, there are a few bugs being addressed however feel free to join the conversation here:

https://github.com/istanbuljs/nyc/issues/668

we seem to still have some issues when source-maps are remapping the directory structure.

**Comment by Rush** [comment]
I confirm the option itself is working but unfortunately it's useless to me without ability to provide a custom coverage dir for `lcov`. Istanbul has an option --dir custom-coverage-dir, for example --dir coverage/api
