### ISSUE TITLE
--all only reports all files with --reporter=text

### ISSUE THREAD

**Issue by dbaston** [istanbuljs/nyc#544]
## Expected Behavior

With `--reporter=cobertura` or `--reporter=lcov`, `--all` should output in `/coverage` for every input file.

## Observed Behavior

Output is only produced for all files with `--reporter=text`.  With `--reporter=cobertura` or `--reporter=lcov`, the effect of the `--all` seems to penetrate only one level deep from the project root.

For example, `modules/process.js` is included in the report, but `components/header/frame.js` is not.

## Forensic Information

**Operating System:** 
Linux lx-1101 3.13.0-112-generic #159-Ubuntu SMP Fri Mar 3 15:26:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Environment Information:** 
https://gist.github.com/dbaston/22688010a41a77624fb747b2b1220b53

**Comment by JaKXz** [comment]
hmm. This might actually be related to our cobertura [and clover] reporters being kinda broken ATM... I usually use `--reporter=lcov` which prints everything just fine AFAICT. Mind giving that a try? :)

See https://github.com/istanbuljs/istanbuljs/issues/13 and https://github.com/istanbuljs/istanbuljs/issues/14

**Comment by bcoe** [comment]
@dbaston perhaps you could share a project that's having this issue, I'd love to get to the bottom of this.

**Comment by dbaston** [comment]
> I usually use --reporter=lcov which prints everything just fine AFAICT.

I'm having the same problem with `--reporter=lcov`.  The output of `--all` is not the same as the output without `--all`, but the "allness" only penetrates one level deep.

@bcoe I don't have a project I can share, but I may be able to create one.

**Comment by bcoe** [comment]
I am unable to reproduce this behavior -- here's yargs running with `--all`.

<img width="1128" alt="screen shot 2017-05-13 at 5 49 09 pm" src="https://cloud.githubusercontent.com/assets/194609/26030305/87d713ea-3804-11e7-9122-314193260314.png">

It might be worth trying the newest version of nyc; there have been a couple fixes related to report generation.

if you are still running into issues after upgrading, please re-open this issue with a failing example 👍
