### ISSUE TITLE
--all with babel-plugin-istanbul does not report coverage for non-transpiled files

### ISSUE THREAD

**Issue by joelmukuthu** [istanbuljs/nyc#545]
## Observed Behavior
If files are excluded from transpilation in .babelrc, then the files that are not included in the test suite are not included in the coverage report, which is the expected behaviour with `--all`

## Expected Behavior
That all the files in the directory excluded from transpilation would be included.

## Setup
directory structure:
```
/client
  /lib
  /test
/server
  /lib
  /test
```
.babelrc:
```json
{
  "only": [ "client" ], 
  "env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
}
```
package.json:
```json
{
  "scripts": {
    "coverage": "cross-env BABEL_ENV=test nyc --all --require babel-register npm test",
    "test": "npm-run-all test:server test:client",
    "test:server": "mocha server/test",
    "test:client": "cross-env BABEL_ENV=test mocha --require babel-register client/test"
  }
}
```
While you could workaround this issue by including `/server` in the transpilation (or removing the `only` config in .babelrc), it would still be nice for nyc to support this case

**Comment by JaKXz** [comment]
Interesting use case. Just curious, have you tried an `"include": ["client", "server"]` in your `.nycrc` or package.json nyc stanza? Not sure if that'll fix it but it's worth a shot.

**Comment by joelmukuthu** [comment]
Yeah I have both `/client` and `/server` in my nyc config but that didn't fix it. I'll find some time tomorrow to create a repository to reproduce this.

**Comment by joelmukuthu** [comment]
Repo: https://github.com/joelmukuthu/nyc-istanbul-all-bug
Travis build showing the bug: https://travis-ci.org/joelmukuthu/nyc-istanbul-all-bug/builds/219197809
Travis build showing what's expected: https://travis-ci.org/joelmukuthu/nyc-istanbul-all-bug/builds/219197761

**Comment by joelmukuthu** [comment]
@JaKXz @bcoe have you had a chance to look at this?

**Comment by psachs21** [comment]
I am also seeing a similar issue. I have an even simpler setup though, i just have a react project with a few non tested files. And when I run nyc, only my tested files show in the coverage report.

Partial Package.json:
```
      "ava": {
		"require": [
			"babel-register",
			"./test-helpers/setup-browser-env.js"
		],
		"babel": {
			"presets": [
				"es2015",
				"stage-0",
				"react"
			]
		},
		"files": [
			"**/*.test.js",
			"**/test.js"
		]
	}
```

Partial babelrc:
```
{
  	"presets": [["es2015", {"modules": false}], "react", "stage-0"],
  	"plugins": ["transform-runtime", "transform-decorators-legacy", "react-hot-loader/babel"],
  	"env": {
		"test": {
			"presets": [["es2015", {"modules": "commonjs"}]],
			"plugins": [
				"istanbul",
			],
			"sourceMaps": "inline"
		}
	}
}
```

Partial nycrc:
```
{
	"require": [
		"babel-register"
	],
	"sourceMap": false,
	"instrument": false,
	"all": true
}
```

**Comment by psachs21** [comment]
Sample reproduction can be found here: https://github.com/psachs21/web-boilerplate

**Comment by coreyfarrell** [comment]
Both repos linked here are based on old versions of NYC and babel 6.  Is this still an issue when using latest NYC with babel 7?

**Comment by joelmukuthu** [comment]
Upgrading babel to v7 seems to fix the issue :tada: However, it was still reproducible with nyc v14 and babel v6, so it might be worth it to add a note to the readme recommending babel v7 even though this issue is an edge case.

- nyc v14 and babel v6 travis build: https://travis-ci.org/joelmukuthu/nyc-istanbul-all-bug/builds/522699903
- nyc v14 and babel v7 travis build: https://travis-ci.org/joelmukuthu/nyc-istanbul-all-bug/builds/522703279

Closing and updating the first comment to recommend the fix.
