### ISSUE TITLE
[help wanted] What does it mean with the I, E Marker?

### ISSUE THREAD

**Issue by Samurais** [istanbuljs/nyc#555]
hi, folks

I have tested project with nyc, but I dont know how to read the report.
* what does the read lines mean?
* and why there are 'I' and 'E' markers?

![image](https://cloud.githubusercontent.com/assets/3538629/25126604/676291dc-2465-11e7-8314-da61f03f866e.png)

**Comment by JaKXz** [comment]
Good question :) 

The `I` flag means that the if path is not taken in your tests, and therefore is not covered. 

The `E` flag means that the else path is not taken in your tests and therefore not covered. 

To find out what any markings mean in the coverage reports, you can mouse over the part you're interested in and a tooltip should give some information. 

Would you like to add this documentation and anything else that was unclear to our [docs site](http://github.com/istanbuljs/istanbuljs.github.io)? It would be a quick win for all of us!

**Comment by Samurais** [comment]
Thanks a lot. Yes, it would be better if we put them in docs site.

**Comment by JaKXz** [comment]
Feel free to make PRs there! :)
