### ISSUE TITLE
coverage folder is not being excluded on nyc@10.2.0

### ISSUE THREAD

**Issue by astorije** [istanbuljs/nyc#557]
## Expected Behavior

`coverage/` folder being excluded even when not present from the exclude list.

## Observed Behavior

<img width="573" alt="screen shot 2017-04-19 at 01 22 12" src="https://cloud.githubusercontent.com/assets/113730/25164400/a58ddb36-249e-11e7-9ccd-4b3b7641eb4e.png">

See comment made at https://github.com/istanbuljs/nyc/pull/502#issuecomment-295098720.

## Bonus Points! Code (or Repository) that Reproduces Issue

Look at https://github.com/thelounge/lounge/blob/master/.nycrc (that gets run with `npm run coverage`). We removed `coverage/` from the exclude list of The Lounge [here](https://github.com/thelounge/lounge/pull/989/commits/2bcbb62af0af93db08c32ecfdd7f8db70dd1584c) but I have just noticed that it is not ignored anymore.

## Forensic Information

**Operating System:** macOS 10.11.6
**Environment Information:** [Result of `sh -c 'node --version; npm --version; npm ls'`](https://zerobin.net/?8e999f346fea4ea9#vr5XFIEtL0zU1+8dfQhUsINXPo5TH9xpnHz/vk/oqvA=)

**Comment by bcoe** [comment]
@astorije I believe the underlying issue might be that the `coverage` folder looks to be nested under the `lounge` folder -- this is a bit strange (I think I might only add the top level `./coverage` to test-exclude).

Should we be excluding it at all levels?

**Comment by astorije** [comment]
I'm not sure what you mean by that, @bcoe.

```sh
$ npm run coverage
...
$ ls -la
...
drwxr-xr-x    5 jeremie  staff   170B May 13 20:47 .nyc_output/
-rw-r--r--    1 jeremie  staff   200B Apr 28 14:23 .nycrc
drwxr-xr-x    5 jeremie  staff   170B Apr 17 23:29 coverage/
...
```

The `lounge` folder on my screenshot is the top-level folder, i.e. what you get when you run `git clone https://github.com/thelounge/lounge`.

**Comment by bcoe** [comment]
@astorije are you running an `lcov` report in the above example? I would expect the top level to look more like this:

<img width="1135" alt="screen shot 2017-05-13 at 7 00 21 pm" src="https://cloud.githubusercontent.com/assets/194609/26030689/a865b968-380e-11e7-9e32-4c09373050b4.png">

I ran the above report with JavaScript in the `coverage` folder, and it doesn't show up in the report -- it seems almost as though nyc thinks tests are being run one level above the root folder is all I can think of.

**Comment by astorije** [comment]
I'm only running `npm run coverage`, which in turn runs `nyc mocha` with [this `.nycrc` file](https://github.com/thelounge/lounge/blob/master/.nycrc) (where there is the `lcov` reporter indeed).
Sorry I'm not helping much, we don't make an extensive use of `nyc`/`istanbul` in the project yet so experience is limited.

**Comment by bcoe** [comment]
@astorije took the time to look into things a little bit for you, sorry for the slow reply.

If you add this to your exclude, `**/coverage/**`, then things should work as expected. The problem is that something in your testing configuration is changing the root folder, so that file paths are reported as `lounge/coverage/foo.js` rather than the expected `coverage/foo.js` -- not quite sure what's munging your file paths (nothing immediately jumped out at me in the project). But adding that additional exclude rule should at least work around the problem.
