### ISSUE TITLE
Coverage result different in separate runs

### ISSUE THREAD

**Issue by anasinnyk** [istanbuljs/nyc#559]
I run next command 
```bash
nyc mocha -u exports -R spec test/**/*.spec.js
```
and after this run I have a different result.
http://prnt.sc/ezg6h5
http://prnt.sc/ezg6ps
once coverage equal 100% once 50%

## Expected Behavior
Coverage will be the same on each run

## Observed Behavior
Coverage changes time by time

## Bonus Points! Code (or Repository) that Reproduces Issue
```js
import { describe, it } from 'mocha'
import { assert } from 'chai'
import * as sinon from 'sinon'
import { Mongo as MongoAdapter } from 'app/lib/adapter'

describe('MongoAdapter', () => {
  const connect = sinon.spy()
  const mongoClient = { connect: url => new Promise(resolve => resolve(connect(url))) }
  const instance = new MongoAdapter({ mongoClient })

  it('connect', async () => {
    const url = 'mongodb://mongo:27017/collection'
    await instance.connect(url)
    assert.isOk(connect.withArgs(url).calledOnce)
  })
})
```

## Forensic Information

**Operating System:** Fedora or Ubuntu
**Environment Information:** NodeJS v7.9, nyc 10.2.2:

**Comment by bcoe** [comment]
@anasinnyk could you link to the repo that is having this issue; if it's a private module, and you are unable to -- perhaps you could share just the `package.json`.

**Comment by anasinnyk** [comment]
It's not actually right now for me. Thanks
