### ISSUE TITLE
Usage is printed for valid command in travis, node 5

### ISSUE THREAD

**Issue by sudo-suhas** [istanbuljs/nyc#560]
## Expected Behavior
On running the npm command `npm test`, `cross-env NODE_ENV=test nyc --cache ava --concurrency 4`, the expected behavior, which I am able to see in my local(node versions 4, 5, 6) and on travis with node version 4 and 6 is to run tests and print the coverage. Can be seen here - https://travis-ci.org/sudo-suhas/elastic-builder/jobs/225877125

## Observed Behavior
The usage is printed out - https://travis-ci.org/sudo-suhas/elastic-builder/jobs/225865154#L1325

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/sudo-suhas/elastic-builder

**Operating System:** Ubuntu 12.04
**Environment Information:** node `v5.12.0`, npm `3.8.6`

**Comment by bcoe** [comment]
@sudo-suhas this is a very weird issue; but since this only happens in Node 5, which is not an LTS of Node I'm tempted to close this issue.

Have you seen similar behavior crop up on any newer versions of Node?

**Comment by sudo-suhas** [comment]
@bcoe I have not faced this issue on any other version of node. I also stopped running builds on node 5. You can close the issue if you want.

**Comment by bcoe** [comment]
@sudo-suhas sounds good; chalk this up to a weird historical issue with Node 5.
