### ISSUE TITLE
Issue getting results when Home folder is a different HDD than OS

### ISSUE THREAD

**Issue by bradbumbalough** [istanbuljs/nyc#561]
## Expected Behavior
Display code coverage for mocha tests.

## Observed Behavior
No files covered, only shows files with `--all` flag but no coverage.
![screen shot 2017-04-27 at 8 11 12 pm](https://cloud.githubusercontent.com/assets/9825605/25509273/b7d3ab34-2b85-11e7-9469-e49288590b26.png)

## Forensic Information

**Operating System:** MacBook Pro Late 2011, 10.12.3
**Environment Information:** `node: 6.10.0` `npm: 3.10.10`
[Link to output.txt gist](https://gist.github.com/bradbumbalough/3c416ba1b65c561ef9d48f59a4104cdb)

The same repository works on my other Mac. The only configuration change I can think of is that this mac has a secondary harddrive that the Home folders is on, while the OS runs off a SSD.

I have also tried other node versions, still doesn't work. When GitLab CI runs my tests, I see the code coverage there.

Thank you for the awesome package and any help you could offer!

**Comment by bcoe** [comment]
@bradbumbalough do you have nyc installed globally, or is it installed in your project directory?

**Comment by bradbumbalough** [comment]
I have it installed in both locations for testing... both result in the same outcome (`npm test` runs `nyc --reporter=text-summary mocha tests`). But just typing `nyc mocha tests` (with nyc and mocha installed globally) also doesn't return anything.

**Comment by bcoe** [comment]
@bradbumbalough this definitely sounds like a disk permissions issue to me; could you try running using `_mocha` rather than `mocha`; I'm curious to see if it works if a subprocess isn't spawned -- my guess is nyc is having trouble accessing your `/tmp` folder.

**Comment by bcoe** [comment]
@bradbumbalough `spawn-wrap` uses https://www.npmjs.com/package/os-homedir to guess the folder that it should write temporary information to -- check that the process you're running `npm test` with has write permission to this location.

**Comment by bcoe** [comment]
@bradbumbalough did you get a chance to check the write permissions on the folder returned by `os-homedir`?

**Comment by bradbumbalough** [comment]
It's the path to my 2nd harddrive `/Volumes/Macintosh HD2`... here's the permissions for that folder. 
![screen shot 2017-05-05 at 8 01 38 am](https://cloud.githubusercontent.com/assets/9825605/25744706/4a25f440-3169-11e7-942a-c6b7e0bcca92.png)
I had previously tried to enable write access for everyone and applied to all files... still didn't work.

I'm wondering if it has to do with my `umask` setting since the node spawn will create a folder on the home dir. Currently it's the default `022`, but I'm not sure what that should be given the configuration. I know it's not really in the scope of nyc at point, but I appreciate any help you might have. 

Thanks!

**Comment by bradbumbalough** [comment]
That was definitely the problem... unfortunatly I couldn't get it to work with my current configuration. I decided (for other reasons too) to reset my storage and keep OS and Home in same drive, using 2nd for Time Machine and large files. NYC works perfectly now!
