### ISSUE TITLE
cache directory is created even with disabled cache

### ISSUE THREAD

**Issue by lo1tuma** [istanbuljs/nyc#563]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior

The cache directory is not created when caching is disabled via CLI flag.

## Observed Behavior

NYC tries to create a `.cache` folder inside of `node_modules` which is a read-only folder in my case, so nyc crashes:

```
Error: EACCES: permission denied, mkdir '/var/jenkins_home/workspace/vice_greenkeeper-nyc-10.3.0-KYGEY35BZNVKHFVMGU26NETJXLH2N255323GM27RZYFF2EISVZGQ/node_modules/.cache'
```

## Bonus Points! Code (or Repository) that Reproduces Issue

We run nyc as a npm run-script: `nyc --cache false --all npm run test:unit`.

## Forensic Information

We use [`nix`](https://nixos.org/nix/) in our CI system to ensure having a reproducible build, hence all build artifacts (e.g. `node_modules` folder) are immutable (i.e. read-only).

**Operating System:** the operating system you observed the issue on.

Ubuntu

**Environment Information:** information about your project's environment, see instructions below:

Linux 4.2.0-23-generic
node v7.7.3
npm  v4.1.2

**Comment by lo1tuma** [comment]
This issue was introduced with nyc version `v10.3.0`.
It works fine with version `v10.2.0` or lower.

**Comment by bcoe** [comment]
@lo1tuma could you give this a shot:

`npm i nyc@next`

I think I figured out what was happening to you.

**Comment by lo1tuma** [comment]
@bcoe I’ve just tested it with version `nyc@10.3.2-candidate.0` and it works fine.
Thank you for quickly providing a fix 🍻.

**Comment by fstoerkle** [comment]
As `10.3.2` is already released, I think this can be closed now

**Comment by bcoe** [comment]
@fstoerkle @lo1tuma awesome 👍
