### ISSUE TITLE
Exclude with negation patterns broken

### ISSUE THREAD

**Issue by davewasmer** [istanbuljs/nyc#569]
## Expected Behavior

Adding an negated exclude pattern would cause nyc to run against files that match the negated exclude pattern. I.e.:

```
$ nyc -x "foo/**" -x "!foo/bar.js"
# all of ./foo/ is ignored, except for ./foo/bar.js
```

## Observed Behavior

Using the example above, nyc ignores all of `./foo/`, including (incorrectly) `./foo/bar.js`. In addition, including _any_ negation pattern in your exclude list appears to remove the default `**/node_modules/**` exclusion patterns.

## Forensic Information

**Operating System:** macOS 10.12.4
**Environment Information:** https://gist.github.com/davewasmer/9d98fb190a0080329923b8c1a2e9c303

-----

I believe I tracked it down to [this block](https://github.com/istanbuljs-archived-repos/test-exclude/blob/master/index.js#L49) in test-exclude, where it seems like you are trying to find negation patterns that would end up negating the default node_modules exclusion pattern:

```js
// I rearranged this block to make it easier to demonstrate, but it's functionally equivalent ...
var negationAllowed = !!micromatch('./node_modules/foo.js', pattern, {nonegate: false}).length;
var negationIgnored = !!micromatch('./node_modules/foo.js', pattern, {nonegate: true}).length;
var negated = negationAllowed !== negationIgnored;
```

If we run this with `!**/node_modules/**` as our pattern, we can see:

```js
var negationAllowed = !!micromatch('./node_modules/foo.js', '!**/node_modules/**', {nonegate: false}).length; // false
var negationIgnored = !!micromatch('./node_modules/foo.js', '!**/node_modules/**', {nonegate: true}).length; // true
var negated = negationAllowed !== negationIgnored; // true
```

I think the intention here was to pick up on any negated pattern applying to node_modules - if ignoring negations caused a match against `node_modules/foo.js`, then the pattern must be trying to negate node_modules.

However, a negated pattern will match _anything_ that doesn't match the pattern. So this ends up working the other way around when checking any arbitrary negated pattern:

```js
var negationAllowed = !!micromatch('./node_modules/foo.js', '!whatever', {nonegate: false}).length; // true <- this is the problem, the random negated pattern matches here
var negationIgnored = !!micromatch('./node_modules/foo.js', '!whatever', {nonegate: true}).length; // false
var negated = negationAllowed !== negationIgnored; // true
```

The end result here is that _any_ negated pattern in the `exclude` option results in:

- That pattern being removed
- The default node_modules exclude pattern being removed

Wasn't sure if I should file here or on test-exclude, since the description on that repo says that it's deprecated.

**Comment by bcoe** [comment]
@davewasmer mind opening the issue here too perhaps:

https://github.com/istanbuljs/istanbuljs/blob/master/packages/test-exclude/test/test-exclude.js#L77

better still, if you have time, a failing test would be great -- test-exclude isn't deprecated, it's just been moved into a mono-repo.

It seems like `node_modules` not being excluded by default might be a regression.

**Comment by davewasmer** [comment]
Added an issue to the istanbuljs monorepo (istanbuljs/istanbuljs#55) as well as a PR with a couple of failing test cases (istanbuljs/istanbuljs#56).
