### ISSUE TITLE
nyc 10.3.2 does not ignore typescript interface files

### ISSUE THREAD

**Issue by peterharding** [istanbuljs/nyc#570]
## Expected Behaviour
Typescript interface files are ignored when calculating coverage.

## Observed Behaviour
Typescript interface files are considered, reducing code coverage below 100%.

## Repo
This repo demonstrates the difference in behaviour between `nyc` versions `10.1.2` and `10.3.2`:
https://github.com/peterharding/nyc-typescript-interface-cover

`10.1.2`
![screen shot 2017-05-08 at 3 36 24 pm](https://cloud.githubusercontent.com/assets/4420975/25828355/9fd9126c-3404-11e7-83f0-885cffd0087d.png)
`10.3.2`
![screen shot 2017-05-08 at 3 36 32 pm](https://cloud.githubusercontent.com/assets/4420975/25828356/9fd9ee94-3404-11e7-9bed-92c6ed0d0d93.png)

`10.1.2`
![screen shot 2017-05-08 at 3 27 36 pm](https://cloud.githubusercontent.com/assets/4420975/25828360/a3d4910c-3404-11e7-8326-24403ad73c12.png)
`10.3.2`
![screen shot 2017-05-08 at 3 27 11 pm](https://cloud.githubusercontent.com/assets/4420975/25828361/a77a40ea-3404-11e7-864b-21167c8f2d57.png)

---

I think there is "nothing to test" for an interface file, so even though the warnings in version `10.1.2` were annoying, it made sense that the interface files were ignored.

Now with version `10.3.2`, the warnings are gone because the interface files are counted towards lines covered. This is incorrect in my opinion, so the point of opening this issue is to determine if this change was intentional.

**Comment by bcoe** [comment]
@peterharding I don't think it makes sense to bake logic into the instrumenter or nyc that's TypeScript specific -- and I can imagine a world where some folks test their interface file? I don't know much about typescript, is this a thing that could happen?

Is it possible to generate the interfaces in a separate location, or with a separate extension, e.g., `Fish.interface.ts`, such that an exclude rule could be added to get rid of them?

We had a bug in nyc that was failing to apply source-maps to the top-level process -- this was what was resulting in the error message and missing coverage for interface files.

**Comment by peterharding** [comment]
@bcoe TypeScript interfaces don't exist at runtime.
For example,
```TypeScript
export interface FileIO {
  readFileSync(filePath: string, encoding: string): string;
  writeFileSync(file: File, data: Buffer): void;
  // ... many other file operations
}
```
Or any other interface file will be compiled down to 
```JavaScript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=FileName.js.map
```
(or some equivalent depending on your compile options).
So I can't see a how someone *could* test their interface file, never mind *would*.

It would be possible to name all interfaces `something.interface.ts`, but this would not follow [best practices for naming interfaces](http://stackoverflow.com/questions/2814805/java-interfaces-implementation-naming-convention/2814831#2814831).

---

Ignoring TypeScript for a moment, I think this issue leads to a more general question: Should an "empty" file require coverage?

The compiled javascript above does not export anything or have any logic. Should `nyc` detect the lack of an export and ignore this file? If yes, then this would solve the interface problem at the same time 😄

**Comment by peterharding** [comment]
After thinking about this a bit, I might be able avoid the problem entirely if I run the tests on the compiled `.js` instead of using `ts-node` on the `.ts`. Will get back to you after trying this.

**Comment by peterharding** [comment]
Works for both versions of `nyc` if you run as shown here:
https://github.com/peterharding/nyc-typescript-interface-cover/tree/run_on_compiled

**Comment by JaKXz** [comment]
Perhaps `ts-node` should not write files that would be empty because they only export `interface`s? 🤔

**Comment by bcoe** [comment]
@peterharding I agree with @JaKXz, it would be nice to be able to support this use-case with `ts-node`; which I know many folks use for tests.

**Comment by peterharding** [comment]
@JaKXz @bcoe you are thinking we should open an issue for `ts-node` ?

**Comment by bcoe** [comment]
@peterharding it might be worthwhile -- maybe they'd at least have a suggestion for us; I'd like to avoid having too much domain specific knowledge in nyc about any specific test runner.

**Comment by ericmorand** [comment]
So, what's the status on this one? Did someone create an issue for ts-node?

**Comment by NearAutomata** [comment]
I had a similar issue where not all files were checked for coverage until I added `"require": ["ts-node/register"]` to the nyc configuration in `package.json`. Unfortunately though interface got checked all of a sudden and obviously had 0%. Using `"exclude": ["**/I[A-Z]*.ts"]` it was painless to filter them out. That solution however, requires that each interface is in its own source file. Otherwise you'd have some false results.

**Comment by ssk910** [comment]
I added `"require": ["ts-node/register/transpile-only"]`, inspired by @ghost. 
And removed `all` flag.
