### ISSUE TITLE
Sourcemap not resolved for uncovered files

### ISSUE THREAD

**Issue by maghis** [istanbuljs/nyc#571]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
I expect both partially covered, completely covered and non covered files to have their names resolved based on the inlined sourcemap.

## Observed Behavior
Only source files that are at least partially covered are correctly resolved, the others show the transpiled path, in all the reporters (I'm using lcov, json and text).

## Bonus Points! Code (or Repository) that Reproduces Issue
My NYC configuration:
```
  "nyc": {
    "exclude": [
      "test/build/test/**"
    ],
    "include": [
      "test/build/**"
    ],
    "reporter": [
      "json",
      "text",
      "lcovonly"
    ],
    "require": [
      "babel-register"
    ],
    "cache": true,
    "all": true
  }
```

## Forensic Information

I'm using node v7.10.0

**Comment by bcoe** [comment]
@maghis I think this would be a neat enhancement. We would need to start grabbing out the sourceMap footer, along with the coverage header from each file we walk.

**Comment by maghis** [comment]
@bcoe the strange thing is that this used to work just fine before 10.3.2

**Comment by bcoe** [comment]
@maghis could you provide an example of a project that is having this issue?

**Comment by dsole** [comment]
I've noticed that this issue does **not** occur when caching is disabled.

**Comment by bcoe** [comment]
@dsole @maghis what's supposed to happen is that when `--all` runs it requires just enough of the source-file to grab the header for tracking coverage information, but doesn't actually require the file (which would result in code executing).

The source-map logic looks for a footer in the file representing source-map information, and writes this into a cache folder -- my hunch is that perhaps the `--all` doesn't place anything in the `./node_modules/.cache` folder for the files not instrumented? which would result in the behavior @dsole is seeing (things working with cache disabled).

Would love help digging into this issue more, we have a [community slack](http://devtoolscommunity.herokuapp.com/) now if either of you feel like discussing in more detail how to debug this issue.

**Comment by maghis** [comment]
Well, I can live disabling the cache, not sure what the best behavior should be.
I tend to err on the side of correctness but I get the optimization point. When is the cache invalidated?

**Comment by bcoe** [comment]
@maghis the cache will be invalidated with any new release of nyc. It will also be invalidated if the shasum of a file being instrumetned changes.

I suggest we keep this issue open; if you can provide a minimal reproduction of the behavior you're seeing, I bet we can figure out why the source-map isn't being appropriately kicked along.

**Comment by JaKXz** [comment]
If this is still an issue with the latest version of nyc, please open a new issue with a link to a minimal reproduction repo.
