### ISSUE TITLE
Can The HTML Reporter Output Single Inline HTML Index File

### ISSUE THREAD

**Issue by gowritharanmageswarasc** [istanbuljs/nyc#572]
I was wondering if there was a way to output a single index.html file (that has all the required CSS/JS as well) when using the HTML reporter option.  Currently, since our source code is included in the Coverage JSON file, it produces sub-directories with its own index.html, CSS, JS, etc..

The use case is that I would like to upload the resulting single HTML file to a Google Could Storage bucket for anyone with access to view directly from the link.  Since GCS is not a true file system, simply uploading all the files that are produced will not work.

Is this possible to do or do you know any tools that would make this inline merge work?  Thank you for your time! Your tool is awesome btw.

**Comment by bcoe** [comment]
@gowritharanmageswarasc sorry for the slow reply! have been more busy with work and life stuff than usual over the past few months.

I like this idea! one thought that comes to mind, is that it would be nice if reports in general were more configurable -- make it easier to provide your own report.

Would love help thinking about how to implement this (and implementing it). The repo we will be working in is actually [here](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-reports).

We have a [community slack now](http://devtoolscommunity.herokuapp.com/) if you feel like talking about this feature.
