### ISSUE TITLE
Unmapped files not ignored after 10.3.0

### ISSUE THREAD

**Issue by njs50** [istanbuljs/nyc#575]
## Expected Behavior
In version 10.2.0 of nyc if a file had nothing to instrument I would see this in my console: 
```File [/Users/.../models/route.ts] ignored, nothing could be mapped``` The console message disappeared in 10.3.0 but the files continued to be ignored

## Observed Behavior
As of 10.3.1 these files are no longer ignored and now show up as 0% coverage.

## Code that Reproduces Issue
this is probably more relevant for something like typescript where we might have files that only have an interface definition. for example a ts file that only contains something like this:
```
export interface Route {
  method: 'get' | 'post' | 'put' | 'patch' | 'delete';
  path: string;
}
```
since this is really only used by the ts compiler the old behaviour of it being skipped for coverage made sense to me. I'm not sure if whatever changed was deliberate or not. Looks like perhaps it was something in 1bf74fddeffd20658423688327e4f848006d8bd0 that changed it

It's definitely something that can be worked around, but not sure if was intended or not

**Comment by bcoe** [comment]
@njs50 the old behavior was definitely a bug, and causing a variety of other issues (using `--all` was basically creating two coverage files, one with source-maps applied and one without).

We've had this discussion in another thread -- I'm not quite sure what the best solution is for typescripts's definition files (this is fairly domain specific to typescript, in general I think if it's a `.js` extension we're doing the right thing by instrumenting it).

What approach could we be using to distinguish definition files from other source files -- can we infer this from the filename somehow?

**Comment by njs50** [comment]
I think it's legit for those interfaces to be defined in a regular .ts file so there probably is no standard way to tell that it's just a type / interface definition. I think the *.d.ts are usually used for defining an interface to external js. In this case these are just internal type definitions.
 
The compiled js from one of these interfaces ends up looking something like ```"use strict";
Object.defineProperty(exports, "__esModule", { value: true });``` so I guess it produces some output, but it isn't actually referenced by anything.

It's probably not unreasonably for us to do something like name them all x.interface.ts and ignore *.interface.ts, or possibly to make them .d.ts files and have those ignored. 

I was really just wanting to check this was expected behaviour so I guess we should be good to close this. 

thanks for the quick response :-)

**Comment by bcoe** [comment]
@njs50 we've had a couple typescript folks bring up the issue ... so it's definitely unexpected behavior, please keep me posted if you figure out a good approach -- maybe we can encourage something as best practice.

**Comment by njs50** [comment]
fwiw I've moved our internal interfaces to declaration files (.d.ts), and are excluding them from coverage reporting. 

The good thing about .d.ts files is they don't produce any compiled output. Since it's not possible for code to be produced from them excluding them from coverage doesn't seem to have any downside.

this doesn't seem an unreasonable way to do things. I didn't see anything in the docs suggesting you shouldn't use them for your internal types/declarations.
