### ISSUE TITLE
Multiple sets of coverage

### ISSUE THREAD

**Issue by StoneCypher** [istanbuljs/nyc#576]
I'd like to use NYC to generate several sets of coverage, for different sets of tests, so that I can assert that unit tests have coverage, and also so that stochastic tests have coverage.

I can do this with some monkeying by just running them distinctly, but I was wondering whether NYC had any kind of support for parallel coverage, which might do a better job in reporting as a result

**Comment by bcoe** [comment]
@StoneCypher we do this ourselves in our test suite:

https://github.com/istanbuljs/nyc/blob/master/package.json#L14

You can use `--no-clean` to run a set of tests without first clearing out the `.nyc_output` folder.

**Comment by bcoe** [comment]
@StoneCypher did the `--no-clean` approach work for you?

**Comment by bcoe** [comment]
@StoneCypher feel free to open a new issue if you ran into any problems, I think with some fiddling `--no-clean` should do the trick for you 👍

**Comment by StoneCypher** [comment]
oh, i'm sorry, i thought i replied to this

the answer i had meant to give was "yes, thank you very much"

my apologies for having left this unanswered by accident

**Comment by bcoe** [comment]
@StoneCypher no worries, I'm glad you're on your feet.

**Comment by sakhi-sl** [comment]
@bcoe Can we have multiple coverage summaries for different folders? Currently it shows overcall coverage summary. Can we do it for individual folders ?
