### ISSUE TITLE
Allow .nycrc.json

### ISSUE THREAD

**Issue by bensaufley** [istanbuljs/nyc#579]
I'd like to be able to save my `.nycrc` as a `.json` file for automatic file type detection in VIM, Visual Studio Code, etc. This is a feature request, not a bug, but for consistency:

## Expected Behavior
I put my configuration, JSON-formatted, in `.nycrc.json` and `nyc` respects that configuration when I run `npm test`, which in turn runs `nyc nf mocha` (`nf` for node-foreman)

## Observed Behavior
nyc does not notice `.nycrc.json` as a configuration file (looking for `.nycrc` _only_), and falls back to default behavior.

## Bonus Points! Code (or Repository) that Reproduces Issue
My repo (with `.nycrc`, no `.json` because as stated that doesn't work) can be found [here](https://github.com/bensaufley/code-words-api).

## Forensic Information

**Operating System:** MacBook Pro, macOS 10.12.4. zsh in Terminal for my command line, to be thorough.
**Environment Information:** nvm running node 6.1.0; yarn for dependencies

**Comment by bcoe** [comment]
@bensaufley this is totally a think now \o/ thanks for helping to implement it.

I've recently setup a community slack (see README.md) if you feel like staying in touch and contributing more to these projects.
