### ISSUE TITLE
`nyc report` seems to fail when run against coverage from old versions of Istanbul

### ISSUE THREAD

**Issue by Lange** [istanbuljs/nyc#586]
I have an [unusual monorepo](https://github.com/nodecg/nodecg-obs) that consists of two packages. One package is a fairly standard npm module. The other package is a Polymer element. As you can imagine, the workflows for testing and reporting coverage for these two packages is quite different, but they do both ultimately output Istanbul coverage reports.

Because this is a monorepo, I want to merge these reports into one single report. However, `nyc report` does not seem to handle the coverage file for the Polymer element as expected.

## Expected Behavior
`nyc report` works with any Istanbul-generated coverage JSON file. In particular, the coverage for `nodecg-widget-obs` is generated by `istanbul@0.3.22`.

## Observed Behavior
`nyc report` seems to not properly account for ignored lines in these older coverage files, and the HTML reports display an error when attempting to view individual files.

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/nodecg/nodecg-obs

Run the following commands to clone the repo, run the tests, move the coverage of both projects into the top-level `.nyc_output` folder, and run a combined report:
```bash
git clone git@github.com:nodecg/nodecg-obs.git
cd nodecg-obs
npm install -g bower lerna@2.0.0-rc.5
npm install

# This will appear to hang for a while, but give it a minute.
npm test
npm run report
```

You'll get both a text report and an HTML report (in the `coverage` directory). The text report is _mostly_ accurate, but seems to not be accounting for ignored lines. The HTML report is the same, but attempting to view the coverage for individual files in the `nodecg-widget-obs` project displays the following error:
![image](https://cloud.githubusercontent.com/assets/873012/26603453/80924000-454c-11e7-86ff-7fa50bb8d0a4.png)

## Forensic Information

**Operating System:** Windows 10 x64
**Environment Information:** https://gist.github.com/Lange/a3688b2dfa68ed3460a0d58521c0442f

Thanks for your time and for this fantastic tool!

**Comment by Lange** [comment]
Update: this error also happens when using the `--reporter=text-lcov`, which prevents me from piping test results to `coveralls`: https://gist.github.com/Lange/4eed096eaf56665c03e53c086d6a1ecf

**Comment by bcoe** [comment]
@Lange unfortunately there have been some breaking changes between the Istanbul 1.x instrumentation format (which nyc uses), and the old 0.x releases of Istanbul; some of which are documented here:

https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/v0-changes.md

merging the old style and new style reports is not likely going to be possible.

**Comment by Lange** [comment]
I actually no longer have this issue, because the package I was using has updated to use a modern version of `istanbul`/`nyc` and now outputs compatible coverage data. All good!

**Comment by bcoe** [comment]
@Lange awesome 👍 hate to fail to give users a workaround, so I'm glad that this isn't blocking you any longer.
