### ISSUE TITLE
Way to tag executed lines with test identifier?

### ISSUE THREAD

**Issue by wysisoft** [istanbuljs/nyc#597]
It would be really awesome if I could tell nyc/istanbul which test is currently running, and it could tag the lines of code executed with the most recent test identifier, so I know which tests are covering which code areas. Any way to make this happen?

**Comment by wysisoft** [comment]
Also, if this gets implemented, I hope that it works with instrument, since that's what I use - instrumented .js files and selenium

**Comment by bcoe** [comment]
@wysisoft not quite sure how we'd pull this off in an elegant way; would definitely like to pull it into a module that does all the bookkeeping, and is enabled optionally, but I really like the idea!

It's kind of similar to the work @addaleax did on tracking subprocess information.

**Comment by bcoe** [comment]
would love help implementing if anyone is interested.

**Comment by wysisoft** [comment]
I might be over simplifying it, but you already have a global variable (I forget its name, something like __globalVar__), I thought you can just add a property called something like testName and whatever the current value of __globalVar__.testName is recorded along with the rest of the instrumentation information, and then its up to users like me to propertly set the __globalVar__.testName value at the start of each individual test? Is this too simple?

**Comment by bcoe** [comment]
@wysisoft sounds like this could work reasonably well, the global variable being set as tests run is `__coverage__` which has coverage information for each file; I would definitely want to only enable this with a flag, as it has the potential to slow down the overall test run.

**Comment by wysisoft** [comment]
Ya I might be alone on this but I think that actually knowing which test provides which coverage is critical for maintaining my code base, also for getting a good place to start when coverage is missing.

**Comment by wysisoft** [comment]
Keep in mind that i'm the worst developer in the world.

So i'd propose having another global object called __coverageTests__.
In instanbul's instrumenter.js, I think  nyc needs to override the AST 'cover' functions so it does another line, something like __coverageTests__.s[id] = (__coverageTests__.s[id].indexOf(__coverage__.currentTest + ';') == -1 ? __coverageTests__.s[id] + ';' : __coverageTests__.s[id]);

then in addDerivedInfoForFile you add a new variable on the coverage, __coverage__.tl (lineTests), and populate the tests for the line.

Then in the html.js detail template you add a td after the linenumber called lineTests and populate it with the values from __coverage__.tl

**Comment by bcoe** [comment]
@wysisoft I haven't thought too hard about this problem yet -- of the top of my head, I feel like you might need to modify both the testing framework and nyc to get this functionality.

What I'd be tempted to do would be to set a global variable in the test suite (assuming it's not spawning any subprocesses) which would indicate the current name of the test that's running; I would then perhaps grab __coverage__ before and after the test execution and diff the two objects -- I think this would be significantly easier than modifying the instrumenter to record this information ... it might however mean you end up writing a new module that mocha requires (or ava, tap, etc) rather than modifying nyc itself.

**Comment by JaKXz** [comment]
I'm going to close this issue for now since it's been a while - while this sounds like a cool idea it might be outside the maintainable scope of nyc for now because of the inherent complexity. I would love to be proven wrong in a PR, or even draft PR :)
