### ISSUE TITLE
Packages is N/A with cobertura report if test files is under one folder

### ISSUE THREAD

**Issue by flyHe** [istanbuljs/nyc#598]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior

Packages should be 100% with cobertura report if test files is under one folder
The right cobertura xml file should be as below (generated by istanbul directly):

<img width="1087" alt="screen shot 2017-06-07 at 4 39 47 pm" src="https://user-images.githubusercontent.com/10543919/26869803-4fa56cb0-4ba0-11e7-9a78-b27ffa459ffe.png">

## Observed Behavior

Packages is N/A with cobertura report if test files is under one folder

<img width="625" alt="screen shot 2017-06-07 at 4 21 36 pm" src="https://user-images.githubusercontent.com/10543919/26869880-a632f91c-4ba0-11e7-912e-7ed2b67dea2a.png">

<img width="1093" alt="screen shot 2017-06-07 at 4 39 54 pm" src="https://user-images.githubusercontent.com/10543919/26869811-556a3888-4ba0-11e7-8080-2bcba6889eb0.png">

## Forensic Information

**Operating System:** OS X Sierra 10.12.5
**Environment Information:** node 6.10.3, npm 3.10.10

**Comment by flyHe** [comment]
- [ ] ResourceAdapters 

- [ ] Resources

**Comment by JaKXz** [comment]
@flyHe thank you for reporting this, but I think it belongs in https://github.com/istanbuljs/istanbuljs/issues.

My completely blind guess is that the [cobertura reporter](https://github.com/istanbuljs/istanbuljs/blob/8c4a22f/packages/istanbul-reports/lib/cobertura/index.js) needs to print something when you do not have multiple subfolders for the Resource name. I could be misunderstanding this, however, so please feel free to reopen this issue & submit a failing test in that repo! :)

**Comment by flyHe** [comment]
@JaKXz moved to https://github.com/istanbuljs/istanbuljs/issues/66
