### ISSUE TITLE
nyc@11.0.2 does not work with babel-register and spawn

### ISSUE THREAD

**Issue by mysticatea** [istanbuljs/nyc#599]
Please use the template provided below, when reporting bugs:
-----

`nyc@11.0.2` seems to fail `child_process.exec` with `--require babel-register`. Example: https://travis-ci.org/mysticatea/cpx/jobs/241057845#L891

```console
$ nyc --require babel-register npm run -s _mocha
```

## Expected Behavior

No errors.

## Observed Behavior

The following error looks to be thrown from `spawn-wrap` of `nyc`.

```
SyntaxError: /home/travis/.node-spawn-wrap-2050-e08970c6c6a6/node: 'return' outside of function (120:2)
    118 |   debug('no main file!', args)
    119 |   foregroundChild(node, args)
  > 120 |   return
        |   ^
    121 | }
    122 | 
    123 | // If there are execArgv, and they're not the same as how this module
      at Parser.pp$5.raise (/home/travis/build/mysticatea/cpx/node_modules/babel-register/node_modules/babel-core/node_modules/babylon/lib/index.js:4454:13)
      at ...
```

## Bonus Points! Code (or Repository) that Reproduces Issue

- https://travis-ci.org/mysticatea/cpx/jobs/241057845#L891

## Forensic Information

**Operating System:**

- Linux (Travis CI), and OSX (Travis CI), and Windows 7.

**Environment Information:**

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

```
'sh' is not recognized as an internal or external command,
operable program or batch file.
```

My machine is Windows :smile:
Please see Travis CI log about environment.

**Comment by mysticatea** [comment]
After I pinned `nyc` at `11.0.1`, this problem disappeared.

**Comment by bcoe** [comment]
@mysticatea the only difference between `11.0.1` and  `11.0.2` was that [spawn-wrap](https://github.com/tapjs/spawn-wrap) was upgraded.

I can't seem to immediately reproduce the issue myself:

`./node_modules/.bin/nyc --require babel-register --reporter=html node lib/yarsay.js `

can you provide a repo of the specific problem, also it would be helpful if you opened a pull request on the spawn-wrap repository.

**Comment by mysticatea** [comment]
I said at the first of samary: "nyc@11.0.2 seems to fail `child_process.exec` with `--require babel-register`."
`lib/yarsay.js` looks to not use `child_process.exec`.

This is a simple repro code:

```js
// test.js
const exec = require("child_process").exec

if (process.argv[2] !== "child") {
  console.log("parent")
  exec(`node "${process.argv[1]}" child`, { stdio: "inherit" }, (err) => {
    console.error(err)
  })
}
else {
  console.log("child")
}
```

```console
$ ./node_modules/.bin/nyc --require babel-register node test.js
```

**Comment by jeffijoe** [comment]
Running into this when testing with AVA which uses Babel.

**Comment by bcoe** [comment]
@jeffijoe @mysticatea see: https://github.com/tapjs/spawn-wrap/pull/58

**Comment by bcoe** [comment]
@hzoo is the inability to return at the top level intentional on babylon's part; trying to figure out whether @isaacs and I should fix this in spawn-wrap or Babylon?

**Comment by bcoe** [comment]
@jeffijoe @mysticatea please give this a try:

`npm i nyc@next`

the next release of nyc lands a fix for this.

**Comment by mysticatea** [comment]
Thank you. I confirmed that `nyc@next` fixed this issue.

**Comment by toddpi314** [comment]
Confirmed this resolves issue for me too, different reproduction scenario revolving around spawn.
