### ISSUE TITLE
Line highlighting of HTML report seems not right

### ISSUE THREAD

**Issue by kyasbal-1994** [istanbuljs/nyc#600]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior

Reporting HTML should be generated correctly.

## Observed Behavior

![](https://i.gyazo.com/bfc02bc9f90501d6f8ab522a3160f871.png)

This appearance seems not right color on highlighting colors on source codes. But, colored band just next to line number seems correct. 

I thought this problem was caused by wrong source map generated from our script. But, source map for generated plain ES5 javascript was also wrong.

(NOTE: This problem was originally reported by @moajo who is contributor of our repository. I translated his issue for reporting)

## Bonus Points! Code (or Repository) that Reproduces Issue

This is my project using nyc but a little bit huge to use reproduce.
https://github.com/GrimoireGL/GrimoireJS

## Forensic Information

**Operating System:**  OS X
**Environment Information:**
My coverage calculation script written in package.json
`"coverage": "nyc --reporter=lcov --reporter=text --reporter=json npm run test && remap-istanbul -i coverage/coverage-final.json -o coverage/html-report -t html"`

**Comment by bcoe** [comment]
@kyasbal-1994 nyc has built in source-map support, for starters I would definitely remove running `remap-istanbul`.

**Comment by kyasbal-1994** [comment]
@bcoe Thanks. I would try later. I will close this issue once this problem being solved.
