### ISSUE TITLE
Problems with --all

### ISSUE THREAD

**Issue by marshmellow1328** [istanbuljs/nyc#603]
## Background
I'm using TypeScript with Jasmine. The only way I figured out how to get nyc to work with Jasmine was to point Jasmine at the transpiled tests. Using `sourceMap`, the coverage report looks good until I add `"all: true"` in my nyc config.

Tests are run using `npm test` which runs `nyc jasmine`. The nyc config in package.json looks like:

```json
  "nyc": {
    "all": true,
    "extension": [
      ".ts"
    ],
    "include": [
      "dist/src/**/*"
    ]
  }
```

## Expected Behavior
I would expect both the files loaded in tests and the files without any coverage to be mapped to their TypeScript source.

## Observed Behavior
The files which aren't loaded by tests report their JS versions instead of the TS versions I'd expect. The files being loaded in tests still report against the TS version.

## Bonus Points! Code (or Repository) that Reproduces Issue
I can't share the repo, but if this is being a problem to recreate I could create a dummy repo with the same setup.

## Forensic Information

**Operating System:** Ubuntu 16.04
**Environment Information:** 
sh -c 'node --version; npm --version; npm ls' > output.txt
https://gist.github.com/marshmellow1328/b086ec34ac8ea8521c23bed60ed59329

**Comment by sublimeye** [comment]
Bump up!

**Comment by sublimeye** [comment]
@marshmellow1328 Try to change included folder from "dist/src/**/*" to `**/dist/src/**` and leave the same configuration.
Here is my config that works fine for me. *But I have an assumption that all you need to do is change the path in `include`

```
  "nyc": {
    "include": [
      "**/shared/**"
    ],
    "all": false,
    "cache": true,
    "sourceMap": false,
    "instrument": false,
    "require": [
      "babel-register"
    ],
    "report-dir": "./tests-report",
    "reporter": [
      "html",
      "lcov",
      "text"
    ]
  }
```

**Comment by sgronblo** [comment]
"Problems with --all" is a bit vague but I'm having a similar issue.

I have the following mocha.opts:

```
--ui tdd
--recursive
--compilers ts:ts-node/register
--timeout 5000
```

The following options for nyc in package.json:

```
  "nyc": {
    "extension": [
      ".ts",
      ".tsx"
    ],
    "exclude": [
      "build/**",
      "test/**/*.ts",
      "**/*.d.ts"
    ],
    "all": true
  },
```

I run `./node_modules/.bin/nyc mocha ./test/unit` and unfortunately the `all` doesn't seem to work with the defined extensions (.ts and .tsx). I currently have a couple of .ts files in my ./src/ directory that I expect should show up with 0% coverage.

**Comment by bcoe** [comment]
@sgronblo @sublimeye @marshmellow1328 sorry for the slow reply, have been dealing with some personal issues and have been an abysmal OSS maintainer the past few months.

For starters, I would make sure that you configure it so `nyc` requires `ts:ts-node/register` rather than mocha; you can do this using nyc's `require` configuration; this way `--all` will properly understand TypeScript syntax.

Otherwise, perhaps @JaKXz can chime in who's done more work with TypeScript than myself.

**Comment by ciekawy** [comment]
currently I'm able to run `ts-node/register` on mocha level rather than with `nyc` (as otherwise running pure mocha without nyc won't work).

see also:
https://github.com/istanbuljs/nyc/issues/618
https://github.com/istanbuljs/nyc/issues/610

**Comment by bcoe** [comment]
@ciekawy `--all`  will not work properly if   `ts-node/register` is required at the mocha level rather than the nyc level, because when `nyc` requires files it won't understand the TypeScript syntax.

This might be a good starting point for debugging your projects, if you're finding you're unable to have nyc instrument the require statement.

**Comment by juanpicado** [comment]
@ciekawy @bcoe could you share your set up for `ts/node/register`. I'm getting empty coverage using `--all` and the tool works randomly in different machines using the same set up.

**Comment by bcoe** [comment]
@mohsen1 do you still have a functional configuration that works with `--all` that you could share?

Is this [tutorial](https://istanbul.js.org/docs/tutorials/typescript/) up to date? there have been a few modifications around how we resolve sourcemaps, and I'm wondering if we might have broken anything.

**Comment by ciekawy** [comment]
as mentioned https://github.com/istanbuljs/nyc/issues/610#issuecomment-319097645 the key change for me was to use ES5 target. To do it just for test I'm using
```
TS_NODE_COMPILER_OPTIONS='{"rootDir": "./", "target":"es6"}' nyc npm run test:unit
```

**Comment by johan13** [comment]
I have encountered a similar problem.

I get a correct coverage report for all files that are used by the unit tests. Files that are not covered at all are not included in the report. When I add `"all": true`, then the uncovered typescript file is included in the report. So far so good! But in the uncovered file, the wrong lines are highlighted as uncovered. It looks as if the line/row is from the transpiled javascript file and not from the original typescript. It as if source maps aren't used.

If I add a `require("unused-file");` so that the file is executed (but no functions are tested) then the coverage report is correct.

Is this the same problem as described here? Did you find a workaround?

**Comment by SanderDeWaal1992** [comment]
We have the same problem as the original issue from @marshmellow1328. 

We don't want to make use of `ts-node/register` because we want to be able to modify the (by ts generated) js files before we use them as input for Mocha/nyc. So we don't have set nyc to require `ts-node/register`.

Any solution/workaround available?

**Comment by squidfunk** [comment]
We're experiencing a similar issue. When adding `"all": true` to our `.nycrc`, code coverage report generation exhibits non-deterministic behavior - sometimes it reports the correct numbers and correct source mappings, sometimes numbers and source mappings are off, roughly in 50% of the cases.

Sometimes it's correct:

<img width="862" alt="bildschirmfoto 2018-03-29 um 15 04 07" src="https://user-images.githubusercontent.com/932156/38090338-8d5c0d16-3362-11e8-8400-688c84a24a45.png">

... and sometimes it's wrong:

<img width="864" alt="bildschirmfoto 2018-03-29 um 15 01 20" src="https://user-images.githubusercontent.com/932156/38090277-6a719ba4-3362-11e8-8042-c76130f29f59.png">

While some files that have 100% coverage suddenly start reporting lower coverage values and wrong source mappings, other files that are part of the report still report correct numbers and source mappings. When we remove `"all": true`, coverage reports are correct 100% of the time. This is how we invoke our tests (TypeScript):

``` sh
$(npm bin)/nyc $(npm bin)/ts-node --require tsconfig-paths/register tests/index.ts
```

Our current "solution" is to remove `"all": true`.

**Comment by ericmorand** [comment]
Why has it been closed? Was it ever fixed?

**Comment by coreyfarrell** [comment]
It was originally closed by the stale bot which was initially a bit aggressive.  That said I believe the issue with `--all` is fixed in nyc 15 (currently in beta).  See #1104 for information about the new release.

**Comment by hari-007** [comment]
#### No matter what, current latest version of **`nyc: 14.1.1`**  always displays my test coverage for my jasmine tests for compiled typescript:


```TEXT
Executed 178 of 178 specs SUCCESS in 3 secs.
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 test.js  |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|

my-company-project@1.18.0-0 posttest my-fs-location nyc report -e .ts --reporter=text-summary

==== Coverage summary ===========

 Statements   : 100% ( 9/9 )
 Branches     : 100% ( 0/0 )
 Functions    : 100% ( 0/0 )
 Lines        : 100% ( 9/9 )

 ==============================
```

That above test.js is my jasmine configuration. This project has istanbul test coverage

- Changed or modified or added all the below .nycrc configuration
- Took entire .nycrc to package.json
- Added or removed or changed values of **`cahce`**, **`all`**, **`sourceMap`**, **`instrument`**, **`temp-dir`** and **`extension`**
- **I feel .nycrc is not at all considering by both** **15.0.0-beta** and **14.1.1** versions. Cause I need to provide -e , -X --report, --reporter in npm commands. If not, report and coverage not genrating with .nycrc 


And this is how my **`.nycrc`** file looks
```JSON
{
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "require": ["ts-node/register"],
    "check-coverage": true,
    "all": true,
    "cache": false,
    "extension": [".ts"],
    "exclude": ["testing/**", "bin.js", "build/testing/**", "node_modules/**", "coverage",  "newrelic.js",  "**/*.d.ts, **/*.spec.ts"],
    "include": ["app/**", "bin/**"],
    "reporter": ["lcov", "text"],
    "sourceMap": true,
    "instrument": true,
    "temp-dir": "./coverage/.nyc_output"
  }
}
```

#### But with just adding **`nyc:15.0.0-beta`**, somehow generated terminal report _(not coverage report of coverage/coverage/index.html)_  looks like satisfying **ancient**  istanbul way of terminal report 

```TEXT
Executed 178 of 178 specs SUCCESS in 3 secs.
---------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
All files                  |   82.57 |     65.9 |   73.71 |   81.97 |
 app                       |   96.51 |       75 |   94.12 |    96.1 |
  app.ts                   |   95.59 |       75 |   94.12 |   95.45 | 54,116,128
  index.ts                 |     100 |      100 |     100 |     100 |
 app/common                |   88.91 |    68.06 |    87.5 |   88.54 |
  agent.ts                 |     100 |      100 |     100 |     100 |
  config.ts                |     100 |      100 |     100 |     100 |
  context.ts               |   86.39 |    66.67 |   81.25 |      86 | 88,125,127,128,129,158,159,160,177,179,181,184,238,264,272,291,362,363,365,366,371
  date.ts                  |     100 |      100 |     100 |     100 |
  environment.ts           |     100 |      100 |     100 |     100 |
  globalKey.ts             |     100 |      100 |     100 |     100 |
  index.ts                 |     100 |      100 |     100 |     100 |
  jwt.ts                   |   95.16 |    85.19 |      96 |   94.64 | 97,125,142
  log.ts                   |   73.86 |    39.47 |   76.67 |   73.26 | 33,34,35,36,38,39,40,41,42,43,44,48,57,80,81,82,83,140,141,143,180,192,195
  status.ts                |     100 |      100 |     100 |     100 |
  tenant.ts                |     100 |       75 |     100 |     100 | 44,48,77
 app/common/cache          |   98.39 |      100 |   95.65 |   98.15 |
  app.ts                   |   98.15 |      100 |   95.45 |   97.83 | 65
  index.ts                 |     100 |      100 |     100 |     100 |
  types.ts                 |     100 |      100 |     100 |     100 |
 app/common/cache/adapter  |     100 |       80 |     100 |     100 |
  abstract.ts              |     100 |      100 |     100 |     100 |
  index.ts                 |     100 |      100 |     100 |     100 |
  lru.ts                   |     100 |       80 |     100 |     100 | 9
 app/common/error          |   98.86 |       50 |   88.89 |   98.39 |
  context-error.ts         |     100 |      100 |     100 |     100 |
  error.ts                 |     100 |       70 |     100 |     100 | 4,5
  index.ts                 |     100 |      100 |     100 |     100 |
  jwt-error.ts             |     100 |      100 |     100 |     100 |
  middleware-error.ts      |     100 |      100 |     100 |     100 |
  nephos-error.ts          |     100 |      100 |     100 |     100 |
  unknown-error.ts         |     100 |      100 |     100 |     100 |
  utility-error.ts         |   90.91 |        0 |      50 |   88.89 | 12
 app/common/middleware     |   81.14 |    66.32 |   77.88 |   81.14 |
  debug.ts                 |      90 |       75 |     100 |    87.5 | 8
  health.ts                |     100 |       75 |     100 |     100 | 7
  index.ts                 |     100 |      100 |     100 |     100 |
  middleware.ts            |     100 |      100 |     100 |     100 |
  parsers.ts               |     100 |       50 |     100 |     100 | 8,14
  preview.ts               |   95.65 |       50 |      80 |   95.24 | 14
  route-security.ts        |     100 |      100 |     100 |     100 |
  rtm.ts                   |     100 |      100 |     100 |     100 |
  security.ts              |     100 |    71.43 |     100 |     100 | 19,23,33,41
  tenant.ts                |   97.78 |    84.62 |     100 |   97.56 | 59
  token.ts                 |   70.68 |    63.27 |   69.01 |   71.28 | ...,175,176,180,205,272,290,292,293,294,302,303,304,305,306,309,311,312,313,315,317,318,319,321,324,325,326,327,328,329,332,337,339,342,356,357,358,361,362,363,377,382,383,418,419,420,421,450,451,452,453,454,455,456,457,458,459,460,462,464,466,468,469,470,472,479,480,494,495,497,558,665,679
 app/common/nephos         |   94.12 |    76.03 |    87.5 |   93.81 |
  auth.ts                  |   94.79 |    79.07 |   92.31 |   94.74 | 173,174,182,184,257
  index.ts                 |     100 |      100 |     100 |     100 |
  jwt.ts                   |   92.31 |       50 |     100 |   91.67 | 61
  service.ts               |   93.33 |    72.41 |   83.33 |   92.86 | 80,91,92,94,95,195,203
 app/common/nephos/svc     |   69.73 |    55.56 |   53.23 |   68.82 |
  account.ts               |   58.18 |    29.41 |   53.85 |      60 | 43,44,45,46,49,67,68,69,102,116,117,118,151,164,165,178,179,192,193,195
  cart.ts                  |     100 |       75 |     100 |     100 | 15
  content.ts               |   68.42 |       50 |   66.67 |   64.71 | 32,33,39,43,44,52
  index.ts                 |     100 |      100 |     100 |     100 |
  paidProgram.ts           |   76.92 |       75 |      75 |   72.73 | 31,32,33
  permission.ts            |   66.67 |       50 |      50 |   63.16 | 40,56,57,58,74,75,77
  session-ipa.ts           |   72.13 |       75 |   41.38 |   71.19 | 64,88,92,95,105,111,112,116,120,124,128,134,135,139,143,144,154
 app/common/nephos/utility |   65.42 |    60.09 |    58.7 |   64.38 |
  cache.ts                 |   49.09 |    41.46 |   47.06 |      48 | ...,117,127,130,131,132,134,135,136,137,160,168,169,170,171,193,194,196,197,200,201,203,204,207,208,210,211,212,217,218,220,221,246,248,250,263,266,267,269,270,291,293,300,317,318,323,324,325,331,340,342,344,347,348,350,351,355,366,368,370,371,372,373,375,378,396,399,400,401,402,403,404,406
  custom-message.ts        |   58.82 |    33.33 |    37.5 |      60 | 28,40,41,42,43,45
  custom-node-common.ts    |   85.29 |    72.59 |   81.82 |   83.87 | 45,71,152,160,195,196,197,210,212,213,214,216,217,222,224,237,249,270,272,274
  index.ts                 |     100 |      100 |     100 |     100 |
 app/init                  |   83.33 |       75 |   66.67 |   82.76 |
  process.ts               |   76.19 |       75 |   66.67 |      75 | 17,18,23,24,36
  startup.ts               |     100 |      100 |     100 |     100 |
 app/lib                   |     100 |      100 |     100 |     100 |
  basic-auth.ts            |     100 |      100 |     100 |     100 |
  body-parser.ts           |     100 |      100 |     100 |     100 |
  bunyan.ts                |     100 |      100 |     100 |     100 |
  cookie-parser.ts         |     100 |      100 |     100 |     100 |
  crypto.ts                |     100 |      100 |     100 |     100 |
  csurf.ts                 |     100 |      100 |     100 |     100 |
  express.ts               |     100 |      100 |     100 |     100 |
  helmet.ts                |     100 |      100 |     100 |     100 |
  jsonwebtoken.ts          |     100 |      100 |     100 |     100 |
  lodash.ts                |     100 |      100 |     100 |     100 |
  lru-cache.ts             |     100 |      100 |     100 |     100 |
  moment.ts                |     100 |      100 |     100 |     100 |
  morgan.ts                |     100 |      100 |     100 |     100 |
  nconf.ts                 |     100 |      100 |     100 |     100 |
  newrelic.ts              |     100 |      100 |     100 |     100 |
  prom-client.ts           |     100 |      100 |     100 |     100 |
  request.ts               |     100 |      100 |     100 |     100 |
  statuses.ts              |     100 |      100 |     100 |     100 |
  useragent.ts             |     100 |      100 |     100 |     100 |
  uuid.ts                  |     100 |      100 |     100 |     100 |
 bin                       |   66.67 |      100 |       0 |   66.67 |
  index.ts                 |   66.67 |      100 |       0 |   66.67 | 15,16,18,20,22,47,48
 bin/helpers               |   52.17 |       25 |    12.5 |   51.11 |
  cleanup.ts               |   42.86 |        0 |       0 |   42.86 | 6,7,8,9
  docker.ts                |      60 |        0 |      25 |   55.56 | 9,10,11,15
  rollup.ts                |   68.75 |      100 |       0 |   68.75 | 57,58,63,64,65
  token.ts                 |   30.77 |       50 |   16.67 |   30.77 | 12,13,14,15,17,18,19,20,21
---------------------------|---------|----------|---------|---------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

> iris-node-common@1.18.0-0 posttest /Users/jujha001/Documents/staples/projects/platform-common/node-common
> nyc report -e .ts  -x "**/*.spec.ts" --reporter=text-summary


=============================== Coverage summary ===============================
Statements   : 82.64% ( 1738/2103 )
Branches     : 65.98% ( 636/964 )
Functions    : 73.93% ( 397/537 )
Lines        : 82.05% ( 1582/1928 )
================================================================================
```


#### Again **`coverage/Icov-report/index.html`** is not generating html coverage with 15.0.0

<img width="2012" alt="Screen Shot 2019-12-04 at 1 17 10 PM" src="https://user-images.githubusercontent.com/5758223/70170412-a2c7d000-169a-11ea-84ec-f4210817ed71.png">

@coreyfarrell : I hope you have a solution for this. If not, please consider my use case for **15**  release.

My Environment:
- Node: v10.16.3
- npm: 6.13.1
- OS: macOS Mojave (10.14.6)

**Comment by coreyfarrell** [comment]
@hari-007 On quick look at what you've posted `.nycrc` should not have settings in an `nyc` key.  The following in how `.nycrc` would need to be written to enable `all`:
```js
{
  "all": true
}
```

Beyond this please open a new issue including all required information.  Given limited time of maintainers smaller reproduction repositories will get looked at faster than a large repository.
