### ISSUE TITLE
NYC doesn't work well with PM2

### ISSUE THREAD

**Issue by nadavye** [istanbuljs/nyc#604]
Please use the template provided below, when reporting bugs:
-----
Here in Sealights, we develop a SAAS quality dashboard that shows among the rest Coverage Information for end-2-end tests.

As part of the development of our NodeJS agent, we are using NYC and we have noticed that it doesn't play well with PM2. We have issues with its Cluster Mode & Logs of the application under test.

## Expected Behavior
PM2 supports "Cluster Mode" which allow several node JS processes to share the same port number.
When used with NYC, it is expected that the functionallity work as useusal, meaning, allow to start few instances of the same microservice on the same network port.

In addition, when using "pm2 logs" we expect to see the logs of the application under test.

## Observed Behavior
1. Only a single instance of the microservice is loaded successfully. Other instances get 'port already in use' message.
2. Using "pm2 logs" shows no output of the application under test.

## Forensic Information

**Operating System:** the operating system you observed the issue on.
CentOS Linux release 7.2.1511 (Core)

**Environment Information:** information about your project's environment, see instructions below:

v6.5.0
5.0.3
@sealights/sl-cloud-api-gateway@1.0.169 /opt/sealights/node_modules/@sealights/sl-cloud-api-gateway
├── UNMET DEPENDENCY @sealights/sl-cloud-infra@^1.0.311
├── UNMET DEPENDENCY @sealights/swagger-restify@^1.1.1
├── UNMET DEPENDENCY @types/mongodb@^2.1.37
├── UNMET DEPENDENCY @types/mongoose@^4.7.3
├── UNMET DEPENDENCY columnify@^1.5.4
├── UNMET DEPENDENCY jsonwebtoken@^7.1.7
├── UNMET DEPENDENCY jwk-to-pem@^1.2.6
├── UNMET DEPENDENCY md5@^2.2.1
├── UNMET DEPENDENCY on-finished@^2.3.0
├── UNMET DEPENDENCY on-headers@^1.0.1
├── UNMET DEPENDENCY request@^2.74.0
├── UNMET DEPENDENCY restify@^4.0.3
└── UNMET DEPENDENCY restify-jwt@^0.4.0

**Comment by nadavye** [comment]
Please note that when istanbul was used (without nyc) everything worked correctly. I assume it is related to 'spawn-wrap'?

**Comment by jamestalmage** [comment]
spawn-wrap would be my first suspect as well. I've never seen it used in clusters.

I would try implementing a no-op spawn-wrap wrapper,  and use it to wrap some trivial cluster implementation. If stuff breaks, we know this needs to be fixed up stream

**Comment by nadavye** [comment]
@jamestalmage  - thanks for your answer. So basically, you suggest that I'll implement the no-op spawn, replace the module in the node_modules so nyc will pick it up and try to run the cluster?

**Comment by bcoe** [comment]
@nadavye @jamestalmage If you isolate the problem to `spawn-wrap`, I'd be happy to introduce a `--no-spawn-wrap` flag to nyc that disables it for you; just let me know where you ended up debugging this issue.

**Comment by RoniSegal** [comment]
Hi, any chance someone looked into this?

**Comment by nadavye** [comment]
Hi Guys,
Any update on this?
Have you had a chance to look at @RoniSegal  reproduction?

**Comment by nadavye** [comment]
Ping

**Comment by nadavye** [comment]
Guys, is there a chance to get some info about how to add this flag? Which area should be modified?
It will allow us to try and resolve that by ourselves.
