### ISSUE TITLE
Istanbul not going through re-exported defaults.

### ISSUE THREAD

**Issue by Lube** [istanbuljs/nyc#606]
## Expected Behavior
Istanbul discovers and checks coverage on re exports

## Observed Behavior
![nyc](https://user-images.githubusercontent.com/4809248/27090629-23013656-5034-11e7-8781-eca217e0dbff.png)

## Forensic Information

https://gist.github.com/Lube/2e5883672d88dddc5ab435e4f368723d

Files re-exported (src/models/repositories/index.js)
```javascript
export { default as User } from './user'
export { default as Spot } from './spot'
export { default as Zone } from './zone'
export { default as Agenda } from './agenda'
export { default as Driver } from './driver'
export { default as Reservation } from './reservation'
export { default as Infraction } from './infraction'
export { default as ParkingRecord } from './parkingRecord'
export { default as Vehicle } from './vehicle'
```

**Comment by bcoe** [comment]
@Lube would you be able provide a minimal reproduction for this issue in a repo? Don't 100% follow what's happening.

**Comment by JaKXz** [comment]
Hi @Lube sorry this was left alone for so long - I'm curious, in your tests are you `require`ing or `import`ing the objects from `src/models/repositories` or from each of the individual files? e.g. `import Vehicle from './vehicle'`? I think for proper coverage reporting from your unit tests you will need to do the latter

**Comment by coreyfarrell** [comment]
Closing as we cannot take any action without the requested minimum reproduction.
