### ISSUE TITLE
New not covered function error, and it can't be suppressed ...

### ISSUE THREAD

**Issue by eisbehr-** [istanbuljs/nyc#608]
Since switching from `istanbul` to `nyc` the reposrt complains about not covered functions. I'm not able to remove this message in the HTML output. In the snippet below you see the error. There is of course no test for an anonymous function.

![func](https://user-images.githubusercontent.com/917005/27133609-0b8ba26a-5113-11e7-8b62-be543d289118.PNG)

I had the idea to suppress this message with `istanbul ignore next`, but this is only possible for the whole block. And thats not good too. I even don't understand why it's only complaining about the `info` row, but not about the `debug` one?!

**Not working:**
```JS
this.mailer = sendmail({
    logger: {
        // put debug and info logs into nowhere
        debug : () => {},
        // istanbul ignore next
        info  : () => {},
        warn  : log.warn,
        error : log.err
    },
    silent: false
});
```

**Not working too:**
```JS
this.mailer = sendmail({
    // istanbul ignore next
    logger: {
        // put debug and info logs into nowhere
        debug : () => {},
        info  : () => {},
        warn  : log.warn,
        error : log.err
    },
    silent: false
});
```

**Working, but will ignore the whole block:**
```JS
// istanbul ignore next
this.mailer = sendmail({
    logger: {
        // put debug and info logs into nowhere
        debug : () => {},
        info  : () => {},
        warn  : log.warn,
        error : log.err
    },
    silent: false
});
```

**Comment by bcoe** [comment]
@eisbehr- the way that the tree is walked during instrumentation has changed slightly, but this should do the trick for you:

```js
this.mailer = sendmail({
    logger: {
        // put debug and info logs into nowhere
        debug :
          /* istanbul ignore next */
          () => {},
        info  :
          /* istanbul ignore next */
          () => {},
        warn  : log.warn,
        error : log.err
    },
    silent: false
});
```

You just need to make sure that the ignore stanza immediately proceeds the function definition.
