### ISSUE TITLE
support for per-each file coverage check

### ISSUE THREAD

**Issue by ciekawy** [istanbuljs/nyc#611]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
support to provide and require thresholds per-each file like in
https://github.com/gotwarlost/istanbul/issues/30

## Observed Behavior
not possible to define per-each file coverage checks 

## Forensic Information
I believe this is just not supported yet so skipping following sections, can add this info anytime

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

**Comment by ciekawy** [comment]
seems like this can be relatively simple to implement by enhancing NYC::checkCoverage https://github.com/istanbuljs/nyc/blob/213206f03a35472fc894e7feb10044aa79df3e50/index.js#L444

**Comment by JaKXz** [comment]
I think this is addressed in #591.

**Comment by ciekawy** [comment]
Looks like exactly what I was looking for. Thanks @JaKXz for pointing this out!

**Comment by bcoe** [comment]
@ciekawy this feature is now landed 👍

**Comment by mkonikov** [comment]
Is there a way to do it both per file and globally like it was done previously in Istanbul?
https://github.com/gotwarlost/istanbul/blob/master/test/cli/sample-project/config-check-mixed.istanbul.yml

Can this be set in an `.nycrc` file?

**Comment by mkonikov** [comment]
I see this was outlined here - https://github.com/istanbuljs/nyc/issues/468 - but doesn't seem possible yet.
