### ISSUE TITLE
tap-nyc

### ISSUE THREAD

**Issue by MegaArman** [istanbuljs/nyc#613]
So this isn't really an issue, but  I just wanted to share a TAP output formatter I released today called tap-nyc. It's meant to be used with nyc to produce condensed output for test failures/success. I've only tested on Linux w/ TapeJS, but it should work with any TAP producing test framework to my knowledge.  Check it out and if you like it, please feel free to include it in the nyc readme and/or website.

https://github.com/MegaArman/tap-nyc
https://www.npmjs.com/package/tap-nyc

nyc rocks

**Comment by bcoe** [comment]
@MegaArman cool! curious, how did nyc misbehave when used with tape?

**Comment by MegaArman** [comment]
nyc + tape alone works OK, but produces too much output to fit on my screen without zooming out a bunch, for example:

![](https://raw.githubusercontent.com/MegaArman/npm_images/master/nyctapealone.png)

With other existing TAP formatters (ex: faucet, so nyc + tap + faucet), the output from nyc is not shown:

![](https://raw.githubusercontent.com/MegaArman/npm_images/master/nyctapefaucet.png)

With tap-nyc things are nicer:

![](https://raw.githubusercontent.com/MegaArman/npm_images/master/tapnyc.png)

**Comment by bcoe** [comment]
@MegaArman I appreciate this work 👍 perhaps you could send an update to the README.md that points folks at this solution who are testing using tape?

**Comment by MegaArman** [comment]
Woohoo, sure thing. I'll do that soon.

**Comment by bcoe** [comment]
@MegaArman landed your PR 👍 thanks for the contribution.

**Comment by snuggs** [comment]
@bcoe @MegaArman this is awesome work. Already using `tap-nyc`(and NYC for that matter) in build pipeline! A Godsend 🙏 .  https://github.com/devpunks/snuggsi/tree/master/bin#test-runner
