### ISSUE TITLE
No coverage with express-openapi

### ISSUE THREAD

**Issue by guillaumeblaquiere** [istanbuljs/nyc#621]
## Expected Behavior
When I run a mocha rest api test on my server, all the called JS appear as covered in report

## Observed Behavior
On the server initialization appear as covered. No coverage for API call. I think it's because of indirection in openapi initialization and no explicit route (only deduce from project structure)

## Bonus Points! Code (or Repository) that Reproduces Issue

the express app server is started like that:
~~~~
...
this.app = express();
...
const buildApiFolder = './build/api';
const buildApiFolderGlob = join(buildApiFolder, '**', '*.js');
    const files = await glob(buildApiFolderGlob);
    const openApiPaths = files
      .filter(file => !file.match(/\.spec\.js/) )
      .map(file => file.replace(/\.js$/, ''))
      .map(file => {
        return {
          path: '/' + relative(buildApiFolder, file).replace(/\\/g, '/'),
          module: require(join(process.cwd(), file)),
        };
      });
    const openapi = Openapi.initialize({
      paths: openApiPaths,
      app: this.app,
      apiDoc,
      consumesMiddleware: {
        'application/json': checkBodyValidity,
      },
    });
    this.openApiSpec = openapi.apiDoc;

    this.app.use(swaggerUI(this.openApiSpec));
...
~~~~
## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:
~~~~
C:\Projets\dev\web_api_nodejs>node --version
v6.11.0

C:\Projets\dev\web_api_nodejs>npm --version
3.10.10
~~~~

**Comment by JaKXz** [comment]
Sorry for the late reply - do you have a repo that can reproduce this issue? Is it still occurring with the latest version of nyc?
