### ISSUE TITLE
Unable to get coverage data using Mocha

### ISSUE THREAD

**Issue by scaljeri** [istanbuljs/nyc#624]
When using

    $> cross-env NODE_ENV=test  nyc --require babel-register mocha

the unit tests runs fine, but the coverage seems incorrect:

![image](https://user-images.githubusercontent.com/1078741/27862733-0d244dd2-6187-11e7-9f64-3ee1e1967284.png)

On [stackoverflow](https://stackoverflow.com/questions/44874558/no-coverage-data-with-nyc-mocha) I didn't get much response, so thats why I'm posting the issue here now

My .nycrc 

    {
      "check-coverage": false,
      "lines": 99,
      "statements": 99,
      "functions": 99,
      "branches": 99,
      "include": [
        "./di.js"
       ],
       "reporter": [
         "lcov",
         "text-summary"
       ],
       "require": [],
      "extension": [
         ".js"
      ],
      "cache": false,
      "all": false,
      "report-dir": "./coverage"
    }

.babelrc:

    {
        "presets": [
        "es2015",
        "stage-0"
      ],
      "plugins": [
        "transform-decorators-legacy",
        "transform-class-properties"
      ],
      "env": {
        "test": {
          "plugins": [
            "istanbul"
          ]
        }
      }
    }

The project which reproduces this issue is public and can be found  [here](https://github.com/scaljeri/di-xxl/tree/v3)

Simply do

    $> git clone https://github.com/scaljeri/di-xxl.git
    $> cd di-xxl
    $> yarn
    $> yarn test

**Comment by adamgajzlerowicz** [comment]
I am having the same issues. With mocha covering number of files running nyc npm test brings me the same result as you have :(

**Comment by JazzFiend** [comment]
Same issue here.

**Comment by bcoe** [comment]
@scaljeri try switching `./di.js` to `di.js` -- this is a glob pattern not a directory path ... it might be good to make our test-exclude library handle this format though.

@JaKXz @adamgajzlerowicz please open your own issues with specific repos being referenced; it tends to be slightly different configuration issues causing people issues.

**Comment by adamgajzlerowicz** [comment]
I have fixed my issue by applying the command correctly.
My test command that was fully working and running tests was this:
`cross-env TEST=TEST cross-env NODE_PATH=./src mocha --require ignore-styles --require jsdom-global/register --compilers js:babel-core/register --recursive \"src/**/*.spec.@(js|jsx)\"`

To use istanbul with this command what I had to do was this: 

`cross-env TEST=TEST cross-env NODE_PATH=./src mocha -G --watch --require ignore-styles --require jsdom-global/register --compilers js:babel-core/register --recursive \"src/**/*.spec.@(js|jsx)\"`

see - it uses the same command and then once that is working you start adding and removing covered files using `package.json` or `.nycrc`

**Comment by scaljeri** [comment]
@bcoe thanks, that did the trick. One last question, the coverage doesn't work when I set `NODE_ENV=test`. I guess this has todo with the fact that in my .nycrc file I have `"instrument": true`, is that right?

**Comment by bcoe** [comment]
@scaljeri sorry or the slow follow up! if you set environment to test, it will start using `babel-plugin-istanbul` rather than `nyc` and sourcemaps -- this is most likely actually preferable.

I recommend setting [instrument to false and sourcemaps to false in the nyc config](https://github.com/istanbuljs/nyc#use-with-babel-plugin-istanbul-for-babel-support).

**Comment by scaljeri** [comment]
@bcoe thanks!

**Comment by bcoe** [comment]
@scaljeri things are working for you? awesome 👍

**Comment by banana618859** [comment]
Test files and test cases cannot be written in the same folder, for example, they cannot be in the "test" folder at the same time
测试文件和测试用例不能写在同一个文件夹内，例如不能同时在"test"文件夹，否则覆盖率结果全为0
