### ISSUE TITLE
Missing branch coverage reporting for certain ES6/promise branches

### ISSUE THREAD

**Issue by cblair** [istanbuljs/nyc#625]
## Expected Behavior
Report branch coverage for `.then()` Bluebird statements with function short-hand. This example queries a database and then collects a result:

```
query.execAsync()
    .then(result => result.Items)
    .map(item => item.toJSON())
    // TODO - nyc coverage reports missing branch here incorrectly.
    .then((exportFormats = []) => ({exportFormats}));
```

## Observed Behavior
Coverage is not reported for the above noted line, even though console logs inserted confirm code execution. Branch coverage will also miss this newly installed code:

```
query.execAsync()
    .then(result => result.Items)
    .map(item => item.toJSON())
    // TODO - nyc coverage reports missing branch here incorrectly.
    .then((exportFormats = []) => {
        console.log('RUNNING');
        return {exportFormats};
    });
```

## Bonus Points! Code (or Repository) that Reproduces Issue
Private code, but will create a public version if needed.

## Forensic Information

**Operating System:** OSX 10.12.5
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.
https://gist.github.com/cblair/80a87a3de827e9fd10936357efca0aa1

**Comment by JaKXz** [comment]
Just curious, your `query.execAsync()` returns a Promise with an asynchronous `.map` function [that returns a promise]? Perhaps I'm misreading something but I'm surprised you can call `.then` if it's just a regular array returned by `.map`.

**Comment by cblair** [comment]
Yeah, I learn something every day with Promises. :)

**Comment by cblair** [comment]
So now that I think about it... there may be two different branches here to test, although its more of a data coverage issue that other branch coverage reporters wouldn't report. `(exportFormats = []) => {...}` needs to be tested for `exportFormats = [...]` and `exportFormats = undefined`. I haven't tested this theory yet, but getting rid of the default param value get's rid of the extra branch. I'll try to confirm.

If this is the case, documentation in the main docs would be good, since its not typical in other coverage reporters in other languages for default param values.

**Comment by bcoe** [comment]
@cblair I think you hit the nail on the head, the problem is that the default parameter assignment doesn't get executed when you're passing in values to the method -- whether or not this behavior is expected is another question.

I recommend opening a conversation [here](https://github.com/istanbuljs/istanbuljs), which is the codebase that performs the actual instrumentation, I would be curious to hear what others think.

**Comment by cblair** [comment]
Thanks @bcoe, I moved the issue to here: https://github.com/istanbuljs/istanbuljs/issues/84.
