### ISSUE TITLE
is "source-map-support" needed for reliable reports with Typescript?

### ISSUE THREAD

**Issue by erwingo** [istanbuljs/nyc#627]
Following this tutorial they ask to install "source-map-support", but I didn't and the reports seem to be working pretty good, so I'm not sure if this is needed.

**Comment by erwingo** [comment]
Nevermind, i just realized that the package was already installed as a devDependencie of nyc 😄

**Comment by bcoe** [comment]
👍 glad things are working for you; there are definitely a few outstanding issues with TypeScript, if you browse through open-issues. If you run into any problems, feel free to join these threads -- also if you feel ambitious, and want to help dig into any of these issues, help is always appreciated.
