### ISSUE TITLE
Unexpected token import when upgrading from 10.1.2 to 11.0.3

### ISSUE THREAD

**Issue by JakeDluhy** [istanbuljs/nyc#628]
## Expected Behavior
I can run my tests
## Observed Behavior
Tests fail with error 
```
(function (exports, require, module, __filename, __dirname) { import server from './routes';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```
## Bonus Points! Code (or Repository) that Reproduces Issue
I run `npm run test:coverage` which (using better npm run) maps to
```json
"test:coverage": {
  "command": "nyc npm test",
  "env": {
    "NODE_ENV": "test",
    "NO_LOGGING": "true"
  }
},
```
`npm test` runs the following
```json
"test": {
  "command": "node test/run-tests.js",
  "env": {
    "NODE_ENV": "test",
    "NO_LOGGING": "true"
  }
},
```
and the script `run-tests` looks like
```javascript
const timer = require('./helpers/timerHelper');

const Mocha = require('mocha');
const path = require('path');
const deasync = require('deasync');
const recursiveSync = deasync(require('recursive-readdir'));
const chokidar = require('chokidar');

// Hack require so that it doesn't poop when getting svgs
const requireHacker = require('require-hacker');
requireHacker.hook('svg', (path) => '');

// Get the passed in flags
const flags = process.argv.slice(2);

// For now, always run with ELECTRON flag
process.env.ELECTRON = 'true';

// Set up jsdom and test helpers
require('jsdom-global/register');
require('./testHelper.js');
require('./assetsNullCompiler.js');

// Set up babel compiling
require('babel-core/register');

const mocha = new Mocha({
    reporter: 'dot',
});

const integrationDir = 'test/integration';
const unitDir = 'test/unit';
// If flags has --only, test only the name of the suite passed in
const testDirs = flags.includes('--only') ?
    [`test/${flags[flags.indexOf('--only') + 1]}`] :
    [integrationDir, unitDir];

// Add the files
testDirs.forEach((dirName) => {
    recursiveSync(dirName)
    .filter((file) => file.substr(-3) === '.js')
    .forEach((file) => {
        mocha.addFile(file);
    });
});

// Start Mirage
require('../mirage').default;
const db = require('../mirage/Database').default;

// Run the tests. If there are any failure exit with a non 0 code to indicate failure
mocha.run((failures) => {
    // If not watching, exit with errors
    if(!flags.includes('--watch')) {
        process.exit(failures);
    }
});

// If watching use chokidar to watch app, mirage, and test and rerun the tests on a file change
const appDir = path.join(__dirname, '../app');
const mirageDir = path.join(__dirname, '../mirage');
const testDir = path.join(__dirname, '../test');

if(flags.includes('--watch')) {
    const watcher = chokidar.watch([
        appDir,
        mirageDir,
        testDir,
    ], { persistent: true });

    watcher.on('change', () => {
        invalidate();
        mocha.run();
    });
}

// Lifted from https://github.com/mochajs/mocha/issues/2061
function invalidate() {
    db.destroyAll();
    mocha.suite.suites = [];
    [appDir, testDir].forEach((dirName) => {
        recursiveSync(dirName).forEach((file) => {
            file = path.resolve(file);
            delete require.cache[require.resolve(file)];
        });
    });
}


process.on('exit', function() {
    timer('process exit');
});
```

Note it's failing on the `require('../mirage').default;` line. Previously `babel-register` was compiling my code but it looks like in the 11 changes this doesn't work anymore
## Forensic Information

**Operating System:** OSX
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.
https://gist.github.com/JakeDluhy/3f19ba3cccc61359a4defba387c677fc

**Comment by bcoe** [comment]
@JakeDluhy rather than requiring `register` programmatically with `require('babel-core/register');`, try executing babel-register with nyc:

```json
{
  "nyc": {
      "require": ["babel-core/register"]
   }
}
```
I think the root problem might be that a library is being loaded that requires module syntax, before the `register` hook has been installed, by pulling this require logic into the nyc configuration, it will ensure that this logic is applied at the outset.

**Comment by JakeDluhy** [comment]
Just tried that, no luck =(. I am still getting the same error.

**Comment by bcoe** [comment]
@JakeDluhy any chance you could provide a GitHub repo with a minimum failing example? I'd happily debug for you.

**Comment by JakeDluhy** [comment]
Sure! Here it is: https://github.com/JakeDluhy/nyc-breaking

Thanks so much!

**Comment by davidbonnet** [comment]
This unresolved issue might be related: https://github.com/standard-things/esm/issues/83.

**Comment by JaKXz** [comment]
Is this still an issue for people? Perhaps this package would help:

https://www.npmjs.com/package/@istanbuljs/nyc-config-babel

**Comment by coreyfarrell** [comment]
@JakeDluhy The issue is that neither babel nor nyc transpile code by default.  To have babel transpile ES modules you need to use `@babel/preset-env` (add to your .babelrc).  Following the instructions on [@istanbuljs/nyc-config-babe](https://www.npmjs.com/package/@istanbuljs/nyc-config-babel) should get this working.  Please note that this works with babel 7 so you will need to update babel and nyc.  If you continue having trouble let us know.

**Comment by przbatte** [comment]
I was having similar issue which gone after removing that setting for all environments in babel.rc file
```javascript
ignore: [
  '**/*.test.js',
],
```
