### ISSUE TITLE
cov_1fanynun32 is not defined

### ISSUE THREAD

**Issue by epyx25** [istanbuljs/nyc#629]
## Expected Behavior
test runs with nyc cover
## Observed Behavior
running `npm test` produces the following error:

>   Rejected promise returned by test
> 
>   Rejection reason:
> 
>     "cov_1fanynun32 is not defined"

Removing nyc from the [test script](https://github.com/epyx25/test/blob/master/package.json#L16) solves the problem, all tests runs as expected.

Looks like related to #514 

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/epyx25/test

Here is the [test](https://github.com/epyx25/test/blob/master/src/test/scraper/testScraper.test.js#L13), and [here is](https://github.com/epyx25/test/blob/master/src/app/scraper/scraper.js#L5) hte tested class. I also tried to cut out internet connection from the test, and load a html page from file, but it did not change anything.
## Forensic Information

**Operating System:** the operating system you observed the issue on.
OS: Ubuntu 16.04

**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.
https://gist.github.com/epyx25/1865ab17587cd3c425cd067ee80ad06a#file-gistfile1-txt

**Comment by keithkml** [comment]
See solution at https://github.com/istanbuljs/nyc/issues/514#issuecomment-322784724

**Comment by JaKXz** [comment]
I'm going to close this in favour of #514. Thank you for the issue!
