### ISSUE TITLE
coverage % changes even though no code change occurred

### ISSUE THREAD

**Issue by epikhighs** [istanbuljs/nyc#630]
## Expected Behavior
 code coverage %s stay the same across multiple coverage runs using the --all option.  If i do not use --all then the code coverage % stays constant.
## Observed Behavior
Even though I do not make any code change, code coverage %s varies b/t two values %Lines 49.5% and 50.44%.

Babel is perhaps behaving in an unexpected way with with the output. 

When I dig into the /coverage directory, the coverage reports show that certain files are either missing or code coverage is not the same in the same file b/t the runs that show variance in % coverage.

Verified that deleting the ./nyc_output directory each time does not help either.

```
File                         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------------------|----------|----------|----------|----------|----------------|
All files                    |    49.26 |    33.48 |     40.4 |     49.5 |                |


-----------------------------|----------|----------|----------|----------|----------------|
File                         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------------------|----------|----------|----------|----------|----------------|
All files                    |     49.9 |    31.17 |    41.98 |    50.44 |                |
```

## Forensic Information

**Operating System:** win 7 64bit
**Environment Information:** 

https://gist.github.com/anonymous/2c5480ae0f397a7cecd82481b9054e5e

**Comment by epikhighs** [comment]
I think the problem was some combination of not using the babel instanbul plugin and including too much in "include" option (I was matching with a leading ** in the include).

But I think it's now producing consistent coverage % for now.

**Comment by bcoe** [comment]
@epikhighs that's good news 👍 please let me know if you run into any more issues in the future.
