### ISSUE TITLE
Feature: Which tests cover this function

### ISSUE THREAD

**Issue by justelad** [istanbuljs/nyc#633]
Hi there,

I had an idea that it would really be helpful if the code coverage could also display which tests (filenames and name of describe/it blocks) result in the specific function(s) being called - not just the number of times a function was called but also who called it.

A wild guess that the overhead of storing and displaying this information might be considerable in terms of size of artefacts so maybe it could be implemented as an explicit flag.

Maintainers - what's your take on this?

Cheers

**Comment by bcoe** [comment]
@elad-nach this is a pretty cool idea and I know a few others are interested in having a similar feature set, see https://github.com/istanbuljs/nyc/issues/597 might be worth joining the istanbul slack, to discuss an approach to implementing this, I know @refack is also interested in this feature

http://devtoolscommunity.herokuapp.com/

**Comment by elad-nach** [comment]
Time to dig in on how nyc works...

**Comment by refack** [comment]
אהלן Elad, 
I discusted this lightly with @bcoe, and we figured that for good coverage we need to hook into `mocha`, `node-tap`, `jest`, and `ava`.
I think I have a solid grip on `mocha` and `node-tap`, plus I need a generic hook for the way `node` core runs the tests which is simply `node test/x/y.js` (so `process.argv.join(' ')` is good enough for me).
If you can cover `jest` and `ava` we get very nice coverage of the test harness landscape.
Cool?

**Comment by bcoe** [comment]
@elad-nach @refack I'm pretty swamped currently working on a new product at npm 😛 but am also around to help keep this moving along. Might be worth starting by just specing out the changes you would like to make to the `__coverage__` object format, such that you can track per-assertion information, then we can start working backwards.

Performance is pretty key in this object, and tiny changes can make a big difference, so my thinking is we should avoid having any test tracking information in the `__coverage__` object, and sprinkle the information in if the feature is enabled.

**Comment by elad-nach** [comment]
אהלן @refack :)
so if i understand correctly - we just need the test runners to report which file is under test (when the test starts and ends).
is there a specific format we'd like to have this in?

**Comment by sinapis** [comment]
Hi guys, can you please confirm status - since this feature was not implemented, there is currently no way to configure istanbul to output coverage per-test info?

**Comment by coreyfarrell** [comment]
You can use [tap](https://github.com/tapjs/node-tap) and enable [coverage maps](https://node-tap.org/docs/coverage/coverage-map/) for filtering on a per file basis (so for example to make `test/util.js` only record coverage for `lib/util.js`).  I'm not aware of other test runners which provide similar functionality.

I do not believe it's reasonably possible to get any further granularity than what tap provides.  Doing so would require a complete rewrite of the way which coverage is counted and I think would cause a severe performance regression.  It would also tie nyc / istanbul to specific testing frameworks.

**Comment by sinapis** [comment]
Thanks for the quick reply!
I'm trying to think of a way to implement this [feature](https://github.com/jest-community/vscode-jest/issues/538) for vscode jest extension. Seems coverage maps is still not granular enough for me. Best solution I could think of is to execute nyc for each test one by one and save each test coverage separately. What are your thought about this? Do you see a better approach?

**Comment by coreyfarrell** [comment]
istanbul has the ability to inject coverage counters to a file or not, this is on a per process basis.  Simply having `require('../lib/util.js')` at the top of your test file usually results in some coverage being counted outside any test.  Beyond that you might be able to get your test running to do some manipulation of the `global.__coverage__` object.  nyc itself does not know what a test is as nyc is agnostic to the test runner and will function without any test framework.

Take `hello-world.js` as an example:
```js
#!/usr/bin/env node
console.log('Hello World');
}
```

Running `nyc node ./hello-world.js` will produce a coverage report showing 100% coverage.  You can see how coverage is counted by running `nyc instrument --compact=false hello-world.js`.  I just did this locally and it produced:
```js
#!/usr/bin/env node

function cov_13x0z18m17() {
  var path = "/usr/src/npm/nyc/hello-world.js";
  var hash = "fa327ba30d6cf0ddcf055ec29a6bfc8793620a26";
  var global = new Function("return this")();
  var gcv = "__coverage__";
  var coverageData = {
    path: "/usr/src/npm/nyc/hello-world.js",
    statementMap: {
      "0": {
        start: {
          line: 2,
          column: 0
        },
        end: {
          line: 2,
          column: 27
        }
      }
    },
    fnMap: {},
    branchMap: {},
    s: {
      "0": 0
    },
    f: {},
    b: {},
    _coverageSchema: "1a1c01bbd47fc00a2c39e90264f33305004495a9",
    hash: "fa327ba30d6cf0ddcf055ec29a6bfc8793620a26"
  };
  var coverage = global[gcv] || (global[gcv] = {});

  if (!coverage[path] || coverage[path].hash !== hash) {
    coverage[path] = coverageData;
  }

  var actualCoverage = coverage[path];

  cov_13x0z18m17 = function () {
    return actualCoverage;
  };

  return actualCoverage;
}

cov_13x0z18m17().s[0]++;
console.log('Hello World');
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImhlbGxvLXdvcmxkLmpzIl0sIm5hbWVzIjpbImNvbnNvbGUiLCJsb2ciXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUNBQSxPQUFPLENBQUNDLEdBQVIsQ0FBWSxhQUFaIiwic291cmNlc0NvbnRlbnQiOlsiIyEvdXNyL2Jpbi9lbnYgbm9kZVxuY29uc29sZS5sb2coJ0hlbGxvIFdvcmxkJyk7XG4iXX0=
```

In theory you could zero out all counters in `global.__coverage__` before each test and save per test results after each test - this is well outside the scope of nyc.  Also this would require disabling any same process parallel testing.  Running `test/test1.js` and `test/test2.js` at the same time wouldn't be an issue, but if `test/test.js has `test 1` and `test 2` you would have to ensure they run one after another.

If you intent to attempt this I would not recommend using `nyc` for coverage collection.  For this you likely need to use `babel-plugin-istanbul` to instrument sources and use other istanbuljs libraries to manage the coverage.  This would be an advanced / very difficult task and would likely be specific to a single test runner.  I'm not sure it's possible to populate the `TN` field of lcov as istanbul has no support for this information.  Likely this would require creating your own `lcov` writer that would use an extended form of istanbul coverage data.
