### ISSUE TITLE
How does this work with child_process'es?

### ISSUE THREAD

**Issue by stevenvachon** [istanbuljs/nyc#635]
I'd like to get similar functionality added to [node-pty](https://npmjs.com/node-pty), but am not sure how `nyc` and `istanbul` work. Does it search a JavaScript AST of `require`'d files for instances of `spawn("node"`?

https://github.com/Tyriar/node-pty/issues/113

**Comment by bcoe** [comment]
Hey @stevenvachon, nyc is using the module [spawn-wrap](https://github.com/tapjs/spawn-wrap) to handle wrapping subprocesses. `spawn-wrap` basically shims `child_process.exec` and `child_process.spawn`, and executes an alternative `node` bin when you run either of these methods.

This alternative `node` executable injects the require-hook logic used by `nyc` to instrument files.

I don't know much about `node-pty`, but I imagine you might be able to configure a similar approach?

**Comment by stevenvachon** [comment]
Thank you. Looking through some of the source code, it looks like its `exec` and `spawn` patches only inject terminal variables before the `node` executable. Is this correct?

**Comment by Morikko** [comment]
We used it on our app @DoctrineLegal during some time. We were able to get the coverage from the `child_process.fork` as well. 

In the final report we saw for:
 - Each file: the coverage merged between all the sub processes
 - Each process: the percentage of all the lines covered by the process over all the files
