### ISSUE TITLE
Invalid regular expression errors while trying to parse/inject functions?

### ISSUE THREAD

**Issue by brid** [istanbuljs/nyc#636]
## Expected Behavior

Running nyc against tests that work with mocha or mocha-grunt should produce coverage reports.

## Observed Behavior

Running tests with nyc before mocha causes errors relating to regular expressions. Looking at the stack trace it appears nyc is injecting it's own code into instrumented files before trying to regex these out, and running into problems.

Running:

> ./node_modules/.bin/nyc ./node_modules/.bin/mocha test/**/*.js

Returns:

`SyntaxError: Invalid regular expression: /^function lockOut(req,res,next){++cov_o5sd0udke\.f[0];++cov_o5sd0udke\.s[11];if((++cov_o5sd0udke\.b[1][0],req\.user)&&(++cov_o5sd0udke\.b[1][1],req\.user\.disabled)){++cov_o5sd0udke\.b[0][0];++cov_o5sd0udke\.s[12];return noAccess(req,res,next);}else{++cov_o5sd0udke\.b[0][1];}++cov_o5sd0udke\.s[13];return next();}\/?$/: Nothing to repeat`

## Forensic Information

Mac OSX El Capitan
Node v6.10.0
mocha: ^3.4.2
nyc: 11.0.3

**Comment by bcoe** [comment]
@brid could you please provide a link to the repo that is having this behavior, or if this isn't possible a repo with a minimal reproduction.

**Comment by mdhornet90** [comment]
I'm also seeing this issue in an Express app I've been building. The code below reproduces it consistently:

```
const express = require('express'),
    app = express();

app.all(function(req, res, next) {});

exports = app;
```

Changing that declaration from `all` to `get` resolves the regex error, as does adding a `'*'` as a path before the function arg.

*Setup:*
macOS Sierra
Node 8.4.0
nyc: ^11.4.1
mocha: ^5.0.1
express: ^4.16.2

run command: `node_modules/.bin/nyc --reporter=lcov node_modules/mocha/bin/_mocha`

**Comment by JaKXz** [comment]
If this is still an issue with the latest version of nyc, please open a new issue with a link to a minimal reproduction repo. Please also try the tutorials at: https://istanbul.js.org/docs/tutorials/
