### ISSUE TITLE
Unknow

### ISSUE THREAD

**Issue by wikidson** [istanbuljs/nyc#638]
hello, the problem :
-----
![image](https://user-images.githubusercontent.com/9945173/28656259-801dc9aa-72d3-11e7-9fde-349b28439117.png)

## version:
"nyc": "^11.0.3",
"ava": "^0.21.0",
"node":  "v7.10.0"
"os": mac 

## config
![image](https://user-images.githubusercontent.com/9945173/28656424-81ca95fc-72d4-11e7-9251-f8fc7e97aa2a.png)

**Comment by bcoe** [comment]
@wikidson it looks like you are loading `babel-register` twice, once in the `ava` configuration, and once int he `nyc` configuration. Try removing it from the `ava` config and I believe it will fix things for you.
