### ISSUE TITLE
Question about .nyc_output and window.__coverage__

### ISSUE THREAD

**Issue by miloss** [istanbuljs/nyc#641]
I am trying to generate HTML report from `window.__coverage__` object, with partial success. It seams that easiest way to to this would be using `nyc`, which as I see only supports creating report from existing `.nyc_output` folder.

Is there a straightforward way to get `.nyc_output` folder from `__coverage__` object? If not, what would be the right direction to go?

Thanks for reading this ✌️

**Comment by bcoe** [comment]
@miloss if you simply output the contents of `window.__coverage__` (assuming it's in Istanbul 1.0 format) to `.nyc_output/out.json`, you should be able to run `nyc report --reporter=html` to get an HTML report.

Would this do the trick for you?

**Comment by miloss** [comment]
Yes, that worked perfectly. Thank you so much 👏

You think this would be worth adding to documentation? Or is this way of getting coverage (from browser/global object) not really recommended in the long term?
