### ISSUE TITLE
Old removed files seem to stay cached in reports

### ISSUE THREAD

**Issue by cdaringe** [istanbuljs/nyc#644]
## Expected Behavior

- no report for old, non-existing file (`project.js`)

## Observed Behavior

- report shows coverage for non-existent file

```sh
🛰  counsel$ yarn test
yarn test v1.0.0-20170807.1537
$ nyc ava test/**/*.test.js && nyc report --reporter=lcov

  8 passed
------------|----------|----------|----------|----------|----------------|
File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------|----------|----------|----------|----------|----------------|
All files   |    69.66 |    48.68 |    70.97 |    68.29 |                |
 Counsel.js |      100 |     92.5 |      100 |      100 |    271,272,275 |
 Project.js |    24.24 |        0 |       20 |       25 |... 74,75,77,78 |
 logger.js  |      100 |      100 |      100 |      100 |                |
 project.js |    12.12 |        0 |        0 |     12.5 |... 74,75,77,78 |  # <== was renamed to `Project.js`
------------|----------|----------|----------|----------|----------------|
✨  Done in 4.15s.
```

- `rm -rf coverage .nyc_output` has no effect pre-`yarn test`
- `🛰  counsel$ find . | grep project.js` produces _nada_
- renaming the `Project.js` to anything else (and updating the code to point to it) resolves the issue
- reverting the rename procedure above resumes the failure

## Bonus Points! Code (or Repository) that Reproduces Issue

- i built [one repo](https://github.com/cdaringe/nyc-caching-fubar-reports)... but it's not reproducing yet.  i'm not sure why?

i'm observing the issue on this [project+branch](https://github.com/cdaringe/counsel/tree/feature/class) in `packages/counsel` (monorepo).  I did completely erase the project from disk, `yarn && yarn bootstrap` in the root, then `yarn test` in `packages/counsel`, and it reproduced for me.

## Forensic Information

**Operating System:** osx, sierra
**Environment Information:** 

...i'm using yarn workspaces, so the script doesn't really create a fair report!, but, i did output `yarn list` [here](https://gist.github.com/cdaringe/bc1a5625438a156379b21306ab3f96a5)!

v8.3.0
5.3.0
(yarn 1.0.0-20170807.1537)

**Comment by bcoe** [comment]
@cdaringe hey 👋 my guess would be their's content in `node_modules/.cache/nyc/.cache` that references the old file -- this sounds like it might be a bug though, it should certainly bust the cache when a file no longer exists (I wonder if workspaces might somehow be interfering).

Try `rm -rf node_modules/.cache/nyc/.cache`

**Comment by cdaringe** [comment]
greetings!

indeed, the cache is there (`<root>/packages/counsel/node_modules/.cache`), and not in `<root>/node_modules/.cache`.  clearing the cache doesn't resolve it.  the fact that i `rm -rf`'d my whole project, re-cloned the source, and the issue still happened, im wondering it there are _other_ caches on disk used?

**Comment by cdaringe** [comment]
a hint, but not the key, is that I had a require statement that still looked like `require('./project')` vs `require('./Project')`.  it as though the report uses the value parsed from the require statement vs the actual resolved file basename.

**Comment by bcoe** [comment]
Oh interesting, I wouldn't be shocked by this. Did things work as expected when you switched to `./project`?

**Comment by cdaringe** [comment]
IIRC, fixing the require statement to match the updated file casing of `Project.js` did not resolve the issue

**Comment by cdaringe** [comment]
I know this isn't super actionable without a reproducible thing.  As noted above I did try to repo and I cannot.  That's why I was wondering if there was any other caching at play?  If you think there are some things you could check that would be rad.  If not and you care to close the issue, I understand too.  Thx!

**Comment by bcoe** [comment]
@cdaringe sorry for the slow reply, have a limited amount of time to put in OSS recently. Is this issue still happening to you; one thing worth trying would be to run nyc with `--no-cache`, this will cause all the caches to be ignored during the test run.

If it continues happening, I would definitely be interested if you could figure out a small reproduction in a repo you could share -- this always makes hunting down a bug easier.

**Comment by cdaringe** [comment]
I'll reopen when i hit it again :). Thx!

**Comment by DanielSchaffer** [comment]
I've run into this several times with TypeScript due to `ts-node`'s caching. Running with `TS_NODE_CACHE=false` works around the problem, but of course it's way too slow. I was able to fix the issue by removing the cache directory, which by default is somewhere in a temp directory. The root of the temp directory is whatever `os.tmpDir()` gives you, and the ts-node cache will be a directory prefixed with `ts-node-` and then SHA hex hash

**Comment by tolotrasamuel** [comment]
For me I deleted the dist or build file generated by typescript and recompiled typescript. When I deleted a ts file, it did not get deleted automatically in the dist folder (or build depending on your case)
