### ISSUE TITLE
nyc fails with "unknown" result on Ubuntu 14.04

### ISSUE THREAD

**Issue by liujinmarshall** [istanbuljs/nyc#646]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
nyc mocha is expected to output coverage data

 
## Observed Behavior
It fails with "4 unknown" even the test finishes on Ubuntu

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|

## Forensic Information

This issue won't appear on version before 11.0.0 (i.e. 10.3.2 works great). I use binary search to find the tipping point. So it looks like the changes in 11.0.0 reveals this issue. Possibly an issue in its dependencies. And 11.0.0 works on OSX and Ubuntu 16.04. 

**Operating System:** Ubuntu 14.04
**Environment Information:** node 8.3.0, npm 5.3.0 (node/npm version don't seem to relevant)

Configure package.json so that npm test could be running:

nyc mocha --require ignore-styles --require test/setup.js --recursive

**Comment by bcoe** [comment]
@liujinmarshall could you please provide a link to the library that is failing to instrument under ubuntu 14.04, alternatively perhaps a minimum failing example.

**Comment by liujinmarshall** [comment]
Somehow I managed to get over this with latest node (8.3.0 at that time) instead of LTS, together with "cross-env NODE_ENV=test" before the nyc command in package.json.

Sorry for the late response. I'll close this issue.

**Comment by bcoe** [comment]
@liujinmarshall good, please don't hesitate to reopen this if you run into this issue again.
