### ISSUE TITLE
nyc ts-node --project does not work on windows.

### ISSUE THREAD

**Issue by rupamroy** [istanbuljs/nyc#647]
## Expected Behavior
On my windows system when i try this
```bash
$(npm bin)/nyc --report-dir coverage/server $(npm bin)/ts-node --project server/tsconfig.json node_modules/jasmine/bin/jasmine.js 'server/**/!(*index).ts'
```
It should run tests for the code and report on coverage.

## Observed Behavior
It throws the following output
```bash
C:\Program Files\nodejs\node.exe: bad option: --project
ERROR: Coverage for lines (0%) does not meet global threshold (90%)
ERROR: Coverage for functions (0%) does not meet global threshold (90%)
ERROR: Coverage for statements (0%) does not meet global threshold (90%)
```
## Additional 
The below code however workings fine.
```bash
$(npm bin)/ts-node --project server/tsconfig.json node_modules/jasmine/bin/jasmine.js 'server/**/!(*index).ts'
```
The .nycrc file looks like this
```yaml
{
    "check-coverage": true,
    "lines": 90,
    "statements": 90,
    "functions": 90,
    "branches": 90,
    "all": true,
    "include": [
        "server"
    ],
    "exclude": [
        "**/index.ts",
        "**/tests/*.ts",
        "**/*.model.ts",
        "**/*.module.ts",
        "server/server.spec.ts"
    ],
    "reporter": [
        "html",
        "json",
        "text-summary"
    ],
    "extension": [
        ".ts"
    ]
}

```

## Forensic Information
**Operating System:** Windows 10 on MINGW64
**Environment Information:** 
https://gist.github.com/rupamroy/fb66b53010b7657e83dcc0a3fa0d1039

**Comment by bcoe** [comment]
@rupamroy are you able to provide a link to the project that is having this issue?

**Comment by rupamroy** [comment]
No sorry i can't do that , This is within a corporate network and not open sourced project.

**Comment by rupamroy** [comment]
Hi Any update on this issue ?

**Comment by bcoe** [comment]
@rupamroy haven't had a chance to spin up a Windows VM, please feel free to join our community slack if you want to try to recruit some folks to dig into this bug:

http://devtoolscommunity.herokuapp.com/

It would be helpful if you could provide a minimal failing reproduction in a toy repo ... doesn't need to be the proprietary codebase you use at work.

**Comment by codercurtis** [comment]
I'm running into this, where I can't get coverage on Windows

**Comment by rupamroy** [comment]
Well i found a solution and noting it down just in case anyone needs it. 
This issue occurs in Git bash on windows the solution is to use a redirection operator `<` between the nyc and ts-node command
```
$(npm bin)/nyc --report-dir coverage/server < $(npm bin)/ts-node --project server/tsconfig.json node_modules/jasmine/bin/jasmine.js 'server/**/!(*index).ts'
```

But now even though the command are working well nyc seems to not honoring the tsconfig path provided in the --project parameter and i have no clue why nyc should be related to tsconfig in any way. Becoz now i am getting the error as if i am not passing the --project parameter. Or due to redirection operator `<` may be the parameter is not getting passed into the ts-node command, Not sure what is going on.

**Comment by rupamroy** [comment]
I have created a demo project https://github.com/rupamroy/test-nyc to show the issue. The issue happens only in windows , the README describes the problem and the command used.
