### ISSUE TITLE
Coverage of code run using vm.runInThisContext

### ISSUE THREAD

**Issue by nwhetsell** [istanbuljs/nyc#652]
Is there any way to get coverage statistics of code run using [`vm.runInThisContext`](https://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_options) in [Jasmine](https://jasmine.github.io)?

Here’s a repository that shows what I’m trying to achieve: https://github.com/nwhetsell/nyc-test.

There are two functions, in two files, in the repository. The [Jasmine spec](https://github.com/nwhetsell/nyc-test/blob/master/spec/spec.js) gets [one function](https://github.com/nwhetsell/nyc-test/blob/master/function1.js) using `require`, and [the other](https://github.com/nwhetsell/nyc-test/blob/master/function2.js) from `vm.runInThisContext`. When testing this on Travis (https://travis-ci.org/nwhetsell/nyc-test), all the tests pass, but the function from `vm.runInThisContext` doesn’t appear in the coverage statistics.

**Comment by nwhetsell** [comment]
I figured out a way to do what I was doing without `vm.runInThisContext`, so closing.

**Comment by JoHuang** [comment]
I went into the same issue when I use Jest. I have to use `vm.runInThisContext` in my case.
Any solutions?
Thanks
