### ISSUE TITLE
cluster code coverage did not be included in the coverage report sometimes

### ISSUE THREAD

**Issue by ruiming** [istanbuljs/nyc#655]
## Observed Behavior
I used cluster to test my server.
Koa server was run in a worker, and I tested the router of the server from master. This prevent the koa crash result in the whole process crash. But it seems that nyc can not calculated coverage report correctly sometimes.
the handle function of route existed in the controller file in `controllers` folder which it simply call some function in service file in `services` folder. Then the final coverage report sometimes did not includes `controllers` folder and `services` folder. It seems that the coverage in worker did not be included in the report. What curious me is that sometimes it will be included and I think it should be always included.

## Bonus Points! Code (or Repository) that Reproduces Issue
This is my main test file. I run my application(koa server) in worker, while mocha in master.
```typescript
// This is TypeScript code
import 'mocha'
import '../src/utils/config'
import { Test } from '../src/utils/Test'
import * as cluster from 'cluster'
import * as process from 'process'

if (cluster.isMaster) {
  const worker = cluster.fork()

  before('initial test data', async () => {
    await Test.Instance.connectDB()
    await Test.Instance.mockData()
    console.log('initial success')
  })
  
  after('destroy test data', async () => {
    await Test.Instance.destroy()
    console.log('destroy success')
  })

  worker.on('message', (msg: string) => msg === 'ok' && run())

} else if (cluster.isWorker) {
  Test.Instance.connectApp().then(() => process.send!('ok')).catch(e => console.log(e))
}
```
When the application in worker was connected, a signal was sent to master which call the `run` function mocha provide which it is used for starting test.
## Forensic Information
- Operating System: Arch Linux
- Node version: v8.4.0
- Npm version: v5.3.0
- nyc version: 11.1.0
- Nyc config:
  ```json
  "nyc": {
    "cache": true,
    "reporter": [
      "lcov",
      "text"
    ],
    "extension": [
      ".js",
      ".ts"
    ],
    "exclude": [
      "test"
    ]
  }
  ```

**Comment by bcoe** [comment]
@ruiming ever make any progress on digging into this? 

One thing comes to mind, are you using typescript-register to handle TypeScript parsing? If so, I would make sure that it's nyc that it's `nyc` itself that requires this module, by adding a `require` stanza to the `nyc` configuration.

If this does turn out to be the problem, I would love some help updating the README.md for nyc, since this order of operation problem often bites people.

**Comment by ruiming** [comment]
No. I had stopped using cluster to test.
I had do some test to try to find the problem. Finally it proves that it is the problem of `espower-typescript/guess`(I am using power-assert)
To test below code:
```typescript
// app.ts
import * as koa from 'koa'

export const server = () => {
  const app = new koa()
  
  app.use(async (ctx, next) => {
    ctx.status = 200
    await next()
  })  

  app.listen(8001)
}
```
Test file:
```typescript
import 'mocha'
import * as cluster from 'cluster'
import * as process from 'process'
import * as request from 'supertest'
import { server } from '../app'

if (cluster.isMaster) {
  const worker = cluster.fork()

  describe('', () => {
    it('', async () => {
      await request('http://localhost:8001')
        .get('/')
        .expect(200)
    })
  })

  worker.on('message', msg => run())
} else if (cluster.isWorker) {
  server()
  
  process.send!('app listen')
}
```
And I run`npm run test1` and `npm run test2` with nyc disable cache.
```
"test1": "nyc mocha --compilers ts:espower-typescript/guess 'test/*.ts' --require source-map-support/register --delay --timeout=10000",
"test2": "nyc mocha --require ts-node/register 'test/*.ts' --require source-map-support/register --delay --timeout=10000"
```

The result is `test1` with full coverage report and `test2` with unknown report.
Then I just change the nyc cache from `false` to `true`, run `test1` then `test2` followed. `test1` works still well but `test2` with zero coverage report instead of unknown report.

To conclude, I think this problem is caused by this `ts:espower-typescript/guess`.

**Comment by bcoe** [comment]
@ruiming great digging. Perhaps you can open an issue on `espower-typescript/guess` and reference this issue? It would be great to get this working for you.

**Comment by ruiming** [comment]
I will, thanks.
