### ISSUE TITLE
Nyc doesn't include files that has spread object syntax on the coverage

### ISSUE THREAD

**Issue by erickzanardo** [istanbuljs/nyc#657]
## Expected Behavior
All files, that aren't excluded on nyc config should be included on the coverage

## Observed Behavior

Files that have the spread operator syntax are been omitted from the coverage

I've included a zip file that contains a simple npm project that reproduces the problem, basically the project has two files `a.js` and `b.js`:

```javascript
// a.js
module.exports = a => ({ ...a })
```

```javascript
// b.js
module.exports = b => Object.assign({}, b)
```

They both are tested but when the cover is executed, the file `a.js` is not listed on the cover report.

I'm using node 8.4, which supports the object spread syntax

[nyc-spread-error.zip](https://github.com/istanbuljs/nyc/files/1257096/nyc-spread-error.zip)

**Comment by bcoe** [comment]
@erickzanardo this should now be fixed in `nyc@11.2.0` mind trying it out?

**Comment by beckend** [comment]
@bcoe works!

**Comment by erickzanardo** [comment]
@bcoe it worked, thanks a lot

**Comment by XVincentX** [comment]
Guys I'm still facing the same issue on Node 6

This is the broken build
https://circleci.com/gh/ExpressGateway/express-gateway/2343
I had to workaround it with this commit: [9c84d0f](https://github.com/ExpressGateway/express-gateway/pull/567/commits/9c84d0fe2e127741f36e68c137ca88214161ef12)
It is working correctly on Node 8, though.
