### ISSUE TITLE
Expand .nycrc to process.argv

### ISSUE THREAD

**Issue by jdalton** [istanbuljs/nyc#660]
I noticed `mocha` will [expand its `mocha.opts`](https://github.com/mochajs/mocha/blob/master/bin/options.js) into `process.argv` args.
This allows scripts that were `--require`'d to detect themselves.

Would `nyc` be open to expanding [its config](https://github.com/istanbuljs/nyc/blob/dd40dc5118741415a7f35626555f58390afd9641/lib/config-util.js#L20-L35) into `process.argv` args too?

If it's something you all would dig, I'm up for creating a PR.

**Comment by bcoe** [comment]
@jdalton I really like this idea, I think we'd just need to be smart and figure out how to make it place nice with features like this:

https://github.com/istanbuljs/nyc/pull/620

We allow folks to override a few parameters like `cwd`, but we then assume that a spawned subprocess won't have these parameters overridden ... `cwd` might be the only edge-case.

**Comment by jdalton** [comment]
Ah nice! To start `nyc` could transfer to `process.argv` the ones it probably won't have problems with then expand as guards or code to handle others is added.

**Comment by bcoe** [comment]
@jdalton that's not a bad idea, maybe just black-list `cwd` for starters?

**Comment by jdalton** [comment]
👌 , I'll work on a PR

**Comment by Rush** [comment]
Maybe related? https://github.com/istanbuljs/nyc/issues/709

**Comment by JaKXz** [comment]
Is this still a valid issue? Is it within the scope of `nyc` or does it belong in an underlying package (yargs)?

**Comment by coreyfarrell** [comment]
I'd be interested in seeing an example of a module that would use this information from `process.argv` but I'm leaning towards calling this out of scope for NYC, I don't think we should mess with `process.argv`.
