### ISSUE TITLE
NYC for performance instrumentation

### ISSUE THREAD

**Issue by jamespedid** [istanbuljs/nyc#665]
Hello, I just have a basic question: can nyc be used for instrumentation purposes other than code coverage? In particular can nyc be used to instrument code as part of a performance test? Thanks in advance!

**Comment by bcoe** [comment]
@jamespedid this is a cool idea; but not something currently supported by `nyc`. If you're curious how `nyc` works behind the scenes, and wanted to crib some of the logic for writing performance instrumentation, all the instrumentation code can be found here:

https://github.com/istanbuljs/istanbuljs
