### ISSUE TITLE
NYC v11.2.0 exclude file with sourcemap from coverage

### ISSUE THREAD

**Issue by Speedy37** [istanbuljs/nyc#668]
## Expected Behavior

Sourcemap of files that are far away from covered .js files should be included by default, not excluded.
This is a regression introduced by #637 

## Observed Behavior

All my sourcemaps are excluded :(

## Forensic Information

shouldInstrument is called with "/myabsolutepath/@msbuildsystem/js.typescript/src/worker.ts"
the relFile path is "../../../../../@msbuildsystem/js.typescript/src/worker.ts"

witch return false due to line 81 in test-exclude/index.js (// Don't instrument files that are outside of the current working directory.)

**Comment by Speedy37** [comment]
Because #649 is likely to cause a lot of regression, can't it be activated by a flag ? (like --filter-sourcemap)

I really like to keep my output files away from my source files

**Comment by bcoe** [comment]
@Speedy37 see https://github.com/istanbuljs/nyc/pull/674, let's try to figure out a solution that fits everyone's needs.

**Comment by Speedy37** [comment]
Since issue #637 it's not possible have coverage if output files are not in a subdirectory of source files without including the source directory manually which is I think an unexpected default behavior.

There is multiple way to solve this:

 - if sources files are outside cwd directory then you must include them manually (current behavior since 1.12.0)
 - multiple root directories (I quite like this one)
 - two separate (include/exclude) filter (instrument/source)

**Comment by Speedy37** [comment]
Finally after checking the sourcecode it's currently not possible to include files outside cwd, so the current behavior is: you can't have source files and instrument files in different roots

**Comment by bcoe** [comment]
@Speedy37 would it be possible to provide a minimal failing example of this, which we could turn into a unit test. In a perfect world I'd like to appropriately handle the exclude logic, regardless of whether source-maps are used. It seems like the logic in #637 needs to be extend on.

**Comment by JaKXz** [comment]
Is this still an issue?
