### ISSUE TITLE
feat: make  'istanbul cover' work the same as Istanbul

### ISSUE THREAD

**Issue by clakech** [istanbuljs/nyc#669]
We used to instrument our server using "istanbul cover app.js" command and then execute some blackbox tests on this app to know our coverage.

I am trying to use "nyc instrument app.js" to do the same but I am not sure if this is the good way to do it. The server shutdown immediately after I start it using "nyc instrument app.js"

With "istanbul cover app.js" the server stay up until we stop it "manually"

How could we achieve the same thing using nyc instead of instanbul ?

## Forensic Information

**Operating System:** OSX
**Environment Information:** node v8.4 npm 5.3

**Comment by bcoe** [comment]
@clakech we haven't yet ported over this feature from Istanbul, definitely sounds like something we should potentially add.

**Comment by clakech** [comment]
Ok any other way to to compute coverage on a running server?

Or any hints to implements this cover command by ourselves?

**Comment by kresss** [comment]
+1 for this feature.

Looks like this would also resolve #548

**Comment by Morikko** [comment]
Just launch your code with nyc: `nyc myserver.js` 
It worked for an express server with this `.nycrc`:
```
  "show-process-tree": true,
  "check-coverage": false,
  "all": true,
  "cache": true,
  "eager": true,
  "instrument": true,
```

I just added a piece of code to make nyc returning the coverage. I believe that you should exit the process from inside, send a signal that it ends, for making nyc returning the coverage. I don't know why. 
More here: https://github.com/istanbuljs/nyc/issues/762#issuecomment-420992372

My conclusion:
 - Return the coverage
 - Can cover patterns (to include unrequired files)
 - Cover and merge automatically sub process (at least the fork one)
 - One limit: the coverage was not complete for few files (1%), even if required, they stayed at 0%
  
I tried to found a pattern among those files to correct them. I only discovered that the not covered files were like this: 
```javascript
module.exports = function f1() {}
```
But many files like this still were covered.
A partial solution was to modify the 0% files to this: 
```javascript
function f1() {}
module.exports = f1
```

After this only 0.1% were uncoverable... I have no reason or logical explanation about why they are uncoverable and why this correction was necessary for only some files.

**Comment by JaKXz** [comment]
This is being worked on in #893.

**Comment by JaKXz** [comment]
@coreyfarrell @AndrewFinlay has this been addressed with the recent `nyc instrument` PRs?

**Comment by coreyfarrell** [comment]
I believe @clakech was confused about how `istanbul` commands are implemented in `nyc`.  I believe the comment by @Morikko is accurate and explains that this is not a bug.
`nyc instrument app.js` will output an instrumented copy of `app.js`.  `nyc ./app.js` will run `./app.js`, at which point it is the responsibility of `app.js` to exit.
