### ISSUE TITLE
babel-plugin-istanbul works on v10.0.0 but not latest

### ISSUE THREAD

**Issue by reggi** [istanbuljs/nyc#670]
I made an initial issue here in the plugin repo. https://github.com/istanbuljs/babel-plugin-istanbul/issues/128

I just saw that the `package.json` I have (in the issue explained below) works with `v10.0.0` but on the latest `v11.2.1` it's not working with that istanbul plugin. Is there something wrong with my config to support the newer release of `nyc`?

---

> Also posted on [StackOverflow](https://stackoverflow.com/questions/46080121/tests-are-passing-coverage-is-not-showing)

I'm trying to get `nyc` `ava` and `babel` to all place nice together.

I've done this a bunch of times, I'm not sure what's going wrong now.

I was having an issue where async / await branches were showing as not covered, so this was working, I'm having trouble integrating the `babel-plugin-istanbul` plugin for tests. 

I have two files in the project, `src/index.js` and `src/test.js`.

    {
        "name": "example",
        "version": "1.0.0",
        "description": "",
        "main": "index.js",
        "scripts": {
            "test": "ava",
            "coverage": "NODE_ENV=test nyc npm run test",
            "report": "nyc report --reporter=html",
            "report:open": "open ./coverage/index.html",
            "cover": "npm run coverage && npm run report && npm run report:open"
        },
        "keywords": [],
        "author": "",
        "license": "ISC",
        "dependencies": {
            "babel-runtime": "^6.26.0",
            "bluebird": "^3.5.0",
            "lodash": "^4.17.4"
        },
        "devDependencies": {
            "ava": "^0.22.0",
            "babel-cli": "^6.26.0",
            "babel-plugin-istanbul": "^4.1.4",
            "babel-plugin-transform-runtime": "^6.23.0",
            "babel-preset-env": "^1.6.0",
            "babel-register": "^6.26.0",
            "nyc": "^11.2.1",
            "sinon": "^3.2.1",
            "testdouble": "^3.2.4"
        },
        "babel": {
            "presets": ["env"],
            "plugins": ["transform-runtime"],
            "env": {
                "test": {
                    "plugins": ["istanbul"]
                }
            }
        },
        "ava": {
            "require": ["babel-register"],
            "babel": "inherit"
        },
        "nyc": {
            "sourceMap": false,
            "instrument": false
        }
    }

Here's whats running:

    > example@1.0.0 coverage /Users/me/Desktop/example
    > NODE_ENV=test nyc npm run test
    
    
    > example@1.0.0 test /Users/me/Desktop/example
    > ava
    
    
      11 passed
    ----------|----------|----------|----------|----------|----------------|
    File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
    ----------|----------|----------|----------|----------|----------------|
    All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
    ----------|----------|----------|----------|----------|----------------|
    
    > example@1.0.0 report /Users/me/Desktop/example
    > nyc report --reporter=html
    
    
    > example@1.0.0 report:open /Users/em/Desktop/example
    > open ./coverage/index.html

Why isn't `src/index.js` showing in the coverage?

---

**Comment by bcoe** [comment]
@reggi trying to reproduce your issue. I used the `package.json` that you provided, and created a test as follows in `test/test.js`:

```js
import test from 'ava';
require('../src')

test('foo', t => {
	t.pass();
});

test('bar', async t => {
	const bar = Promise.resolve('bar');

	t.is(await bar, 'bar');
});
```

coverage is outputting for me as expected; could you provide a small example repo that's failing to output coverage?

**Comment by jeantimex** [comment]
Hi @bcoe, I have the same issue with @reggi, v11.2.0 works fine with coverage report, but something is broken in v11.2.1. And here is my .nycrc:
```
{
  "require": [
    "babel-register"
  ],
  "sourceMap": false,
  "instrument": false,
  "include": [
    "src/**/*.js"
  ],
  "exclude": [
    "test/**/*.spec.js"
  ]
}
```
my .babelrc is:
```
{
  "presets": ["env"],
  "env": {
    "test": {
      "plugins": ["istanbul"]
    }
  }
}
```
I am sticking with v11.2.0 for now.

**Comment by bcoe** [comment]
@jeantimex could you please open a new issue, I believe you might be experiencing something different -- as I was unable to reproduce @reggi's problem, and their issue was related to upgrading from `10.x` to `11.x` not from `11.2.0` to `11.2.1`.

In the issue you open, would you please provide a repo that reproduces your issue? this will help us get it fixed fairly quickly.

**Comment by jeantimex** [comment]
Hi @bcoe, interesting, I was trying to created a repo for you, but turns out v11.2.1 is working fine for me. Here is the repo, https://github.com/jeantimex/nyc-demo. I am not sure what is going on, but I am happy that it's working for me now, thanks!

**Comment by bcoe** [comment]
@jeantimex; I wonder if it might be related to the issue here?

https://github.com/istanbuljs/nyc/issues/668

are you using sourcemaps in the repo having issues?
