### ISSUE TITLE
Feat: allow a custom results processor 

### ISSUE THREAD

**Issue by JayKan** [istanbuljs/nyc#671]
I'm just curious if there is any way that you guys can expose a `testResutlsProcess` property on `.nycrc` file just like how `Jest` is doing it on its `jest.config.json`(https://facebook.github.io/jest/docs/en/configuration.html#testresultsprocessor-string)

Let me know if this is something you guys would be interested in adding

**Comment by JaKXz** [comment]
@JayKan sorry for the delayed reply, I'd be happy to help review a PR, if you're still interested :)
