### ISSUE TITLE
Do I misunderstand how you glob? If not, I'm losing test cases and I don't know why

### ISSUE THREAD

**Issue by StoneCypher** [istanbuljs/nyc#673]
## Expected Behavior
Small-medium (430 cases in ~20 files) testset on library.  100% coverage.

Tried to switch from shallow match for test names run to deep match.  No change, as expected.  

```
> jssm@5.8.0 test /Users/johnhaugeland/projects/jssm
> nyc ava src/js/tests/**/*.js


  430 passed
----------------------------|----------|----------|----------|----------|----------------|
File                        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------|----------|----------|----------|----------|----------------|
All files                   |      100 |      100 |      100 |      100 |                |
 js                         |      100 |      100 |      100 |      100 |                |
  jssm-util.js              |      100 |      100 |      100 |      100 |                |
  jssm.js                   |      100 |      100 |      100 |      100 |                |
 js/tests                   |      100 |      100 |      100 |      100 |                |
  array_transitions.js      |      100 |      100 |      100 |      100 |                |
  arrow.js                  |      100 |      100 |      100 |      100 |                |
  comment.js                |      100 |      100 |      100 |      100 |                |
  compile.js                |      100 |      100 |      100 |      100 |                |
  forced transitions.js     |      100 |      100 |      100 |      100 |                |
  general.js                |      100 |      100 |      100 |      100 |                |
  graph node lists.js       |      100 |      100 |      100 |      100 |                |
  histo.js                  |      100 |      100 |      100 |      100 |                |
  layout.js                 |      100 |      100 |      100 |      100 |                |
  machine_attributes.js     |      100 |      100 |      100 |      100 |                |
  machine_name.js           |      100 |      100 |      100 |      100 |                |
  parse actions.js          |      100 |      100 |      100 |      100 |                |
  parse.js                  |      100 |      100 |      100 |      100 |                |
  sample_select.js          |      100 |      100 |      100 |      100 |                |
  seq.js                    |      100 |      100 |      100 |      100 |                |
  sm_tag.js                 |      100 |      100 |      100 |      100 |                |
  stop light.js             |      100 |      100 |      100 |      100 |                |
  weighted_histo_key.js     |      100 |      100 |      100 |      100 |                |
  weighted_rand_select.js   |      100 |      100 |      100 |      100 |                |
  weighted_sample_select.js |      100 |      100 |      100 |      100 |                |
----------------------------|----------|----------|----------|----------|----------------|
```

## Observed Behavior
Move one test case into subdirectory.  Expect no change.

Only the test set now in the subdirectory is actually run.

```
John-Haugeland:tests johnhaugeland$ mkdir util
John-Haugeland:tests johnhaugeland$ mv histo.js util/

(in editor, twiddle histo.js reference from ../../../lib to ../../../../lib)

John-Haugeland:tests johnhaugeland$ npm run test

> jssm@5.8.0 test /Users/johnhaugeland/projects/jssm
> nyc ava src/js/tests/**/*.js


  4 passed
---------------|----------|----------|----------|----------|----------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------|----------|----------|----------|----------|----------------|
All files      |     7.07 |     1.01 |    15.56 |     6.15 |                |
 js            |      3.5 |     1.01 |        5 |     3.56 |                |
  jssm-util.js |    24.14 |    16.67 |    16.67 |    28.57 |... 21,31,47,55 |
  jssm.js      |     1.17 |        0 |        0 |     1.29 |... 821,828,835 |
 js/tests/util |      100 |      100 |      100 |      100 |                |
  histo.js     |      100 |      100 |      100 |      100 |                |
---------------|----------|----------|----------|----------|----------------|
John-Haugeland:tests johnhaugeland$ 
```

## Bonus Points! Code (or Repository) that Reproduces Issue

The repo that exhibits this behavior is [jssm](https://github.com/StoneCypher/jssm).  In this repo, `nyc` runs `ava` from the command `npm run test`, which executes `nyc ava src/js/tests/**/*.js` from [line 10 of package.json](https://github.com/StoneCypher/jssm/blob/master/package.json#L10).

A branch that has repro behavior [lives here](https://github.com/StoneCypher/jssm/tree/BrokenTestBehavior).

If you would like to manually repro from `master`:

1. Pull the `node` project [jssm](https://github.com/StoneCypher/jssm) or install from npm with `npm install jssm`
1. Go to where you pulled or installed `jssm`
1. Change the test runner script on [line 10 of package.json](https://github.com/StoneCypher/jssm/blob/master/package.json#L10) from `nyc ava src/js/tests/*.js` to `nyc ava src/js/tests/**/*.js` (the difference being the `/**` before the filename)
1. Create a subdirectory in `src/js/tests/` with your choice of name (I used `util`)
1. Move any test set of your choice into the subdirectory (I used `histo.js`)
1. Modify the moved test set's `require` of the built library from `const jssm = require('../../../build/jssm.es5.js');` to `const jssm = require('../../../../build/jssm.es5.js');` (that is, from three `../` to four) to reflect its new location on disk

You should now see the test rig focus solely on the test you moved into the subdirectory, which will continue to pass, and ignore the tests in the directory above it, causing coverage to drop to 7%.

## Forensic Information

**Operating System:** MacOS Sierra 10.12.4 .
**Environment Information:** [gisted](https://gist.github.com/StoneCypher/258adda3c5dcf47b97dbc6eacd2dfd57)

**Comment by bcoe** [comment]
@StoneCypher the appropriate tests run with that glob in ava, but are failing to show up in coverage report?

Perhaps see if you can reproduce with a failing test in the matching library itself:

https://github.com/istanbuljs/istanbuljs/tree/master/packages/test-exclude

**Comment by StoneCypher** [comment]
no

1) create test rig using glob to match test files.

2) produce large working test set across 20+ test files.  run and get complete coverage.

3) create subdirectory.  move one test file into subdirectory.  re-run.  only one test file in subdirectory is now executed; none in original directory are executed.

**Comment by StoneCypher** [comment]
also i really love your tool and am thankful for it

when i try to be terse to be clear, sometimes i sound butthurt.  i'm not.  nyc saves me hella time

**Comment by bcoe** [comment]
A quick work around might be to simply match both:

`ava src/js/tests/*.js src/js/tests/**/*.js`

I do think `**/*.js` should be matching 0 or more subfolders though (not 1 or more) so definitely seems like something worth putting a test case around. I think the problem might actually relate to AVA, it's the test runner itself not running all the tests as expected right?

**Comment by StoneCypher** [comment]
> A quick work around might be to simply match both:

my quick workaround is to just not organize my tests in subdirectories 😂

.

>  I think the problem might actually relate to AVA, it's the test runner itself not running all the tests as expected right?

I do not well understand the relationship between these tools.  That is plausible.  Should I re-file there?

**Comment by bcoe** [comment]
@StoneCypher sorry for not following up; yeah I believe it would be worth opening an issue on AVA, as I think this might be where the glob rule is behaving slightly differently.

**Comment by StoneCypher** [comment]
ok
