### ISSUE TITLE
Kindly help to understand this report behaviour

### ISSUE THREAD

**Issue by i0natan** [istanbuljs/nyc#675]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
In a report, number of lines should be equal or lower than the statements amount

## Observed Behavior
49% lines coverge, 3% statements, see image below

## Bonus Points! Code (or Repository) that Reproduces Issue
Image here:
[https://drive.google.com/open?id=0B3Fb7WBXXHqDczJCYTdjZXJtQzg](https://drive.google.com/open?id=0B3Fb7WBXXHqDczJCYTdjZXJtQzg)

## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.
 node --version - v8.2.1
npm version            
inflowzapi: '1.0.4',   
npm: '5.3.0',          
ares: '1.10.1-DEV',    
cldr: '31.0.1',        
http_parser: '2.7.0',  
icu: '59.1',           
modules: '57',         
node: '8.2.1',         
openssl: '1.0.2l',     
tz: '2017b',           
unicode: '9.0',        
uv: '1.13.1',          
v8: '5.8.283.41',      
zlib: '1.2.11' }

**Comment by bcoe** [comment]
I do think you could potentially have more statements than lines, if you had for instance a line that looked something like this:

`const x = 99; const y = 22; const q = 33`.

This is going to be 1 line and 3 statements. 3% vs 49% seems a bit extreme; but certainly possible.

Did you ever make any headway on this issue? I apologize for the slow response.

**Comment by JaKXz** [comment]
@i0natan could it be possible that you're instrumenting transpiled or minified code?
