### ISSUE TITLE
Issues with meta.loc.start.line when running lcov reports

### ISSUE THREAD

**Issue by juancarlosfarah** [istanbuljs/nyc#677]
## Summary

I'm instrumenting my code with `babel-plugin-istanbul`, then running some tests against a running server. I can get the tests to run fine and I output the resulting `window.__coverage__` object to a series of `*.json` files, that I then copy to `.nyc_output`. If I then run `nyc report --reporter=text-summary`, output is fine, without a problem. However, when I try to output an `lcov` report, I get the error posted under **Observed Behaviour**. 

## Expected Behavior

Running `nyc report --reporter=lcov` should produce an `lcov` report.

## Observed Behavior

Running `nyc report --reporter=lcov` produces an error:

```
/Users/juancarlosfarah/Git/siv/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:53
            line = meta.loc.start.line,
                           ^

TypeError: Cannot read property 'start' of undefined
```

I can see in my `*.json` files copied from the `window.__coverage__` object, that there is no `loc` property, although I do find `start` and `line`. [Here](https://gist.github.com/juancarlosfarah/bf608531ade333d0ba7f0e6ddb3a0091) is a sample `coverage.json` file. However, on the `*.json` files produced directly by `nyc`, I do see a `loc` property. I believe this error stems from this discrepancy.

## Bonus Points! Code (or Repository) that Reproduces Issue

Will try and prepare if necessary.

## Forensic Information

**Operating System:** macOS Sierra 10.12.6 (16G29)
**Environment Information:**

[nyc-environment-report.txt](https://gist.github.com/juancarlosfarah/86c3e8b0969d6220b6345478ce420c81)

**Comment by juancarlosfarah** [comment]
Found the issue! I actually had some old code that had been instrumented with Istanbul directly that was clearly not compatible with the `lcov` reporter from `nyc`. So when running the reports, it did not find the `loc` property. By removing that from the codebase and instrumenting everything with the `babel-plugin-istanbul` through `webpack`, the issue got resolved.

**Comment by bcoe** [comment]
@juancarlosfarah wonderful \o/ I apologize for the slow response, but am happy that you've got things worked out.

**Comment by marcoturi** [comment]
I'm have the same issue. Same error, but I have it only from bitbucket pipelines, and randomly.

```
npm info lifecycle ta-spotlight-fe@0.3.1~posttest: ta-spotlight-fe@0.3.1
npm info ok 
/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:53
            line = meta.loc.start.line,
                       ^
TypeError: Cannot read property 'loc' of undefined
    at /opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:53:24
    at Array.forEach (native)
    at LcovOnlyReport.onDetail (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:50:27)
    at LcovReport.(anonymous function) [as onDetail] (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
    at Visitor.(anonymous function) [as onDetail] (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
    at visitChildren (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/opt/atlassian/pipelines/agent/build/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:126:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bensaufley** [comment]
I'm encountering this issue, also with TypeScript, on [this repo](https://github.com/bensaufley/typeorm-api-base), [this branch](https://github.com/bensaufley/typeorm-api-base/tree/bs_authentication). It's intermittent, but pretty regular. Tests finish, and then I see this ([here's an example failure on CircleCI](https://circleci.com/gh/bensaufley/typeorm-api-base/10)):

```
/usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:54
            line = meta.loc.start.line,
                        ^

TypeError: Cannot read property 'loc' of undefined
    at /usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:54:25
    at Array.forEach (<anonymous>)
    at LcovOnlyReport.onDetail (/usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:50:27)
    at LcovReport.(anonymous function) [as onDetail] (/usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
    at Visitor.(anonymous function) [as onDetail] (/usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (<anonymous>)
    at visitChildren (/usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/usr/src/typeorm-api-base/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:126:5)
```

I inserted a `console.log` on L51 of `lcovonly/index.js`:

```js
if (!branchMap[key]) console.log(node, lines, branches, branchMap, key);
```

And what I get is this, consistently:

```
ReportNode {
  path: Path { v: [ 'graphql', 'types', 'Query.ts' ] },
  parent: 
   ReportNode {
     path: Path { v: [Array] },
     parent: 
      ReportNode {
        path: [Path],
        parent: null,
        fileCoverage: undefined,
        children: [Array],
        c_full: [CoverageSummary] },
     fileCoverage: undefined,
     children: [ [Circular], [ReportNode], [ReportNode], [ReportNode] ],
     c_full: CoverageSummary { data: [Object] } },
  fileCoverage: 
   FileCoverage {
     data: 
      { path: '/usr/src/typeorm-api-base/src/graphql/types/Query.ts',
        statementMap: [Object],
        fnMap: {},
        branchMap: {},
        s: [Object],
        f: {},
        b: [Object] } },
  children: [],
  c_full: 
   CoverageSummary {
     data: 
      { lines: [Object],
        functions: [Object],
        statements: [Object],
        branches: [Object] } } } { '3': 1 } { '0': [ 1, 1 ] } {} '0'
```

I don't know what to make of all that, but it points me to [Query.ts](https://github.com/bensaufley/typeorm-api-base/blob/master/src/graphql/types/Query.ts), which appears to have `lines` and `branches` but no `branchMap`. That file is simply this:

```ts
import { default as gql } from 'graphql-tag';

const Query = gql`
type Query {
  users: [User]
  user(id: String!): User
}
`;

export default Query;
```

It seems like it could be the template literal here? But another wrinkle is that it only started showing up on [this branch](https://github.com/bensaufley/typeorm-api-base/tree/bs_authentication), where `Query.ts` hasn't been modified.

Here's my [mocha.opts](https://github.com/bensaufley/typeorm-api-base/blob/bs_authentication/test/mocha.opts), for what it's worth:

```
--require ts-node/register
--require tsconfig-paths/register
--require source-map-support/register
--full-trace
test/**/*.spec.ts
```

And my [nycrc.json](https://github.com/bensaufley/typeorm-api-base/blob/bs_authentication/.nycrc.json):

```json
{
  "all": true,
  "exclude": [
    "src/index.ts",
    "src/migrations",
    "**/node_modules/**"
  ],
  "extension": [
    ".ts"
  ],
  "include": [
    "src/**/*.ts"
  ],
  "reporter": [
    "lcov",
    "text",
    "text-summary"
  ],
  "sourceMap": true,
  "instrument": true,
  "cache": false
}
```

It may not be related, but while coverage reports (when they succeed) work properly, stack traces with nyc don't appear to properly utilize sourceMaps: `at User.<anonymous> (/usr/src/typeorm-api-base/src/entities/User.ts:2:3164)`. Running mocha without `nyc` gives me the proper stack trace: `at User.<anonymous> (/usr/src/typeorm-api-base/src/entities/User.ts:103:21)`.

**Comment by bensaufley** [comment]
@bcoe or anyone else, any insight here? It doesn't happen every time, but it happens most times. More recent failures on CircleCI [here](https://circleci.com/gh/bensaufley/typeorm-api-base/17). Without changing anything in my code, just re-running my test suite, sometimes `branchMap` is empty and sometimes it isn't.

**Comment by chenzhh** [comment]
Hey guys, I want to  share you with my own experience.  Just delete the whole report folder and try again. It indeed resolved my issue.

**Comment by bensaufley** [comment]
@chenzhh by “report folder” do you mean nyc_output? I’ve been deleting nyc_output (and coverage fwiw) and using cache: false but I’m still getting this failure intermittently.

**Comment by pateketrueke** [comment]
Same here, it is working fine on Travis CI but suddenly I got the same error.

I noticed it appears as most people said: randomly but regularly.

> Just delete the whole report folder and try again.

I did it but it solved nothing on my case.

**Comment by blimmer** [comment]
I'm experiencing pretty much the same thing that @bensaufley is describing above in https://github.com/istanbuljs/nyc/issues/677#issuecomment-376024465 .

This is the error I get about 80% of the time:

```
/home/travis/build/src/my-code/node_modules/istanbul-reports/lib/lcovonly/index.js:52
        const line = meta.loc.start.line;
                          ^
TypeError: Cannot read property 'loc' of undefined
    at Object.keys.forEach.key (/home/travis/build/src/my-code/node_modules/istanbul-reports/lib/lcovonly/index.js:52:27)
    at Array.forEach (<anonymous>)
    at LcovOnlyReport.onDetail (/home/travis/build/src/my-code/node_modules/istanbul-reports/lib/lcovonly/index.js:49:27)
    at LcovReport.(anonymous function) [as onDetail] (/home/travis/build/src/my-code/node_modules/istanbul-reports/lib/lcov/index.js:20:23)
    at Visitor.(anonymous function) [as onDetail] (/home/travis/build/src/my-code/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/travis/build/src/my-code/node_modules/istanbul-lib-report/lib/tree.js:114:17)
    at getChildren.forEach.child (/home/travis/build/src/my-code/node_modules/istanbul-lib-report/lib/tree.js:118:15)
    at Array.forEach (<anonymous>)
    at ReportNode.Node.visit (/home/travis/build/src/my-code/node_modules/istanbul-lib-report/lib/tree.js:117:24)
    at getChildren.forEach.child (/home/travis/build/src/my-code/node_modules/istanbul-lib-report/lib/tree.js:118:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @src/my-code@0.5.0 test:unit: `NODE_ENV=test TS_NODE_PROJECT=./tests/unit/tsconfig.json nyc mocha --opts ./tests/unit/mocha.opts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @src/my-code@0.5.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-07-18T21_10_02_209Z-debug.log
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

I'm running ts-node and it seems to blow up when a gql tag is used (I've modified the mutation to obfuscate the code, but the problem occurs with this too):

```typescript
import gql from 'graphql-tag';

const myMutation = gql`
  mutation something(
    $var1: String!
    $var2: String!
    $var3: String!
    $var4: String!
    $var5: String!
    $var6: String!
    $var7: Boolean
  ) {
    track(
      events: [
        {
          var1: $var1
          var2: $var2
          var3: $var3
          var4: $var4
          var5: $var5
          var6: $var6
          var7: $var7
        }
      ]
    )
  }
`;
```

The line number it's erroring on is a conditional:

```typescript
  const url =
    process.env.NODE_ENV === 'production'
      ? 'https://example.com/foo'
      : 'https://example.com/bar';
```

I added a logging statement, similiar to above:

```typescript
if (!branchMap[key]) console.log(node, lines, branches, branchMap, key);
```

and this is the log message:

```
ReportNode {
  path: Path { v: [ 'my-file.ts' ] },
  parent:
   ReportNode {
     path: Path { v: [Array] },
     parent:
      ReportNode {
        path: [Path],
        parent: null,
        fileCoverage: undefined,
        children: [Array],
        c_full: [CoverageSummary] },
     fileCoverage: undefined,
     children:
      [ [ReportNode],
        [ReportNode],
        [ReportNode],
        [ReportNode],
        [Circular] ],
     c_full: CoverageSummary { data: [Object] } },
  fileCoverage:
   FileCoverage {
     data:
      { path:
         '/Users/blimmer/code/some-code/src/my-file.ts',
        statementMap: [Object],
        fnMap: [Object],
        branchMap: [Object],
        s: [Object],
        f: [Object],
        b: [Object] } },
  children: [],
  c_full:
   CoverageSummary {
     data:
      { lines: [Object],
        functions: [Object],
        statements: [Object],
        branches: [Object] } } } [Object: null prototype] { '8': 1, '25': 1, '26': 1, '39': 1, '42': 1, '43': 5, '44': 10 } { '0': [ 1, 1 ], '1': [ 1, 6 ] } { '0':
   { loc: { start: [Object], end: [Object] },
     type: 'cond-expr',
     locations: [ [Object], [Object] ],
     line: 39 } } '1'
```

When I quarantine the `gql` tag to its own file and `exclude` that file from the `nyc` config, I no longer get the error.

I'm trying to get a small repo that reproduces this issue, but I'm struggling to extract the exact code that triggers this behavior.

**Comment by staadecker** [comment]
I have the same issue as described in the comment. Also using Typescript. Any solutions?

**Comment by gugu** [comment]
Not a fix, but helped me:

Replace `"target": "es5/es6"` in your tsconfig with `"target": "esnext"`

By default, typescript makes a lot of unneeded changes in your code and it can screw up nyc's understanding of your code.

Modern versions of node.js do not need all these transformations

**Comment by dmbarreiro** [comment]
This [issue](https://github.com/istanbuljs/istanbuljs/issues/260) on istanbuljs helped me with this. Like many others I'm having the problem with typescript. 

As the [issue](https://github.com/istanbuljs/istanbuljs/issues/260) suggests I removed `--require ts-node/register` from mocha and added it to `nyc` require array like @coreyfarrell suggested and so far I haven't faced the error again (I've been trying to reproduce the issue for an hour when before I could easily have it in a couple of minutes).

Hopefully this helps solving some of the issues reported here.

**Comment by taitelman** [comment]
for me , what did the trick is to add into the packages.json nyc stanza: 
```"nyc": {
"include": [
      "src/**/*.js"
    ]
```

**Comment by hari-007** [comment]
I am still getting this issue. Here is the sample repository which reproduced this issue: https://github.com/hari-007/node-jasmine-nyc-sample

I even noticed this error pattern: For every test run of 2, 5, 7, 9 .... (tried up to 9). 

Here is the screenshot: 
![image](https://user-images.githubusercontent.com/5758223/71327153-02174400-24d3-11ea-9c7f-4b66c6bdbd6e.png)


I have 3 project which are recently converted from istanbul report to nyc. I don't have any issues with tests. All the projects test are working as expected and coverage also shows exactly source directory report (instead of including dist or spec directories **[like earlier issue](https://github.com/istanbuljs/nyc/issues/603#issuecomment-561780144)**) And those projects information:
-  Project 1 >>  **Typescript** + **Jasmine** + **nyc** 
- Project 2 >> contains 3 sets of code base
   - 1 >> ( **React** + **Babel**) + **Jamsine** + **nyc**
   - 2 >> ( **flowjs** + **Babel**) + **Jamsine** + **nyc**
   - 3 >> ( **Es6** + **Babel**) + **Jamsine** + **nyc**
- Project 3 >> **Es6** + **Babel** + **Jamsine** + **nyc**

**Comment by jackwry** [comment]
I have also been experiencing this issue too. As @dmbarreiro mentions; this [issue](https://github.com/istanbuljs/istanbuljs/issues/260) also adresses this problem (see this [comment](https://github.com/istanbuljs/istanbuljs/issues/260#issuecomment-458928605)).

For me, updating to nyc 15.0.0 resolved this issue.
