### ISSUE TITLE
`--all` does not include `.ts` files that use typecasting

### ISSUE THREAD

**Issue by nddeluca** [istanbuljs/nyc#679]
This one stumped me for a while on a typescript code base I added coverage too.  I wasn't seeing all my source files being included when using `--all`, and narrowed it down to files that use the `<T>` or `as T` typecasting syntax.  Seemed a bit strange, but I was able to set up a new repository and observe the issue in isolation (see below).

Note: This is only when using the `-all` flag.  If one of the files that is affected is included in a test, then it shows up in the coverage report.  Also, the typescript generic syntax (ex. `function<T>()`) does not have this issue either, so I don't believe it's related to the appearance of the brackets.

-----

## Expected Behavior

`--all` should include all `.ts` files

## Observed Behavior

`--all` does not include `.ts` files that use typecasting

## Bonus Points! Code (or Repository) that Reproduces Issue

See https://github.com/nddeluca/nyc-ts-test.

You can clone, `npm install`, and `npm test` to observe the issue.
There are three example `.ts` files named `a`, `b`, and `c`.

`a` gets included in the coverage report
`b` and `c` both use typecasting and get ignored.

If you edit the code and remove the typecasting, the files will show up in the coverage.

## Forensic Information

**Operating System:** the operating system you observed the issue on.

Darwin Kernel Version 16.3.0

**Environment Information:** information about your project's environment, see instructions below:

Node 8.4.0
NPM 5.3.0
Typescript 2.4.2

**Comment by bcoe** [comment]
@nddeluca `--all` needs to be able to parse all of the files as it walks them. How are you transpiling the source?

If you're using something like `typescript-register`, make sure that it's `nyc` that requires `typescript-register` rather than your test framework.

**Comment by Edo78** [comment]
I had the vary same problem and solved it moving the require of `ts-node/register` from mocha to nyc.

Maybe it should be documented or if it's already then it should be easier to find.

**Comment by jonaskello** [comment]
I'm using tape with typescript and have this same problem. If I move the `--require ts-node/register` to nyc instead of tape I get this error: `TypeError: Unable to require `.d.ts` file.`

This is the same error as in #504. Actually in that issue, the solution is to move `--require ts-node/register` from nyc to mocha, and in this issue it the solution is the other way around 😕

**Comment by jonaskello** [comment]
I found a solution to my problem above. It is to put `--require ts-node/register` in nyc and exclude `*.d.ts` files. So my .nycrc.json now looks like this:

```json
{
  "all": true,
  "include": ["src/*"],
  "exclude": ["src/index.ts", "**/*.d.ts"],
  "extension": [".ts"],
  "reporter": ["html", "lcov", "text"],
  "sourceMap": true,
  "require": ["ts-node/register"]
}
```

**Comment by Aqours** [comment]
@jonaskello how to include custom types when using `nyc mocha` ?

`global.d.ts` file included by tsconfig.json
```js
declare const DEBUG: boolean;
```

`index.ts`
```js
if (DEBUG) {
    console.log('debug');
}
```

It will throw an error `error TS2304: Cannot find name 'DEBUG'.` when I runing `nyc mocha`. It seems tsconfig.json not be used by ts-node. But it works fine if I put `--require ts-node/register` to mocha not nyc.

**Comment by JaKXz** [comment]
I've updated the [TS tutorial](https://istanbul.js.org/docs/tutorials/typescript/) that had some of the tips in here, with some of the newer tips. If you are able, please contribute to those docs :) https://github.com/istanbuljs/istanbuljs.github.io
