### ISSUE TITLE
Is that possible to get coverage from multiple mocha runs in together

### ISSUE THREAD

**Issue by soulbeing** [istanbuljs/nyc#681]
Please use the template provided below, when reporting bugs:

## Expected Behavior
So basically, I want to run my whole suit of mocha tests twice with different env variables, the way I run it is like the following

mocha env CONTEXT_PATH=' ' &&  mocha env CONTEXT_PATH='/wow/cool'

(because our test code base is very big, and Context_path effect the our code quite a bit, we don't want to double the test code volume, but still need to test both cases)

So I tried put nyc at the very beginning, then I get the coverage table for the first half only,
then I tried put nyc before each mocha, then I get the coverage table for each of them

I'm wondering if there anyway so that I can get a single coverage result table for both mocha tests altogether?

**Comment by ORESoftware** [comment]
yeah but you have to write the results to a different directory, for example

```
coverage/
   foo/
   bar/
```

you can give each of your separate runs a uuid if you want

**Comment by soulbeing** [comment]
but still I have separate numbers for my code coverage right? like for first case I got 80%, for second I got 85%,  I would imagine in together my coverage would reach 87 or something, so how can I get this value? any idea?

**Comment by bcoe** [comment]
@soulbeing you can combine several runs of `nyc` using the `--no-clean` option between runs. nyc itself does this, take a look here:

https://github.com/istanbuljs/nyc/blob/master/package.json#L14

Two test runs are executed, and then `report` is run to combine the results.
