### ISSUE TITLE
issues with line injection and obscure uses of ecmascript features

### ISSUE THREAD

**Issue by devsnek** [istanbuljs/nyc#685]
## Expected Behavior
parses all javascript normally and in an unopinionated way

## Observed Behavior
throws on `class Snekfetch extends (transport.extension || Object) {` because your injector thinks the leading and trailing parens are the ones it created
```js
class Snekfetch extends(cov_2rjobbskuk.b[58][0]++,transport.extension)||(cov_2rjobbskuk.b[58][1]++,Object){/**
```
https://github.com/devsnek/snekfetch/blob/76d9cbda468270b81c3306c9b490db5620054e59/src/index.js#L11

https://github.com/devsnek/snekfetch
**Operating System:** all of them
**Environment Information:**
node 8.5.0
npm 5.3.0
nyc 11.2.1

**Comment by bcoe** [comment]
Hey @devsnek thanks for the bug report. Are you using babel or any other transpilation libraries, or just vanilla JavaScript?

Assuming that you are using plain-old-JavaScript, this will likely be a bug we need to address in [istanbul-lib-instrument](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-lib-instrument).

**Comment by devsnek** [comment]
@bcoe I have no transformation of my code
