### ISSUE TITLE
NYC to work with ES6 code

### ISSUE THREAD

**Issue by basickarl** [istanbuljs/nyc#689]
I'm not sure I'm using this the way I should. I'm not using babel since Node v8.6.0 is fine with everything I've written.

Node: v8.6.0
NYX: v11.2.1
Mocha: v4.0.1

```
km@Karls-MBP ~/dev/main (master) $ node_modules/.bin/nyc --all report
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

**Comment by basickarl** [comment]
Istanbul under the hood, that should support it I guess.

**Comment by bcoe** [comment]
@basickarl could you share a repo that is having this issue? You should be using something closer to:

`nyc --all mocha test/*.js`

Report can be used to re-run reports after you've done a test run, but before you run report you should run tests once with `nyc` so that it collects coverage.

**Comment by patrick-walters-q2** [comment]
Running in to this same issue it appears, when changing `nyc mocha ./tests/**.*.js` to use the `--all` flag it fails for something else, looking in to it now but code is ES6 but not using babel for anything.

**Comment by NamanAulakh** [comment]
Same issue here, did anyone find the solution?

**Comment by patrick-walters-q2** [comment]
The solution did not work for me with NYC but with Istanbul I was able to get it working again. I dug around for an hour or so with nyc but I don't think the same settings are currently supported and it expects for everyone to use babel or TypeScript, not geared for native development using ES6 yet.

**Comment by robinyy** [comment]
Same issue here, although I'm using `nyc` + `babel-plugin-istanbul`.  What weird is https://github.com/bcoe/es2015-coverage/tree/master/coverage-babel works just fine (even after I upgrade nyc, mocha etc), would add more codes and change folder structures to investigate later

**Comment by coreyfarrell** [comment]
I'm closing this issue as we have not been given a link to any repository which reproduces this issue.  If anyone is still experiencing this issue with the latest version of nyc please open a new issue including a link to a minimal reproduction repository.
