### ISSUE TITLE
nyc needs running twice in order to generate coverage information

### ISSUE THREAD

**Issue by robertmain** [istanbuljs/nyc#690]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
Having been run once, `nyc` should generate a coverage report

## Observed Behavior
The first run reports "unknown" test coverage  
The second time, correctly reports 0% coverage (it's a new project)
The commands being executed are in `package.json` scripts. See below:
```json
"scripts": {
    "test": "./node_modules/.bin/nyc ./node_modules/.bin/_mocha --require ts-node/register -R spec test/**/*.ts",
    "posttest": "./node_modules/.bin/nyc report --reporter=json && ./node_modules/.bin/codecov -f coverage/*.json",
    "prebuild": "rm -rf dist",
    "build": "tsc"
},
```

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/robertmain/jukebox/tree/develop/

## Forensic Information

**Operating System:** Windows 10

**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:
`sh -c 'node --version; npm --version; npm ls' > output.txt`

2. share a gist with the contents of output.txt.  
https://gist.github.com/robertmain/06913a128701ee0249ac220a9352ae05

**Comment by bcoe** [comment]
Try moving ` --require ts-node/register ` to `nyc` rather than having `mocha` perform the instrumentation. If you then all add `--all` to `nyc`, I think it should solve both your problems.

**Comment by robertmain** [comment]
I actually ended up with this:
```json
"scripts": {
"test": "nyc --all _mocha --require ts-node/register -R spec test/**/*.ts",
"__coverage": "rm -rf coverage && nyc report",
"coverage:html": "npm run __coverage -- --reporter=html",
"coverage:json": "npm run __coverage -- --reporter=json",
"codecov": "npm run coverage:json && codecov -f coverage/*.json",
"prebuild": "rm -rf dist",
"build": "tsc"
}
```

which seems to have solved both my problems. Does that seem reasonable to you?

**Comment by JaKXz** [comment]
I'm going to close this issue with this link: https://istanbul.js.org/docs/tutorials/typescript/

Thank you for posting your solution - please do open a new issue if you are still having problems, with  links to reproduction of the problem.

**Comment by robertmain** [comment]
Oh nice! +1
