### ISSUE TITLE
nyc only reports coverage for included files

### ISSUE THREAD

**Issue by robertmain** [istanbuljs/nyc#691]
## Expected Behavior
All files under a given folder (for example `src/`) should be included in the coverage report with a coverage rating of "0%".

## Observed Behavior
Failure to `import` a given source file into a test file causes it to have no test coverage data generated.

## Bonus Points! Code (or Repository) that Reproduces Issue
http://github.com/robertmain/develop

## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:
`sh -c 'node --version; npm --version; npm ls' > output.txt`

2. share a gist with the contents of output.txt.
https://gist.github.com/robertmain/06913a128701ee0249ac220a9352ae05

**Comment by bcoe** [comment]
@robertmain if you run with `--all` this should do the trick for you. You will need to make sure that nyc performs the instrumentation step with `babel-register`, etc., so that it's able to understand ES2015 code in the files that it walks during the application of `--all`.

**Comment by robertmain** [comment]
@bcoe  I ran it with `all` in the config file and it didn't work. However, when I ran it with `--all` as you suggested it works correctly. Might want marking as a bug? :)

**Comment by coreyfarrell** [comment]
I just tried with `"nyc": {"all": true}` in my package.json it worked for me.  How are you setting the option in config?

**Comment by robertmain** [comment]
Command line

**Comment by coreyfarrell** [comment]
That also worked for me.  The links in this ticket are 404's so I can't look at your example repo but I'm not able to get `--all` to fail on command-line, in `package.json` or in `.nycrc`.
