### ISSUE TITLE
nyc with mocha-chrome

### ISSUE THREAD

**Issue by killmenot** [istanbuljs/nyc#707]
Hi,

Are anyone use nyc with [mocha-chrome](https://github.com/shellscape/mocha-chrome) for running tests? By some reason when I run coverage using mocha-chrome, it generates me empty results but tests are run

``` 
nyc --reporter=html --reporter=text mocha-chrome test/testrunner.html
```

**Comment by bcoe** [comment]
@killmenot mocha chrome is spinning up code in a headless browser, so the hooks that nyc has put in place for when you call `require` or spawn a subprocess would not be working. You have a couple options available to you.

1. I recommend looking at the library @mikeal has written [cappadonna](https://github.com/mikeal/cappadonna), it supports test coverage in a headless browser using Google's puppeteer.
2. alternatively, it might be worth looking at nyc's `instrument` feature; this allows you to preemptively instrument your files for coverage, before they're run in the browser. 

Feel free to ping me in Istanbul's community slack if you have any more questions:

http://devtoolscommunity.herokuapp.com/
