### ISSUE TITLE
Extend .nycrc exclude option with command line instead of overwriting it

### ISSUE THREAD

**Issue by Rush** [istanbuljs/nyc#709]
## Expected Behavior
.nycrc
```
{
  exclude: [ "foo1" ]
}
```
`nyc --exclude foo2 npm test`

Expect both `foo1` and `foo2` to be ignored

## Observed Behavior
Only `foo2` is ignored and the setting to ignore `foo1` is silently removed

**Comment by Rush** [comment]
I have several dirs that I test separately with the `--cwd` option and I need to provide a different set of excludes to each different directly. This results in very redundant set of npm scripts. Ideally list of excludes should just extend each other.

**Comment by bcoe** [comment]
@Rush have been a bit heads down working on some exciting stuff for a future release of Istanbul; Would love your help with a patch, if you're interested.

**Comment by isaacs** [comment]
I'm running into this with tap v11 as well.  I'd like to always exclude `tap-snapshots/*.js` by default, but adding that to the nyc bin command line makes it re-cover `test/**` and friends.

Maybe there could be an additional cli or .nycrc option to add an exclude without overwriting the existing setting?

**Comment by bcoe** [comment]
@isaacs @Rush there are definitely also situations where you want to replace the exclude rule, rather than append to the existing exclude rule. I like the idea of adding an additional command line option; what if we had something like `--append-exclude`; which appended rather than replacing?

@Rush any interest in implementing this?

**Comment by Rush** [comment]
I want to look at this but probably not in the next 2 weeks. If somebody could pick it up earlier it would be awesome 

Another syntax could be `--exclude +foo --exclude -bar`

**Comment by JaKXz** [comment]
This is a yargs feature, right?

**Comment by JaKXz** [comment]
@Rush @bcoe I'm going to close this issue because I think it's outside the scope of `nyc`. Please feel free to reopen if you disagree.
