### ISSUE TITLE
How to add a file using to include options when there is folder is exclude

### ISSUE THREAD

**Issue by tcelestino** [istanbuljs/nyc#721]
Hi guys,

I'm using to `.nycrc`  and I'm adding a folder in `exclude` options. But I need to add a specific file that on folder in `include` options. I've been trying add to file on `include` option, but it is show me on terminal:

![image](https://user-images.githubusercontent.com/190265/32796012-9b8ec41e-c954-11e7-8336-d33d04e70642.png)

Is it possible?

**Comment by bcoe** [comment]
👋 hey @tcelestino you should be able to do this:

```json
{
  "exclude": "lib/!(snuh.js)"
}```

Where `snuh.js` is the name of the file you don't want to exclude, and `lib` is the directory you want to exclude everything else in. Feel free to reopen if this doesn't do the trick for you.
