### ISSUE TITLE
'nyc --reporter=text' won't show all files info tested 

### ISSUE THREAD

**Issue by LeonDWong** [istanbuljs/nyc#723]
The cov script `cross-env nyc --reporter=text --reporter=lcov npm run test` & test script`cross-env NODE_ENV=test ava test/*.test.js --tap`i used to run can show all files(four files in /test). Somehow, i update one of my test case, then nyc result seems incomplete(only two files out of four files).

Here's nyc output:
![image](https://user-images.githubusercontent.com/17465046/32928618-bcd63efa-cb8d-11e7-802a-25241e69770a.png)
Here's my test directory:
![image](https://user-images.githubusercontent.com/17465046/32928641-e2af45d6-cb8d-11e7-988a-d73017eff9f4.png)

Could anyone help?

**Comment by bcoe** [comment]
@LeonDWong by default `nyc` does not show files in the test folder. In your configuration, provide an alternative `exclude` settings that do not include the `test` patterns, and this should do the trick for you:

https://github.com/istanbuljs/nyc#excluding-files

If you have any more questions, perhaps hop into chat:

http://devtoolscommunity.herokuapp.com/
