### ISSUE TITLE
SPAWN_WRAP_SHIM_ROOT variable setup requires spawn-wrap update 

### ISSUE THREAD

**Issue by sridharmallela** [istanbuljs/nyc#725]
This is an enhancement request!

## Expected Behavior

expected `nyc` to allow user set to a path where `spawn-wrap` shim files

## Observed Behavior

`nyc` errors out not able to create `spawn-wrap` temp directory on virtual machine with read only permissions to `$HOME` directory. 

```js
Error: EACCES: permission denied, mkdir '/home/****'
     at Error (native)
     at Object.fs.mkdirSync (fs.js:922:18)
     at sync (******/node_modules/nyc/node_modules/mkdirp/index.js:71:13)
     at Function.sync (******/node_modules/nyc/node_modules/mkdirp/index.js:77:24)
     at setup (******/node_modules/nyc/node_modules/spawn-wrap/index.js:405:10)
     at wrap (******/node_modules/nyc/node_modules/spawn-wrap/index.js:53:18)
     at Object.<anonymous> (******/node_modules/nyc/bin/nyc.js:57:3)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
```

## Bonus Points! Code (or Repository) that Reproduces Issue
`nyc` uses `spawn-wrap` version 1.3.8 as bundled dependency, but with the latest `spawn-wrap` @1.4.1 provides an ability to set `SPAWN_WRAP_SHIM_ROOT` variable to change `.node-spawn-wrap-*` directory location

## Forensic Information

**Operating System:** Linux.

```bash
$ nyc --version
11.3.0
$ node --version
v8.9.0
$ npm --version
5.5.1
```

*unfortunately due to our corporate policy, code or package details are not being reported.*

> i did update my fork with changes and tested it out, https://github.com/istanbuljs/nyc/compare/master...sridharmallela:master
> Will submit the PR, if you are ok with me contributing or my changes look good.

**Comment by bcoe** [comment]
@sridharmallela please take this for a spin:

`npm i nyc@next` -- you should see `11.4.0` with the updated `spawn-wrap`; this will go out soon once it's been tested on the `next` tag for a bit.

**Comment by sridharmallela** [comment]
@bcoe thanks for getting on to it, seems like there is an issue with `spawn-wrap` with nyc not able to run in windows or mac os. I have [created an issue](https://github.com/tapjs/spawn-wrap/issues/67), may be we might need to delay the release until it is fixed.
