### ISSUE TITLE
fix: string `//# sourceMappingURL=` breaking tests

### ISSUE THREAD

**Issue by zanona** [istanbuljs/nyc#726]
> This bug was initially reported on https://github.com/avajs/ava/issues/1595, however, it was confirmed this happened with mocha as well so it might be something happening with `nyc`.

## Expected Behavior

Files containing the string `//# sourceMappingURL=` to be tested without breaking.

## Observed Behavior

Apparently, there's a bug where files containing a string with the initial part of a sourcemap instruction, i.e: `//# sourceMappingURL=`, will fail to generate code coverage as well as being tested.

## Bonus Points! Code (or Repository) that Reproduces Issue

Repro: https://github.com/zanona/ava-sourcemap-fail

## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v8.7.0
darwin 16.7.0
ava --version > 0.23.0
npm --version > 5.5.1
```

**Comment by novemberborn** [comment]
I think the source map util used by nyc does a string search for the comment pattern. It doesn't generate an AST for the file.

If it's possible try breaking up the string, e.g. `'//# source' + 'MappingURL='` to avoid this problem.

**Comment by zanona** [comment]
thank @novemberborn. yep, that's why I have done so far to work around it, however, I believe the parser can be improved to only catch '//# sourceMappingURL=' on the beginning of lines, etc.

**Comment by novemberborn** [comment]
This is an upstream issue though, see https://github.com/thlorenz/convert-source-map/issues/60.

**Comment by zanona** [comment]
@novemberborn  Haha, oh my that's NPM 😜 It feels like "The Twelve Tasks of Asterix".
Thanks for pointing that out.

**Comment by zanona** [comment]
it seems this has now been fixed at https://github.com/thlorenz/convert-source-map/commit/46a6c17c1d58f72ab0f1934669670ed179f06c72 which sits under 1.5.1, so as long as nyc updates their dependencies, it's all good here as well.

**Comment by bcoe** [comment]
@zanona  thanks for tracking down this upstream bug.
