### ISSUE TITLE
Source-map ignored when reporting coverage for VS Code extension

### ISSUE THREAD

**Issue by TheRealPiotrP** [istanbuljs/nyc#728]
Folks, I'm on the last mile of incorporating Istanbul into my project and I need a bit of help.

I'm working on instrumenting [the C# extension](https://github.com/omnisharp/omnisharp-vscode/) for VS Code using Istanbul. I originally started with [this example](https://github.com/codecov/example-typescript-vscode-extension). This example works quite well, but assumes that mocha wireup occurs before VS Code loads an extension. That, unfortunately, is not always a fair assumption.

To ensure that my code is instrumented before invoked I chose to go with a build approach. Specifically, I:
* `tsc` my .ts files
* `nyc instrument` the resultant js files
* Run my tests
* report coverage data

All of this works today, except my coverage report is based on the `tsc`'d JS files instead of the source TS files.

I have already:
* Added `"inlineSourceMap": true` to `tsconfig.json`
* Passed to `nyc instrument` both `--source-map true` and `--require source-map-support/register`

Unfortunately, I'm grasping at straws at this point so I could use some insights.

## Expected Behavior
Report honors inline sourcemap and reports in terms of source .ts files

## Observed Behavior
Report ignores inline sourcemap and reports in terms of intermediate .js files
## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/TheRealPiotrP/omnisharp-vscode/tree/dev/piotrp/istanbul
* git clone
* cd omnisharp-vscode
* npm i
* npm cov
* nyc report

## Forensic Information
Inline source map exists in .js file. A different but similar source map is then added to the js file generated by `nyc instrument`. Specifically, the instrumented js file includes two source maps.

**Operating System:** OS X 10.13.1
**Environment Information:** 
https://gist.github.com/TheRealPiotrP/087c3112ebcee449de8ccb1894211e92

**Comment by bcoe** [comment]
@TheRealPiotrP I apologize for taking so long to provide feedback, had a particularly busy tail end of the year. Did you make any headway on this issue? I believe inline source-maps should work.

**Comment by DanTup** [comment]
I'm having the same issue. I've got coverage reports based on the JS files, but cannot get them translated to TS. My setup is basically the same as @TheRealPiotrP's above. Eg.:

I'm effectively doing this:

```
npm run compile
nyc instrument --require source-map-support/register --exclude-after-remap --cwd=out . .
nyc -e .ts --require source-map-support/register --exclude-after-remap --clean node ./out/test/test_all.js
```

In my test script, I use `signal-exit` to write the coverage data to disk (I couldn't get it working at all without this; I presume the way Code is loading the tests stops `nyc` from getting access to `__coverage__` to persist it).

The output from the above has my coverage based on JS files:

<details>
<summary>(output)</summary>
<pre><code>
-------------------------------------------|----------|----------|----------|----------|----------------|
File                                       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------------------|----------|----------|----------|----------|----------------|
All files                                  |    44.79 |    25.31 |    34.49 |     46.5 |                |
 Users/danny/Dev/Dart-Code/test            |      100 |    83.33 |      100 |      100 |                |
  test_all.ts                              |      100 |    83.33 |      100 |      100 |              6 |
 out/src                                   |    59.38 |    39.85 |    48.02 |    61.35 |                |
  analytics.js                             |     47.5 |    21.67 |    41.67 |     47.5 |... 152,153,155 |
  analyzer_status_reporter.js              |    54.55 |    38.46 |    38.46 |     54.9 |... 116,117,118 |
  config.js                                |    70.37 |       50 |    63.64 |    74.51 |... 63,64,65,66 |
  context.js                               |      100 |      100 |      100 |      100 |                |
  editors.js                               |       50 |        0 |        0 |       50 |          5,6,7 |
  extension.js                             |    68.35 |    45.26 |     37.5 |    70.34 |... 390,415,416 |
  file_change_handler.js                   |    62.96 |       50 |    83.33 |    62.96 |... 50,51,52,55 |
  open_file_tracker.js                     |       88 |       75 |       80 |    94.74 |             31 |
  project.js                               |    38.46 |        0 |        0 |    38.46 |... 11,12,13,15 |
  project_upgrade.js                       |    30.43 |     9.09 |    42.86 |    31.82 |... 65,66,68,69 |
  user_prompts.js                          |    31.11 |    26.32 |    16.67 |     35.9 |... 62,63,67,70 |
  utils.js                                 |     59.8 |    50.36 |    50.94 |    62.57 |... 331,332,335 |
 out/src/analysis                          |    37.44 |    18.06 |    25.77 |    38.07 |                |
  analyzer.js                              |    33.33 |    12.96 |       25 |    34.38 |... 193,195,196 |
  analyzer_gen.js                          |    40.98 |    33.33 |    26.15 |    40.98 |... 808,824,839 |
 out/src/commands                          |    22.36 |     1.92 |     5.22 |     24.8 |                |
  channels.js                              |    33.33 |        0 |        0 |       40 |... 14,18,19,20 |
  debug.js                                 |    29.63 |        0 |     8.57 |     35.4 |... 170,171,173 |
  edit.js                                  |    10.96 |        0 |      3.7 |    11.59 |... 107,109,114 |
  sdk.js                                   |    23.62 |     4.84 |     3.03 |    25.42 |... 171,175,176 |
  type_hierarchy.js                        |    14.29 |        0 |     7.14 |       15 |... 2,94,99,102 |
 out/src/debug                             |       34 |    24.07 |    31.25 |    35.05 |                |
  utils.js                                 |       34 |    24.07 |    31.25 |    35.05 |... 145,146,149 |
 out/src/decorations                       |    23.26 |     4.35 |     9.09 |    26.32 |                |
  closing_labels_decorations.js            |    23.26 |     4.35 |     9.09 |    26.32 |... 61,64,67,68 |
 out/src/flutter                           |       50 |     7.69 |       35 |    51.39 |                |
  device_manager.js                        |    44.19 |       10 |    18.18 |    46.34 |... 54,58,62,63 |
  flutter_daemon.js                        |    58.06 |        0 |    55.56 |    58.06 |... 44,45,47,48 |
 out/src/providers                         |    32.71 |    11.85 |     29.2 |    33.99 |                |
  assist_code_action_provider.js           |     62.5 |       50 |    57.14 |    71.43 |    12,21,25,26 |
  dart_completion_item_provider.js         |     4.63 |        0 |       10 |     4.67 |... 201,203,205 |
  dart_definition_provider.js              |    31.25 |        0 |    14.29 |    35.71 |... 20,26,27,28 |
  dart_diagnostic_provider.js              |    46.43 |     7.69 |       30 |    52.17 |... 40,43,47,48 |
  dart_document_symbol_provider.js         |    16.67 |        0 |    16.67 |    16.67 |... 44,52,53,54 |
  dart_formatting_edit_provider.js         |       80 |       50 |    85.71 |    84.62 |          19,22 |
  dart_highlighting_provider.js            |    14.29 |        0 |       20 |    14.29 |... 41,42,43,45 |
  dart_hover_provider.js                   |       80 |    68.57 |    66.67 |    85.11 |... 51,54,62,66 |
  dart_language_configuration.js           |      100 |      100 |      100 |      100 |                |
  dart_reference_provider.js               |    45.45 |      100 |    14.29 |    55.56 |    10,11,15,19 |
  dart_rename_provider.js                  |    10.42 |        0 |     7.14 |    10.64 |... 76,77,79,80 |
  dart_type_formatting_edit_provider.js    |    84.62 |       50 |    85.71 |    83.33 |          18,21 |
  dart_workspace_symbol_provider.js        |    22.22 |    27.27 |        0 |       30 |... 24,25,26,30 |
  debug_config_provider.js                 |    25.64 |        0 |       25 |    25.64 |... 54,55,56,57 |
  fix_code_action_provider.js              |       60 |       25 |    57.14 |    66.67 |... 23,27,28,29 |
  legacy_dart_workspace_symbol_provider.js |    12.07 |        0 |        5 |    12.28 |... 113,114,116 |
  legacy_debug_config_provider.js          |       75 |      100 |       50 |       75 |             12 |
  snippet_completion_item_provider.js      |       90 |       50 |       50 |       90 |          27,28 |
 out/src/pub                               |    60.71 |       50 |       40 |    60.71 |                |
  pub.js                                   |    60.71 |       50 |       40 |    60.71 |... 34,35,36,37 |
 out/src/sdk                               |    26.67 |        0 |       10 |    27.59 |                |
  sdk_manager.js                           |    26.67 |        0 |       10 |    27.59 |... 41,47,48,49 |
 out/src/services                          |       76 |    71.74 |       85 |    75.26 |                |
  stdio_service.js                         |       76 |    71.74 |       85 |    75.26 |... 155,156,158 |
 out/src/views                             |    37.33 |       20 |       50 |    38.36 |                |
  packages_view.js                         |    37.33 |       20 |       50 |    38.36 |... 117,118,119 |
 out/test                                  |    92.65 |       80 |    93.33 |    96.77 |                |
  helpers.js                               |     90.7 |    91.67 |    91.67 |     97.3 |              5 |
  test_all.js                              |       96 |     62.5 |      100 |       96 |             17 |
 out/test/flutter                          |       90 |       50 |      100 |       90 |                |
  index.js                                 |       90 |       50 |      100 |       90 |              8 |
 out/test/general                          |       90 |       50 |      100 |       90 |                |
  index.js                                 |       90 |       50 |      100 |       90 |              8 |
-------------------------------------------|----------|----------|----------|----------|----------------|
</code></pre>
</details>

Note: my `test_all.ts` script appears for both ts and js - that's the script invoked directly by nyc. However the other files that all show only as `.js` are the ones that I had to instrument and log myself.

My sourcemaps exist alongside my JS files and are referenced at the end of the js files. After instrumentation, the source maps have not changed at all (and the instrumented files still have the reference at the end).

I have tried every combination of command line args I can come up with based on all the things I've read in the issue tracker and online.

I don't really know enough about how this should work to debug further - I can't tell at what step things go wrong. For example, are the source maps from TypeScript good enough, or do they need updating for instrumented files? Should the coverage data in the output json reference the JS files or the TS files (who translates, the reporting or the recording?).

My current theory is that the source maps should be applied in memory in `__coverage__` before persisting to the json file? I'll keep digging, but any help would be appreciated!

**Comment by DanTup** [comment]
I finally got it working by using remap-istanbul. I found so many issues with these tools (both nyc and remap-istanbul seem to fail if you don't run them in the correct root of the project (`out/src`) even if you supply their `-cwd`/`-b` args.

Here's some sample output showing `.ts` tests:

https://travis-ci.org/Dart-Code/Dart-Code/jobs/350548276

**Comment by bcoe** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/24993, I'm interested in overhauling our TypeScript support and would love your feedback and requirements.

**Comment by DanTup** [comment]
I think most of my complications were really around the VS Code side of things rather than TypeScript. There's definitely some wonkiness around paths though; there were various tools I had to invoke in really weird folders to make things work (some of them let you provide a "base path" that claimed to fix this, but they totally don't work).

My repo (Dart-Code) is all set up and working now (you can clone it, `npm install` and `npm test` though it requires a Dart and Flutter SDK for the tests to run properly), you can see all the craziness to make it work here:

https://github.com/Dart-Code/Dart-Code/blob/75a1005d8216c9ca92c319d59e1ea8591ebf32e4/package.json#L788

**Comment by jedwards1211** [comment]
@DanTup I bet you'll have more luck using Babel to transpile your TS using `@babel/preset-typescript` and `babel-plugin-istanbul`?

**Comment by jedwards1211** [comment]
@bcoe since VSCode extension testing basically works by launching VSCode with the path to a JS file to execute the tests, it would be great if NYC had a well-documented JS API.  Unfortunately, given that the argument to `new NYC()` is the command-line arguments, it seems that NYC wasn't designed with anything other than the CLI in mind...

**Comment by jedwards1211** [comment]
Okay I got everything working using `@babel/preset-typescript` and `babel-plugin-istanbul` in my skeleton repo: https://github.com/jedwards1211/vscode-extension-skeleton

All I had to do was use a few NYC methods in the test runner, and run `nyc report` afterwards.

```ts
import path from 'path'
import Mocha from 'mocha'
import glob from 'glob'
import NYC from 'nyc'

export async function run(): Promise<void> {
  const nyc = new NYC()
  await nyc.createTempDirectory()
  // Create the mocha test
  const mocha = new Mocha({
    ui: 'tdd',
  })
  mocha.useColors(true)

  const testsRoot = path.resolve(__dirname, '..')

  const files: Array<string> = await new Promise((resolve, reject) =>
    glob(
      '**/**.test.js',
      {
        cwd: testsRoot,
      },
      (err, files) => {
        if (err) reject(err)
        else resolve(files)
      }
    )
  )

  // Add files to the test suite
  files.forEach(f => mocha.addFile(path.resolve(testsRoot, f)))

  const failures: number = await new Promise(resolve => mocha.run(resolve))
  await nyc.writeCoverageFile()

  if (failures > 0) {
    throw new Error(`${failures} tests failed.`)
  }
}
```

**Comment by DanTup** [comment]
@jedwards1211 

> @DanTup I bet you'll have more luck using Babel to transpile your TS using @babel/preset-typescript and babel-plugin-istanbul?

I'm not very familiar with babel, but adding more tools to fix something that shoul work without seems a bit extreme (and sadly also very common in JS).

My coverage is kinda broken right for other reasons anyway (I've split things into more shards as part of moving to GH actions so now need to merge the coverage results) so it's probably going to be overhauled soon anyway. It was already working through a huge bunch of kludges, so I may look for something better when I have a little more time.

**Comment by jedwards1211** [comment]
@DanTup 
> adding more tools to fix something that shoul work without seems a bit extreme 

Well if you use TS then you have to run istanbul on it afterwards and use this remap-istanbul tool, so it's really debatable which toolchain is better or worse.  At least when using Babel the remap step is unnecessary since TS transpilation and istanbul instrumentation are performed in a single step with a single source map output that doesn't need to be remapped.

**Comment by jedwards1211** [comment]
Actually the main awkwardness I've encountered so far with using babel is that its watch mode and error output don't integrate very cleanly with the `problemMatcher` configuration in the VSCode tasks.

**Comment by eriolchan** [comment]
> Okay I got everything working using `@babel/preset-typescript` and `babel-plugin-istanbul` in my skeleton repo: https://github.com/jedwards1211/vscode-extension-skeleton
> 
> All I had to do was use a few NYC methods in the test runner, and run `nyc report` afterwards.
> 
> ```ts
> import path from 'path'
> import Mocha from 'mocha'
> import glob from 'glob'
> import NYC from 'nyc'
> 
> export async function run(): Promise<void> {
>   const nyc = new NYC()
>   await nyc.createTempDirectory()
>   // Create the mocha test
>   const mocha = new Mocha({
>     ui: 'tdd',
>   })
>   mocha.useColors(true)
> 
>   const testsRoot = path.resolve(__dirname, '..')
> 
>   const files: Array<string> = await new Promise((resolve, reject) =>
>     glob(
>       '**/**.test.js',
>       {
>         cwd: testsRoot,
>       },
>       (err, files) => {
>         if (err) reject(err)
>         else resolve(files)
>       }
>     )
>   )
> 
>   // Add files to the test suite
>   files.forEach(f => mocha.addFile(path.resolve(testsRoot, f)))
> 
>   const failures: number = await new Promise(resolve => mocha.run(resolve))
>   await nyc.writeCoverageFile()
> 
>   if (failures > 0) {
>     throw new Error(`${failures} tests failed.`)
>   }
> }
> ```

@jedwards1211 Thanks for your solution. After I follows your steps, I meet with "TypeError: nyc_1.default is not a constructor" when I trigger "npm test". I have already added index.d.ts in typings/nyc, do you have any idea about it?
