### ISSUE TITLE
extending config breaks coverage

### ISSUE THREAD

**Issue by genepaul** [istanbuljs/nyc#732]
## Expected Behavior
Using `"extends": "./path/to/.nycrc"` should work the same as using all the configuration options in the same config.

## Observed Behavior
Using `"extends'` causes broken/unknown coverage - ignores any extended configs

## Bonus Points! Code (or Repository) that Reproduces Issue
http://github.com/genepaul/nyc-test

## Forensic Information

**Operating System:** Windows 7
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

https://gist.github.com/genepaul/b07ab7795a89dab1cc490b5a5593e93a

**Comment by genepaul** [comment]
This appeared to work in a previous version (10.x.x). After upgrading to latest (^11), it appears to have broken.

**Comment by genepaul** [comment]
from what I can tell, `yargs` seems to check that the file is `.json` to do the extend. But I am certain this works with `.nycrc` in `10.2.0` of nyc, so I'm not sure what changed.

**Comment by bcoe** [comment]
@genepaul I've landed your feature in yargs, and published it to the `next` tag:

`npm i yargs@next`

mind trying to upgrade yargs in nyc, and if the upstream fix works for you, we can publish a new version of nyc.

**Comment by genepaul** [comment]
@bcoe - I tested this on a project that had been breaking when upgrading nyc, and verified that extending configs works fine now.

**Comment by bcoe** [comment]
@genepaul great 👍 if you'd like to submit a patch with the yargs update, so that we don't forget, I'll get it landed soon.

**Comment by genepaul** [comment]
Done.

**Comment by Gopikrishna19** [comment]
@bcoe can we please have a release for this change?

**Comment by JaKXz** [comment]
This fix has been implemented
