### ISSUE TITLE
Typescript reports with error: property 'start' of undefined

### ISSUE THREAD

**Issue by ozum** [istanbuljs/nyc#733]
## Expected Behavior

Same report during repeated execution.

## Observed Behavior

I have a code with 100% coverage. Using typescript and without changing any file, when I execute `nyc` repeatedly, I get different coverage reports.

![screen shot 2017-11-30 at 14 21 26](https://user-images.githubusercontent.com/1497060/33428420-d31080b2-d5d9-11e7-81a9-66edafec03de.png)

![image](https://user-images.githubusercontent.com/1497060/33428439-e801e45c-d5d9-11e7-8f27-b1689fa8f6e9.png)

(See repo below) I executed `npm run test:cover` 6-7 times repeatedly and once every few I got reports below 100%. Reports below 100% has following error in HTML reports:

```js
Cannot read property 'start' of undefined
TypeError: Cannot read property 'start' of undefined
    at ...node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:50:29
    at Array.forEach ()
    at annotateStatements (...node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:46:33)
    at Object.annotateSourceCode (...node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:190:9)
    at HtmlReport.onDetail (...node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:217:39)
    at Visitor.(anonymous function) [as onDetail] (...node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (...node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at ...node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach ()
    at visitChildren (...node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
```

## Bonus Points! Code (or Repository) that Reproduces Issue

https://github.com/ozum/fix-set/tree/typescript-try

## Forensic Information

**Operating System:** MacOS 10.12.6
**Environment Information:**

node v9.2.0
npm v5.5.1
nyc v11.3.0 or nyc v11.4.0 (Repo has v11.4.0 in package.json)

**Comment by bcoe** [comment]
@ozum are you still running into this issue? I haven't been able to reproduce so far running `npm run test:cover`.

**Comment by ozum** [comment]
@bcoe, I was away from that code for a while. Currently, I also cannot reproduce. I'm closing this issue. I will open another ticket, if happens again.

Thanks,

**Comment by bcoe** [comment]
@ozum great, might have been something that was fixed upstream 👍

**Comment by ZehuaZhang** [comment]
I've encountered the same problem, I don't think it's a good practice just to close the bug rather than fixing it?

**Comment by alihassan0** [comment]
I have encountered the same problem as well. nyc keeps giving different results everytime I run it (alternating between 100% coverage & 50% coverage) and I am faced with the same error when it fails. (However I don't use typescript)

**Comment by coreyfarrell** [comment]
No action will be taken without a reproduction against latest nyc.  If you are experiencing an issue please post a new issue and include all required information.

**Comment by ZehuaZhang** [comment]
@coreyfarrell Thanks for the reply, I've created a ticket for it https://github.com/istanbuljs/nyc/issues/1124

**Comment by ZehuaZhang** [comment]
> I've encountered the same problem, I don't think it's a good practice just to close the bug rather than fixing it?

Why the downvote...
