### ISSUE TITLE
spawn wrap blocking release of 11.4.0

### ISSUE THREAD

**Issue by astorije** [istanbuljs/nyc#735]
v11.4.0 was released with the `dist-tag` of `next`, but `npm install` picks up `latest` (default). I added a comment at https://github.com/istanbuljs/nyc/commit/e8225d5223a93fd7fcb37b9f3f8baa17a415d5d5#commitcomment-25987704 about this. Sorry for the duplicate, but I figured a GitHub issue would be more suitable for communicating this.

You need to fiddle with `npm dist-tag add` and `npm dist-tag rm` to remove the current tag on v11.4.0 and assign the correct one. [This doc](https://docs.npmjs.com/cli/dist-tag) explains it well :)

Thanks a lot for your hard work!!

**Comment by bcoe** [comment]
@astorije I haven't released `v11.4.0` to latest yet, because there appears to be a Windows issue with `spawn-wrap`.

**Comment by bcoe** [comment]
see: https://github.com/tapjs/spawn-wrap/issues/67

**Comment by bcoe** [comment]
CC: @sridharmallela

**Comment by astorije** [comment]
Aaah, my bad, I could have sworn this was a npm publish snafu (this is far from an impossible situation to end up in!). Sorry for the patronization then :)

**Comment by sridharmallela** [comment]
@bcoe as `spawn-wrap`, v1.4.2 resolves shebang issue, can you publish new nyc version, since 11.4 has  `spawn-wrap` as bundled dependency.

**Comment by codler** [comment]
![screen shot 2017-12-07 at 09 57 34](https://user-images.githubusercontent.com/102052/33706676-24ca945a-db35-11e7-9ca5-d0f912c37763.png)

**Comment by bcoe** [comment]
@sridharmallela @astorije @codler could you please give `nyc@11.4.1` a try?

**Comment by astorije** [comment]
FYI @bcoe 11.4.0 was fine for me, the missing piece was the complete release.

Things still look 👌 on 11.4.1 :)
