### ISSUE TITLE
How to use this in travis?

### ISSUE THREAD

**Issue by Delagen** [istanbuljs/nyc#737]
Please use the template provided below, when reporting bugs:
-----

package.json
```
{
...
	"scripts": {
		"_mocha": "_mocha \"spec/*.spec.js\"",
		"test": "npm run test-cov",
		"test-cov": "nyc --require @babel/register --exclude dist/** --exclude spec/** --reporter text npm run -s _mocha"
	},
	"devDependencies": {
		"@babel/core": "^7.0.0-beta.34",
		"@babel/plugin-transform-runtime": "^7.0.0-beta.34",
		"@babel/preset-env": "^7.0.0-beta.34",
		"@babel/register": "^7.0.0-beta.34",
		"coveralls": "^3.0.0",
		"eslint": "^4.12.1",
		"mocha": "~4.0.1",
		"nyc": "^11.4.0"
	},
...
}
```

```
> nyc --require @babel/register --exclude dist/** --exclude spec/** --reporter text npm run -s _mocha


internal/child_process.js:323

    throw errnoException(err, 'spawn');

    ^


Error: spawn EACCES

    at _errnoException (util.js:1024:11)

    at ChildProcess.spawn (internal/child_process.js:323:11)

    at ChildProcess.wrappedSpawn [as spawn] (.../node_modules/nyc/node_modules/spawn-wrap/index.js:92:15)

    at exports.spawn (child_process.js:502:9)

    at module.exports (.../node_modules/nyc/node_modules/foreground-child/index.js:39:15)

    at Object.<anonymous> (.../node_modules/nyc/bin/nyc.js:65:3)

    at Module._compile (module.js:635:30)

    at Object.Module._extensions..js (module.js:646:10)

    at Module.load (module.js:554:32)

    at tryModuleLoad (module.js:497:12)
```

## Expected Behavior
No errors
## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

https://travis-ci.org/epoberezkin/ajv-merge-patch/builds/312396270

**Comment by Delagen** [comment]
Strange but the same works in https://travis-ci.org/mysticatea/cpx

**Comment by bcoe** [comment]
@Delagen not quite sure what's happening to you, but I believe it's related to glob pattern expansion, the following works:

`"test-cov": "nyc --exclude 'dist/**' --exclude 'spec/**' --reporter text npm run test-spec"`

I'd be tempted to pull the configuration options into either a `.nycrc` or the `nyc` stanza in your package.json, which should eliminate this category of bug.

**Comment by Delagen** [comment]
@bcoe no, it's looks like Spawn of processes is restricted, so it's not config related, it's works locally fine
