### ISSUE TITLE
Error with windows + nyc + execFileSync + bash + node

### ISSUE THREAD

**Issue by pangrr** [istanbuljs/nyc#738]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
No error.
## Observed Behavior
`nyc mocha` on source file with` execFileSync('bash', ['-c', 'node --version'])` results in error:

`bash: /c/Users/xxx/.node-spawn-wrap-42508-a62de97b29d7/node: C:\Program: bad interpreter: No such file or directory`

No error in linux.

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/pangrr/demo-nyc_exec_bash_node_error

## Forensic Information

**Operating System:** the operating system you observed the issue on.

windows 7

**Environment Information:** information about your project's environment, see instructions below:

node 8.7.0
GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
nyc 11.3.0
mocha 4.0.1

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

**Comment by pangrr** [comment]
it's due to spawn-wrap.js

**Comment by gucong3000** [comment]
Related: https://github.com/tapjs/spawn-wrap/pull/70

**Comment by gucong3000** [comment]
I think we should reopen this issue until spawn-wrap solves the problem and updates the dependencies.

**Comment by gucong3000** [comment]
This problem still continues to be reproduced today.

**Comment by gucong3000** [comment]
@pangrr Will you please reopen this issue until it is repaired and then closed?

**Comment by gucong3000** [comment]
Related: https://github.com/tapjs/spawn-wrap/pull/76

**Comment by msm1089** [comment]
I am getting this error:

$ nyc --reporter=html --reporter=text yarn run test

/c/Program Files (x86)/Yarn/bin/yarn: /c/Users/XXX/.node-spawn-wrap-13208-21ee5d328e1d/node: C:\Program: bad interpreter: No such file or directory
/c/Program Files (x86)/Yarn/bin/yarn: line 19: /c/Users/XXX/.node-spawn-wrap-13208-21ee5d328e1d/node: No error
/c/Program Files (x86)/Yarn/bin/yarn: /c/Users/XXX/.node-spawn-wrap-13208-21ee5d328e1d/node: C:\Program: bad interpreter: No such file or directory
/c/Program Files (x86)/Yarn/bin/yarn: line 19: /c/Users/XXX/.node-spawn-wrap-13208-21ee5d328e1d/node: No error

Could this be reopened please?

Operating System: the operating system you observed the issue on.
Windows 10

Environment Information: information about your project's environment
[output.txt](https://github.com/istanbuljs/nyc/files/2999345/output.txt)
