### ISSUE TITLE
NPM is out of date

### ISSUE THREAD

**Issue by BrandonZacharie** [istanbuljs/nyc#739]
## Expected Behavior
nyc 11.4.0 to be latest on NPM
## Observed Behavior
nyc 11.3.0 is latest on NPM
## Forensic Information
https://www.npmjs.com/package/nyc
```
➜  npm outdated
Package  Current  Wanted  Latest  Location
nyc       11.4.0  11.4.0  11.3.0  example
```
**Operating System:**
MacOS High Sierra

**Environment Information:**
node v8.9.1
npm 5.6.0

**Comment by bcoe** [comment]
will release update soon, was waiting on upstream fix to spawn-wrap.
