### ISSUE TITLE
Problem with symlinks

### ISSUE THREAD

**Issue by tomasruud** [istanbuljs/nyc#741]
## Expected Behavior
I usually run tests using the script `cross-env NODE_ENV=test nyc tape ./lib/**/*.spec.js | faucet`. And when doing this from the actual directory of my project, the coverage and reports shows correct results.

## Observed Behavior
Running this command from a symlinked directory on Windows produces 0% coverage.

## Forensic Information

**Operating System:** Windows
**Environment Information:**
https://gist.github.com/tomasruud/6c6585ea93ca8ddfec959521c46f8685

**Comment by tomasruud** [comment]
Accidentally posted to early

**Comment by JaKXz** [comment]
Sorry for the late reply @tomasruud - are you still experiencing this issue [with the latest version of nyc]? Are you able to share a repo that reproduces the problem?

**Comment by tomasruud** [comment]
I'm not sure to be honest. I see that we've moved this project to `^13.0.0` of nyc, so I guess it's working, but I haven't tried it in a long time.
