### ISSUE TITLE
Coverage reports don't include TS files unless explicitly compiled

### ISSUE THREAD

**Issue by lumaxis** [istanbuljs/nyc#742]
## Expected Behavior

When running `nyc` with `mocha` which is using `ts-node` to transpile TypeScript files on the fly, TypeScript files should be part of the coverage report.

## Observed Behavior

`nyc` is only generating coverage output for the only `.js` file in my project:

```
-------------|----------|----------|----------|----------|----------------|
File         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------|----------|----------|----------|----------|----------------|
All files    |    52.37 |    29.71 |    75.61 |    52.37 |                |
 file.js     |    52.37 |    29.71 |    75.61 |    52.37 |... 759,764,766 |
-------------|----------|----------|----------|----------|----------------|

=============================== Coverage summary ===============================
Statements   : 52.37% ( 210/401 )
Branches     : 29.71% ( 71/239 )
Functions    : 75.61% ( 31/41 )
Lines        : 52.37% ( 210/401 )
```

It however works when I first manually compile all my files using `tsc` and then it even shows the actual `.ts` files, not only the `.js` files.

## Forensic Information

**Operating System:** macOS 10.13.1
**Environment Information:** https://gist.github.com/lumaxis/cd33c2bbf98dab6e4f5dcc9ff6bf5984

### `.nycrc`
```json
{
    "all": true,
    "cache": false,
    "exclude": [
        "coverage",
        "**/editor.js",
        "**/gulpfile.js",
        "**/tasks.js",
        "**/test/**",
        "**/*_test.js"
    ],
    "extensions": [
        ".js",
        ".ts"
    ],
    "report-dir": "./coverage",
    "reporter": [
        "cobertura",
        "html",
        "text",
        "text-summary"
    ],
    "temp-directory": "./coverage/.nyc_output"
}
```

### mocha.opts
```
--exit
--reporter spec
--require dotenv/config
--require ts-node/register
--slow 200
--timeout 4000
```

**Comment by lumaxis** [comment]
I think I solved this by reducing the config file to
```json
{
    "cache": true,
    "extensions": [
        ".ts"
    ],
    "report-dir": "./coverage",
    "reporter": [
        "cobertura",
        "html",
        "text",
        "text-summary"
    ],
    "temp-directory": "./coverage/.nyc_output"
}
```
Especially removing `"all": true` and `"extensions": [ ".js" ]` seemed to be important. Not sure why it is mentioned in https://istanbul.js.org/docs/tutorials/typescript/ but it appears I need neither them nor `source-map-support/register` to get a working `mocha` & TypeScript setup.

**Comment by bcoe** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/24993, I'm interested in overhauling our TypeScript support and would love your feedback and requirements.

**Comment by kleinfreund** [comment]
@lumaxis The extension configuration key for nyc is `extension`, not `extensions` which is very confusing. Could you update your posts so that other people have a chance to solve this issue, please?

**Comment by kleinfreund** [comment]
@lumaxis Oh, it is relevant. I need the following in my package.json for nyc to recognize the TypeScript source files I’m testing with ava.

```json
"nyc": {
  "extension": [
    ".ts"
  ]
}
```

**Comment by bcoe** [comment]
@kleinfreund seems like maybe we could add another tutorial to https://istanbul.js.org/ and/or a note in the README about needing to support `.ts` extensions?

I'd argue this specific issue can be closed though; want to go ahead and open an issue if you think it's worthwhile, or heck, would happily take a pull request.

**Comment by JaKXz** [comment]
@lumaxis would you mind trying something like this? https://github.com/istanbuljs/istanbuljs/pull/282
