### ISSUE TITLE
support question - from istanbul to nyc

### ISSUE THREAD

**Issue by ORESoftware** [istanbuljs/nyc#746]
I have this StackOverflow question:

https://stackoverflow.com/questions/47763448/nyc-equivalent-of-istanbul-command

I am trying to convert my existing `istanbul` commands to `nyc`, but I am having some trouble. Please help, will upvote, thanks

**Comment by bcoe** [comment]
@ORESoftware :wave: to combine multiple reports you can use the `report` command (we do this for nyc's own test suite):

https://github.com/istanbuljs/nyc/blob/master/package.json#L14

Passing `--no-clean` to nyc when starting the second test run results in the `.nyc_output` directory not being reset, such that reports from multiple test runs will be combined.
