### ISSUE TITLE
--reporter=html reports only a subset of output of --report=text

### ISSUE THREAD

**Issue by lsiden** [istanbuljs/nyc#752]
## Expected Behavior
I expect --reporter=html and --reporter=text to report the same files.

## Observed Behavior
--reporter=html reports only a subset of the files.

## Bonus Points! Code (or Repository) that Reproduces Issue
 version 11.3.0

## Forensic Information
Mac OS 10.13.2

[output.txt](https://github.com/istanbuljs/nyc/files/1569371/output.txt)

**Comment by bcoe** [comment]
@lsiden this sounds quite odd -- any chance that you could provide a link to a repo that reproduces this issue; one thought, the HTML report nests files by folder, I wonder if some of the files are nested in a folder and being missed?
