### ISSUE TITLE
Instrumenting files on the fly

### ISSUE THREAD

**Issue by ORESoftware** [istanbuljs/nyc#753]
I filed this issue at the old istanbul repo, since this is a command line feature request, thought I should move it here.

https://github.com/gotwarlost/istanbul/issues/855

say we have an Express server:

```js
app.use(function(req,res,next){
    const k = cp.spawn('istanbul instrument');
    fs.createReadStream('foo.js').pipe(k.stdin).pipe(res);
});
```

is there a way to instrument a file like this on the fly, and serve it to the browser?

**Comment by bcoe** [comment]
@ORESoftware istanbul (the library that nyc builds on top of) exposes an API for instrumenting files; you can see the API in action here:

https://github.com/devongovett/browserify-istanbul/blob/f87ccb1bfee4561bb136d83d418435645fdc04aa/index.js#L29

use this as a starting point, and you should be able to pull off what you're looking for.

**Comment by ORESoftware** [comment]
thx seems like a streaming API is not that useful, since istanbul instruments an entire file at once
