### ISSUE TITLE
Istanbuljs ignore a file on coverage report

### ISSUE THREAD

**Issue by marcodsx** [istanbuljs/nyc#755]
Hi, I tried to test some mocha-chai-nyc feature to figure out how to use them for my work. I found a tutorial to understand mocha-chai on https://semaphoreci.com/community/tutorials/getting-started-with-node-js-and-mocha. I followed that tutorial and rebuild the app converter and test proposed by the tutorial.

You can find my project on https://github.com/marcodsx/converter-mocha-chai

It works and if you have nyc, chai and mocha installed globally you can clone repository and:
- start app/server.js by running "node app/server.js"
- run "mocha" and note that we have 6 working tests that pass.

You know if you run "**nyc mocha**" you have also the coverage report, I found the issue in the report.

**It seems that a file in my project is ignored from report.** In this case the file ignored is app/server.js
I expect that also that file should compare on report but not. I don't know if this is an issue or a limit. Could you please check and give me an answer?
Thanks & Happy Christmas :santa:
Marcods

## Forensic Information
**Operating System**: I working on kubuntu 16.04
**Environment Information:**
v9.2.0
5.6.0
converter@1.0.0 /home/marcods/HIGECO/personal/progetti/nodetesting/converter/github/converter-mocha-chai
├─┬ chai@4.1.2
│ ├── assertion-error@1.0.2
│ ├── check-error@1.0.2
│ ├─┬ deep-eql@3.0.1
│ │ └── type-detect@4.0.5 deduped
│ ├── get-func-name@2.0.0
│ ├── pathval@1.1.0
│ └── type-detect@4.0.5
├─┬ express@4.16.2
│ ├─┬ accepts@1.3.4
│ │ ├── mime-types@2.1.17 deduped
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├─┬ body-parser@1.18.2
│ │ ├── bytes@3.0.0
│ │ ├── content-type@1.0.4 deduped
│ │ ├── debug@2.6.9 deduped
│ │ ├── depd@1.1.1 deduped
│ │ ├─┬ http-errors@1.6.2
│ │ │ ├── depd@1.1.1 deduped
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── setprototypeof@1.0.3
│ │ │ └── statuses@1.3.1 deduped
│ │ ├── iconv-lite@0.4.19
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── qs@6.5.1 deduped
│ │ ├─┬ raw-body@2.3.2
│ │ │ ├── bytes@3.0.0 deduped
│ │ │ ├── http-errors@1.6.2 deduped
│ │ │ ├── iconv-lite@0.4.19 deduped
│ │ │ └── unpipe@1.0.0 deduped
│ │ └── type-is@1.6.15 deduped
│ ├── content-disposition@0.5.2
│ ├── content-type@1.0.4
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── depd@1.1.1
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.1
│ ├─┬ finalhandler@1.1.0
│ │ ├── debug@2.6.9 deduped
│ │ ├── encodeurl@1.0.1 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── parseurl@1.3.2 deduped
│ │ ├── statuses@1.3.1 deduped
│ │ └── unpipe@1.0.0
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.2
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@2.0.2
│ │ ├── forwarded@0.1.2
│ │ └── ipaddr.js@1.5.2
│ ├── qs@6.5.1
│ ├── range-parser@1.2.0
│ ├── safe-buffer@5.1.1
│ ├─┬ send@0.16.1
│ │ ├── debug@2.6.9 deduped
│ │ ├── depd@1.1.1 deduped
│ │ ├── destroy@1.0.4
│ │ ├── encodeurl@1.0.1 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── etag@1.8.1 deduped
│ │ ├── fresh@0.5.2 deduped
│ │ ├── http-errors@1.6.2 deduped
│ │ ├── mime@1.4.1
│ │ ├── ms@2.0.0 deduped
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── range-parser@1.2.0 deduped
│ │ └── statuses@1.3.1 deduped
│ ├─┬ serve-static@1.13.1
│ │ ├── encodeurl@1.0.1 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── parseurl@1.3.2 deduped
│ │ └── send@0.16.1 deduped
│ ├── setprototypeof@1.1.0
│ ├── statuses@1.3.1
│ ├─┬ type-is@1.6.15
│ │ ├── media-typer@0.3.0
│ │ └── mime-types@2.1.17 deduped
│ ├── utils-merge@1.0.1
│ └── vary@1.1.2
├─┬ mocha@4.0.1
│ ├── browser-stdout@1.3.0
│ ├── commander@2.11.0
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0 deduped
│ ├── diff@3.3.1
│ ├── escape-string-regexp@1.0.5
│ ├─┬ glob@7.1.2
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ ├── once@1.4.0 deduped
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3
│ │ ├─┬ minimatch@3.0.4
│ │ │ └─┬ brace-expansion@1.1.8
│ │ │   ├── balanced-match@1.0.0
│ │ │   └── concat-map@0.0.1
│ │ ├─┬ once@1.4.0
│ │ │ └── wrappy@1.0.2 deduped
│ │ └── path-is-absolute@1.0.1
│ ├── growl@1.10.3
│ ├── he@1.1.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └─┬ supports-color@4.4.0
│   └── has-flag@2.0.0
└─┬ request@2.83.0
  ├── aws-sign2@0.7.0
  ├── aws4@1.6.0
  ├── caseless@0.12.0
  ├─┬ combined-stream@1.0.5
  │ └── delayed-stream@1.0.0
  ├── extend@3.0.1
  ├── forever-agent@0.6.1
  ├─┬ form-data@2.3.1
  │ ├── asynckit@0.4.0
  │ ├── combined-stream@1.0.5 deduped
  │ └── mime-types@2.1.17 deduped
  ├─┬ har-validator@5.0.3
  │ ├─┬ ajv@5.5.2
  │ │ ├── co@4.6.0
  │ │ ├── fast-deep-equal@1.0.0
  │ │ ├── fast-json-stable-stringify@2.0.0
  │ │ └── json-schema-traverse@0.3.1
  │ └── har-schema@2.0.0
  ├─┬ hawk@6.0.2
  │ ├─┬ boom@4.3.1
  │ │ └── hoek@4.2.0 deduped
  │ ├─┬ cryptiles@3.1.2
  │ │ └─┬ boom@5.2.0
  │ │   └── hoek@4.2.0 deduped
  │ ├── hoek@4.2.0
  │ └─┬ sntp@2.1.0
  │   └── hoek@4.2.0 deduped
  ├─┬ http-signature@1.2.0
  │ ├── assert-plus@1.0.0
  │ ├─┬ jsprim@1.4.1
  │ │ ├── assert-plus@1.0.0 deduped
  │ │ ├── extsprintf@1.3.0
  │ │ ├── json-schema@0.2.3
  │ │ └─┬ verror@1.10.0
  │ │   ├── assert-plus@1.0.0 deduped
  │ │   ├── core-util-is@1.0.2
  │ │   └── extsprintf@1.3.0 deduped
  │ └─┬ sshpk@1.13.1
  │   ├── asn1@0.2.3
  │   ├── assert-plus@1.0.0 deduped
  │   ├─┬ bcrypt-pbkdf@1.0.1
  │   │ └── tweetnacl@0.14.5 deduped
  │   ├─┬ dashdash@1.14.1
  │   │ └── assert-plus@1.0.0 deduped
  │   ├─┬ ecc-jsbn@0.1.1
  │   │ └── jsbn@0.1.1 deduped
  │   ├─┬ getpass@0.1.7
  │   │ └── assert-plus@1.0.0 deduped
  │   ├── jsbn@0.1.1
  │   └── tweetnacl@0.14.5
  ├── is-typedarray@1.0.0
  ├── isstream@0.1.2
  ├── json-stringify-safe@5.0.1
  ├─┬ mime-types@2.1.17
  │ └── mime-db@1.30.0
  ├── oauth-sign@0.8.2
  ├── performance-now@2.1.0
  ├── qs@6.5.1 deduped
  ├── safe-buffer@5.1.1 deduped
  ├── stringstream@0.0.5
  ├─┬ tough-cookie@2.3.3
  │ └── punycode@1.4.1
  ├─┬ tunnel-agent@0.6.0
  │ └── safe-buffer@5.1.1 deduped
  └── uuid@3.1.0

**Comment by bcoe** [comment]
@marcodsx looking at your testing repo, I believe the expectation is that I would start the server in a separate process and then run the tests which interact with it? in this scenario, coverage _will not_ be collected for `server.js` -- because it is running in a separate process that has not instrumented the code with coverage.

You can fix this! rather than starting the server separately, start the server in a `before` statement in your tests, and shut it down in an `after` statement; I do something similar here:

https://github.com/npm/oauth2-server-pg/blob/master/test/server.js#L17

although in restify rather than express.

This is similar to the problem that @SuperFun99 describes [here](https://github.com/istanbuljs/nyc/issues/762) I might pull together a tutorial for testing express and put it up on the website for folks to reference (the link to `oauth2-server-pg` should be a good starting point).

**Comment by JaKXz** [comment]
closing in favour of https://github.com/istanbuljs/istanbuljs.github.io/issues/140
