### ISSUE TITLE
Coverage unknown after following README and #374.

### ISSUE THREAD

**Issue by mikethehud** [istanbuljs/nyc#761]
## Expected Behavior

Coverage report.

## Observed Behavior

```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

I have followed all the steps in the [README](https://github.com/istanbuljs/nyc/blob/master/README.md#use-with-babel-plugin-istanbul-for-babel-support) as well as in https://github.com/istanbuljs/nyc/issues/374

Maybe I'm missing something trivial?

## Bonus Points! Code (or Repository) that Reproduces Issue

[Repo](https://github.com/mikethehud/react-selekt/tree/coverage-fixes)

## Forensic Information

**Operating System:** Windows 10
**Environment Information:** https://gist.github.com/mikethehud/771816b64ed9f7b1bf94d9389dd0a519

**Comment by bcoe** [comment]
@mikethehud sorry for the slow reply -- there's been a little bit of a backlog in my ability to keep up with open-source recently.

Are you still running into issues? I cloned your repo and seem to be getting coverage information.

**Comment by mikethehud** [comment]
Yeah I managed to get the coverage running but I now get the `constructor {` highlight as mentioned in https://github.com/istanbuljs/nyc/issues/374. I followed all the steps you outlined there, still getting 98% on the branches though.

Just commited to master with the new coverage: https://github.com/mikethehud/react-selekt

**Comment by sridharmallela** [comment]
@mikethehud -- how did you resolve `unknown` coverage ?

**Comment by jwalton** [comment]
Aha!  I was running into this, and I think I found the culprit.  babel-register will cache compiled code in ~/.babel.json.  Deleting this file fixed my problem, so somehow it was loading un-instrumented code from the cache.  Deleting ~/.babel.json fixed it for me, but a better fix would be to run your tests with:

    BABEL_DISABLE_CACHE=1 NODE_ENV=test nyc mocha ...

**Comment by JaKXz** [comment]
I'm going to close this issue for now - if it's still occurring on the latest versions of babel and nyc please open a new issue! I think that this has been fixed in the meantime though.
