### ISSUE TITLE
How to determine why a file is included in code coverage

### ISSUE THREAD

**Issue by Itschrismorgan** [istanbuljs/nyc#770]
Question:

We are running into an issue where files are being included in a code coverage unexpectedly. It is causing our build process to fail because the files are below our thresholds. The confusion is because our code change has nothing to do really with the files that are failing code coverage. We haven't been able to figure out why they are being included.

I know we could just add the files to the exclude option but it bothers me that we can't figure it why they are being included.

Is there a way to see why IstanbulJS is including a file?

Sorry, I can't share a gist or example of this.

**Comment by JaKXz** [comment]
Sorry for the late reply! You can check your include or exclude globs and see if they produce the result you expect for the filename(s) that you are looking at. The default include and exclude globs are documented on the readme. 

Any file that is used somehow in a test will be included, if it matches the include/exclude globs. And finally if you are using the `--all` flag, you will see files that are not tested as well as tested.

Without a reproduction however, I will need to close this issue.
