### ISSUE TITLE
nyc returns Unknown for all fields after test run successfully

### ISSUE THREAD

**Issue by hekod777** [istanbuljs/nyc#771]
## Description

nyc returns Unknown for all fields after test run successfully.
```
  18 passed
  1 known failure

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```json
    "test": "cd test/resources && npm install && nyc ava ../app-test.js",
```

## Relevant Links

- Project link: https://github.com/GoogleChrome/rendertron
- Reproduction steps (this app requires Node 8 because it contains ES7 codes):
1.
```
git clone https://github.com/GoogleChrome/rendertron.git
cd rendertron
npm install
npm install nyc --save-dev
```
2. modify `"test"` in `package.json` to `"test": "cd test/resources && npm install && nyc ava ../app-test.js",`

3. `npm run test` 

## Environment

```
node -v => 8.9.4
ava --version => 0.20.0
npm --version => 5.6.0
nyc => 11.4.1
```

## Additional Info

I have tried solutions from #374 and readme. But coverage is still `unknown`.

The source code is using ES7 syntax, `async await`. I have transpiled ES7 codes down to ES6 compatible.

But coverage is unknown for both ES7 source code and ES6 compatible code.

I have tried the same solution for another node module. It worked and generated .nyc_output file after `npm run test`.

But this time, after running `npm run test`, it did NOT generate .nyc_output file.

**Comment by NhatDuy1407** [comment]
The same issue, please help me!
### Run test as below:
```
nyc --reporter=html --reporter=text mocha --require ts-node/register src/**/*.spec.ts

339 passing (12s)

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

**Comment by NhatDuy1407** [comment]
@hekod777 in my case, because src/**/*.spec.ts didn't include *.spec.js, nyc made the report based on javascript files. So, I think you should check the folder "../app-test.js" is existing or not.

**Comment by JaKXz** [comment]
The rendertron project specifically is an interesting case, I've looked at it a few times... its structure doesn't necessarily play nicest with nyc. For the adventurous, I would recommend something else from  https://istanbul.js.org/integrations/ (primarily jest or node-tap).

For now however, I'm going to close this issue as stale since I know the project has moved on to TypeScript and I think there are other issues in here relating to it.

**Comment by jsdevel** [comment]
I'm facing this same problem.  Here's what coverage output looks like:

```
=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```

This only recently starting happening for me on a project I maintain.

**Comment by JaKXz** [comment]
@jsdevel please open a new issue, using the latest version of NYC and providing a reproduction in a repo that follows the documented instructions

**Comment by Yash-Singh1** [comment]
The solution for me was to delete the `node_modules` and reinstall all the packages:

```sh
rm -rf node_modules/
npm install
```
