### ISSUE TITLE
What does nyc report actually do?

### ISSUE THREAD

**Issue by hekod777** [istanbuljs/nyc#772]
Due to the way my test files are structured, after running `nyc test ../test.js`, `.nyc_output` folder is created under /test/resrouces folder. As a result, `nyc report` fails. All fields are marked `unknown`.

I tried to use `--temp-directory ../../.nyc_output` to put the coverage files in `root/.nyc_output` folder. It was successful. Coverage files appear in the `.nyc_output` folder.

Then I run `nyc report` in posttest. All fields are still marked unknown.

I'd like to know how does this `nyc report` actually work. and how to fix it.

reproduction steps:

```
git clone https://github.com/GoogleChrome/rendertron.git
cd rendertron
npm install
npm install nyc --save-dev
```

add the following lines to `package.json`
```json
"scripts":{
   "test1": "cd test/resources && npm install && nyc --temp-directory ../../.nyc_output ava ../app-test.js",
    "posttest1": "nyc report",
    "test2":"cd test/resources && npm install && cd .. && nyc ava ./app-test.js",
    "posttest2":"nyc report",
}
```

```
npm run test1
```
the output is all unknown

```
npm run test2
```
I can see the code coverage, but 3 tests failed.

**Comment by JaKXz** [comment]
Sorry for the late reply @hekod777 

I think you can achieve what you want to with `nyc report --temp-dir ../path/to/.nyc_output`. For more information try `npx nyc report --help`.

**Comment by jwk15** [comment]
Is there any way to get nyc to generage an html report say by specifying a `coverage-summary.json` file? To be frank, the help information isn't much help here.
