### ISSUE TITLE
Coverage report randomly skips a TypeScript file

### ISSUE THREAD

**Issue by durad** [istanbuljs/nyc#773]
## Expected Behavior
Executed source files should always be included in the coverage report.

## Observed Behavior
About 50% of the time a source does not get included in the coverage report.

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/durad/nyc-issue

Run `npm install` and then run `npm run repro-steps` several times. Script `repro-steps` will run the `nyc` and then try to `ls` the file in the `coverage` folder. Even though there is nothing different from run to run, and there is a console.log outputting text during the test which proves that the source file is executed during testing, about 50% of the time the corresponding report file will not be there.

Sometimes it works (last line shows the file):

``` bash
/mnt/c/dev/nyc-bug * master$
/mnt/c/dev/nyc-bug * master$ npm run repro-steps

> nyc-bug@0.0.1 repro-steps /mnt/c/dev/nyc-bug
> npm run test-cleanup && npm run test && ls -lsa ./coverage/index.ts.html


> nyc-bug@0.0.1 test-cleanup /mnt/c/dev/nyc-bug
> rm -rf .nyc_output coverage


> nyc-bug@0.0.1 test /mnt/c/dev/nyc-bug
> nyc mocha --opts mocha.opts



  hello
Hello from index.ts!
Result: Hello World!
    ✓ rejects with registration validation errors on startup


  1 passing (21ms)

2049 -rwxrwxrwx 1 root root 2565 Feb  1 20:38 ./coverage/index.ts.html
```

Sometimes it doesn't (`ls` can not find the file):
``` bash
/mnt/c/dev/nyc-bug * master$
/mnt/c/dev/nyc-bug * master$
/mnt/c/dev/nyc-bug * master$ npm run repro-steps

> nyc-bug@0.0.1 repro-steps /mnt/c/dev/nyc-bug
> npm run test-cleanup && npm run test && ls -lsa ./coverage/index.ts.html


> nyc-bug@0.0.1 test-cleanup /mnt/c/dev/nyc-bug
> rm -rf .nyc_output coverage


> nyc-bug@0.0.1 test /mnt/c/dev/nyc-bug
> nyc mocha --opts mocha.opts



  hello
Hello from index.ts!
Result: Hello World!
    ✓ rejects with registration validation errors on startup


  1 passing (10ms)

ls: cannot access './coverage/index.ts.html': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

## Forensic Information

**Operating System:** the operating system you observed the issue on.

Windows Subsystem for Linux (WSL) on Windows 10

**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

https://gist.github.com/durad/dabe0be7ac075b18419983919e099adb

**Comment by TomasRas** [comment]
+1
