### ISSUE TITLE
Incorrect Success is returned when the tests fail but the code-coverage check passes.

### ISSUE THREAD

**Issue by ramyaa** [istanbuljs/nyc#775]
if I have a code-coverage threshold of "lines > 85%" and if one of my tests fail due to which the threshold drops from my original 90% to 87% (note that it is still above the code-coverage threshold), in this scenario I would still expect "$?" (Output returned by my prev command) to give me a non-zero value (meaning failure).
But then it returns zero (meaning success).

## Expected Behavior
if tests fail and even if the code-coverage check passes, it should return a failure (non-zero value)

## Observed Behavior
if tests fail and if the code-coverage check passes, it now returns a success (zero value)

**Operating System:** Ubuntu 16

node version : v6.11.3

**Comment by JaKXz** [comment]
Hi @ramyaa thanks for the issue, sorry for the delayed reply. Can you post a minimal reproduction of this issue with the latest nyc?
