### ISSUE TITLE
Including all files when not using require or register

### ISSUE THREAD

**Issue by cdibbs** [istanbuljs/nyc#776]
## Expected Behavior
When running a lesser-known testing framework (called [Alsatian][1]) with nyc and ts-node, there should be an option to cover all files, despite the absence of a `require` definition in the config.

## Observed Behavior
Coverage seems correct, in terms of individual files, but the results don't include files not directly imported by the tests. My understanding of `"all": true` that I've gleaned from issues and docs scattered about is that it won't actually include all files without a `require`. If I try to require `ts-node/register` with nyc (again, despite it seeming to work, coverage-wise, without that), then all desired files are included, but coverage becomes nonsense, highlighting random byte ranges.

## Bonus Points! Code (or Repository) that Reproduces Issue
`package.json` and [runner.ts][2]
```json
  "scripts": {
    "precover": "rimraf ./coverage/*",
    "cover": "nyc npm run unittest",
    "unittest": "ts-node --project tsconfig-xunit.json src/spec-lib/runner.ts"    
  },
  "nyc": {
    "include": [
      "src/lib/**"
    ],
    "extension": [
      ".ts"
    ],
    "exclude": [
      "typings",
      "**/*.d.ts",
      "**/*.test.ts",
      "**/*.spec.ts"
    ],
    "reporter": [
      "json",
      "html"
    ],
    "all": true
  }
```
## Forensic Information

**Operating System:** the operating system you observed the issue on.
Windows 10, Powershell

**Environment Information:** information about your project's environment, see instructions below:
1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.
[gist of output.txt][output]

[1]: https://github.com/alsatian-test/alsatian
[2]: https://github.com/alsatian-test/alsatian/wiki/running-with-ts-node
[output]: https://gist.github.com/cdibbs/4d66e319e8f745c019143a530afc8250

**Comment by cdibbs** [comment]
I've added a project that demonstrates the bug.

https://github.com/cdibbs/tsnode-alsatian-scrambled-coverage-issue

It's also possible this is a ts-node bug, but I am not familiar enough with the inner workings of nyc or ts-node to know for sure.

**Comment by JaKXz** [comment]
@cdibbs sorry for the late reply. I'm not sure what you meant by:

> there should be an option to cover all files, despite the absence of a require definition in the config.

I was going to suggest trying the newly published https://www.npmjs.com/package/@istanbuljs/nyc-config-typescript but I don't know how you'd get coverage without using a require hook.
