### ISSUE TITLE
My .js "logic" files are not being considered for coverage when I am testing the coverage of a react project, even when specified in the "include" option

### ISSUE THREAD

**Issue by opr** [istanbuljs/nyc#779]
## Expected Behavior
To test coverage of my actions.js "logic" files in my react app, when it is structured like so:
(removed some files to make it more concise)
```
├───assets
│   ├───js
│   │   │
│   │   ├───react
│   │   │   │   index.jsx
│   │   │   │
│   │   │   └───Formality
│   │   │       │   FieldFactory.jsx
│   │   │       │   Formality.jsx
│   │   │       │
│   │   │       └───Logic
│   │   │               actions.js
│   │   │
│   │   └───test
│   │           core_spec.js
│   │           test_helper.js
```

## Observed Behavior

I have tried with the below code in `.nycrc` but it still not checked.
```
"include": [
    "assets/js/react/Formality/Logic/actions.js"
  ]
```
Only files in the "root folder" of the component I'm testing get checked.

Although if I put a .js file (in the repo below, I have put `hello.js` in the "Formality" component root) it is checked.

## Bonus Points! Code (or Repository) that Reproduces Issue
feel free to grab https://github.com/opr/formality and run `yarn install` or `npm install` then try ` yarn run cross-env NODE_ENV=coverage BABEL_ENV=coverage nyc mocha --require babel-core/register ./assets/js/test/test_helper.js ./assets/js/test`

## Forensic Information

**Operating System:** the operating system you observed the issue on.
Windows 10

**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

https://gist.github.com/opr/2f2b3126bbcba4ba3ed9eb51bb50729a

**Comment by opr** [comment]
I have a suspicion that this is to do with the depth of these js files from where nyc is running? Is there any way to specify how deep it can go?

**Comment by opr** [comment]
Still suffering from this - I can still replicate my issue. Any help in where to start with implementing a fix would be appreciated!

**Comment by coreyfarrell** [comment]
The .nycrc in the repo you linked has `"exclude": ["assets/js/**/*.js"]` in .nycrc.  'exclude' cannot be overridden by 'include', it's not processed in that order.  Have you tried:
```js
"exclude": [
  "assets/js/**/*.js",
  "!assets/js/react/Formality/Logic/actions.js"
]
```
