### ISSUE TITLE
NPM thinks that 11.4.1 is the latest!

### ISSUE THREAD

**Issue by Milad** [istanbuljs/nyc#780]
## Expected Behavior
npm should see 11.5.0 as the latest version
## Observed Behavior
npm thinks 11.4.1 as the latest version
## Forensic Information
https://www.npmjs.com/package/nyc

**Comment by mdlavin** [comment]
@bcoe I see this same behavior. Is there a chance you forgot to push the new build to npm?

**Comment by corbinu** [comment]
@bcoe @mdlavin 11.5.0 is on npm 11.4.1 is simply marked as latest. I believe all that needs to be done is `npm dist-tag add latest nyc@11.5.0`

**Comment by bcoe** [comment]
@mdlavin @corbinu I usually publish to the `next` tag first, for a QA period, and then promote to `latest`; Unfortunately, I dropped the release of `11.5.0` on the floor and haven't QAd it appropriately. `11.5.0` will be prompted to `latest` soon.

**Comment by corbinu** [comment]
@bcoe if it isn't to much trouble can you please do `npm dist-tag add nyc@11.4.1 latest` then that way NPM will know that 11.5.0 is prerelease?

**Comment by cibergarri** [comment]
this is still happening with version 11.6.0
