### ISSUE TITLE
Different screenshot in your README.md?

### ISSUE THREAD

**Issue by jacobbogers** [istanbuljs/nyc#786]
What options give me the last "summary line" like in this screenshot (from your readme)
https://github.com/istanbuljs/nyc/blob/master/screen.png

"text" and "text-summary" dont produce the same output

**Comment by bcoe** [comment]
👋 hey @jacobbogers, the screen-shot in the README is out of date. The output of the `text` report now summarizes the project totals on the first line, next to the heading "All Files".

I would happily accept a pull request with an updated screen-shot, if you have the time 👍
