### ISSUE TITLE
Need to be able to specify which .nycrc file to use

### ISSUE THREAD

**Issue by intervalia** [istanbuljs/nyc#788]
## Expected Behavior
In Istanbul I could use this CLI parameter:
`--config=test/.istanbul-client.yml`
to specify the exact version of the config file to use for this run.

## Observed Behavior
I can not seem to do the same for NYC.

We have different runs of NYC for our Node-side code and for our browser-side code and want to keep they separated. But to do that we would need to have two different .nycrc files and the ability to specify which one to use.

It seems that we only have the ability to have a single .nycrc file and it must be called `.nycrc`

If there a way to add the `--config` option into NYC similar to what was available in Istanbul?
`nyc --config=test/.nycrc-client.yml`

**Comment by intervalia** [comment]
Is this done through `--nycrc-path`?

**Comment by intervalia** [comment]
Yes, that is the answer.

**Comment by bcoe** [comment]
@intervalia awesome sounds like this did the trick for you? sorry for the discrepancy.
