### ISSUE TITLE
Ignore implicit else branch

### ISSUE THREAD

**Issue by mathieug** [istanbuljs/nyc#791]
![image](https://user-images.githubusercontent.com/951183/37275457-8f8717ba-25df-11e8-9acd-3402e6a71a66.png)

How do I ignore this implicit else branch (code after a condition containing a throw)?
I’ve tried `/* istanbul ignore else */` before the if but it only deletes the E. To ignore the E and the two red lines, I have to put `/* istanbul ignore else */` and two times `/* istanbul ignore next */` for each two red lines. For me the two red lines are the else branch but not for Istanbul.

Versions:
node 8.9.45
npm 5.6.0
nyc 11.4.1

**Comment by JaKXz** [comment]
`ignore else` is to reduce the total number of branches reported, and you need `ignore next` to ignore the lines not covered as well. I think the instrumenter is counting things correctly here - sorry for the late reply.

**Comment by coreyfarrell** [comment]
Oh sorry my eyes got crossed, I didn't see the closing `}`'s correctly.  In any case I don't think istanbul is able to understand that the if block never returns, so it doesn't understand that `logger.error` is part of an "implicit" else block.  To be honest I don't think it's likely we'll find a way to make istanbul understand this.

In this situation I'd refactor the catch block:
```js
/* istanbul ignore next */
if (err.code !== 11000) {
  logger.error(...);
  throw err;
}

logger.warn(...);
throw new Conflict(...);
```

**Comment by coreyfarrell** [comment]
I'm closing this ticket as I don't believe it's possible for NYC / istanbul to support understanding the implicit else case as described here.

**Comment by mathieug** [comment]
Ok thanks. I’m not going to change my code for test or coverage. I expected a way with ignore else.
