### ISSUE TITLE
Branch and line coverage 100%, but Statements only 98% (and no 'uncovered lines' displayed)?

### ISSUE THREAD

**Issue by pmcb55** [istanbuljs/nyc#792]
## Expected Behavior
To show me which lines are uncovered to result in '% Stmts' being only 98.45%? How can I have 100% line and branch coverage, yet be missing Functions or statements - i.e. see observed behaviour below?

## Observed Behavior
```
------------------|----------|----------|----------|----------|----------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------|----------|----------|----------|----------|----------------|
All files         |    99.62 |      100 |    97.75 |      100 |                |
 src              |    99.59 |      100 |    97.62 |      100 |                |
  Context.js      |      100 |      100 |      100 |      100 |                |
  ContextError.js |      100 |      100 |      100 |      100 |                |
  RdfBuild.js     |    98.48 |      100 |       95 |      100 |                |
  RdfQuery.js     |      100 |      100 |      100 |      100 |                |
 src/utils        |      100 |      100 |      100 |      100 |                |
  RdfUtils.js     |      100 |      100 |      100 |      100 |                |
------------------|----------|----------|----------|----------|----------------|
```
## Forensic Information

**Operating System:** the operating system you observed the issue on.
Ubuntu 17.10
**Environment Information:** information about your project's environment, see instructions below:
[output.txt](https://github.com/istanbuljs/nyc/files/1803796/output.txt)

**Comment by pmcb55** [comment]
So, I found the problem! By configuring NYC to generate a HTML report I could see the uncovered statements, which were '.map()' statements that my tests only executed on empty map instances.

But I still think the above text report should have still indicated the line numbers of the uncovered statements. Once I saw them in the HTML report it was immediately obvious what the problem was - so I think this issue is still worth leaving open.

**Comment by Zikoel** [comment]
I had the same problem and I solved in the same way! I think report this information on the text report would be right.

**Comment by coreyfarrell** [comment]
We need a link to a demo repo to triage this issue.  My own projects do report line numbers in when statements are not covered.

**Comment by ezfe** [comment]
@coreyfarrell I reproduced this due to a callback in my code:

```
async sampleFunction(records: SampleModel[], transaction: Transaction): Promise<void> {
    return await repository.insert(records, transaction, async () => {});
}
```

The issue was due to lack of coverage on the `async () => {}` callback.
