### ISSUE TITLE
Error getting the coverage report using rewire / cross-env

### ISSUE THREAD

**Issue by mirgj** [istanbuljs/nyc#800]
I'm trying to get the coverage report using nyc and it works well if I'm not using the cross-env plugin. 
```
nyc mocha --ui bdd --reporter spec --colors --require babel-core/register tests --recursive
```
this instruction runs the test and generate the report correctly. But if I only add `cross-env NODE_ENV=test ` before the previous command the output will be empty 

## Expected Behavior
should generate the coverage report

## Observed Behavior
the report is empty

node: 
this is my babel plugin and I think the issue is related to the **babel-plugin-rewire**. Indeed, even removing the cross-env and placing the plugins collection in the root will give me the same empty coverage result.
```

{
  "presets": ["es2015"],
  "env": {
    "test": {
      "plugins": ["istanbul", "babel-plugin-rewire"]
    }
  }
}
```

**Comment by juank11memphis** [comment]
I am getting the same

**Comment by mirgj** [comment]
@juank11memphis I've found a solution to this issue. Please look my repo https://github.com/mirgj/es6-rewire-nyc it contains a readme which explain how I've fixed it (while the code is actually the one that create issues).

**Comment by juank11memphis** [comment]
Thanks @mirgj I will give it a shot
