### ISSUE TITLE
Wrong TypeScript code coverage for class field declaration

### ISSUE THREAD

**Issue by vekexasia** [istanbuljs/nyc#802]
## Expected Behavior
Should not mark them as uncovered.

## Observed Behavior
Marks type definitions (and even commas) uncovered)

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/RiseVision/rise-node/

## Forensic Information

**Operating System:** the operating system you observed the issue on.
Ubuntu
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.
https://gist.github.com/vekexasia/a04a90c588bbd94063078ddb1fbd8edd

### Extra infos

Running `npm run test-cover-unit` without coveralls produces the lcov-report where you can inspect one module (ex src/modules/delegates.ts). As you can see in the image below there are several fields that are marked as uncovered (in their type definition??) and some are not (look at constants).

![image](https://user-images.githubusercontent.com/200523/38074104-f1d8cae8-332d-11e8-94e1-72bd5891430b.png)

**Comment by cibergarri** [comment]
It happens the same to me, I think it's related with the inject decorator, because other properties without the decorator work properly.

**Comment by vekexasia** [comment]
@cibergarri What's fun is that some of them are not marked as uncovered (look at line 29).

Let me know if you find any workaround for this.

**Comment by cibergarri** [comment]
And what is more, I would swear that wasn't happening some days ago.... Weird

**Comment by cibergarri** [comment]
@vekexasia, I have found a workaround, iyou can fix it by downgrading ts-node package to version 3.3.0.

Hope it helps.
Regards.

**Comment by vekexasia** [comment]
@cibergarri thanks I'll try.

**Comment by cibergarri** [comment]
Hi again @vekexasia .

@blakeembrey, in the ts-node repository has givenme a much better solution, you can keep the latest version of ts-node and change the require configuration:
`require": [ "ts-node/register/type-check" ]`

https://github.com/TypeStrong/ts-node/issues/564
