### ISSUE TITLE
Denpendency spawn-wrap is not maintained

### ISSUE THREAD

**Issue by pangrr** [istanbuljs/nyc#803]
## Expected Behavior
Bug in spawn-wrap should be fixed.
## Observed Behavior
[Pull request](https://github.com/tapjs/spawn-wrap/pull/70) to fix bug in spawn-wrap gets no response from admin.
## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

**Comment by pangrr** [comment]
It could be a negative experience if nyc depends on something not maintained.

**Comment by JaKXz** [comment]
I'm not sure we need to find/make an alternative to spawn-wrap until it gives us serious issues... on that basis I'm going to close this issue for now.

**Comment by demurgos** [comment]
@JaKXz I sent a message on the `node-tooling` slack: I can help with merging my fixes to `spawn-wrap`.
