### ISSUE TITLE
Question: can nyc be controlled while it is collecting code coverage data?

### ISSUE THREAD

**Issue by dtgriscom** [istanbuljs/nyc#813]
I'm starting to use nyc to measure code coverage with my Node-based server system under Linux. I'm using a custom test system that stimulates the server and evaluates results. I'd like to have nyc trace coverage while the testing runs, but at the moment I have to restart the nyc/server system before starting tests, and exit after every set of tests to generate the code coverage report.

I'd like to leave the server system running continuously, and without restarting a) reset the statistics, and b) trigger generation of the coverage report. This could be done internal to the server code (perhaps by calling Istanbul functions), or external to the server (perhaps by sending signals).

Is there a way to a) reset the code coverage statistics, and b) trigger writing of the coverage report(s), without exiting and restarting the whole system?

(Previously posted at https://github.com/gotwarlost/istanbul/issues/875 ...)

**Comment by JaKXz** [comment]
Hi @dtgriscom sorry for the late reply, this sounds a bit similar to #597, and in the same way sounds really complex and a bit beyond the scope of what nyc is trying to do. You are more than welcome to try to take a crack at a PR or writing your own library/extensions to nyc :)

**Comment by dtgriscom** [comment]
Thanks for the response. I'm not surprised, and unfortunately you won't be surprised to hear I'm unlikely to be able to submit a PR...


Thanks for the cool tool,
Dan

**Comment by JaKXz** [comment]
There's also #607 which is tangentially related. To accomplish:

>Is there a way to a) reset the code coverage statistics, and b) trigger writing of the coverage report(s), without exiting and restarting the whole system?

You could try messing around with the internals of nyc but there isn't an official programmatic API atm so I'm not sure this is possible.
