### ISSUE TITLE
Question: Does nyc have caching beyond the cache folder?

### ISSUE THREAD

**Issue by peterjwest** [istanbuljs/nyc#817]
nyc seems to have very different running time between first and second runs on a newly cloned repository, which doesn't seem to be affected by deleting the cache folder.

Do you know why that could be?

The background is that I'm running nyc on Travis, which inexplicably takes 30x as long to complete, but only the first time (irrespective of the state of the cache folder).

**Comment by coreyfarrell** [comment]
It could also be effected by babel caching which is stored in ~/.babel.json for some versions, newer versions seem to use `node_modules/.cache/@babel`.

**Comment by JaKXz** [comment]
@peterjwest hope your question was answered, I'm going to close this for now. If you feel this needs to be documented somewhere, https://github.com/istanbuljs/istanbuljs.github.io would be a great place to start.
