### ISSUE TITLE
KotlinJs Code Coverage

### ISSUE THREAD

**Issue by shadowrider** [istanbuljs/nyc#818]
I couldn't find anyone trying to use `nyc` to get code coverage for Kotlin files. I image it would work similar to how it works with TypeScript, where `nyc` uses source map files. Does anyone know what needs to be done in order for this to work? I would love to contribute to `nyc` to support this feature, but currently have no idea where to start.

## Expected Behavior
Ability to get code coverage for Kotlin files which get transpiled to JS.

## Observed Behavior
Coverage summary reports as `Unknown%`

## Things I've tried
**Command:** `nyc mocha path/to/test/bundle.test.js --require=source-map-support/register --recursive`
**Config:**
```
{
    "tempDirectory": "./coverage/.nyc_output",
    "report-dir": "./coverage",
    "lines": 100,
    "statements": 100,
    "functions": 100,
    "branches": 100,
    "include": [
      "src/main/**/*.kt",
      "../src/main/**/*.kt"
    ],
    "exclude": [
      "**/coverage",
      "**/test"
    ],
    "reporter": [
      "lcov",
      "text-summary"
    ],
    "require": [
    ],
    "extension": [
      ".kt"
    ],
    "cache": true,
    "all": true
  }
```
If I require `babel-register` then I get errors as `babel` tried to go through Kotlin files.

## Forensic Information

**Operating System:** macos 10.12
**Environment Information:** OpenJDK 1.8.0_162, Kotlin 1.2.30, Node 8.11.1, NPM 5.6, Babel-Core 6.26, Mocha 5.1.1, NYC 11.7.1

**Comment by JaKXz** [comment]
Do you have an example repo to reproduce this? :)

**Comment by shadowrider** [comment]
Would you like me to put one together? It takes a few minutes to update `js/package.json` in https://github.com/elizarov/KotlinMultiplatformPlayground

**Comment by Snipx** [comment]
Same issue here. I've been trying to debug the root cause and for now I am inclined to think the problem is somehow hidden in source mapping. But not sure yet if it's indeed the root cause and which side causes the problem. Have you had any success with the problem, @shadowrider ?

**Comment by JaKXz** [comment]
@Snipx @shadowrider sorry for dropping this for so long. Yes I would love to see a small demo repo to try things out on.

My question is what is the/is there a babel equivalent for Kotlin? If your test runner is executing on transpiled js files with sourcemaps, then nyc should be able to map them back to the original source files. 

cc @coreyfarrell any thoughts on this?

**Comment by darran-kelinske-fivestars** [comment]
I am interested in pursuing this again. Did anyone make any progress that was undocumented?
