### ISSUE TITLE
Incorrect coverage reporting for code appearing across combined runs

### ISSUE THREAD

**Issue by colinrcummings** [istanbuljs/nyc#821]
## Expected Behavior

When combining multiple runs, coverage  for code tested across runs should report correctly. 

## Observed Behavior

Running code coverage for unit tests with `jasmine` and integration tests with `jest` independently results in correct code coverage reporting; however, running combined code coverage for both does not. 

### Test

*test/unit/specs/app/assets/javascripts/dummy.js*

```javascript
// jasmine
import { foo } from 'app/assets/javascripts/dummy';

it('foo returns val', () => {
  expect(foo(1)).toBe(1);
});
```

### Coverage Script

```
nyc --extension=.jsx --temp-directory=./test/unit/coverage/.nyc_output --report-dir=./test/unit/coverage --reporter=text-summary --reporter=lcov npm run test:unit
```

### Coverage Report (:heavy_check_mark: correct)

*test/unit/coverage/lcov-report/assets/javascripts/dummy.js.html*

![image](https://user-images.githubusercontent.com/9815009/39266717-cd42c79e-4898-11e8-8b81-d93a89f65d12.png)

### Test

*test/integration/specs/app/assets/javascripts/dummy.test.js*

```javascript
// jest
import { baz } from 'app/assets/javascripts/dummy';

test('baz returns val via bar', () => {
  expect(baz(2)).toBe(2);
});
```
### Coverage Script

```
npm run test:integration -- --coverage
```

### Coverage Report (:heavy_check_mark: correct)

*test/integration/coverage/lcov-report/assets/javascripts/dummy.js.html*

![image](https://user-images.githubusercontent.com/9815009/39267032-b27977d6-4899-11e8-87d6-bb2e197331d4.png)

### Coverage Script

```
nyc --no-clean --silent --temp-directory=./test/coverage/.nyc_output npm run test:unit && nyc --no-clean --silent --temp-directory=./test/coverage/.nyc_output npm run coverage:integration && nyc --temp-directory=./test/coverage/.nyc_output --report-dir=./test/coverage --reporter=text-summary --reporter=lcov report
```
 
### Coverage Report (:x: incorrect)

*test/coverage/lcov-report/assets/javascripts/dummy.js.html*

![image](https://user-images.githubusercontent.com/9815009/39267525-10850524-489b-11e8-90ec-6206a1fdca5e.png)

## Forensic Information

**Operating System:** 
Windows 7 Professional

**Environment Information:** 
[gist](https://gist.github.com/colinrcummings/a88d633d9c72de315b7cdade12a1c8e9)

**Comment by coreyfarrell** [comment]
@colinrcummings can you provide a link to a repository showing a minimal reproduction?

**Comment by colinrcummings** [comment]
@coreyfarrell, thanks for the followup. See a minimal reproduction attempt [here](https://github.com/colinrcummings/nyc-issue-821). Good news: I couldn't reproduce the issue with the latest version, so this issue can be closed. Potentially attributable to one of the following version changes in the last year since this issue was opened:

`nyc`: 13.0.1 -> 13.3.0
`jasmine`: 3.1.0 -> 3.3.1
`jest`: 22.4.3 -> 24.3.0

**Comment by coreyfarrell** [comment]
Of what you listed I suspect the jest upgrade is probably most significant, jest 22 used babel 6 with an older major version of the istanbul libraries, jest 24 uses the current istanbul libraries with babel 7.  Anyways glad everything is working for you now.
