### ISSUE TITLE
NYC swallows error code if test runs out of memory

### ISSUE THREAD

**Issue by stringbeans** [istanbuljs/nyc#823]
## Expected Behavior
`nyc` will forward the exit code resulting from tests that run out of memory.

## Observed Behavior
If `nyc` is used on a test which fails due to JS running out of memory, `nyc` seems to swallow the error and report exit code = 0

## Forensic Information
To reproduce:
1. create a mocha test with the following code:

```
describe('test', function() {
  before(function() {
    const myArr = [];
    while (true) myArr.push('makeThisLongerToDieQuicker');
  });

  it('will never get here', () => {

  });
});
```

2. run `node_modules/.bin/mocha test.js`
3. run `echo $?` (notice that the exit code is `134`)
4. run `node_modules/.bin/nyc node_modules/.bin/mocha test.js`
5. run `echo $?` (notice that the exit code is `0`)

I'm using `mocha@5.1.1` and `nyc@11.7.1` with node v8.9.3

**Operating System:** MacOSX 10.12.6

**Comment by mlrawlings** [comment]
Duplicate of https://github.com/istanbuljs/nyc/issues/798

Interestingly, if you look at the issue I opened, it is only the combination of `nyc mocha` that causes the issue, so I'm not sure which side the issue is on.  `mocha` only preserves the error code as does `nyc node`.

**Comment by stringbeans** [comment]
@mlrawlings ahh apologies on the dupe! i wasnt able to find it when i was searching. thats an interesting thing about it being specific to mocha though. 

seems like if running only `mocha` with the failing test produces the correct error code, i wouldnt expect the issue to be on mocha's side... maybe? 😕

**Comment by JaKXz** [comment]
Mind if we isolate the discussion to #798? Thanks :)
