### ISSUE TITLE
question: Difference between `nyc -i ./a.js node ./b.js` and `nyc node -r ./a.js ./b.js`.

### ISSUE THREAD

**Issue by jdalton** [istanbuljs/nyc#824]
I'm wondering what the difference is between 
`nyc -i ./a.js node ./b.js`,
`nyc node -r ./a.js ./b.js`, or even
`nyc -i ./a.js node -r ./a.js ./b.js`

I can see there is a difference in behavior in my script but the specifics are harder to nail down.

It looks like nyc is spawning a child process for the `node` bit so I'm wondering how the `nyc -i /a.js` can carry over into the spawned child. Any insight into the flow of things would be appreciated.

**Comment by coreyfarrell** [comment]
Sorry for missing this, one difference you might see is with `nyc --all`, especially if using `babel-plugin-istanbul`.

With `istanbul` in your babel.config.js settings:
`nyc --instrument=false --all -i @babel/register node ./b.js` will instrument and report ./a.js
`nyc --instrument=false --all node -r @babel/register ./b.js` will not instrument or report ./a.js

I'm not sure about `nyc -i @babel/register node -r @babel/register ./b.js`, IMO it's better to try avoiding this.

As for getting the requires into the child process this is done by https://github.com/tapjs/spawn-wrap#readme (this also helps nyc setup require hooks in the child processes for the normal instrumentation).
