### ISSUE TITLE
No coverage information is shown when we use a local node installation 

### ISSUE THREAD

**Issue by timur-han** [istanbuljs/nyc#827]
## Expected Behavior
Executed unit tests to be included in the coverage reports
## Observed Behavior
No unit tests are included in the coverage reports

## Forensic Information
We are using gradle to lunch a gulp task running the following command and gradle downloads the 8.9.4 version of nodejs and runs the command with it. Consquently, the following is executed (I also tested it directly from a bash shell, which also did fail):
```
./node_modules/cross-env/dist/bin/cross-env.js  NODE_ENV=test .gradle/nodejs/node-v8.9.4-linux-x64/bin/node ./node_modules/nyc/bin/nyc  ./node_modules/mocha/bin/mocha  --exit ./spec/**/*.js
```
Consequently, 3 test cases are run but no coverage information is shown. If we run nyc with the global node installation it works:

```
./node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=test node ./node_modules/nyc/bin/nyc  ./node_modules/mocha/bin/mocha  --exit ./spec/**/*.js
```
The difference is we use node instead of .gradle/nodejs/node-v8.9.4-linux-x64/bin/node. The versions are the same but somehow it behaves differently. 

Any idea how we could resolve this weird issue? Any help will be appreciated. 

**Operating System:** the operating system you observed the issue on.
OpenSuse / Ubuntu

**Environment Information:** 
We use node 8.9.4 and npm version 5.8.0, unfortunately I cannot post the dependency tree due to privacy policies of the organization that I'm working in.

**Comment by rohitrishi** [comment]
OS: Windows 10
Node: 6.10.1(installed using the installer) and 8.11.1(installed using nvm)
NPM packages used: NYC, babel-plugin-istanbul
Task runner: grunt

I think I am running into the same issue. I have two node versions installed on my machine.
I had installed Node 6.10.1 on my machine locally using the node installer a couple of months ago.
Everything worked fine with that.

I just installed nvm and installed Node 8.11.1. When I run my test with that node version there are no metrics being generated even though all the tests are run.
 
But when I switch back to Node 6.10.1 using nvm, I see the metrics being generated after the test run is complete.

Is it possible that Node 6.10.1 that I had installed using the node installer is considered the "global" version. Should I uninstall it and re-install it(6.10.1) using nvm?

**Comment by JaKXz** [comment]
Hi @timur-han sorry for the late reply! Are you able to provide a minimal demo repo with instructions on how to get things working? I would honestly suggest going with a minimal package.json in your project just for your javascript tests if possible.

**Comment by coreyfarrell** [comment]
I suspect this is a limitation of spawn-wrap.  I think for spawn-wrap to work correctly `node` needs to be run from the PATH.   Can gradle prepend your path to prefer it's own version of node like nvm does?
