### ISSUE TITLE
Unable to lookup source

### ISSUE THREAD

**Issue by golonikum** [istanbuljs/nyc#837]
## Expected Behavior
Content of the source files must be in the coverage report.
## Observed Behavior
All report files contain the same excepion log: 
Unable to lookup source: ...(ENOENT: no such file or directory, open '...')
## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/golonikum/testNycIssue
```
npm install
npm run testWithCoverage
```
Open coverage/index.html and click on source.js link.
## Forensic Information

**Operating System:** Microsoft Windows 10 Enterprise.
**Environment Information:** https://gist.github.com/golonikum/70385ce51a8bfe1b91947058d9f39197

**Comment by JaKXz** [comment]
Hi @golonikum sorry for the late reply! Would you like to submit a PR with your change? otherwise I will try to make some time for it but we welcome contributions :) It would be interesting to see if we can reproduce this in a failing test

**Comment by coreyfarrell** [comment]
@golonikum I've merged your fix, thank you.
