### ISSUE TITLE
Support/feature: Streaming instrumentation

### ISSUE THREAD

**Issue by ORESoftware** [istanbuljs/nyc#839]
With istanbul, we could avoid using the fs, and just stream instrumented code, like so:

```js
app.use(function(req,res,next){
    const k = cp.spawn('istanbul instrument foo.js');
    k.stdout.pipe(res);
});
```

we also could do it this way:

```js
import istanbul = require('istanbul');
const instrumenter = new istanbul.Instrumenter();

app.use(function(req,res,next){
   const filename = path.resolve(req.foo);
   fs.readFile(filename, function(err, data){
     instrumenter.instrument(data, filename, function (err, generatedCode) {
        res.write(generatedCode);
        res.end();
      });
  });
});
```

are either of these things possible with NYC?

**Comment by JaKXz** [comment]
Hi @ORESoftware sorry for the late reply, and thanks for filing this issue, it looks interesting. There is work being done on the `instrument` command in #893 to match the old istanbul functionality. I'm not sure if it actually prints to stdout like your first example... I could be wrong though.

You could also look at the istanbuljs monorepo (the way jest does) and use those libraries yourself to do what you're trying to do.
