### ISSUE TITLE
all reports return 0% for coverage

### ISSUE THREAD

**Issue by robcornelius** [istanbuljs/nyc#842]
my package.json contains
```
"nyc": {
        "include": ["public_html/js/**/*.js"],
        "exclude": ["public_html/js/resources/**/*.js", "public_html/data/**/*.js"],
         "temp-directory": "./alternative-tmp",
         "all": true,
         "report-dir": "coverage",
         "check-coverage": true
    },
  "scripts": {
    "test": " nyc instrument public_html/js/"
  },
```
and I am have nyc installed globally and run
`nyc --reporter=html npm test`
 
My source js files live under ./public_html/js/**/*.js and the test files live under ./test/**/*.js

I am running all of this on windows 10 64 bit

I have tried using karma-coverage but that seems very broken so I thought I would try to cut out the middleman

Any advice will be appreciated

**Comment by a5his** [comment]
If you are using `babel` toolchain then you should be using `babel-plugin-istanbul`.

**Comment by coreyfarrell** [comment]
If you are running tests in the browser then your test web server needs to process JS sources with `babel-plugin-istanbul` or `istanbul-lib-instrument` before serving them.  You need to retrieve the global `__coverage__` variable from the browser before closing each page.  Then you would use `istanbul-lib-coverage` to merge it into the node.js `__coverage__` variable so `nyc` can find it.

I don't know anything about karma (sorry) but `nyc` does not run in the browser.
