### ISSUE TITLE
Pass options to babel-register when requireing it

### ISSUE THREAD

**Issue by SevenOutman** [istanbuljs/nyc#846]
`nyc --requrie babel-register` should provide a way to pass config to `babel-register`.

In my case I invoked Yarn via shelljs, and babel-register applied for the globally installed Yarn scripts, which is not expected. The result obviously should not be affected by code outside of the project itself. As babel-register doesn't look for `.babelrc` (not for now, will be resolved in Babel 7), I wish there was a way to pass options to babel-register when `--require`ing it.

**Comment by coreyfarrell** [comment]
The way to accomplish this is to create a helper module as such:
```js
// test/helpers/register.js:
require('babel-register')({/* set options */});
```
Then use `nyc --require test/helpers/register.js` instead of directly requiring babel-register.  There is no user friendly way for us to take the options argument directly from command-line.
