### ISSUE TITLE
Question: is it possible to have multiple settings in package.json

### ISSUE THREAD

**Issue by dlednik** [istanbuljs/nyc#857]
I have unit tests and Rest endpoint tests that are run separately. 

There are specific folders for each of those. But when I set nyc section in package.json it affects both test runs. Is it possible to make multiple configurations in package.json?

**Comment by coreyfarrell** [comment]
You cannot have multiple sections in package.json but you can use `--nycrc-path` CLI argument to point to a different config file (instead of the default `.nycrc`).
