### ISSUE TITLE
NYC not count Method properties

### ISSUE THREAD

**Issue by RoniSegal** [istanbuljs/nyc#858]
## Expected Behavior
NYC should count Method properties and report 5 methods for file
inside the code I have 'Method Properties' (es6) inside 'obj3' and NYC not counts them.
## Observed Behavior
NYC not count Method properties and report only 2 methods for file

## Bonus Points! Code (or Repository) that Reproduces Issue
# code 
```javascript
function execute (){
    console.log(`
    ************** Enhanced Object Properties examples **************

                      === Property Shorthand ===
                 `);

    let x = 1;
    let y = 2;

    let obj = {
        x,
        y
    };
    console.log(`Value obj:`, JSON.stringify(obj));

    console.log(`
                    === Computed Property Names ===
              `);

    let quux = () => ` foo`;

    let obj2 = {
        foo: "bar",
        ["baz" + quux()]: 42
    };

    console.log(`Value obj2:`, JSON.stringify(obj2));

    console.log(`
                       === Method Properties ===
              `);

    let obj3 = {
        foo(a, b) {
            a + b;
        },
        bar(x, y) {
            x * y;
        },
        * quux2(x, y) {
            x + y;
        }
    };

    console.log(`Value obj3:`, obj3);

}
module.exports.execute = execute;
``` 
# fnMap from coverage-final.json
`{
  "0": {
    "name": "execute",
    "decl": {
      "start": {
        "line": 1,
        "column": 9
      },
      "end": {
        "line": 1,
        "column": 16
      }
    },
    "loc": {
      "start": {
        "line": 1,
        "column": 19
      },
      "end": {
        "line": 48,
        "column": 1
      }
    },
    "line": 1
  },
  "1": {
    "name": "(anonymous_1)",
    "decl": {
      "start": {
        "line": 21,
        "column": 15
      },
      "end": {
        "line": 21,
        "column": 16
      }
    },
    "loc": {
      "start": {
        "line": 21,
        "column": 21
      },
      "end": {
        "line": 21,
        "column": 27
      }
    },
    "line": 21
  }
}`
## Forensic Information

**Operating System:**
windows
**Environment Information:**

https://gist.github.com/RoniSegal/1db891cfa7953c4e1b12597dfdddb0c8

**Comment by bcoe** [comment]
agreed, if a method shorthand is used for an object property it would appear as though we do not count it in our function map -- interestingly, if you switch to `{a: (args) => {}}` it works as expected.

**Comment by coreyfarrell** [comment]
This is a bug in `istanbul-lib-instrument`.  I've posted a patch for it at istanbuljs/istanbuljs#182.
