### ISSUE TITLE
Coverage output is empty with TypeScript & Mocha

### ISSUE THREAD

**Issue by CynicalBusiness** [istanbuljs/nyc#861]
## Expected Behavior
NYC Creates coverage reports

## Observed Behavior
NYC reports, both the table printed to the console and `lcov.info`, are empty. No matter how much I change imports, mess with configs, or update build settings for TS, I still get a completely empty coverage output.

The contents of `.nyc_output` are several JSON files containing nothing but `{}`.

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/VevoxDigital/Lynxii
This is the repository I'm having trouble with

## Forensic Information

**Operating System:** Windows 7 64-bit
**Environment Information:** https://gist.github.com/CynicalBusiness/f6d3c9329e2216b971dcf75e6b9d1b88

I'm really not sure what to do at this point. The few tests I have run and pass without issue, I just cannot seem to generate coverage for them.

**EDIT:** Coverage doesn't generate on TravisCI either, leading me to believe the issue is not OS-dependent.

**Comment by bcoe** [comment]
Please see https://github.com/Microsoft/TypeScript/issues/24993, I'm interested in overhauling our TypeScript support and would love your feedback and requirements.

**Comment by JaKXz** [comment]
Hi @CynicalBusiness sorry for the late reply. I tried getting Lynxii up and running locally but am having a bunch of compiler issues with TypeScript. If I could get it working, I would make a PR with these changes to your nyc config [everything else looks great]:

```json
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true,
    "include": [
      "src"
    ]
```

after running `yarn add -DW @istanbuljs/nyc-config-typescript`. This has worked for other TypeScript projects so let me know if you are still having problems.

**Comment by PoByBolek** [comment]
For what it's worth, I recently had a similar issue with running nyc from gulp (on Windows 10) with precompiled TypeScript files.

I was trying to generate test coverage by starting nyc like this:

    childProcess.spawn(
        path.join("node_modules", ".bin", "nyc"),
        [
            "--reporter=text",
            "--all",
            "--include=src/**/*.js",
            "--show-process-tree",
            path.join("node_modules", ".bin", "mocha"),
            "src/**/*.spec.js",
        ],
        {
            stdio: "inherit",
            shell: true,
        }
    );

Which generated this output:

    ----------|----------|----------|----------|----------|-------------------|
    File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
    ----------|----------|----------|----------|----------|-------------------|
    All files |        0 |        0 |        0 |        0 |                   |
    ----------|----------|----------|----------|----------|-------------------|
    nyc
    ├─┬ C:\Program Files\nodejs\node.exe D:\...\node_modules\mocha\bin\mocha src/**/*.spec.js
    │ │   64.38 % Lines
    │ └── C:\Program Files\nodejs\node.exe D:\...\node_modules\mocha\bin\_mocha src/**/*.spec.js --no-config --no-package --no-opts --diff --extension js --reporter spec --slow 75 --timeout 2000 --ui bdd
    │       64.38 % Lines
    └── C:\Program Files\nodejs\node.exe D:\...\node_modules\nyc\bin\nyc.js --reporter=text --all --include=src/**/*.js --show-process-tree node_modules\.bin\mocha src/**/*.spec.js
          0 % Lines

Note that there is this extra nyc.js process at the end with 0 % line coverage. However, starting nyc directly from the command line didn't produce any coverage report either altough the process tree looked different:

    D:\...> node_modules\.bin\nyc --reporter=text --include=src/**/*.js --show-process-tree node_modules\.bin\mocha src/**/*.spec.js
    ----------|----------|----------|----------|----------|-------------------|
    File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
    ----------|----------|----------|----------|----------|-------------------|
    All files |        0 |        0 |        0 |        0 |                   |
    ----------|----------|----------|----------|----------|-------------------|
    nyc
    └─┬ C:\Program Files\nodejs\node.exe D:\...\node_modules\mocha\bin\mocha src/**/*.spec.js
      │   64.38 % Lines
      └── C:\Program Files\nodejs\node.exe D:\...\node_modules\mocha\bin\_mocha src/**/*.spec.js --no-config --no-package --no-opts --diff --extension js --reporter spec --slow 75 --timeout 2000 --ui bdd
            64.38 % Lines

I finally got this to work by calling nyc and mocha directly from within my Gulpfile. This basically copies the behavior of [`nyc/bin/nyc.js`](https://github.com/istanbuljs/nyc/blob/master/bin/nyc.js) but without spawning any additional processes:

    function runTestsWithCoverage(callback) {
        const options = JSON.parse(fs.readFileSync("./package.json"));
        options.nyc = options.nyc || {};
        options.mocha = options.mocha || {};
        const nyc = new NYC(options.nyc);
        if (options.nyc.clean) {
            nyc.reset();
        } else {
            nyc.createTempDirectory();
        }
        if (options.nyc.all) {
            nyc.addAllFiles();
        }

        const mocha = new Mocha(options.mocha);
        mocha.files = glob.sync("src/**/*.spec.js"));
        mocha.run(code => {
            process.exitCode = Math.min(code, 255);

            nyc.writeProcessIndex();
            nyc.maybePurgeSourceMapCache();
            if (options.nyc.checkCoverage) {
                nyc.checkCoverage({
                    lines: options.nyc.lines,
                    functions: options.nyc.functions,
                    branches: options.nyc.branches,
                    statements: options.nyc.statements
                }, options.nyc['per-file']);
            }
            if (!options.nyc.silent) {
                nyc.report();
            }

            callback(process.exitCode ? new Error(process.exitCode) : undefined);
        });
    }
