### ISSUE TITLE
ReferenceError: cov_2f2nf56osd is not defined

### ISSUE THREAD

**Issue by s-a** [istanbuljs/nyc#874]
Using `puppeteer` in mocha unit tests will lead to the following error while performing code coverage.

I tried to exclude `node_modules` with `nyc.exclude` settings without success. Does anyone know how to work around this problem?

```bash
Error: Evaluation failed: ReferenceError: cov_2f2nf56osd is not defined
    at el (<anonymous>:1:7)
      at ExecutionContext.evaluateHandle (node_modules\puppeteer\lib\ExecutionContext.js:88:13)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by s-a** [comment]
Lucky shot. It helps to add this to `package.json`

```js
  "nyc": {
    "exclude": [
      "test-helper"
    ]
  },
```

This is the folder where I uses `puppetter` module.

**Comment by bcoe** [comment]
@s-a 👍 there are some known incompatibilities between nyc and puppeteer; so your correction seems reasonable.

You might also look at this:

https://github.com/istanbuljs/puppeteer-to-istanbul

which is an attempt to allow you to run Istanbul coverage reports with puppeteer.
