### ISSUE TITLE
nyc 12.0.2 failing to run tests

### ISSUE THREAD

**Issue by Bamieh** [istanbuljs/nyc#875]
I've just created a new project with nyc, and the nyc coverage tool is failing, this behavior is failing only in the latest version (`12.0.2`) it does work fine on older versions (`11.9.0`).

Command Ran:
```
$ nyc mocha
```

`.nycrc` file:

```
{
  "description": "nyc Coverage tool configurations.",
  "nyc": {
    "extension": [ ".js" ],
    "include": [
      "src/**/*.js"
    ],
    "reporter": [
      "lcov",
      "text"
    ],
    "sourceMap": false,
    "instrument": false
  }
}
```

## Expected Behavior
To work as `11.9.0`
![image](https://user-images.githubusercontent.com/6191849/42116741-5e20781a-7c01-11e8-80d0-39f0441a36ca.png)

## Observed Behavior
version `12.0.2` does not work.

![image](https://user-images.githubusercontent.com/6191849/42116665-f96162c2-7c00-11e8-9327-4fa3e5a464ed.png)

## Forensic Information

tested on multiple machines, the issue is with `nyc` version `12.0.2`

**Operating System:** mac.
**Environment Information:** 

```
node: v10.3.0
npm: 6.1.0
```

**Comment by JaKXz** [comment]
Does v13 work for you?

**Comment by Bamieh** [comment]
sadly i just used another library since the setup greatly exceeded my expected time. The magic promised by nyc is not super valid as you have wear a swim-suite and dive deep into the readme and issues to get the basic setup working.

To get real coverage instead of having only the tested files covered you have to have this config files as the minimum required configs:

```
{
  "all": true,
  "require": [
    "babel-register"
  ],
  "extensions": [
    ".js"
  ],
  "include": [
    "src/**/*.js"
  ],
  "reporter": [
    "lcov",
    "text-summary"
  ],
  "sourceMap": false,
  "instrument": true
}
```

... this is far from magic
- I have to require `babel` although my project is not using it.
- I have to realize that I have to `"instrument"` the code, if I didnt nyc just fails silently giving Unknown coverage.
- I have to learn about the `"all"` flag. Why do i need to set the `"all"` flag since I am explicitly `"including"` the files I want to test the coverage against.
- All this, plus the latest version was broken (how did that pass the basic unit tests?).

Sorry if this comes out as a negative comment, but I hope this would be taken as constructive feedback, and huge thanks to providing this tool and offering your time to OSS. ❤️

**Comment by coreyfarrell** [comment]
I'm closing this ticket since it appears you've moved on and the ticket does not contain information needed to triage.  We cannot provide any help on this issue without seeing a repository demonstrating the issue.
