### ISSUE TITLE
How to configure reporters?

### ISSUE THREAD

**Issue by Viatorus** [istanbuljs/nyc#876]
I would like to change the filename of the json reporter:
https://github.com/istanbuljs/istanbuljs/blob/3ef809b9ad430439844f1d9f5c4f4f2958030a8b/packages/istanbul-reports/lib/json/index.js#L8

How can I configure this using nyc?

With the _karma-coverage-istanbul-reporter_ I can set it this way:

```js
// Most reporters accept additional config options. You can pass these through the `report-config` option
'report-config': {
  // all options available at: https://github.com/istanbuljs/istanbuljs/blob/aae256fb8b9a3d19414dcf069c592e88712c32c6/packages/istanbul-reports/lib/html/index.js#L135-L137
  html: {
    // outputs the report in ./coverage/html
    subdir: 'html'
  }
}
```

**Comment by JaKXz** [comment]
Hi @Viatorus sorry for the late reply, I don't think it's possible to change the _name_ of the json file produced. And I'm pretty sure there are good reasons for that in the way NYC works, like combining coverage across multiple reports and such. You should be able to change the report dir like you mentioned, there's mention of that config option on the readme and I think in the tutorials as well. 

Any thoughts @coreyfarrell @bcoe?

**Comment by coreyfarrell** [comment]
You can change the directory using command-line `--report-dir` or config `reportDir`.  NYC doesn't implement support for setting other report config options.  To support this you would need to pass report config per reporter, but the `reporter` option is an array not an object.

So short answer I'm not sure how this could be implemented in NYC while maintaining compatibility with existing configuration by file and command-line.
