### ISSUE TITLE
nyc with the npm package `config` - does not load env files

### ISSUE THREAD

**Issue by osher** [istanbuljs/nyc#877]
## Expected Behavior
Assuming the Given:
- Given a project that uses `config`.
- Given the project has a `config/test.yaml` with test settings
- Given the `env-pass NODE_ENV=test node_modules/mocha/bin/mocha -b` commnd runs successfully and all tests pass. ([env-pass](https://www.npmjs.com/package/env-pass) is a cli utility to pass env vars).

Then, when running The command: 
```
Set NODE_ENV=test && nyc -r lcov --show-process-tree --report-dir coverage/unit mocha -b
```
I expect that suites that `require('config')` to get the **test** values and both the tests and the SUT should run with these settings, and all tests should pass.

## Observed Behavior
`config` declares at startup:
```
WARNING: NODE_ENV value of 'test ' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
```
`config` finds `config/default.yaml`, but does not find `config/test.yaml`.
The tests therefore fail.

## Forensic Information

**Operating System:** Windows 10 pro
**Environment Information:** 
- **Node version:** 8.9.4
- npm ls: https://gist.github.com/osher/034c5185e2f9aee68c0b38f1f6b901c1

**Comment by osher** [comment]
wow. we're entering voodoo zone:

I just found out that `config` can find `config/dev.yaml`, but not `config/test.yaml`.
(ie `NODE_ENV=dev` vs `NODE_ENV=test`)

Does that ring a bell to anyone?

**Comment by osher** [comment]
baaaah.
I'm working around the problem by 
```
copy config/test.yaml config/unit.yaml
Set NODE_ENV=unit
nyc -r lcov --show-process-tree --report-dir coverage/unit mocha -b
```
but this does not fit with our team's standards...  help?

**Comment by osher** [comment]
I broke down with `nyc`. I fellback to `istanbul@1.1.0-alpha.1'

**Comment by coreyfarrell** [comment]
Could you link to an example repo showing this issue ocuring?  Do you know if this is a Windows specific issue or does it happen on Linux or Mac as well?  Worth noting that neither nyc nor the istanbuljs libs touch (or even read) NODE_ENV, many people use this to control babel settings.

**Comment by osher** [comment]
Didn't forget you - I will, but am flodded at the moment.
the project found a temporal setup with `istanbul@1.1.0-alpha.1`, but it basically understood it' can't stay like this - so I'll be back.

Sorry for the delay.
![image](https://user-images.githubusercontent.com/803101/43251905-ea26788c-90c9-11e8-9a3d-bfe42be5db53.png)

**Comment by coreyfarrell** [comment]
`config` is not part of nyc so I don't think this is the right place to report this issue.  Based on what you've posted it seems like the `Set` command on Windows is not working the way you want.  I suggest you should just use `env-pass` or `cross-env` to set variables.
