### ISSUE TITLE
coverage not reported for files with "test" in the name

### ISSUE THREAD

**Issue by andrewplummer** [istanbuljs/nyc#886]
I found a very strange bug that I actually hit. I [set up a repo](https://github.com/andrewplummer/nyc-bug-test) to test it.

Basically, when any required file has `test` in the name as a standalone word (i.e. `test` or `foo-test`, but not `footest`), coverage will not be reported for that file. Interestingly, this bug doesn't occur for symlinked files. I encountered this when I renamed my file from `xxxtest` to `xxx-test`.

You can confirm this by cloning the repo and trying:

```
nyc bin/foo
nyc bin/symtest
nyc bin/footest
```

Coverage will be correctly output for the first 2 only, but will report as 0% for the third.

OS: OSX High Sierra 10.13.5
Node: v6.9.1
NPM: 3.10.8

**Comment by andrewplummer** [comment]
Confirmed that bug exists in node 10.6.0 and npm 6.1.0 as well.

**Comment by coreyfarrell** [comment]
This is a documentation bug, `**/*-test.js` is excluded by default.  See https://github.com/istanbuljs/istanbuljs/blob/d23d023d43c7b030e708518e6791b67f39c4c9ad/packages/test-exclude/index.js#L130 for correct list of excludes.

When I get a chance I will be posting a patch to fix this issue, but the fix will be to update the README.md.

**Comment by andrewplummer** [comment]
Okay... well I thought I could workaround by passing an `include` flag, but that doesn't seem to work... any way I can explicitly override the excludes?

**Comment by coreyfarrell** [comment]
You can use the [`exclude` flag](https://github.com/istanbuljs/nyc#excluding-files), but note that this *replaces* all default exclude paths.  I'm not happy with this need to completely replace the exclude list.  I'm exploring options to make it easier to manipulate the list without completely replacing them, but it's still in the early idea stage.

**Comment by andrewplummer** [comment]
Ok, this worked for me! I basically have passed `"exclude": "none"` in my .nycrc file now (couldn't think of anything else. Using the include flag would have been slightly more intuitive but this solution works just fine for me! Thanks!

**Comment by coreyfarrell** [comment]
FWIW the `exclude` setting is actually an array so the correct setting would be `"exclude: []`.
