### ISSUE TITLE
Dose nyc support yaml format configuration file?

### ISSUE THREAD

**Issue by poppinlp** [istanbuljs/nyc#892]
I found configuration file named `.nycrc` in your README which is in JSON format. So dose this support yaml configuration file?

**Comment by coreyfarrell** [comment]
Only JSON is supported.

**Comment by poppinlp** [comment]
OK. Thanks. Do you think you need a PR for that? :)

**Comment by coreyfarrell** [comment]
I'd be open to this if it can be done without bloating NYC.  Specifically I do not want `npm install nyc` to actually include modules needed to process YAML (or other format types).  Instead I'd be looking for NYC to report an error if `.nycrc.yaml` is found but the module needed to load it is not installed.  So `npm install --save-dev nyc js-yaml` would be needed.

I think we'll need something similar to `interpret` (but not exactly the same).  `interpret` is designed to hook the node.js `require()` funciton, we cannot do that.  So NYC cannot use `require-yaml`, it would need to use a module that simply loads YAML without touching the node.js module loader (js-yaml I think?).

**Comment by poppinlp** [comment]
OK. I agree with you.
I'll think about what you said. And yep, i think `js-yaml` is good.

**Comment by JaKXz** [comment]
@poppinlp are you still interested in writing that PR?
