### ISSUE TITLE
Consistent naming for *-directory options

### ISSUE THREAD

**Issue by AndrewFinlay** [istanbuljs/nyc#895]
## Expected Behavior
Should be able to use `--temp-dir --report-dir` and/or `--temp-directory --report-directory`
Not a big issue but one that's annoying while configuring nyc, and it should be an easy fix.

## Observed Behavior
Must use --temp-directory and --report-dir

## Bonus Points! Code (or Repository) that Reproduces Issue
N/A

## Forensic Information
Should be able to do this with a few yargs aliases, let me know if you'd like a PR

**Comment by coreyfarrell** [comment]
I'm leaning towards adding a --temp-dir option and making --temp-directory `deprecated`, or at least undocumented.  My preference is that we not have two officially documented ways.  yargs is outside my area of knowledge so I'm unsure how this would be accomplished.  If you'd like to submit a PR that would be nice.

**Comment by AndrewFinlay** [comment]
Hi Corey,

I've put up a PR for this here, #897.  It's pretty straight forward aside from how to test that the deprecated command still works.
