### ISSUE TITLE
how to instrument tsx files

### ISSUE THREAD

**Issue by henryhp** [istanbuljs/nyc#900]
## Expected Behavior

instrument tsx files

## Observed Behavior

nyc -e jsx -e tsx -e ts -e js instrument src src_dst
![image](https://user-images.githubusercontent.com/5212157/43889959-0de8b77e-9bf8-11e8-98dd-64831e746fd3.png)
and the file  index.tsx not be intrumented

## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

**Comment by coreyfarrell** [comment]
Please link a repository so we can know what is going wrong.  See also https://istanbul.js.org/docs/tutorials/typescript/.

**Comment by henryhp** [comment]
ok  here are the rep link 
https://github.com/henryhp/nyc-tsx-examale

and  nyc instrument src src_dst,  fooTsx.tsx has been instrumented,but index.tsx does not work

node v10.4.1
npm 6.1.0
mac os 10.13.6

**Comment by ORESoftware** [comment]
1. transpile tsx to js
2. send the js to the browser

**Comment by henryhp** [comment]
and the coverage report will see as js file?

**Comment by ORESoftware** [comment]
@henryhp read this article:
https://medium.com/@the1mills/front-end-javascript-test-coverage-with-istanbul-selenium-4b2be44e3e98

**Comment by bennyn** [comment]
For me `nyc` always complains about import statements when trying to instrument `.tsx?` files.

**Example:**

> (function (exports, require, module, __filename, __dirname) { import {Candlestick} from "../../app/chart";

I would like to get coverage for my TSX files using the Jasmine testing framework and node-ts. Here is the config I put together:

**.nycrc**

```json
{
  "nyc": {
    "cache": false,
    "extension": [
      ".ts",
      ".tsx"
    ],
    "include": [
      "src/**/*.ts"
    ],
    "reporter": [
      "lcov"
    ],
    "require": [
      "ts-node/register/type-check"
    ]
  }
}
```

**package.json**

```json
"coverage": "nyc jasmine"
```

Am I missing something obvious in my configs? 👀 

I got it running with `jasmine-ts` (which uses `node-ts` under the hood) like this:

**package.json**

```json
"coverage": "nyc -r lcov -e .ts -x \"*.test.ts\" jasmine-ts \"src/**/*.test.ts\""
```

**Comment by JaKXz** [comment]
Thank you for the issue! I would like to really consolidate all the typescript issues we've been having, but, in this case are you satisfied with the answers here and the tutorial? Please do feel free to contribute any improvements :)

**Comment by basickarl** [comment]
Any answer? I'd like to know this also.
