### ISSUE TITLE
Call for testers of `next` version of nyc and istanbul dependencies.

### ISSUE THREAD

**Issue by coreyfarrell** [istanbuljs/nyc#902]
I'm seeking testers for nyc@13, babel-plugin-instrument@5 and `next` versions of modules from the istanbul monorepo so we can promote it to latest.  If you have a chance please retest some of your projects using these `next` versions, report and regressions here (only issues which did not exist in 12.0.2).  For bugs that are not new please open a separate ticket.

Be aware these `next` are meant for use with Babel 7, not babel 6.  If you've followed the ES2015 tutorial please see the updated version at https://github.com/istanbuljs/istanbuljs.github.io/blob/54992fdc8cdd2bfd5a471754f315c51724bef520/content/docs/tutorials/es2015.md.

CC @bcoe @JaKXz @hzoo @JLHwung @addaleax @kevinrambaud @LinusU @pedrocarrico @kevinkir @CodeTroopers @stoffeastrom @bmeck @msluther @chrismohr

**Comment by LinusU** [comment]
Tried it here: https://github.com/ctrl-alt-deseat/ctrlpanel-core

Works great 🙌

**Comment by coreyfarrell** [comment]
I've reopened this ticket as babel 7.0.0 was released so `npm i nyc@next` will now use `^7.0.0` of babel instead of using a beta version.  babel-plugin-istanbul has not yet been updated (it is not a dependency of nyc).  I plan to publish that the `next` tag on npm tomorrow.

Anyone who has a chance to test some of their projects the updated `nyc@next` would be appreciated.
