### ISSUE TITLE
Use nyc report to report karma coverage generated files

### ISSUE THREAD

**Issue by basickarl** [istanbuljs/nyc#903]
Hi I'm using karma-coverage to generate coverage in the coverage directory.
![screen shot 2018-08-14 at 12 14 20](https://user-images.githubusercontent.com/10507098/44086035-9b07af54-9fbb-11e8-8104-5cc63fe81355.png)

I'm wondering. How would I use `nyc report` to report these?

**Comment by JaKXz** [comment]
Sorry I'm not sure I fully understand your question.

`nyc report` takes the last unit test run with coverage enabled to spit out the coverage reports given that data.

It looks like karma-coverage is giving you that functionality already.

**Comment by AmeCode** [comment]
I have a similar question how can nyc report be used to report remap-istanbul generated .json file?

**Comment by Aqours** [comment]
1. delete `.nyc_output/*` files
2. copy your generated .json file to `.nyc_output/`
3. run `nyc report`

Above works fine.

**Comment by JaKXz** [comment]
To build on @Aqours suggestion, I think this would also work - set your nyc config like so:

```json
"reporter": [],
"tempDir": "<folder where your json files are generated>"
```

I'm going to close this issue for now, feel free to submit a PR for documenting this to https://github.com/istanbuljs/istanbuljs.github.io
