### ISSUE TITLE
nyc not working with node cli option correctly.

### ISSUE THREAD

**Issue by viane** [istanbuljs/nyc#910]
## Background
Right now I'm use mocha/supertest to test my APIs, the server end has special list of accepted ciphers, so the old command line that I use is:

>node --tls-cipher-list='ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:' node_modules/mocha/bin/_mocha test/server/test.js -bail --timeout 10000 --reporter spec

## Expected Behavior
Above command line will execute and test correctly for the APIs, however, when I try to load mocha into nyc, which looks like:

>node --tls-cipher-list='ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:' **node_modules/nyc/bin/nyc** node_modules/mocha/bin/_mocha test/server/test.js -bail --timeout 10000 --reporter spec | bunyan -o short && nyc report --reporter=lcov

## Observed Behavior
The testcase breaks with ssl cipher issue, the exception is the same as if I don't run node with the option of `--tls-cipher-list`.

## Temporary work around
If I use global nyc then it will work as I expect, the CLI like this:

>**nyc** node --tls-cipher-list='ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:' node_modules/mocha/bin/_mocha test/server/test.js -bail --timeout 10000 --reporter spec

So Im wondering if its possible for nyc to be used locally with node cli option enabled?

**Operating System:** OSX.
**Environment Information:**
v8.10.0
6.4.0

**Comment by coreyfarrell** [comment]
@viane I recommend that you set the `NODE_OPTIONS` environmental variable.  For example:
```sh
cross-env NODE_OPTIONS="--tls-cipher-list='...'" node nyc mocha
```

This way the node will get the option no matter how many sub-processes are spawned.

**Comment by coreyfarrell** [comment]
I believe this will be resolved by using the `NODE_OPTIONS` environment, if you have further questions let us know and we can reopen.
