### ISSUE TITLE
After reinstalling node_modules NYC skip some folders 

### ISSUE THREAD

**Issue by olandreievvirtru** [istanbuljs/nyc#917]
I reinstall my node_mudules and after that NYC start skip `lib/` folder

My config:
```|
"scripts": {
    ...
    "test": "NODE_ENV=local  mocha -t 5000 --recursive tests/ --opts ./tests/mocha.opts",
    "coverage": "nyc npm test && nyc report --reporter=lcov",
  },
  "nyc": {
    "exclude": [
      "tests"
    ],
    "sourceMap": false,
    "instrument": false
  },
  "devDependencies": {
    "mocha": "^2.2.5",
    "nyc": "^11.6.0",
    "sinon": "^6.0.0",
    ...
  },
```
 My folder structure:
```bash
├── routes
│   ├── *.js
│   ├── *.js
│   ├── *.js
│   └──  *.js
├── lib
│   ├── folder
│   │   ├── folder
│   │   │    ├── *.js
│   ├── folder2
│   │   ├── folder2
│   │   │    ├── *.js
│   ├── ...
│   └──  *.js
├── node_modules
├── tests
├── package.json
├── ...
└── .gitignore
```
## Expected Behavior
File                         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    98.04 |       75 |      100 |       98 |                   |
 envs             |      100 |      100 |      100 |      100 |                   |
  local.js        |      100 |      100 |      100 |      100 |                   |
 lib                 |       100|       100|      100 |      100 |                   |
...|...|...|...|...|
 routes           |    97.96 |       50 |      100 |    97.92 |                   |
  ***.js |      100 |       50 |      100 |      100 |                45 |
  *****.js   |      100 |      100 |      100 |      100 |                   |
  *****.js       |      100 |      100 |      100 |      100 |                   |
  *****.js       |       90 |      100 |      100 |       90 |                12 |
## Observed Behavior
File                         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------|----------|----------|----------|----------|-------------------|
All files         |    98.04 |       75 |      100 |       98 |                   |
 envs             |      100 |      100 |      100 |      100 |                   |
  local.js        |      100 |      100 |      100 |      100 |                   |
 routes           |    97.96 |       50 |      100 |    97.92 |                   |
  ***.js |      100 |       50 |      100 |      100 |                45 |
  *****.js   |      100 |      100 |      100 |      100 |                   |
  *****.js       |      100 |      100 |      100 |      100 |                   |
  *****.js       |       90 |      100 |      100 |       90 |                12 |

## Forensic Information
**Operating System:** MAC.
Even if I add: 
```
    "include": [
      "lib/",
      "routes/",
      "envs/"
    ],
```
to NYC config, output not changing. Coverage for `lib/` folder still missed.

**Comment by coreyfarrell** [comment]
NYC is a complicated system with many interactions to other software.  Please link to a repository demonstrating the issue you are having.

**Comment by JaKXz** [comment]
Do you have tests exercising the `lib/` folder? You can also try the `--all` option.
