### ISSUE TITLE
Vue html report is compiled wrong "Unable to lookup source"

### ISSUE THREAD

**Issue by ilearnio** [istanbuljs/nyc#920]
## Observed Behavior

It compiles .js files correctly, but for .vue files it tries to resolve them by a path that contains `?#######` in the end, so it cannot be resolved. That's one issue, another is that the html cannot be opened in browser

![image](https://user-images.githubusercontent.com/14331216/45842006-23afdb80-bd24-11e8-9ba5-32bbbd588f4f.png)

Also it worth to mention that it reads the .vue files and checks the coverage, but as I said earlier clicking on files doesn't work (getting "file not found" Chrome's page) and if I manage to open it there is that error on the screenshot above.

![image](https://user-images.githubusercontent.com/14331216/45842282-eb5ccd00-bd24-11e8-82ab-f4f6e245f6ab.png)

So my question is, is this a bug that should be fixed or I can prevent it from adding that "?######" somehow?

## Forensic Information

**Operating System:** the operating system you observed the issue on.

OSX High Sierra

**Environment Information:** information about your project's environment, see instructions below:

Node 8.11.3
Yarn 1.9.4
Nyc 13.0.1

Also I don't use webpack or karma, testing vue with Node only.

package.json:
```
"scripts": {
  "unit": "mocha --require test/unit/setup src/**/*.spec.js --watch-extensions js,vue",
  "cover": "rm -rf coverage .nyc_output && nyc yarn unit",
},
"nyc": {
  "cache": true,
  "extension": [
    ".js",
    ".vue"
  ],
  "include": [
    "src/**/*.js",
    "src/**/*.vue"
  ],
  "reporter": [
    "html",
    "text",
    "text-summary"
  ]
},
```

**Comment by nadavye** [comment]
Watching

**Comment by ilearnio** [comment]
Oh, I just found out that it's not related to nyc because source-maps have these `?7b82448b` as well. Something is wrong in my setup. Sorry that disturbed you 😣, closing

**Comment by sterlingstokes** [comment]
@ilearnio For posterity's sake, can you describe what was wrong in your setup? I am having the same issue.

**Comment by ilearnio** [comment]
@sterlingstokes I was using `vueify` package to compile vue files in Node. It was adding these numbers to the end of paths, so I had to fork it and fix that as well as other stuff for my needs https://github.com/ilearnio/vueify#1f23ac8

**Comment by ilearnio** [comment]
Basically this was the fix for me https://github.com/ilearnio/vueify/commit/b2824c900bedf64106343d71a8bf4cb662106e7c#diff-ee97c5091b89979aace94674818996baR200
