### ISSUE TITLE
nyc.include not working in package.json

### ISSUE THREAD

**Issue by toymachiner62** [istanbuljs/nyc#923]
I noticed the default nyc config only generates coverage for files which have a unit test covering some of the file.

When adding this section to my `package.json`, it's not including all of the files in my `src/` dir

Not generating code coverage for files in `src/` that don't have a test importing that file
```json
"nyc": {
    "include": [
      "src/**/*.js"  <--- NOT GENERATING COVERAGE FOR FILES IN src/ THAT DON'T HAVE A TEST
    ],
    "exclude": [
      "src/db",
      "**/*.spec.js",
      "coverage"
    ]
  }
```

Generating code coverage for files in `src/` that don't have a test importing that file - as expected, but i don't want to have to `exclude` so many other files/folders.
```json
"nyc": {
    "all": true,
    "exclude": [
      "src/db",
      "**/*.spec.js",
      "coverage"
    ]
  }
```

**Comment by aleskozina** [comment]
This is also applied to the cli variant. `--include|-n` has no effect.

**Comment by JaKXz** [comment]
Hi @toymachiner62 @aleskozina sorry for the late reply - can you provide a [minimal] repo that reproduces this problem with the latest version of nyc?

**Comment by AndrewFinlay** [comment]
I'm not sure that there is a problem here, this looks like expected behaviour to me.  By default nyc only instruments the set of files it encounters during a test, if you want to include untested files in your coverage you add the --all flag to expand that set.  The include and exclude arrays only serve to remove files from the set of covered files.

This is probably an issue with the documentation, it's not really clear that the 'include' array can only reduce the set of covered files.

**Comment by toymachiner62** [comment]
@AndrewFinlay The way that I understood the `include` flag was to be the exact opposite of `exclude`.

In my case I want to `include` only files in my `src` dir. 

Instead this is what I'm doing in my `package.json`

```json
"nyc": {
    "all": true,
    "exclude": [
      "node_modules",
      "prod_node_modules",
      "src/db",
      "src/index.js",
      "**/*.spec.js",
      "coverage",
      "test/"
    ]
  }
```

**Comment by AndrewFinlay** [comment]
Assuming that you want your first config to work, have you tried the following?

```json
"nyc": {
    "all": true,  <--- SPECIFY THIS TO GET COVERAGE FOR FILES IN src/ THAT DON'T HAVE A TEST
    "include": [
      "src/**/*.js"  
    ],
    "exclude": [
      "src/db",
      "**/*.spec.js",
      "coverage"
    ]
  }
```

**Comment by JaKXz** [comment]
@AndrewFinlay unfortunately that won't work because specifying `exclude` does not extend on the defaults, it replaces them. @toymachiner62 your `exclude` config looks good to me, we do something similar with our istanbuljs monorepo.

**Comment by AndrewFinlay** [comment]
@JaKXz @toymachiner62, correct me if I'm wrong, but your issue is that you want to generate coverage for files that don't have a test right?

**Comment by toymachiner62** [comment]
That's wrong. I just want to choose which files to include in my coverage report.

**Comment by AndrewFinlay** [comment]
What nyc command are you running?

**Comment by toymachiner62** [comment]
I have an npm script `test-coverage: nyc --reporter=lcov npm run test`

**Comment by AndrewFinlay** [comment]
As far as I understand it, you need to use `--all` to get Nyc to even consider your source files that aren't touched by your tests.  From there you can remove files from that covered set using the `include` and `exclude` arrays.

On it's own, `include` can't expand the set of source files reported on beyond those touched by your tests.

Anyway if this isn't the issue I'd be keen to know what it was, will keep an eye out.
