### ISSUE TITLE
Options For Larger Scale Reports

### ISSUE THREAD

**Issue by Delamater** [istanbuljs/nyc#929]
Question:
We have a use case for >= 100,000 unit test files. So, the report that is generated builds an HTML file that is very large (>= 62 MB) and difficult to scroll through easily. Is it possible to build a report that allows us to define grouping methods for the HTML report output? Perhaps grouped by source name, or custom tags.

**Comment by coreyfarrell** [comment]
Generally test files are ignored by istanbul, so do you mean 100k units in a single package?  TBH I'd suggest looking at ways to split that module into more manageable pieces.

That said reporting is handled by [istanbul-reports](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-reports/lib), the current HTML report is in the html folder.  We would be willing to accept PR's to work towards this.  I'm not sure if we'd want to modify the existing html report to support this use case, probably best to start by copying to a new 'html-huge' folder.

**Comment by Delamater** [comment]
Sorry @coreyfarrell, I'm still learning here and probably using the wrong terminology. I've defined a hundred thousand js files and used the --root command to include them in my istanbul reporting capabilities. They all show up in my report, but only one file (test.js) actually runs. My thought was that many developers in my organization would develop many tests for code coverage, for which I'd want to group for a centralized manager to review. I haven't quite figured out yet how to organize these tests so that they all run. Everything but the main test.js is ignored as you say.

**Comment by JaKXz** [comment]
You could try [SonarQube](https://docs.sonarqube.org/display/PLUG/JavaScript+Coverage+Results+Import#space-menu-link-content) with the lcov reporter, but I can't guarantee that will fit your need.
