### ISSUE TITLE
Use NYC or Istanbul for languages other than Javascript?

### ISSUE THREAD

**Issue by Delamater** [istanbuljs/nyc#930]
Question: 
New to istanbul and NYC. I'm trying to understand if we can apply this tool to a custom built programming language. I see that I can build the coverage.json and use the reporting directive of istanbul to consume that coverage.json. I wonder if there is a way to build a mapping file that tells NYC or istanbul how to interpret my programming language instead of building the coverage.json directly.

**Comment by coreyfarrell** [comment]
Istanbul uses babel under the hood to perform [instrumentation](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-lib-instrument), so 'JS similar' languages such as TypeScript are supported via babel.  It's hard to give a good answer without knowing anything about your custom language.

**Comment by coreyfarrell** [comment]
Generating the coverage.json is language specific so I think this would be up to your compiler to generate coverage counters associated with source locations (so yes generating your own coverage JSON file).  Once you do that it shouldn't be too difficult to use nyc to produce reports based on the coverage.json you generated.  That said this is out of scope for NYC itself.  Once you've generated valid coverage.json if you have trouble getting NYC to produce reports we could possibly help you.
