### ISSUE TITLE
How to disable source code minify?

### ISSUE THREAD

**Issue by IgorNovozhilov** [istanbuljs/nyc#931]
How to disable source code minify at startup `nyc`?
![default](https://user-images.githubusercontent.com/3082812/47453668-02845400-d7d6-11e8-929d-b3c8c2070d11.png)

**Comment by IgorNovozhilov** [comment]
How?

**Comment by JaKXz** [comment]
@IgorNovozhilov could you provide a minimal reproduction in a public repo? Since there are so many moving parts we need that to help understand your problem

**Comment by IgorNovozhilov** [comment]
```
git clone git@github.com:demo-source/nyc-issues-931.git
cd nyc-issues-931/
npm i
node_modules/.bin/nyc npm test
```
output
```
ReferenceError: undefFunc is not defined
    at Object.myFunction (/home/igor/development/test/nyc-issues-931/work.js:1:973)
    at myTest (/home/igor/development/test/nyc-issues-931/test.js:4:10)
    at Object.<anonymous> (/home/igor/development/test/nyc-issues-931/test.js:7:1)
```
just for `npm test`
```
ReferenceError: undefFunc is not defined
    at Object.myFunction (/home/igor/development/test/nyc-issues-931/work.js:2:5)
    at myTest (/home/igor/development/test/nyc-issues-931/test.js:4:10)

```

config in package.json
```
    "nyc": {
        "exclude": [
            "test.js"
        ]
    }
```
work.js:1:973 - is minified
test.js:7:1 - is not minified
How can I make the `work.js` file not be minified, that would be in the test report to understand where the error in the source file?

**Comment by coreyfarrell** [comment]
NYC supports a `compact: false` configuration option or command-line `nyc --compact=false node ./test.js`.  Note lines still will not line up to the original source as instrumentation code is inserted to the source.  For this you will need to enable `produce-source-map` in nyc and use [source-map-support](https://github.com/evanw/node-source-map-support).  I've had mixed results testing with that module... it's complicated.

The `--compact` option is documented in `nyc --help`, the config option is not documented (probably should be).

**Comment by IgorNovozhilov** [comment]
@coreyfarrell. Tried a lot of things, '--compact=false', including. So far, the best option is to restart the tests if they fall. But without 'nyc' 
```sh
$ nyc npm test || npm test
```
it's a best option, short and easy :slightly_smiling_face:

**Comment by IgorNovozhilov** [comment]
жаль, что это не будет поддержано

**Comment by andinoJamesV** [comment]
> NYC supports a compact: false configuration option or command-line nyc --compact=false node ./test.js.  Note lines still will not line up to the original source as instrumentation code is inserted to the source.  For this you will need to enable produce-source-map in nyc and use source-map-support.  I've had mixed results testing with that module... it's complicated.
> The --compact option is documented in nyc --help, the config option is not documented (probably should be).

Do you have any advice about setting this up I am stuck here on this problem at the moment
