### ISSUE TITLE
Question : How to generate HTML report using nyc report tool from .json file ?

### ISSUE THREAD

**Issue by chintan-cybg** [istanbuljs/nyc#935]
I have collected front end coverage data  from  window.__coverage__   in .json format.
Is it possible to generate detailed coverage report which show coverage data line by line ? 

currently i am using below command to generate report 
nyc report --reporter=html  after putting json file  in   .nyc_output   directory 

Overall report is generated in coverage directory and it shows data for the same. when i click on filename it show below error.  

Cannot read property 'start' of undefined
TypeError: Cannot read property 'start' of undefined 

Am i missing some step here  ?

**Comment by JaKXz** [comment]
Can you provide a minimal reproduction with the latest version of nyc?
