### ISSUE TITLE
Exception thrown when requiring a file twice, once as a source file and once as a compiled file

### ISSUE THREAD

**Issue by ehmicky** [istanbuljs/nyc#940]
[Demo repository](https://github.com/ehmicky/nyc-bug)

Running `nyc node c.js` produces the following output:

```
/home/ether/Desktop/nyc-bug/node_modules/nyc/node_modules/istanbul-lib-source-maps/lib/transformer.js:97
            mappedCoverage.addStatement(mapping.loc, hits);
                           ^

TypeError: mappedCoverage.addStatement is not a function
    at /home/nyc-bug/node_modules/nyc/node_modules/istanbul-lib-source-maps/lib/transformer.js:97:28
    at Array.forEach (<anonymous>)
    at SourceMapTransformer.processFile (/home/nyc-bug/node_modules/nyc/node_modules/istanbul-lib-source-maps/lib/transformer.js:88:34)
    at /home/nyc-bug/node_modules/nyc/node_modules/istanbul-lib-source-maps/lib/transformer.js:169:24
    at Array.forEach (<anonymous>)
    at SourceMapTransformer.transform (/home/nyc-bug/node_modules/nyc/node_modules/istanbul-lib-source-maps/lib/transformer.js:159:25)
    at MapStore.transformCoverage (/home/nyc-bug/node_modules/nyc/node_modules/istanbul-lib-source-maps/lib/map-store.js:143:8)
    at SourceMaps.remapCoverage (/home/nyc-bug/node_modules/nyc/lib/source-maps.js:29:41)
    at NYC.getCoverageMapFromAllCoverageFiles (/home/nyc-bug/node_modules/nyc/index.js:436:30)
    at NYC.report (/home/nyc-bug/node_modules/nyc/index.js:442:18)
```

`c.js` contains:

```js
require('./a')
require('./b')
```

`a.js` contains:

```js
module.exports = {}
```

`b.js` is produced by `babel a.js --out-file b.js --source-maps` and contains:

```js
module.exports = {};

//# sourceMappingURL=b.js.map
```

`b.js.map` contains:

```
{"version":3,"sources":["a.js"],"names":[],"mappings":"AAAA,MAAM,CAAC,OAAP,GAAiB,EAAjB","file":"b.js","sourcesContent":["module.exports = {}\n"]}
```

## Expected Behavior

`nyc` should exit without errors.

## Observed Behavior

`nyc` throws an exception.

## Forensic Information

**Operating System:** Ubuntu `19.04`.
**Environment Information:** node `v12.2.0`, npm `6.9.0`, nyc `14.1.1`

## Notes

Why would anyone require both the source files and the built/transpiled files? I got into that use case with a source file that exports constants. Those constants are only used by unit tests, i.e. not exported in transpiled files. I.e. tests need to require the source file (to get the constants) + require the transpiled file (to run the code).

**Comment by ehmicky** [comment]
Adding a commit because of the stale bot (this issue is still pending).

**Comment by paulsmirnov** [comment]
My setup (and the result) is quite similar. I'm running tests of different nature during a single coverage pass:

1. Unit tests, which import corresponding source files.
2. Functional tests, which import rollup+babel compiled library.

Tests pass but then NYC fails with "TypeError: mappedCoverage.addStatement is not a function".

**Comment by JaKXz** [comment]
Is this still occurring with the latest versions of nyc and using babel-plugin-istanbul as documented with the preset configuration?

**Comment by paulsmirnov** [comment]
@JaKXz Please give me some time to check it on Monday if you are unable to verify yourself the case I've prepared above. Or you disagree with the example?

**Comment by ehmicky** [comment]
Thanks for checking this out @JaKXz. I've just updated the demo repository with the latest version of `nyc` and the bug still appears. The setup is using `@babel/cli`, not `babel-plugin-istanbul`.

**Comment by paulsmirnov** [comment]
@JaKXz I've updated dependencies in my MWE at [paulsmirnov/issue-nyc-940](https://github.com/paulsmirnov/issue-nyc-940) but it still crashes (nyc@14.1.1, babel-plugin-istanbul@5.1.4, @babel/core@7.4.4, rollup@1.12.3). It is easy to reproduce as described in README.

**Comment by coreyfarrell** [comment]
I've labeled this so the stale bot will leave it alone.  This is a difficult issue I'm not sure how to solve.

**Comment by ehmicky** [comment]
Alright, no worries. If you want to close this issue instead, this might be more appropriate.

**Comment by russellrobinson** [comment]
I'm having this problem too with various Typescript projects.

It seems to be unpredictable, in that a fellow developer hasn't seen the problem on his Mac, and sometimes it goes away on my Ubuntu.

Our deployment - which uses Docker Ubuntu Alpine - never seems to hit the problem.

I hope that helps.

**Comment by coreyfarrell** [comment]
@ehmicky I've found the cause and solution to this issue.  The linked PR fixes your demo repository - I verified by manually editing the `node_modules/istanbul-lib-source-maps/lib/transform.js` installed from your repository.

**Comment by ehmicky** [comment]
@coreyfarrell Great! Thanks for looking into this.
