### ISSUE TITLE
Upgraded to 13.1.0 : Coverage unknown

### ISSUE THREAD

**Issue by navkirat-singh** [istanbuljs/nyc#946]
After upgrade to ver. 13.1.0. from 12.0.2, nyc has stopped generating coverage report. My test cases are executed through mocha and after the execution, following coverage report gets generated.

Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )

I've tried explicitly setting the --hook-run-in-context and --hook-run-in-this-context but still no coverage report gets generated.

My .nycrc file is 
`{
  "include": [
    "./src/**/*.js"
  ],
  "exclude": [
    "./src/**/*.spec.js"
  ],
  "reporter": [
    "text-summary",
    "html"
  ]
}`

**Comment by coreyfarrell** [comment]
We cannot help without a repository demonstrating the problem.  I'm marking this issue stale, if the required information is not provided this issue will be closed.

**Comment by mcoakley** [comment]
I was having a similar issue but even without upgrading. What I did figure out is that I had the latest Node version on my system. Using nvm to run Node LTS I had no issues and my coverage reports started working again.
