### ISSUE TITLE
Coverage for nyc executed outside current working directory

### ISSUE THREAD

**Issue by andrewcharnley** [istanbuljs/nyc#950]
Hi,

I have a lerna repo using npm's relatively new "file:" dependency feature to load resources from parent directories. For a given package when I run "npm run test" within a package it should use nyc/mocha from ../../node_modules/.bin.

`    
    "test:unit": "NODE_ENV=test ../../node_modules/.bin/mocha ./src/*.spec.js ./src/**/*.spec.js",
    "coverage:unit": "../../node_modules/.bin/nyc -- npm run test:unit",
`

If I install nyc globally (wish to avoid) and run directly (without ../../node_modules/.bin/nyc) **files are be covered correctly**. However when running as above only one file will show coverage.

I've tried the --cmd param (which --help shows correctly as the package dir) and also various combinations of "include".

Here's my nyc (13.1.0) config:

`
  "nyc": {
    "sourceMap": false,
    "all": true,
    "instrument": true,
    "include": ["src"],
    "exclude": [
      "**/*.spec.js"
    ],
    "check-coverage": true,
    "per-file": true,
    "lines": 100,
    "statements": 100,
    "functions": 100,
    "branches": 100,
    "reporter": [
      "text"
    ]
  },
`

**Comment by JaKXz** [comment]
Hi @andrewcharnley sorry for the delayed response. We use lerna and nyc for the [istanbuljs monorepo](https://github.com/istanbuljs/istanbuljs) which contains all the instrumentation libraries nyc uses. You can take a look at the config we use there, but without a repo or minimal reproduction I can't offer much more help than that.
