### ISSUE TITLE
Invalid Cobertura report getting generated

### ISSUE THREAD

**Issue by acesiddhu** [istanbuljs/nyc#965]
Demo for reproing the bug
https://github.com/MicrosoftDocs/pipelines-javascript

## Expected Behavior
packages should contain package and package should contain classes

## Observed Behavior
```
<?xml version="1.0" ?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage lines-valid="14" lines-covered="14" line-rate="1" branches-valid="0" branches-covered="0" branch-rate="1" timestamp="1546961803906" complexity="0" version="0.1">
  <sources>
    <source>F:\AgentLocal\_work\8\s</source>
  </sources>
  <packages>
    <class name="test.js" filename="tests\test.js" line-rate="1" branch-rate="1">
```
## Forensic Information

**Operating System:** Windows
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

    "test": "nyc --reporter=cobertura --reporter=html ./node_modules/.bin/mocha tests/**/*.js --reporter mocha-junit-reporter --reporter-options mochaFile=./TEST-RESULTS.xml"

this might be related to https://github.com/istanbuljs/istanbuljs/issues/14
I have tried with latest nyc version as well

**Comment by coreyfarrell** [comment]
The code for the cobertura reporter lives at https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-reports/lib/cobertura.  Unfortunately I'm unable to provide further help on this issue as I do not know anything about cobertura.

**Comment by acesiddhu** [comment]
@coreyfarrell let me know if we need to move this issue to above repo.

**Comment by jjscaria** [comment]
@acesiddhu Looks like there's already a thread going on about this issue: https://github.com/istanbuljs/istanbuljs/issues/66

**Comment by acesiddhu** [comment]
@jjscaria seems like this is the same issue. Thanks for pointing out,

**Comment by coreyfarrell** [comment]
Closing this issue in favor of istanbuljs/istanbuljs#66.
