### ISSUE TITLE
Can someone here answer on this question?

### ISSUE THREAD

**Issue by Guseyn** [istanbuljs/nyc#970]
https://stackoverflow.com/questions/54195826/istanbul-test-coverage-information

**Comment by JaKXz** [comment]
Thanks for the question! You would be more than welcome to post this on our slack group and I think it would reach more eyes. I can also tell you that I think the answer is documented here: https://istanbul.js.org/docs/advanced/alternative-reporters/

**Comment by Guseyn** [comment]
Thank you very much. I'll also put here information about command: 
```bash
nyc report --reporter=json-summary
```
