### ISSUE TITLE
nyc coverage report doesn't recognise source map

### ISSUE THREAD

**Issue by chrisflemming** [istanbuljs/nyc#971]
I'm having difficulty getting nyc to recognise a source map. My original source is typescript which is then transpiled using webpack. Webpack is adding an inline sourcemap to the transpiled output.

I'm then using nyc to instrument the transpiled output:
`nyc instrument build/library.js instrumented`
 I can see the inline source map in the instrumented code.

After testing, I'm dumping the contents of `window.__coverage__` to `.nyc_output/out.json` as explained here: https://istanbul.js.org/docs/advanced/coverage-object-report/

I'm then using nyc to generate a report:
`nyc report`
However the report only lists the one transpiled file, it doesn't recognise the source map.  I need coverage measurements for each of my original typescript source files.

Does anyone have any suggestions regarding what I am doing wrong here?

Many thanks.

**Comment by chrisflemming** [comment]
Cross posted here: https://stackoverflow.com/questions/54231448/nyc-coverage-report-doesnt-recognise-source-map

**Comment by tex0l** [comment]
What version of node are you using ?
I'm experiencing a similar issue after upgrading to nodejs 11.7 or 11.8 (not sure, still investigating).

**Comment by coreyfarrell** [comment]
Please provide a link to repository with a minimal reproduction of the issue.

**Comment by ludetc** [comment]
@chrisflemming Were you able to resolve this? ~thanks

**Comment by rajekumar1536** [comment]
@chrisflemming Please post your solution if its resolved.
