### ISSUE TITLE
Minor release

### ISSUE THREAD

**Issue by Krinkle** [istanbuljs/nyc#972]
Would like to see a release soon, in particular for support of running as `nobody` on Linux. https://github.com/istanbuljs/nyc/commit/ff834aa68

Thanks!

-------

Next release:

* [x] Address Snyk warning. https://github.com/istanbuljs/nyc/commit/409a2f5e340891975a7f
* [x] Restore option fallback. https://github.com/istanbuljs/nyc/commit/28b6d09c5a0
* [x] Support running as `nobody` on Linux. https://github.com/istanbuljs/nyc/commit/ff834aa68
* [x] Land hash algorithm change that adtops SHA256. – https://github.com/istanbuljs/caching-transform/pull/11
* [x] Release of caching-transform for hash algorithm change.
* [x] Bump dependencies.

**Comment by coreyfarrell** [comment]
I'd like to get istanbuljs/caching-transform#11, plus some dependency updates and a new caching-transform release first, then an nyc release including those updates.

**Comment by bcoe** [comment]
@coreyfarrell 👍 will let you take lead on drafting up what you'd like to see in a release of nyc and Istanbul; perhaps you could write up in an issue with check boxes what you'd like to tackle, feel free to delegate a bit to me;

This is my pet little bit of work I'd like to do soon: https://github.com/istanbuljs/istanbuljs/issues/273

**Comment by coreyfarrell** [comment]
nyc 13.2.0 is now published to npm.  You can install using `npm install nyc@next`.  I'm going to do some testing with some larger repos that use `nyc`, probably publish to `latest` in about a week.

Please let me know if you find any regressions in 13.2.0 (specifically something that currently works correctly in 13.1.0 but not 13.2.0).

**Comment by coreyfarrell** [comment]
nyc@13.2.0 has now published to the `latest` tag.
