### ISSUE TITLE
error with mocha on Node.js 11.7.0

### ISSUE THREAD

**Issue by keenwon** [istanbuljs/nyc#973]
## Expected Behavior

No error, consistent with node v10.

### koa-subdomain

repo: https://github.com/keenwon/koa-subdomain
ci: https://travis-ci.org/keenwon/koa-subdomain

node v10:

![image](https://user-images.githubusercontent.com/5516478/51438469-99827e80-1ce7-11e9-9515-3c04473c4c04.png)

node v11.7.0:

![image](https://user-images.githubusercontent.com/5516478/51438477-b5862000-1ce7-11e9-96a9-c0bc7d5645f3.png)

### ELint

repo: https://github.com/keenwon/elint
ci: https://travis-ci.org/keenwon/elint

node v10:

![image](https://user-images.githubusercontent.com/5516478/51438490-ea927280-1ce7-11e9-85fb-363e6f26cdf6.png)

node v11.7.0:

![image](https://user-images.githubusercontent.com/5516478/51438495-f9792500-1ce7-11e9-9fd4-0999e899fb95.png)

## Forensic Information

**Operating System:** macOS and Linux
**Environment Information:** https://gist.github.com/keenwon/846364069714c310e45e630eeba0d24d

**Comment by johannespfeiffer** [comment]
Same here. We used the docker image node:11-alpine and noticed that coverage was down to about 15% (100% before) a few days ago.
As a workaround we now use node:11.6-alpine.

**Comment by nicojs** [comment]
I can confirm this problem on windows, so it doens't seem to be OS specific

**Comment by boneskull** [comment]
Mocha got bit by this too.  pinning to v11.6.0 seems to fix.

**Comment by bcoe** [comment]
see: https://github.com/nodejs/node/issues/25650

**Comment by bcoe** [comment]
this is fixed in `Node@11.8.0`

https://nodejs.org/en/blog/release/v11.8.0/
