### ISSUE TITLE
caching issue with check-coverage & report

### ISSUE THREAD

**Issue by brewster1134** [istanbuljs/nyc#974]
i noticed that when i make configuration changes, the results are not reflected when i use either `nyc check-coverage` or `nyc report`. the only way (that i can find) to force it to refresh, is by running `nyc mocha`

* it happens regardless of if configuration options are set from `package,json` or the command line
* it still happens when `cache` is set to to `false`
* it happens with any configuration option is changed
* it even happens with a new shell session

although it happens with any option, the most visually obvious option i was using test with was `all`. here are steps to reproduce...

```shell
### initial report
nyc report --reporter text
# no files reported (correct)

nyc report --reporter text --all
# no files reported (incorrect)
nyc mocha -all
# all files reported (correct)
nyc report --reporter text --all
# all files reported (correct)

### works in reverse too

nyc report --reporter text
# no files reported (incorrect)
nyc mocha
# no files reported (correct)
nyc report --reporter text
# no files reported (correct)
```

**Comment by coreyfarrell** [comment]
Both `nyc report` and `nyc merge` operate on existing results.  They do not perform instrumentation, they only operate on existing files.  Also note that these sub-commands do not support the `--all` option.
