### ISSUE TITLE
nyc merge fails on missing parent directory of output

### ISSUE THREAD

**Issue by quasicomputational** [istanbuljs/nyc#976]
## Link to bug demonstration repository.

https://github.com/quasicomputational/nyc-merge-missing-parent

## Expected Behavior

nyc creates the directory and writes to the named file.

## Observed Behavior

```
  thing
    ✓ is okay


  1 passing (7ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
failed access input directory non-existent-directory/mocha.json with error:

ENOENT: no such file or directory, stat 'non-existent-directory/mocha.json'
```

## Forensic Information

**Operating System:** Debian.
**Environment Information:** https://gist.github.com/quasicomputational/e423212b707fa2232d04b8dd7578bbf9

**Comment by coreyfarrell** [comment]
FYI you're command-line is incorrect.  The `nyc merge` command requires a positional argument `<input-directory>` before `[output-file]`.  That said even using the correct arguments results in an exception if the destination is a file in a non-existent folder so I've posted a patch for that.
