### ISSUE TITLE
Programmatically add nyc to mocha

### ISSUE THREAD

**Issue by gatsbyz** [istanbuljs/nyc#987]
Current code: 

```
const specFiles = glob.sync('**/*.spec.js', {cwd: directory});

  const mocha = new Mocha();
  mocha.timeout(test.timeout);

  specFiles.forEach(file => {
    mocha.addFile(path.join(directory, file));
  });

  const failures = await new Promise((resolve) => {
    mocha.run(resolve);
  });
```

I want to implement here the `nyc mocha` behavior as it would function in `package.json`'s `npm test` script. Please help!

**Comment by gatsbyz** [comment]
@bcoe  <3

**Comment by JaKXz** [comment]
I'm going to close this issue as a duplicate since there have been [many others](https://github.com/istanbuljs/nyc/search?q=programmatic&type=Issues), especially #499 or #720.
