### ISSUE TITLE
No coverage for files with `n` notation of BigInt()

### ISSUE THREAD

**Issue by kmdrGroch** [istanbuljs/nyc#990]
As it was posted in 10ths of issues, whenever you have e.x. `10n` in the file, this file has no coverage (it is omitted or so).

@coreyfarrell adding `plugins: ["bigInt"]` doesn't solve the problem.

There is no doc, info about solving this problem, so it would be nice to find one, so everyone can use this feature.

if you need repo with `n` notation:
https://github.com/kmdrGroch/BigMath

**Comment by coreyfarrell** [comment]
I just did the following:
```sh
git clone https://github.com/kmdrGroch/BigMath
cd BigMath
npm it
firefox coverage/index.html
```

I'm seeing coverage for `src/*.ts` with the exception of interfaces.ts (which does not contain any bigInt notation).  Maybe you need to flush your node_modules / package-lock.json to clear up an outdated dependency.

**Comment by kmdrGroch** [comment]
@coreyfarrell yea it seems there was some not updated dependency (or sth was cached, HELLO NODE). It indeed worked.
```json
"nyc": {
    "check-coverage": true,
    "lines": 100,
    "statements": 100,
    "functions": 100,
    "branches": 100,
    "include": [
      "src/**/*.js"
    ],
    "reporter": [
      "html"
    ],
    "plugins": [
      "bigInt"
    ],
    "report-dir": "./coverage"
  },
```
For reference for other people in the future ._.
