### ISSUE TITLE
How To Increase Node Memory Limits For Istanbul Report Command - Question

### ISSUE THREAD

**Issue by Delamater** [istanbuljs/nyc#994]
I have a directory with 19,025 coverage json files (~700mb) within it. I run the following command to generate a single html report. 

istanbul report --root build/istanbul --dir build/report/2019-02-18

Normally, with a smaller set of json files, this would work fine. However, when node runs into the 1.5 GB limit it will crash and respond with this message:

- "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory"

With node, I understand you can increase this limit by executing node --max_old_space_size=8192 and that will allow a larger memory space. However, if I run the Istanbul Report command, it seems to use a different memory space. 

Is there a way to increase the memory space in which the Istanbul Report command can utilize before node bombs out?

Many thanks in advance.

**Comment by coreyfarrell** [comment]
Without testing you should be able to accomplish your goal with: `node --max_old_space_size=8192 istanbul report --root build/istanbul --dir build/report/2019-02-18`.  You may also be able to accomplish this by setting the `NODE_OPTIONS` environmental variable (this is mentioned in `node -h`).

That said we do not provide an `istanbul` tool.  That tool is associated with https://github.com/gotwarlost/istanbul#readme but it is deprecated and not maintained.  I definitely recommend switching to `nyc`.

If my suggestion doesn't work even after switching to `nyc` please comment and we can reopen this issue but we are unable to support the legacy `istanbul` tool.

**Comment by Delamater** [comment]
Thanks for your response @coreyfarrell. While I wasn't able to get it to work with your command, it was close. My final command that works looks like this:

node --max_old_space_size=8192 "D:\somePath\node_modules\.bin\\..\istanbul\lib\cli.js" report --root build/istanbul --dir build/report
