### ISSUE TITLE
Document nyc configuration

### ISSUE THREAD

**Issue by wyqydsyq** [istanbuljs/nyc#996]
It appears there is no documentation on nyc configuration

The readme says `Any configuration options that can be set via the command line can also be specified...`, followed by an example `package.json` configuration that doesn't actually explain the  available options or their values.

**Comment by paulmelnikow** [comment]
I'd be willing to work on this. I love both testing and code coverage, and wish it were a little bit easier to set up!

**Comment by Ryuno-Ki** [comment]
In case somebody runs into this …
The `.nycrc` looks somewhat like this (for me):

```json
{
  "check-coverage": true,
  "per-file": true,
  "lines": 80,
  "include": [
    "src/*js"
  ],
  "exclude": [
    "test/*js"
  ],
  "reporter": [
    "lcov",
    "html",
    "text"
  ],
  "report-dir": "./coverage"
}
```

Actually the config file can have different file extensions (or none at all) as I learned from reading the source code.
